### ISSUE TITLE
Doublon dans les membres d'organisations

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#1]
On trouve fréquemment des organisations pour lesquels les membres sont présents plusieurs fois, potentiellement avec les mêmes rôles.

Ici il s'agit d'un exemple de l'organisation Etalab, mais je viens de faire le ménage :

<img width="237" alt="capture d ecran 2017-09-06 a 16 06 46" src="https://user-images.githubusercontent.com/1231232/30119244-725704f4-9325-11e7-8849-063b4145c778.png">

Actuellement l'interface d'administration ne permet plus d'associer un utilisateur déjà membre puisqu'il ne s'affichera pas dans l'auto-complétion.

Il y a peut-être du ménage à faire dans la base de données et/ou des contraintes à ajouter.
Il faut aussi tester côté API s'il est possible d'associer à nouveau un membre.

**Comment by abulte** [comment]
Should be ok with opendatateam/udata#1111 and opendatateam/udata#1112
