### ISSUE TITLE
Envoyer un message court lorsqu'une action est faite sur une issue

### ISSUE THREAD

**Issue by bzg** [etalab/data.gouv.fr#100]
## La fonctionnalité que vous avez en tête

Je me suis rendu compte que Github ne notifiait pas l'auteur d'une issue au moment où celle-ci reçoit un label de la part d'un mainteneur.

Du coup l'issue peut être vue (et commencer à être traitée, même de façon minimale) sans que l'auteur de l'issue sache que sa demande a été vue.

Je propose qu'un message humain soit envoyé à chaque fois qu'une issue est vue et reçoit un traitement quelconque, comme de recevoir un label.

**Comment by bboulesteix** [comment]
Merci pour cette _issue_ @bzg. Je pensais comme toi que GitHub envoyait des notifications au créateur d’une issue quand cette dernière se voyait attribuer une étiquette, mais apparemment non, dommage. Dans ces conditions, un petit message écrit ne ferait pas de mal, tu as raison.

> Je propose qu'un message humain soit envoyé à chaque fois qu'une issue est vue et reçoit un traitement quelconque, comme de recevoir un label.

Ça me semble être une excellente idée. Le message en question pourrait être publié par un membre de l’équipe @etalab/datagouv, en guise d’accusé de réception, et sous la forme d’un premier commentaire dans l’issue.

**Comment by bboulesteix** [comment]
La marche à suivre étant claire pour les personnes concernées, je ferme le ticket. Encore merci @bzg.

**Comment by bzg** [comment]
Merci! Pour être sûr de bien comprendre: cela veut dire qu'on envoie une confirmation écrite en commentaire d'une issue dès que celle-ci est l'objet d'un traitement (nouveau label, assignation, ajout à la feuille de route, etc.) ?

**Comment by bboulesteix** [comment]
Ça veut dire que quand une nouvelle _issue_ est créée sur ce dépôt, on publie un commentaire en réponse, en mentionnant l’auteur du ticket, pour en accuser réception et dire ce que nous comptons en faire par la suite. 

Le commentaire en question peut expliquer pourquoi telle ou telle étiquette est ajoutée au ticket, ou pourquoi le ticket va être assigné à telle ou telle personne. Je pars du constat que les étiquettes affectées à un ticket changent rarement en cours de route. Même chose pour les assignations.

Quant à la feuille de route, les nouveaux tickets y sont automatiquement ajoutés, tous, sans exception, il ne me semble donc pas utile de confirmer par écrit ce qui est déjà fait automatiquement par GitHub.
