### ISSUE TITLE
Handle None values in extras endpoint

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#1001]
Hydra will need to "invalidate" some properties (eg `check:status` from 200 to `None` if a timeout occurred).

We could:
- accept None as valid extra value
- remove attribute from dict if a None value is sent

**Comment by quaxsze** [comment]
L'endpoint a une méthode `DELETE` pour retirer un extra du dictionnaire. Cela ne convient pas?

**Comment by abulte** [comment]
C'est ce que je demandais en regardant le code :-) Le truc c'est que ça ferait plus de logique côté hydra : il faut savoir quels attributs sont passés à `None` puis envoyer un UPDATE et un DELETE. Je pense que c'est plus simple si c'est géré côté udata.

**Comment by maudetes** [comment]
J'arrive un peu en retard, mais est-ce que la solution 1 n'était pas préférable (`accept None as valid extra value`)?

**Comment by abulte** [comment]
Tu remarqueras que j'ai préféré la 2. :-) Je trouve ça plus propre au niveau sortie de l'API et ça permettra peut-être de ne pas trainer trop d'attributs inutiles. En revanche c'est un peu plus de logique côté API.
