### ISSUE TITLE
Affichage de la date relative sur les cartes de jeux de données et ressources

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1004]
S'appuyer sur la date affiché dans les ressources (potentiellement créer une propriété date publique)

![Image](https://user-images.githubusercontent.com/60264344/208107313-cc4daec8-99db-4225-aa46-99a58f7de0b2.png)

Voir https://github.com/etalab/data.gouv.fr/issues/1006 et https://github.com/etalab/data.gouv.fr/issues/1007 pour les dates moissonées

**Comment by maudetes** [comment]
@agarrone est-ce qu'on veut que la date réelle s'affiche au hover?

**Comment by agarrone** [comment]
Oh ça serait optimal ☀️

**Comment by nicolaskempf57** [comment]
On ne pourra pas vraiment faire ça de manière accessible (cf. les problèmes existants sur https://github.com/etalab/data.gouv.fr/issues/924). Sinon il faut faire un fonctionnement avec un bouton et un affichage au "clic".

C'est envisageable pour le score qualité mais pour la date réelle, c'est peut-être beaucoup ? Dites moi ce que vous en pensez.

**Comment by agarrone** [comment]
Ca me semble too much aussi. 
Pour le score ça ne me semble pas critique que ce ne soit pas accessible sur la carte si ça l'est sur la page ce qui n'est pas le cas aujd :/
