### ISSUE TITLE
Ajout de tag dans les json de l'API pour différencier les ressources

### ISSUE THREAD

**Issue by flrt** [etalab/data.gouv.fr#101]
## Problème
Lorsque l'on utilise l'API pour obtenir les URL des fichiers de données, il n'y a pas moyen de distinguer les différentes sources de données.

### Ex: Dataset des finess
Dans le json renvoyé en consultant l'URL https://www.data.gouv.fr/api/1/datasets/53699569a3a729239d2046eb/
il y a 2 fichiers de données CSV :

- les établissements sans informations de géolocalisation : `etalab-cs1100502-stock-20181011-0458.csv`
- les établissements avec informations de géolocalisation : `etalab-cs1100507-stock-20181011-0450.csv`

Dans le JSON, les 2 entrées sont bien dans les `resources`, les 2 entrées ont la même information `"mime": "text/csv",` et `"format": "csv",` mais aucun moyen de faire la différence entre les 2, aucune possibilité de distinguer le fichier géolocalisé de celui qui ne l'est pas, sauf à se baser sur le contenu de l'URL : `etalab-cs1100502-stock...` vs `etalab-cs1100507-stock...` ou sur le titre du document.
Il me semble que c'est un manque important de l'API.

## Solution possible
Avoir dans la description de la ressource, des méta-données supplémentaires, permettant de différencier les 2 ressources. Les tags sont soient prédéfinis et positionnés par le producteur, soit libres, mais il faudrait en ajouter.

**Comment by abulte** [comment]
Les producteurs ont accès à un attribut `extras` sur chaque ressource, un dictionnaire libre modifiable via l'API. Il leur appartient dès lors d'ajouter d'éventuelles informations dans cet attribut pour faciliter le travail des réutilisateurs.
