### ISSUE TITLE
Investiguer les problématiques sur les mails

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1010]
Investiguer les problématiques de récupération de compte

https://support.etalab.gouv.fr/#ticket/zoom/52107

https://support.etalab.gouv.fr/#ticket/zoom/52106

https://support.etalab.gouv.fr/#ticket/zoom/51300

https://support.etalab.gouv.fr/#ticket/zoom/48730

https://support.etalab.gouv.fr/#ticket/zoom/48398

**Comment by maudetes** [comment]
Merci ! J'ai répondu à chacun des tickets.
Je n'ai pas encore identifié d'erreur technique de notre côté. Si c'est le cas, je créerai un ticket dédié en fonction :)
