### ISSUE TITLE
Corriger l'affichage des resources qui ont un nom très long

### ISSUE THREAD

**Issue by nicolaskempf57** [etalab/data.gouv.fr#1012]

**Comment by maudetes** [comment]
Est-ce qu'on pourrait avoir un exemple de cas pour voir le problème ? :pray:

**Comment by nicolaskempf57** [comment]
> Est-ce qu'on pourrait avoir un exemple de cas pour voir le problème ? 🙏

Avant : 
![image](https://user-images.githubusercontent.com/8336712/210220559-1cb18bb3-e2aa-4a4c-8a18-623ded570899.png)

Après :
![Capture d’écran 2023-01-02 à 12 04 27](https://user-images.githubusercontent.com/8336712/210223086-16885020-92e1-4c62-a56c-d8df164e3f40.png)

This prevents the button "see data" text from showing on 2 lines.

**Comment by nicolaskempf57** [comment]
@agarrone je veux bien le lien du jdd original où tu as trouvé l'erreur si tu l'as encore.

**Comment by agarrone** [comment]
https://dev.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/
Dans les ressources communautaires
