### ISSUE TITLE
Intégrer Dolist à data.gouv.fr

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1017]
Les inscriptions à l'infolettre passe encore par Mailjet ce qui pose un problème d'actualisation de la base de contact. 
L'objectif est de permettre aux usagers de s'inscrire directement à l'infolettre sur data.gouv.fr. 

Voir si l'on veut utiliser le composants DSFR : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/lettre-d-info-et-reseaux-sociaux

**Comment by maudetes** [comment]
Newsletter url has been updated and will be deployed in production shortly.
