### ISSUE TITLE
Corriger l'url de validation sur les nouvelles cartes ressources

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1018]
L'url de validation est erronée sur dev.data.gouv.fr (au moins pour certaines ressources), ex: https://dev.data.gouv.fr/fr/datasets/bornes-de-recharge-pour-vehicule-electrique-1/.
La validation renvoie donc une 500.

Il faudrait corriger l'url de validation, en particulier sur le paramètre `schema_url` (qui devrait être une url) ou `schema_name`.

**Comment by nicolaskempf57** [comment]
Dans l'exemple, nous utilisons une URL et non le nom du schéma, parce que le schéma possède plusieurs versions. Cependant, le catalogue contient seulement les versions 2.0.3 et 2.1.0 et ne contient pas la version du fichier (1.0.3).

Ce n'était effectivement pas un cas prévu. Dans ce cas, que faisons-nous ? On affiche un warning et on supprime le bouton ? Si on utilise `schema_name`, la dernière version du schéma est utilisé mais elle ne correspond pas au fichier.

**Comment by maudetes** [comment]
J'invoque @geoffreyaldebert pour répondre à ton commentaire! :)

**Comment by nicolaskempf57** [comment]
> J'invoque @geoffreyaldebert pour répondre à ton commentaire! :)

🧙🧙‍♂️🧙‍♀️

**Comment by geoffreyaldebert** [comment]
han ça y est je comprends. La v1.0.3 est sorti du catalogue car elle ne respecte plus les spécifications frictionless (qui ont évolué récemment). Je réfléchis à comment changer ça mais une solution serait d'ouvrir les url de la métadonnée schéma à toute url sur internet et pas seulement se limiter au catalogue schema.Data.gouv.fr

**Comment by maudetes** [comment]
Merci pour l'explication !
En attendant une solution plus générique à ce problème et pour éviter que ce soit bloquant, je proposerais bien de griser le bouton de validation avec un texte qui s'affiche au hover, genre `Version du schéma inconnue : '1.3.0'`? On pourrait garder le bouton de documentation though?

**Comment by nicolaskempf57** [comment]
Est-ce que ce bug est corrigé par https://github.com/etalab/data.gouv.fr/issues/1052 ? Ou est-ce qu'on part avec la solution proposée par @maudetes ?
