### ISSUE TITLE
Prévisualisation moissonneur ckan

### ISSUE THREAD

**Issue by mkazmiers** [etalab/data.gouv.fr#102]
Bonjour,

Dans le cadre de tests menés pour moissonner l'infra de dev de DATASUD (mutualisé CRIGE/Région SUD),
j'ai testé le moissonnage CKAN sur next.data.gouv.fr.
Lorsqu'on monte un nouveau point de moissonnage (sans filtre), on a pas accès à la prévisu par défaut.
Lorsqu'on édite le point de moissonnage en question, on a accès à la prévisu. Elle est en erreur.
![image](https://user-images.githubusercontent.com/16324693/47282695-7fe67380-d5e0-11e8-9297-79b58c330364.png)

Mathieu

**Comment by mkazmiers** [comment]
Bonjour,

Je me relance dans les tests du moissonneur CKAN de data.gouv, sur next.data.gouv.fr, depuis la version en prod de DATASUD. Avez-vous pu examiner l'erreur du mois dernier ?

Merci pour votre retour !

**Comment by abulte** [comment]
Bonjour,

Je vois que le moissonneur ici https://next.data.gouv.fr/fr/admin/harvester/5c1bc4b6dc47091474367b2d se lance correctement (mais finit avec des erreurs). Le problème que vous évoquez doit donc être réglé (a priori l'URL n'était pas bonne) ?

Sinon n'hésitez pas à rouvrir cette _issue_.

**Comment by mkazmiers** [comment]
OK, j'avais testé les deux URL https:/trouver.datasud.fr/ et https://trouver.datasud.fr/dataset/ mais n'avais aucun signe de succès pour le moissonnage
