### ISSUE TITLE
Déployer les nouvelles cartes ressources avec previz en production :rocket:

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1020]
Suite à https://github.com/etalab/data.gouv.fr/issues/730.

- [x] faire les release en version finale sur NPM (udata-front-plugin-helper, explore.data.gouv.fr)
- [x] faire les release en version finale sur pypi (udata-tabular-preview, udata-front)
- [x] rajouter les traductions de udata-tabular-preview (connecter Crowdin)
- [ ] https://github.com/etalab/data.gouv.fr/issues/1018
- [x] https://github.com/etalab/data.gouv.fr/issues/615

**Comment by nicolaskempf57** [comment]
explore.data.gouv.fr publié en 1.0.1 : https://www.npmjs.com/package/@etalab/explore.data.gouv.fr/v/1.0.1

**Comment by maudetes** [comment]
https://github.com/etalab/data.gouv.fr/issues/1018 will be done later!
