### ISSUE TITLE
Investiguer la métadonnées point de contact

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1024]
Si on récupère la donnée par moissonnage :
- Quelle complétude ? 
- Le plus souvent s'agit-il de personne ou d'email ? 

En lien avec #1005

**Comment by restuccia** [comment]
Je pense qu'il y a des obligations (INSPIRE ou HVD) liées à ce sujet. À vérifier.

**Comment by maudetes** [comment]
L'investigation est probablement close. Voir la suite : https://github.com/etalab/data.gouv.fr/issues/1182
