### ISSUE TITLE
Fix les onglets de la home

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1031]
Les onglets ne fonctionnent pas sur la home. 
Apparement pas de pb ailleurs. 

https://user-images.githubusercontent.com/60264344/213294515-e301e922-5a60-4767-9340-455a6d9ca3bc.mov

**Comment by maudetes** [comment]
Indeed, je reproduis sur Chrome (pas sur Firefox). Je me permets de rajouter au sprint @nicolaskempf57

**Comment by nicolaskempf57** [comment]
Je confirme sur https://demo.data.gouv.fr/fr/, https://dev.data.gouv.fr/fr/ et master. Je regarde ça de suite.
