### ISSUE TITLE
Fixes sur la nouvelle page jeu de données

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1032]
- [x] Les cartes des jeux de données en home sont un peu grande. La taille du producteur n’est pas la même que sur les reuses
- [x] Etendre un peu la description par défaut au maximum de celle de droite. Si la taille de la description match avec la colonne de droite, l’afficher complètement plutôt que de mettre un “lire plus”. 
![Image](https://user-images.githubusercontent.com/60264344/213444316-c8803296-1f9e-4bfd-b3c9-29fcca603cc9.png)

- [x] Remettre le tooltip sur le score qualité
- [ ] Creer une *pages* licences 

- [ ] Peut-on explorer le fait de rendre les onglets sticky ? (reporté) https://www.kaggle.com/datasets/ayushnitb/starcraft-players-dataset

- [x] Le bouton de copié collé ne semble pas fonctionner
- [x] Problème du scroll infini avec le footer
- [x] Je ne parviens pas à ouvrir les extras (exemple : https://dev.data.gouv.fr/fr/datasets/population/)

- [x] Le bouton d’ajout est très collé à la ressource :
![Image](https://user-images.githubusercontent.com/60264344/213444354-d6f2d45c-2dcb-429a-a979-b7f6958aa047.png)

- [ ] Profiter pour faire les petits ajustements de tailles sur les commentaires ?
- [x] Pagination :
    - Sur les réutilisation je reviens sur les fichiers
    - Sur les commentaires je ne reviens pas en haut
   
- [x] L’alignement n’est pas le même entre les métadonnées (May doit être au même niveau que le lien)
![Image](https://user-images.githubusercontent.com/60264344/213444404-536b8a67-e144-4444-8792-f1d1d622233d.png)
    
- [x] Sur une description très longue lorsque qu’on la referme il faut remonter en haut

- [x] On peut laisser couler un peu plus la taille de la description après les métadonnées avant de mettre le lire plus

- [ ] Est-ce qu’on crée un onglet API ? (reporté) 

- [x] Le crayon me semble un peu loin 
![Image](https://user-images.githubusercontent.com/60264344/213444458-d044d0b6-0d31-4d79-9ed7-3fd16080811a.png)

- [x] Je trouve que l’espace est chelou mais je sais pas trop comment faire (Edit : [nouveau design](https://www.figma.com/file/vqJxE4lFRdmq3jbVU0kPmz/Page-jeux-de-donn%C3%A9e?node-id=218%3A13504&t=sQpllnIoHlQI22cF-1))
![Image](https://user-images.githubusercontent.com/60264344/213444487-e22fc633-b29c-48bc-a9ba-cbea6d0d9c5c.png)

- [x] Problème d’espacement et taille de police dans les encarts : 
![Image](https://user-images.githubusercontent.com/60264344/213444518-df125230-753b-49d8-ba02-5eab88ec35e8.png)

- [x] Changer les liens des CTA vides pour orienter vers la bonne doc

- [x] Peut-on étendre par défaut ?

![Image](https://user-images.githubusercontent.com/60264344/213444552-a3f7f022-461a-4847-b8c6-d02d11aeaa73.png)

- [x] Veut-on exactement la même couleur entre notre bleu et celui des illus ? 
![Image](https://user-images.githubusercontent.com/60264344/213444582-cf955ff2-e586-4982-8346-a4971a4b17a8.png)

- [x] Onglet structure par encore sur dev ? 
- [x] Quid du bandeau ? 
![Image](https://user-images.githubusercontent.com/60264344/213444601-e164f351-ea7a-425d-a391-7cf3847eb6aa.png)

- [x] Mettre en gras ce texte : 

![Image](https://user-images.githubusercontent.com/60264344/213444626-f851dd2f-b34a-4452-a8b7-42bbffca060a.png)

**Comment by nicolaskempf57** [comment]
> Les cartes des jeux de données en home sont un peu grande. La taille du producteur n’est pas la même que sur les reuses

Je vais modifier la taille du texte sur les cartes jeux de données, qui est plus grande que sur Figma.

> Remettre le tooltip sur le score qualité

On met le [i] en plus du reste ?

> Peut-on explorer le fait de rendre les onglets sticky ?

Je vais regarder s'il y a un problème particulier et faire un test

> Le bouton de copié collé ne semble pas fonctionner

Corrigé quand on mettra à jour dev grâce à https://github.com/etalab/data.gouv.fr/issues/1031

> Problème du scroll infini avec le footer

Le problème actuel ne peut pas être corrigé sans https://github.com/etalab/data.gouv.fr/issues/1013. Cependant, je ne trouve plus le cas qui a nécessité cet ajustement. Je vais annuler le changement et je referais des tests.

> Je ne parviens pas à ouvrir les extras (exemple : https://dev.data.gouv.fr/fr/datasets/population/)

Corrigé quand on mettra à jour dev grâce à https://github.com/etalab/data.gouv.fr/issues/1031

> Profiter pour faire les petits ajustements de tailles sur les commentaires ?

Ils sont sur Figma quelque part ?

> L’alignement n’est pas le même entre les métadonnées (May doit être au même niveau que le lien)

Je vais changer pour utiliser un tableau qui fera cet effet

> Sur une description très longue lorsque qu’on la referme il faut remonter en haut

C'est le fonctionnement normal, je vais regarder pour remonter en cas de scroll, mais il me semble que ça faisait un drôle d'effet la dernière fois qu'on avait voulu le faire

>  Est-ce qu’on crée un onglet API ?

On peut changer le système de hook actuel pour proposer la création d'onglets au lieu de l'ajout après les ressources

> Je trouve que l’espace est chelou mais je sais pas trop comment faire

Je ne sais pas non plus. En mettant le bouton et le tri sur la meme ligne, le rendu est bizarre.

>  Peut-on étendre par défaut ?

Le tableau permet de choisir en étendu sans scroll, ou non étendu avec scroll. Comme on ne contrôle pas le nombre de colonnes, on ne peut pas faire autrement tant que le DS n'a pas changé ça. Sauf à refaire des modifications sur le composant.

> Veut-on exactement la même couleur entre notre bleu et celui des illus ?

Ce n'était pas le cas sur Figma. Voici ce que ça donne avec la meme couleur.
![Xnapper-2023-01-23-13 47 36](https://user-images.githubusercontent.com/8336712/214043798-cc49dd10-6d2a-4c46-a1e1-fa31ca5d9374.png)


> Onglet structure par encore sur dev ?

Non, je viens seulement de faire la [PR](https://github.com/opendatateam/udata-tabular-preview/pull/19).

> Quid du bandeau ?

Je l'ai oublié. On affiche toujours le même ? Ou est-ce que le contenu peut changer ?

**Comment by agarrone** [comment]
> On met le [i] en plus du reste ?
 Yes comme sur le tooltip
   
> > Profiter pour faire les petits ajustements de tailles sur les commentaires ?
> 
> Ils sont sur Figma quelque part ?
> 
 
> C'est le fonctionnement normal, je vais regarder pour remonter en cas de scroll, mais il me semble que ça faisait un drôle d'effet la dernière fois qu'on avait voulu le faire

Preneur d'une démo pour être sûr qu'on s'est compris

> On peut changer le système de hook actuel pour proposer la création d'onglets au lieu de l'ajout après les ressources
Interessant. A rediscuter. 

> Le tableau permet de choisir en étendu sans scroll, ou non étendu avec scroll. Comme on ne contrôle pas le nombre de colonnes, on ne peut pas faire autrement tant que le DS n'a pas changé ça. Sauf à refaire des modifications sur le composant.
Pas critique donc laissons pour le moment. 


> Ce n'était pas le cas sur Figma. Voici ce que ça donne avec la meme couleur. ![Xnapper-2023-01-23-13 47 36](https://user-images.githubusercontent.com/8336712/214043798-cc49dd10-6d2a-4c46-a1e1-fa31ca5d9374.png)
Je pense que c'est une erreur de notre part. En tout cas je ne me souviens pas de cet arbitrage. Mais je pense que tu peux laisser tel quel car c'est le même que l'on utilise sur les pages d'onboarding sauf erreur de ma part. 


> Je l'ai oublié. On affiche toujours le même ? Ou est-ce que le contenu peut changer ?
C'est un bandeau spécifique pour chaque jeux de données où c'est pertinent. Si possible il faut permettre de pouvoir le changer facilement. Pas forcément que ce soit administrable par tout le monde cependant.

**Comment by nicolaskempf57** [comment]
@agarrone pour le tooltip tu préfères avec le [i] à gauche ou à droite ?
![Xnapper-2023-01-26-15 11 08](https://user-images.githubusercontent.com/8336712/214857464-06261cf1-efc7-4497-84c6-ac627913f6e4.png)
![Xnapper-2023-01-26-15 11 45](https://user-images.githubusercontent.com/8336712/214857474-fb9562dc-b952-4743-9853-bdacfcc33f46.png)

**Comment by agarrone** [comment]
A gauche comme sur les cartes ça me semble bien :)
