### ISSUE TITLE
Permettre de trier par date de mise à jour plutôt que date de publication

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1035]
Suite au refacto des dates

**Comment by quaxsze** [comment]
Feature compliqué à mettre en place.
- La liste des JDD est triée par la base de données de recherche ElasticSearch, qui ne dispose pas de la date `last_update`. Cette date ne fait pas partie du modèle de données elle est calculée à postériori.
- On peut tenter de rajouter cette date dans l'indexation d'ElasticSearch mais dans le cas de figure où une personne utiliserait udata sans ElasticSearch et en rebasculant la recherche sur MongoDB cette stratégie ne marchera plus.
MongoDB ne permet d'indexer que sur des champs du modèle. Ainsi l'interface promettrait à l'utilisateur un tri par date de mise à jour mais le résultat serait incohérent.

**Comment by agarrone** [comment]
Il me semble que c'est une fonctionnalité critique au bon fonctionnement de data.gouv.fr. 
Qu'en penses tu @maudetes ? 

Quel est le cas de figure où une personne utiliserait udata sans ElasticSearch ?

**Comment by maudetes** [comment]
> Il me semble que c'est une fonctionnalité critique au bon fonctionnement de data.gouv.fr. Qu'en penses tu @maudetes ?

Je rebondis sur ce qu'a dit @quaxsze. La question technique est surtout sur la cohérence avec la recherche Mongo. Si c'est une fonctionnalité critique, on peut quand même tenter, quitte à documenter la différence de comportement. Par contre, on fera avec les dates qu'on a, qui sont biaisées (ressources distantes et moissonnées).

> Quel est le cas de figure où une personne utiliserait udata sans ElasticSearch ?

Par défaut, udata n'embarque plus ElasticSearch, mais utilise Mongo pour la recherche. Mais difficile de savoir ce que font les réutilisateurs de udata

**Comment by tboye** [comment]
There are users of `udata` out there who prefer MongoDB search :wink: 

Just wanted to confirm that current behavior is indeed inconsistent and search on calculated fields is not a trivial task...
