### ISSUE TITLE
Supprimer les liens qui pointent vers Google+ depuis des sites Etalab

### ISSUE THREAD

**Issue by bboulesteix** [etalab/data.gouv.fr#104]
La [page Google+ d’Etalab](https://plus.google.com/117902389749487955734) va bientôt être archivée. Une fois qu’elle ne sera plus en ligne, nous devrons supprimer les liens qui pointent vers Google+ depuis les sites entretenus par Etalab, pour éviter les erreurs 404.

## Liste des sites qui pointent vers Google+

* [ ] https://www.data.gouv.fr/fr/

**Comment by bboulesteix** [comment]
Ah, super. 🙂 Je vois toujours l’icône Google+ dans le _footer_ de data.gouv.fr de mon côté, c’est normal ? La modification effectuée sur le thème date d’hier, peut-être y a-t-il une petite latence ?

**Comment by abulte** [comment]
Oui il faut qu’on déploie la nouvelle version.

**Comment by bboulesteix** [comment]
<img width="203" alt="capture d ecran 2018-11-15 09 52 02" src="https://user-images.githubusercontent.com/3286488/48541080-1c3c2700-e8bc-11e8-9ad0-028c302fdccf.png">

Problème en partie résolu —[ la page Google+ d’Etalab](https://plus.google.com/117902389749487955734) est toujours en ligne, mais elle n’est plus accessible depuis le pied de page de data.gouv.fr. 🙂 Je ferme donc cette issue. Un grand merci à vous. 👏
