### ISSUE TITLE
Faire une liste du différentiel entre les métadonnées DCAT et ce qu'on a aujourd'hui

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1045]
Comparer par rapport aux métadonnées INSPIRE pour commencer, et leur demander sinon leur "schéma".

**Comment by agarrone** [comment]
Si tu as une update là dessus je suis preneur @maudetes sinon je clos en attendant futur prio

**Comment by maudetes** [comment]
A first differential has been made between [ecosphère schema](https://github.com/ecolabdata/ckanext-ecospheres/blob/main/ckanext/ecospheres/scheming/ecospheres_dataset_schema.yaml) and udata's by abulte :pray: : https://docs.google.com/spreadsheets/d/1zHLJxZ6Lya74a2lRMqLMC4KSaXtdSH6LqqkClmgaP3g/edit?usp=sharing

**Comment by maudetes** [comment]
Additional input on this topic: https://github.com/abulte/ecospheres-datagouvfr-metadata/blob/main/ecospheres-datagouvfr-metadata.md (by @abulte again)
