### ISSUE TITLE
Remonter le bouton "ajouter" ressource dans l'espace admin

### ISSUE THREAD

**Issue by margot-sanchez** [etalab/data.gouv.fr#1055]
## L’amélioration que vous avez en tête
En tant qu'admin d'un jeu de données avec de multiples ressources je souhaite que le bouton ajouter soit en haut et non tout en bas car le scroll est très très long. 

![image](https://user-images.githubusercontent.com/15428433/220928371-e1a0aeb8-d439-4668-a127-66cc93acb5ff.png)
![image](https://user-images.githubusercontent.com/15428433/220928454-53e97196-eb62-4a04-9ef0-96db039f0225.png)

## Les alternatives possibles
Idéalement il faudrait revoir le parcours utilisateur mais ce petit quick fix me simplifierait déjà bien la vie :) 

Merci data.gouv.fr <3

**Comment by agarrone** [comment]
Je clos car on est en train de retravailler tout le parcours / l'admin. 
Merci du retour :)
