### ISSUE TITLE
Investiguer le changement de base de données pour ouverture.data.gouv.fr

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1057]
## Base Notion

La base Notion utilisée pour les tests est disponible ici : https://conciergerie.notion.site/TEST-Suivi-ouverture-donn-es-2de001dfa9084b4ea8c49f856e2ccf62

Elle reprend la base du suivi d'ouverture avec une checkbox en plus pour indiquer s'il faut ou non rendre le suivi public, comme indiqué dans la [page Notion du produit ouverture](https://www.notion.so/apigouv/ouverture-data-gouv-fr-99deea5c2a794759969c82d7b5ee9d52?pvs=4).

D'autres changements peuvent être apportés au besoin.

Par rapport au produit actuel, il manque l'information de type (données, API, code source).

Il faudra également ajouter une Formula `Nom Producteur` qui contient `prop("Producteur de données")`. Cela permet de récupérer les noms des producteurs via l'API. Sinon il faut faire une requête d'API par producteur et on va dépasser la limite.

Il est possible d'ajouter une Formula `Statut public` avec le code ci-dessous pour supprimer le mapping entre les statuts de la base et ceux affichés dans le projet.

```javascript
if(prop("Statut") == "Fait", "Disponible", if(prop("Statut") == "Abandonné", "Non disponible", "Planifié"))
```

Concernant la date estimée de publication, pour éviter d'avoir un formatage dans le projet, le plus simple serait de simplement modifier le select sur Notion pour que les choix soient sous la forme `T4 2023` et non `2023 T4`. Cela ne semble pas avoir d'impact sur la base comme le champ n'est jamais utilisé comme tri et qu'il est possible d'ordonner les valeurs possible par drag & drop.

## Api Notion

Pour pouvoir interagir avec l'API Notion, il est nécessaire de créer une intégration et la lier à la Workspace Etalab. Il faudra le faire avec un compte qui dispose de droits d'accès suffisants.

### Pagination

L'API Notion est paginée avec une taille de page maximum de `100`. Cela fonctionne avec un système qui permet uniquement de savoir s'il y a encore des pages à charger. Un bouton `charger plus de résultats` est affiché si besoin.

### Rate limiting

L'API a une limite à 3 req/s : https://developers.notion.com/reference/request-limits
Cela n'a pas d'impact pour nous comme nous utilisons un cache Flask de 600s.

**Comment by agarrone** [comment]
Top ! Si tu as un peu de temps tu peux jeter un œil au code d'ouverture on compte y faire quelques modifs (changer le header et footer pour matcher avec datagouv, ajouter quelques colonnes)

**Comment by nicolaskempf57** [comment]
Oui j'ai un peu regardé ! Il y a également des changements techniques à prévoir avec la fin des développements de VuePress (fin 2020), son remplacement par VitePress (2022) et la fin du support de vue 2 (fin 2023).

**Comment by agarrone** [comment]
Si tu penses que c'est plus pertinent et efficace de partir de 0 à toi de voir :)

**Comment by nicolaskempf57** [comment]
Oh non non, on pourra reprendre le contenu déjà développé !

**Comment by agarrone** [comment]
A quelle API fais tu référence ? 
On compte récolter les besoins avec un formulaire du type : https://tally.so/r/npro68 (qui alimentera directement la base)

**Comment by nicolaskempf57** [comment]
@agarrone ok ! J'attends le retour de @maudetes mais on peut probablement le supprimer alors.

Dans le code, il y a une route d'API `/api/demande` pour poster des demandes dans une table qui s'appelle `Demandes d'ouverture`, mais il n'y a rien qui permet aux utilisateurs de le faire réellement. Donc j'imagine que c'est un reliquat de quelque chose qui a été fait et supprimé, ou qui a été commencé mais pas mis en place.

**Comment by maudetes** [comment]
Yes, je pense qu'on n'en a pas besoin!
