### ISSUE TITLE
Flux RSS des résultats du moteur de recherche

### ISSUE THREAD

**Issue by bjperson** [etalab/data.gouv.fr#106]
Pour faciliter la veille.

Par ailleurs, comme il y a plein d'outils pour afficher facilement ces flux dans des pages web, cela fournirai un moyen simple aux petits producteurs de promouvoir leurs jeux de données sur leurs sites respectifs.

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
