### ISSUE TITLE
Les utilisateurs individuels n’ont pas de raccourci vers Discussions

### ISSUE THREAD

**Issue by bboulesteix** [etalab/data.gouv.fr#107]
## Problème

Dans l’interface administrateur de data.gouv.fr, au niveau de la barre latérale à gauche, les utilisateurs individuels ont accès à moins de liens rapides que les organisations. 

<img width="1440" alt="capture d ecran 2018-11-02 11 01 51" src="https://user-images.githubusercontent.com/3286488/47909624-c4032f00-de90-11e8-87ed-292677e4646c.png">

Par liens rapides, j’entends les liens qui apparaissent dynamiquement quand on clique sur **Moi** ou sur le nom d’une organisation, dans la barre latérale, et qui agissent comme des ancres pour accéder rapidement à la bonne section de la page de suivi.

Les utilisateurs individuels ont accès aux liens rapides suivants :

* Jeu de données (toujours au singulier)
* Réutilisations

<img width="230" alt="capture d ecran 2018-11-02 10 59 34" src="https://user-images.githubusercontent.com/3286488/47909592-b057c880-de90-11e8-81b0-d363959e77af.png">

Les organisations ont accès aux liens rapides suivants :

* Jeu de données (toujours au singulier)
* Réutilisations
* Anomalies
* Discussions

<img width="230" alt="capture d ecran 2018-11-02 10 59 21" src="https://user-images.githubusercontent.com/3286488/47909598-b64da980-de90-11e8-8aeb-6b1f453c29af.png">

## Solution possible

Comme les jeux de données publiés par des utilisateurs individuels peuvent aussi faire l’objet de discussions ou de signalements en cas d’anomalie, il ne me semblerait pas si déraisonnable que ça d’ajouter des liens rapides vers les sections **Anomalies** et **Discussions** pour les utilisateurs individuels _aussi_.

## Questions

Je ne sais pas si :

1. Ma proposition a déjà été faite par quelqu’un d’autre ?
2. Il y a une raison pour ne **pas** ajouter d’accès rapides dans le menu des utilisateurs individuels ?

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
