### ISSUE TITLE
Explorer les métriques Matomo (previz et exploration)

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1082]

**Comment by nicolaskempf57** [comment]
J'ai amélioré la détection des téléchargements grâce à l'ajout d'un indicateur à Matomo que le lien sur les jdds est un téléchargement.

J'ai ajouté les évènements suivants sur Matomo :
- Ouverture / Fermeture d'une ressource
- Affichage de la preview
- Affichage des structures de données
- `Sort` d'une liste
- Changement d'onglet sur la home
- Changement de hash (utilisé pour les onglets des pages datasets, reuses et orga)

Est-ce qu'on veut d'autres choses ? @agarrone 

Pour l'explore, on peut déjà suivre le suivre dans les liens sortants donc je n'ai rien ajouté.

**Comment by agarrone** [comment]
Trop bien merci !
