### ISSUE TITLE
Soucis d'accessibilité sur la tabulation des pages datasets

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1087]
Exemple sur https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/

* On tabule sur les liens de la description au-delà du `Lire plus`.
* En tabulant sur les fichiers, la pagination rentre à l'intérieur de l'accordéon du fichier, même s'il est replié

[Capture d’écran vidéo de 11-05-2023 10:08:18.webm](https://github.com/etalab/data.gouv.fr/assets/28541902/5e66ff00-a4b1-48cc-b91d-2888a2e092d2)

**Comment by nicolaskempf57** [comment]
Pour les fichiers, comme on est sur un fonctionnement de type "accordéon", je vais pouvoir corriger le fonctionnement pour qu'il soit le même pour tous les utilisateurs :
- le contenu de l'accordéon n'est pas visible (ni lu par une technologie assistive)
- il faut appuyer sur le bouton pour afficher le contenu de l'accordéon
- pour les outils qui gèrent `aria-controls`, les utilisateurs peuvent accéder directement au contenu ouvert
- pour les outils qui ne gèrent pas `aria-controls`, il faudrait que le bouton de l'accordéon soit à la fin de la liste de boutons et non au début, sinon ils n'ont pas cette information.

Pour le read-more c'est plus complexe. Le fonctionnement est correct pour les utilisateurs au clic et pour les utilisateurs avec une technologie assistive (il faudrait retirer le bouton read-more de l'accessibility tree pour être exact). Cependant, si on veut désactiver le <kbd>tab</kbd> des liens masqués, on doit le faire pour tous les utilisateurs ce qui va nuire à l'accessibilité.
