### ISSUE TITLE
Inconsistance dans les termes utilisés pour le tri des résultats de recherche

### ISSUE THREAD

**Issue by bboulesteix** [etalab/data.gouv.fr#110]
## Problème

Quand un utilisateur fait une recherche sur data.gouv.fr, il peut trier les résultats de recherche qui lui sont affichés, selon plusieurs critères qui dépendent du type d’élément recherché (jeux de données, organisations ou réutilisations).

Dans le cas des jeux de données **et** des réutilisations, il est possible de trier les résultats selon le nombre de fois où ils ont été mis en **favoris**. Le hic, c’est que dans le cas des **réutilisations**, le critère de tri s’appelle `Favoris` dans un premier temps, puis `Abonnés` dans un second temps, ce qui est à la fois déroutant et inconsistant.

![7](https://user-images.githubusercontent.com/3286488/47922353-28d18000-deb7-11e8-87ef-ad3d9a3e2366.png)

## Comment reproduire le bug

1. Allez sur : https://www.data.gouv.fr/fr/search/?q= ;
2. Se placer sur l’onglet **Jeux de données** ;
2. Cliquer sur : `Trier par` > `Favoris`
3. Constater le terme employé (`Favoris`) ;
4. Recommencer l’opération sur l’onglet **Réutilisations**
5. Constater que le terme employé devient `Abonnés`.

## Solution proposée

Remplacer `Abonnés` par `Favoris` dans l’onglet **Réutilisations**. Plus largement, toujours parler de **Favoris**, partout dans l’interface, pour éviter d’introduire des divergences de vocabulaire là où il est question de (plus ou moins) la même chose.

**Comment by noirbizarre** [comment]
C'est la solution inverse qui a été retenue étant donné qu'il est fait référence aux abonnés partout et que c'est le seul endroit où l'on parle de favori.

**Comment by noirbizarre** [comment]
cf. https://github.com/opendatateam/udata/pull/2013
