### ISSUE TITLE
Créer des alertes : Doublon orga + liens 404 (nouveau canal mattermost)

### ISSUE THREAD

**Issue by mikoa9** [etalab/data.gouv.fr#1100]
Créer un nouveau canal mattermost, ex datagouv-alertes-curation, afin de recevoir 2 types d'alertes (pour le moment) :

1. Organisations en doublon
- recevoir des alertes dès qu’une organisation est créée avec le même nom d’une orga existante
- informations : Organisation en doublon : Nouvelle organisation [nom de la nouvelle organisation] + [lien de la nouvelle organisation] + Ancienne organisation [nom de l’ancienne organisation] + [lien de l’ancienne organisation]

2. Détection de liens morts (url 404)
- recevoir des alertes quand un lien de réutilisation renvoie vers une page 404
- informations : Réutilisation avec page 404 détectée : [nom de la réutilisation] + [lien de la réutilisation data.gouv] + [lien de la réutilisation 404]

3. Invitation à passer en revue les admins actuels de data.gouv.fr (voir [discussion sur ce sujet](https://mattermost.incubateur.net/betagouv/pl/irtkh5ydj3bficyzerccq3kfya))
- faire une liste des admins actuels (à voir si possible par API)
- alerte sur mattermost pour passage en revue

A dispo pour en discuter !
Merci
Clarisse

**Comment by Pierlou** [comment]
Yes je peux faire ça ! Chaud pour un peu plus de détails : 
- qu'est-ce qu'on entend par doublon ? Un nom très similaire, ou le fait que le slug se termine par `-X` ? (ou autre ?)
- est-ce que si on se base sur le slug, on considère comme doublon la création de l'orga `mon-organisation-1` si `mon-organisation` a été supprimée ?

**Comment by maudetes** [comment]
C'est à @mikoa9 de clarifier, mais je pense qu'on peut partir sur un nom totalement équivalent.
Pour les slugs, ça me paraît une bonne heuristique, bonne idée. :+1: De ma compréhension, une fois l'objet définitivement supprimé (les objets marqués comme "supprimé" sont purgés quotidiennement), les slugs sont libérés :)

**Comment by mikoa9** [comment]
Hello, merci de reprendre ce sujet :)
- Par doublon, oui ça peut être le nom identique avec slug qui se termine par "-x" mais si on peut trouver en plus d'autres règles quand le nom de l'organisation change très peu ça peut être cool (car malheureusement ça arrive aussi). Si besoin Pierlou tu me diras je peux regarder et te donner des exemples d'orga doublon de ce type
- Pour moi, peut-être pas nécessaire de considérer le doublon de "l'orga-1" si "orga" a été supprimée (car du coup plus un doublon- juste un autre traitement de nettoyage) 
On peut en parler de vive voix si vous voulez ?
Clarisse

**Comment by Pierlou** [comment]
> quand le nom de l'organisation change très peu

C'est très vite complexe de faire des tests sur la similitude de chaînes de caractères, je serais plus partant (au moins dans un premier temps) pour des règles métiers plus simples (sur les slugs ça me parait être un bon début). Je peux l'implémenter comme ça et on en parle d'ici jeudi ? :)

**Comment by mikoa9** [comment]
yes si trop compliqué, dans ce cas on commence déjà par les slugs c'est très bien et on en reparlera :)

**Comment by maudetes** [comment]
Le dernier point est done dans https://github.com/etalab/datagouvfr_data_pipelines/pull/94.
