### ISSUE TITLE
Eviter de bumper d'autres librairies lors de la release

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1101]
Lors de la release avec bumpr, un remplacement est effectué du numéro de version.
Dans les cas où les fichiers de version contiennent à la fois la version du package principal à remplacer ainsi que d'autres dépendances, celles-ci peuvent être bumpées par erreur, ex : https://github.com/etalab/udata-front/commit/fc517914f728c40a312d542e4364eb871da54391.

**Comment by nicolaskempf57** [comment]
Je ne sais pas si on veut voir ça ici ou dans un autre ticket. 
La version de dev créée par bumpr sur udata-front (ex: `3.2.7.dev`) ne respecte pas la norme de [semantic versioning](https://semver.org/) demandée par NPM ce qui peut causer des erreurs pour des librairies tierces (ex: chromatic, pour publier notre storybook, s'attend à une version valide).
Une solution correcte serait `3.2.7-dev` avec la possibilité d'avoir des numéros de version après le tiret comme `3.2.7-dev.1`.

**Comment by nicolaskempf57** [comment]
Je viens de tester mais non ça ne marche pas non plus. La syntaxe de semver.org est très restrictive : 

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>
```

**Comment by maudetes** [comment]
oh incroyable : https://regex101.com/r/Ly7O1x/3/
et je pense qu'on va être obligé de regarder plus en détail côté bumpr :)
