### ISSUE TITLE
[API] tri par date décroissante de création ne fonctionne pas

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/data.gouv.fr#1103]
## Description du bug

Quand on requête `https://www.data.gouv.fr/api/1/datasets/?page_size=100&sort=-created` le sorting ne fonctionne pas correctement car les datasets qui apparaissent en premier ne sont pas forcément ceux créés les plus récemment.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à `https://www.data.gouv.fr/api/1/datasets/?page_size=100&sort=-created`
2. Constater

## Comportement attendu

un sorting efficace et correct

**Comment by maudetes** [comment]
## Quelques notes en vrac après discussion

### A conserver
* Garder l'affichage d'une unique date sur le front pour les utilisateurs
* Garder les infos séparées entre dates internes et dates moissonnées dans le modèle

### Possibilités d'évolutions
* Rajouter la date interne en retour de l'API en plus de la date computée et moissonnée pour exhaustivité
* Faire en sorte que created_at_internal soit un champ du modèle mis à jour à chaque `pre_save` (ex: comme pour les slugs) -> permettant un sort
* Avoir un sort sur la date computée et interne sur l'API de liste, en effet -created_at_internal correspond à un besoin utilisateur de modération de l'activité de la plateforme
    * A voir si ce besoin existe sur l'API de search
* Rajouter une section dans la doc sur ces différentes dates

Ces réflexions s'appliquent aussi pour les dates de dernières modifications.
