### ISSUE TITLE
Rajouter un bouton de feedback dans le header

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1105]
- [x] Rajouter un bouton de feedback dans le header de data.gouv.fr qui pointe vers : https://tally.so/r/mOld5R
- [x] Rajouter un lien "Donnez votre avis" dans le footer dans la section "Support"
- [ ] Faire une integration sur mattermost (depuis Tally ou Notion) (exemple annuaire : https://github.com/etalab/annuaire-entreprises-site/blob/be2e93251657afa1d0dcc0993b189ef84605637b/pages/api/feedback/nps.ts#L22)
 

![Image](https://github.com/etalab/data.gouv.fr/assets/60264344/e876699d-3487-4efb-9c67-78136289c54d)

Envisageable dans le sprint ? @maudetes @nicolaskempf57

**Comment by maudetes** [comment]
Ca me paraît faisable :)

**Comment by maudetes** [comment]
Je clos ce ticket, l'ajout d'intégration peut se faire dans un deuxième temps (étant donné que l'intégration n'existe pas directement, donc pas complètement trivial).
