### ISSUE TITLE
Onglets non visibles lors d'un lien direct vers une discussion

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#1114]
## Description du bug
Avec un lien direct vers une discussion, les onglets d'une page de JDD ne sont pas visibles. (Chrome 114)

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à https://www.data.gouv.fr/fr/datasets/fr-200052264-t0023-0000-1/#/discussions/64aebddb070654c86b928c5a
2. Remonter sur la navigation par onglets
4. Constater le bug : les onglets ne sont pas visibles

![image](https://github.com/etalab/data.gouv.fr/assets/295709/93c90b08-8b2e-4ec7-b4f4-9f04ab2ad2d2)

**Comment by agarrone** [comment]
Thanks :)
