### ISSUE TITLE
Migrer des geozones aux référentiel de l'INSEE

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1116]
Les [geozones](https://github.com/etalab/geozones) se voulaient être un référentiel spatial et administratif, mais n'a pas été maintenu dans le temps.

On décide donc de privilégier le référentiel de l'INSEE comme métadonnée pour la couverture spatiale des jeux de données.
Voir la publication RDF du COG par l'INSEE à utiliser comme référentiel : https://rdf.insee.fr/geo/index.html

On aura donc comme aujourd'hui un champ `spatial` qui comporte une entité nommée et/ou une géométrie.

A voir s'il est possible d'avoir une migration approximative des geozones au référentiel de l'INSEE selon les usages.

L'usage du référentiel de l'INSEE peut se découper en deux tâches :
- [ ] extraction des informations utiles du RDF dans un script et stockage en format JSON sur datagouv
- [ ] importation de ces informations dans udata (à l'image de https://github.com/opendatateam/udata/blob/a947558fee449e13e53a5bba9cb28848aec0b053/udata/core/spatial/commands.py#L135)

**Comment by geoffreyaldebert** [comment]
@quaxsze can you begin the work around cleaning geozones in udata and try to use new ones from @Pierlou : https://demo.data.gouv.fr/fr/datasets/demo-geozones/

**Comment by abulte** [comment]
PI je suis tombé sur https://sws.geonames.org/, utilisé par les Belges

```
            <dct:spatial>
               <dct:Location rdf:about="https://sws.geonames.org/2802361/"/>
            </dct:spatial>
```
