### ISSUE TITLE
API datasets :  renvoyer une erreur dans le cas d'un paramètre d'organization qui n'est pas un id

### ISSUE THREAD

**Issue by K4ST0R** [etalab/data.gouv.fr#1125]
## Description du bug

Le filtre organization renvoi une erreur 500
https://doc.data.gouv.fr/api/reference/#/datasets/list_datasets

=> `https://www.data.gouv.fr/api/1/datasets/?page=1&page_size=20&organization=france-competences`

```
{
  "message": "Internal Server Error"
}
```

**Comment by maudetes** [comment]
Bonjour,

Il faut utiliser l'identifiant de l'organisation : https://www.data.gouv.fr/api/1/datasets/?page=1&page_size=20&organization=5d767ad36f44414d5b3645c8.
En effet, nous devrions retourner une erreur explicite plutôt que de renvoyer une 500 dans le cas où il ne s'agit pas d'un ID.

**Comment by K4ST0R** [comment]
Ok! Merci beaucoup!
Oui effectivement une erreur 400 avec un message serait plus appropriée.
