### ISSUE TITLE
Optimisations site Ouverture (favicon + balise title)

### ISSUE THREAD

**Issue by mikoa9** [etalab/data.gouv.fr#1129]
Hello,

Quelques optimisations sur le site : https://ouverture.data.gouv.fr/
- Ajouter un favicon https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icone-de-favoris/
- Modifier la balise Title par : Ouverture data.gouv.fr (pour que ce texte s'affiche sur les onglets des fenêtres)
- Corriger ce cas : sur le site ouverture, on doit cliquer sur le bouton Charger plus de données, alors qu'il n'y a qu'un JDD présenté : https://ouverture.data.gouv.fr/?organization=Minist%C3%A8re+de+l%27Int%C3%A9rieur
Quelle est la règle actuelle (nombre de JDD max) pour que s'affiche le bouton ?
Merci !

Clarisse

**Comment by nicolaskempf57** [comment]
> * Sur le site ouverture, on doit cliquer sur le bouton Charger plus de données, alors qu'il n'y a qu'un JDD présenté.
>   Exemple : https://ouverture.data.gouv.fr/?organization=Minist%C3%A8re+de+l%27Int%C3%A9rieur
>   Quelle est la règle actuelle (nombre de JDD max) pour que s'affiche le bouton ?

On récupère les données de Notion 100 lignes à la fois, sans tenir compte des filtres, et ensuite seulement on applique les filtres.

**Comment by nicolaskempf57** [comment]
On va également charger automatiquement les données restantes au chargement de la page. Cf. https://github.com/etalab/ouverture.data.gouv.fr/pull/31/commits/fe4e614c60658014ba95a2d11af6f7b56af88d08
