### ISSUE TITLE
Clé API par organisation ou jeu de données

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#113]
Bonjour,

À ma connaissance, les seules clés d'API disponibles actuellement sont celles personnelles qui donnent accès aux organisations auxquelles on appartient.

Est-il possible de générer des clés par organisation ou par jeu de données ? Ceci permettrait de mieux découper les permissions, sans obliger à utiliser des clés personnelles de quelqu'un qui n'est pas forcément réellement au sein d'une organisation, qui l'a quitté etc

**Comment by odtvince** [comment]
Il est possible (voir conseillé) de créer des utilisateurs dédiés pour les robots de versement de données qui auront ainsi leur propre clef d'API (et peuvent appartenir à une ou plusieurs organisations).
