### ISSUE TITLE
Problème de traduction sur la page de login

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#1131]
Les intitulés de champ ne sont pas traduits sur le [formulaire de login](https://www.data.gouv.fr/fr/login).

<img width="585" alt="Capture d’écran 2023-08-01 à 10 33 34" src="https://github.com/etalab/data.gouv.fr/assets/119625/c479dd2a-2175-435b-9ed5-3933ca19cd67">

Chrome, Safari, MacOS

**Comment by nicolaskempf57** [comment]
Je tombe par hasard sur l'issue mais pour compléter le bug sur le [formulaire d'inscription](https://www.data.gouv.fr/fr/register?next=%2Ffr%2Flogin) les champs ajoutés par udata-front sont traduits et pas ceux venant de `flask_security`.

**Comment by maudetes** [comment]
Le problème vient de ce setting additionnel introduit par erreur : https://github.com/opendatateam/udata/blob/d69ddfa5e0eed547201d59d397a325b961f06521/udata/settings.py#L103
Il sera corrigé dans https://github.com/opendatateam/udata/pull/2897
