### ISSUE TITLE
Ajout de commentaires sur discussion fermée

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#1139]
## Description du bug
Je suis pratiquement certain qu'il est possible d'ajouter un commentaire sur une discussion qui a été fermée.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Fermer une discussion
2. Ajouter un commentaire sur cette discussion via l'API
3. Constater le bug

Code pertinent https://github.com/opendatateam/udata/blob/6d4f3540b0c1b932534e353f55b2cc92d0481bac/udata/core/discussions/api.py#L106

## Comportement attendu
Si une discussion est fermée, il n'est pas possible d'ajouter un autre commentaire.

**Comment by AntoineAugusti** [comment]
@maudetes Wonderful! J'ai même hésité à faire une PR étant donné que j'avais déjà identifié le code path pertinent ^^

**Comment by maudetes** [comment]
Ahah oui merci :pray:
