### ISSUE TITLE
Simplifier le menu déroulant qui permet de choisir une licence

### ISSUE THREAD

**Issue by bboulesteix** [etalab/data.gouv.fr#114]
## Contexte

Quand une personne publie des données sur https://www.data.gouv.fr, elle a la possibilité de choisir une licence. Le choix d’une licence n’est pas obligatoire. Mais si la personne décide de choisir une licence, voici ce qui lui est proposé. 👇 

<img width="891" alt="capture d ecran 2018-11-30 16 42 12" src="https://user-images.githubusercontent.com/3286488/49298979-f0758f80-f4be-11e8-9d56-58723eaf7757.png">

Ça fait quand même **beaucoup** de licences, non ? 😎  

## Solution proposée

**Tenir compte du contexte, pour limiter les choix possibles**. Nous pourrions tenir compte du statut du producteur, pour afficher des licences appropriées, cohérentes avec son statut. Il faudrait alors distinguer deux cas : le cas où la publication est faite par un service public certifié est celui où la publication est faite par un particulier — si j’oublie d’autres cas, faites-moi signe.

### 1. La publication est faite par un service public certifié

Si la publication est faite par une administration, c’est-à-dire un service public certifié, reconnaissable à son badge, alors il ne faudrait proposer que 4 licences :

- licence ouverte (à choisir par défaut) ;
- OdBL ;
- licence homologuée (rare donc potentiellement facultative) ;
- pas de licence (la loi CADA s’applique alors).

Idéalement, dans 99 % des cas, les données publiées par des administrations devraient l’être sous [licence ouverte](https://github.com/etalab/licence-ouverte/blob/master/LO.md). 

### 2. La publication n’est pas faite par un service public certifié

Dans tous les autres cas, c’est-à-dire en l’absence de badge, pour tous les autres producteurs de données, nous proposerions les licences suivantes :

- licence ouverte ;
- OdBL ;
- domaine public.

## Questions

1. Devrions-nous créer un champ `Autre licence`, dans le menu déroulant qui permet de choisir une licence ? Ce champ permettrait à l’utilisateur de préciser la licence associée aux données, si cette dernière ne figure pas dans le menu déroulant. Est-ce une si bonne idée que ça ? Je ne sais pas. 🤔 Je pense que ce champ ne serait utilisé que par des utilisateurs très renseignés sur le sujet.
2. Dans quelle mesure les licences proposées sur https://www.data.gouv.fr sont elles influencées par les licences associées aux jeux de données moissonnés ? Je pose la question pour savoir si nous devons impérativement proposer la `LICENCE A`, sous prétexte qu’une ville publie des données sous `LICENCE A` sur sa plateforme, avant de faire moissonner sa plateforme par https://www.data.gouv.fr. De mon point de vue, ce n’est pas nécessaire. Les licences proposées dans le cadre de données publiées depuis l’interface de https://www.data.gouv.fr n’ont pas à inclure toutes les licences récupérées dans le cadre des moissonnages, puisqu’on parle de **nouveaux** jeux de données, de créations et non pas d’importations.
3. Pourrions-nous ajouter des explications sur ce qu’implique le choix de telle ou telle licence ? Peut-être pas dans le menu déroulant directement, mais pas loin. L’idée consisterait à résumer très rapidement à l’utilisateur ce que permet de faire la licence qu’il vient de choisir — les gens cools parlent de _feedback loop_, je crois. GitHub fait ça très bien. Voir plus bas. 👇 

<img width="992" alt="capture d ecran 2018-11-30 17 02 02" src="https://user-images.githubusercontent.com/3286488/49300110-af32af00-f4c1-11e8-8058-9a43d825f8b0.png">

_P.-S. Les suggestions ci-dessus ont en très grande partie été soufflées par @mchoquet._ 🙏

**Comment by abulte** [comment]
Merci @bboulesteix pour ces suggestions. Je suis évidemment pour qu'on puisse simplifier cette partie particulièrement absconse du processus de publication 👏. Mais comme tout bon développeur je me pose la question du stock :-) Qu'est-ce qu'on fait de tout ce qui existe et qui ne rentre pas dans le nouveau _scope_ ? D'ailleurs ce serait intéressant de savoir ce qui est choisi aujourd'hui, je vais essayer de sortir quelques stats.

**Comment by jdesboeufs** [comment]
Pour information geo.data.gouv.fr est en train d'être adapté. Le partie publication ne produira plus que de la LO 2.0 (par défaut) et de l'ODbL (opt-in).

Par contre @bboulesteix je pense que dans ton cas 2 il faut laisser du choix car justement les organismes qui ne sont pas des services publics ont le choix, et peuvent être amenés à utiliser CC0 ou d'autres licences influencées par leur écosystème.

J'aime bien ce que fait GitHub dans ce cas là.
<img width="313" alt="capture d ecran 2018-12-03 a 11 06 40" src="https://user-images.githubusercontent.com/1231232/49367179-9279bf80-f6eb-11e8-811f-5ad816a75634.png">

**Comment by cquest** [comment]
+1 avec la proposition et la remarque de Jérôme

Pour les services public certifiés, choix limités (LO sélectionnée par défaut)
Pour les autres producteurs, réordonner pour avoir les choix les plus courants en premier (LO, ODbL) mais tout laisser... je supprimerai même éventuellement le "pas de licence"

**Comment by agarrone** [comment]
Je clos cette issue car traité dans un autre ticket.
