### ISSUE TITLE
Remplacer le formulaire Infolettre Dolist par Brevo (HP datagouv)

### ISSUE THREAD

**Issue by mikoa9** [etalab/data.gouv.fr#1142]
Aujourd’hui on passe par le formulaire Dolist : https://f.info.data.gouv.fr/f/lp/infolettre-data-gouv-fr-landing-page/lk3q01y6  qui met automatiquement à jour la liste de contacts de notre infolettre. On souhaite dorénavant passer par l’outil Brevo avec le même type de système.

A faire :
- Recréer la maquette de la landing page sur Brevo : https://landingpages.brevo.com/editor/ed5c87fb-cfa8-40f4-889c-c1d3a349bc11/design/9d702c41-2d18-47db-8d20-bbdab8a641fe
- Vérifier les paramétrages 
- Remettre à jour la liste de contacts, depuis dolist (+ tests ajout email, voir si cela remonte dans la base)
- Ajouter l’iframe sur la HP

A voir :
- On garderait la même URL que celle de Dolist : infolettre-data-gouv-fr-landing-page (à voir)
- En revanche on changerait le nom de domaine d’hébergement : info.data.gouv.fr (dolist) par data.gouv.fr (brevo) car on enverrait nos emails maintenant via : infolettre@data.gouv.fr et non plus infolettre@info.data.gouv.fr, ça ne pose pas de pb particulier ?

On en discute avant :)

Merci

Clarisse

**Comment by agarrone** [comment]
Thanks à discuter à la prochaine planif :)

**Comment by agarrone** [comment]
Link : https://qvo970cr.sibpages.com/
@maudetes
