### ISSUE TITLE
Prévoir un empty state lorsqu'on a pas d'image

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1146]
![Image](https://github.com/etalab/data.gouv.fr/assets/60264344/31c0a051-f717-4940-96e2-5e650899c59d)

En particulier pour les reuses et les orgas

**Comment by maudetes** [comment]
C'est ok pour toi Antonin si on clôt du coup?

**Comment by agarrone** [comment]
Yes
