### ISSUE TITLE
Filtre de ressources par schéma : ne pas inclure datapackages

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#1148]
## Description du bug
Le filtre des ressources par schéma fait apparaitre les schémas qui sont de type datapackage `"schema_type": "datapackage"`

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à https://www.data.gouv.fr/fr/datasets/
1. Cliquer sur le filtre de schéma
1. Constater le bug
![image](https://github.com/etalab/data.gouv.fr/assets/295709/c85d5fae-c43b-436c-a0d8-18590d35f74c)

`etalab/schema-irve` est un datapackage

## Comportement attendu
Je ne pense pas qu'il soit pertinent de proposer un filtre pour un schéma "datapackage", qui est plus virtuel qu'autre chose

**Comment by maudetes** [comment]
J'attendrais confirmation de @geoffreyaldebert, mais on peut facilement ajouter une logique d'exclusion de schémas. J'ai fait un premier jet dans https://github.com/opendatateam/udata/pull/2882 mais il va falloir mettre à jour la logique front.

**Comment by geoffreyaldebert** [comment]
Hello, en l'état, je suis d'accord avec @AntoineAugusti et je pense qu'on pourrait les exclure du champs de recherche. Ta logique me convient bien @maudetes go 🚀

**Comment by thbar** [comment]
Ça me paraît logique aussi et je crois que ça ne remonte rien actuellement si ne me trompe pas !

Par contre petit regard "utilisateur" là dessus que ça m'évoque : je suis en train de consommer les fichiers IRVE autant statiques que dynamiques (on va à la pêche aux producteurs ayant des fichiers invalides avec @cyrilmorin en ce moment) et je me suis un peu posé la question de savoir si à un moment, un consommateur de package pourrait justement souhaiter avoir un filtre pour dire "donne moi tout ce qui touche à ce package" en global.

Evidemment, on peut faire N paginations sur le endpoint datasets (une par schéma qui m'intéresse), mais je me demandais si à défaut de chercher par datapackage (ça m'aurait été utile dans ce cas précis pour ne pas paginer tout 2 fois), on pourrait chercher en OR ("schema1" OR "schema2") ?

En lisant https://guides.data.gouv.fr/publier-des-donnees/guide-data.gouv.fr/api/reference/datasets par exemple j'ai l'impression que cette possibilité n'est pas évoquée.

Ce n'est pas dramatique de paginer deux fois quand on a 2 schémas, mais potentiellement ça serait intéressant ergonomiquement parlant (et intéressant si on veut faire du "batch" en filtrant sur 10, 15 schémas pour des consolidations plus généralisées).

Voilà curieux d'avoir votre input là dessus :-)

**Comment by maudetes** [comment]
Merci pour ce retour !
Aujourd'hui, ce n'est pas possible de filtrer avec un OR (c'est aussi absent pour les autres filtres : organisations, tags, etc). Ca pourrait éventuellement être envisagé, mais j'ai pas l'impression que ça ait beaucoup été remonté comme besoin jusqu'ici par contre.
Sinon, vu votre use case, vous pourriez partir du [catalogue des ressources en CSV](https://www.data.gouv.fr/fr/datasets/catalogue-des-donnees-de-data-gouv-fr/#/resources/4babf5f2-6a9c-45b5-9144-ca5eae6a7a6d) et le filtrer sur la colonne schéma, **qui ne semble pas exister aujourd'hui** ! Dans tous les cas, je pense qu'on peut rajouter cette info dans le catalogue (cc @Pierlou qui peut être intéressé).

**Comment by thbar** [comment]
Merci @maudetes. Oui ça semble un cas à la marge à ce stade, clairement :smile: merci pour la suggestion ça pourrait aider !
