### ISSUE TITLE
Problème d'affichage des anomalies via la notif mail

### ISSUE THREAD

**Issue by romtal** [etalab/data.gouv.fr#115]
Lorsqu'on reçoit un mail indiquant une anomalie sur un jeu de données, le lien du mail renvoie vers la page du jeu de données sans ouvrir la popup de l'anomalie...
Certains producteurs n'ayant pas le réflexe de cliquer sur le bouton rouge, l'anomalie n'est du coup pas toujours traitée...

**Comment by agarrone** [comment]
Les anomalies sont dépréciées et seront intégralement repensées durant la prochaine thématique.
