### ISSUE TITLE
Mise à jour du footer et mise en place de bandeau infolettre

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1154]
![Image](https://user-images.githubusercontent.com/60264344/262926538-62c961c6-e20c-490c-8fc5-a1c524b27f45.png)

Voir Figma : https://www.figma.com/file/TUJ8QkHNkJRHolBflBThyP/Menu-data.gouv.fr?type=design&node-id=54%3A24770&mode=design&t=UBIUKli9HFNpgW0P-1

Edit :

Nouveau lien : https://www.figma.com/file/fvtAhJSd1hURLxy8GXmc3k/%F0%9F%8E%81-%5BWIP%5D-Syt%C3%A8me-U?type=design&node-id=40-6910&mode=design&t=40rz947PQR4ERXxR-0

**Comment by maudetes** [comment]
A voir si on peut rajouter un petit lien vers https://social.numerique.gouv.fr/@datagouvfr :)
