### ISSUE TITLE
Résoudre incohérence des résultats de recherche sur la page orga

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1156]
Signalement d'incohérence sur la recherche au sein d'une organisation : https://support.etalab.gouv.fr/#ticket/zoom/64081.
Pour reproduire, aller sur la page https://www.data.gouv.fr/fr/organizations/haute-autorite-de-sante-has/?q=2021#/datasets, avec le filtre de recherche « 2021 ».

Puis sur celle-là sans le filtre de recherche https://www.data.gouv.fr/fr/organizations/haute-autorite-de-sante-has/#/datasets (fonctionne dans un autre onglet, ou même en repassant via la page de recherche des organisations).
Seuls 10 résultats sont retournés, alors qu'il devrait y en avoir 31.
![image](https://github.com/etalab/data.gouv.fr/assets/28541902/5febf00b-a8e1-4fdd-ab36-43cb9dd75b6c)

Un autre bug lié : en cherchant « 2022 » à partir de la page avec la recherche sur 2021, le filtre d’organisation saute et retourne 4345 résultats.

Reproduit sur Firefox, connecté ou en navigation privée.

**Comment by nicolaskempf57** [comment]
Pour le premier point, ça a l'air d'être un problème de cache côté jinja. On a ce comportement sur la page, dans le code source sur navigateur et via curl.

J'essaie de reproduire le 2e point. Pour l'instant j'ai réussi une seule fois, sans l'inspecteur web. J'imagine que la requête se fait sans l'id de l'orga mais je ne sais pas encore pourquoi
