### ISSUE TITLE
recupération de ressource en échec depuis point de moissonnage ckan

### ISSUE THREAD

**Issue by mkazmiers** [etalab/data.gouv.fr#116]
Bonjour,

Nous testons actuellement le moissonnage de CKAN DATASUD vers data.gouv.fr.
La déclaration du point de moissonnage et le filtre sur une 'organisation' fonctionnent.
La remontée de ressources des datasets ckan est par contre systématiquement en échec : 
![image](https://user-images.githubusercontent.com/16324693/50334024-4f9b5280-0507-11e9-9ced-9fd71fb1b1e9.png)

Le nom des ressources est détecté.
![image](https://user-images.githubusercontent.com/16324693/50334053-65107c80-0507-11e9-992c-efcc6a080558.png)

J'ai vérifié, ces données sont téléchargeables en un clic dans CKAN. Ex. pour le dataset filaire-des-voies-accm : https://trouver.datasud.fr/dataset/filaire-des-voies-accm/resource/577c830f-8d18-4400-952f-f6787a72ed78

D'où peut venir ce problème ?

Merci pour votre retour,
Mathieu

**Comment by abulte** [comment]
Le moissonneur attend dans le champ `resource_type` de l'API de ckan le type de ressource (comme son nom l'indique) et non le nom du fichier. Il semble y avoir une déviation par rapport modèle standard de ckan dans votre cas.

Les `resource_type` que nous reconnaissons sont les suivants :

```
RESOURCE_TYPES = ('file', 'file.upload', 'api', 'documentation',
                  'image', 'visualization')
```

Cf https://trouver.datasud.fr/api/3/action/package_show?id=filaire-des-voies-accm
