### ISSUE TITLE
Apparition d'un membre d'une orga plusieurs fois

### ISSUE THREAD

**Issue by IshanB** [etalab/data.gouv.fr#117]
## Description du bug
Julien-Pierre Durand apparaît plusieurs fois en tant que membre de l'organisation Saint-Etienne
![image](https://user-images.githubusercontent.com/28890473/50891594-e8353c00-13fc-11e9-8c13-038a59fb641d.png)

## Comment reproduire le bug
Peut-être dû aux pbs de timeout actuels de datagouv ?

**Comment by abulte** [comment]
A fin de debug, le détail des membres sur l'organisation. Les doublons ont été ajoutés dans la même seconde ou presque. Il me semble pourtant qu'on avait blindé le process au niveau de l'ajout de membres...

```
[(datetime.datetime(2019, 1, 8, 16, 48, 10, 841000), <User: Mehdi CHEBIRA>), (datetime.datetime(2019, 1, 9, 9, 35, 13, 692000), <User: Julien-Pierre DURAND>), (datetime.datetime(2019, 1, 9, 9, 35, 19, 175000), <User: Julien-Pierre DURAND>), (datetime.datetime(2019, 1, 9, 9, 35, 19, 259000), <User: Julien-Pierre DURAND>), (datetime.datetime(2019, 1, 9, 9, 35, 19, 368000), <User: Julien-Pierre DURAND>), (datetime.datetime(2019, 1, 9, 9, 35, 19, 463000), <User: Julien-Pierre DURAND>), (datetime.datetime(2019, 1, 9, 9, 35, 19, 558000), <User: Julien-Pierre DURAND>), (datetime.datetime(2019, 1, 9, 9, 35, 19, 674000), <User: Julien-Pierre DURAND>), (datetime.datetime(2019, 1, 9, 9, 35, 20, 974000), <User: Julien-Pierre DURAND>)]
```

**Comment by abulte** [comment]
TODO:
- isoler l'éventuel problème sur le front
- repasser la migration https://github.com/opendatateam/udata/blob/master/udata/migrations/2017-07-07-deduplicate-org-members.js une fois le fix 
https://github.com/opendatateam/udata/pull/1984 déployé

**Comment by abulte** [comment]
Repasser la migration et attendre

**Comment by agarrone** [comment]
@maudetes d'actualité ?

**Comment by agarrone** [comment]
So far so good
