### ISSUE TITLE
Validata front : l'utilisation de schémas "à la carte" semble cassée

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/data.gouv.fr#1170]
Détail des travaux d'investigations dans : https://gitlab.com/validata-table/validata-ui/-/issues/186

**Comment by amelie-rondot** [comment]
Intégré dans les travaux de la migration du projet vers un mono-repo

**Comment by amelie-rondot** [comment]
Nouvelle issue correspondante : https://gitlab.com/validata-table/validata-table/-/issues/8
