### ISSUE TITLE
Impossibilité de supprimer un jeu de données

### ISSUE THREAD

**Issue by romtal** [etalab/data.gouv.fr#118]
## Description du bug
Problème de suppression d'un jeu de données sur data.gouv.fr avec comme identifiant erreur : 58b53cee41e04726b03721d4a23ff7f7

Je ne suis pas parvenu à reproduire le bug...la fiche est maintenant supprimée...

![impossible modifier jeu de donnees](https://user-images.githubusercontent.com/15154033/50958330-bb4a5d00-14c0-11e9-8707-20247586de8b.JPG)

**Comment by abulte** [comment]
Merci @romtal. Il s’agit d’une erreur JS non liée à la suppression (problème de timing au chargement de l’app je pense) https://sentry.data.gouv.fr/etalab/www-datagouvfr/issues/531706/events/1691417/.

**Comment by taniki** [comment]
Je viens de vérifier. Ca fonctionne bien sur `next`. Comme indiqué par @abulte il s'agit d'un problème de chargement de la SPA admin
