### ISSUE TITLE
Dumps CSV : jeux de données introuvables

### ISSUE THREAD

**Issue by pierredittgen** [etalab/data.gouv.fr#119]
## Description du bug
Quand on utilise le dump CSV des organisations, jeux de données et ressources, pour certaines organisations, on obtient une liste de ressources associées à un jeu de données introuvables dans la liste des jeux de données.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Télécharger les dumps CSV :
  - wget https://www.data.gouv.fr/organizations.csv -O organizations.csv
  - wget https://www.data.gouv.fr/datasets.csv -O datasets.csv
  - wget https://www.data.gouv.fr/resources.csv -O resources.csv
2. Dans `organizations.csv`, chercher "Mairie d'Aire-sur-Adour" (id organisation : "5b9a1371634f417f35dc4a7c")
3. Dans `datasets.csv`, chercher les jeux de données relatifs à cette organisation : aucun résultat
4. Dans `resources.csv`, chercher les ressources relatives à cette organisation : 48 ressources !
    - les 48 ressources sont toutes liées à l'identifiant de jeu de données "5a95767ec751df6e3b4bb8f8"
    - cet identifiant est introuvable dans le fichier `datasets.csv`

## Comportement attendu
Je m'attends à trouver un jeu de données avec l'identifiant 5a95767ec751df6e3b4bb8f8 rattaché à l'organisation 5b9a1371634f417f35dc4a7c dans le fichier `datasets.csv`

Ce n'est pas un cas isolé :
- dans `resources.csv` je liste 28834 identifiants uniques de jeux de données
- dans `datasets.csv` je liste 20227 identifiants uniques de jeux de données
=> Il manque donc, a priori, au moins 8607 jeux de données  

Dans les faits, en effectuant la différence entre les deux ensembles d'identifiant, on constate que :
- dans `datasets.csv`, il y a 21 datasets absents de `resources.csv` (donc des jeux de données sans ressources)
- dans `resources.csv`, il y a 8628 identifiants de jeux de données absents de `datasets.csv` (donc des ressources sans jeux de données)

**Comment by abulte** [comment]
Bonjour Pierre,

Merci pour le signalement. Le problème racine est ici https://github.com/opendatateam/udata/issues/1977 et nous travaillons sur une solution ici https://github.com/opendatateam/udata/pull/1979.

Je ferme donc cette _issue_. Merci !

**Comment by pierredittgen** [comment]
Sur le dépôt https://github.com/pierredittgen/data.gouv.fr-check/, un nouveau script permet d'extraire la liste des identifiants de datasets référencés dans les ressources mais inconnus
 dans la table dataset

```bash
./dataset_resource_inconsistencies.sh 
Download dumps from data.gouv...
done.
Work on it...
Generating stats file dist/dataset_ids_not_found.csv

Dataset unique ids count in datasets table: 7196
Dataset unique ids number in resources.csv: 29987
Unknown dataset ids number in resources.csv: 23005
```

cf. [dataset_ids_not_found.zip](https://github.com/etalab/data.gouv.fr/files/3590032/dataset_ids_not_found.zip)

**Comment by abulte** [comment]
Si je prends la première ligne de  `dataset_ids_not_found.csv`, je tombe sur `53698e08a3a729239d20336f` qui est bien dans le fichier des datasets. J'ai raté un truc ?

```
$ cat data/datasets.csv|grep 53698e08a3a729239d20336f
"53698e08a3a729239d20336f";"2013-01 - Tableau synthétique de l’évolution de la demande et de la délivrance pour les principales catégories de visas";"2013-01-tableau-synthetique-de-levolution-de-la-demande-et-de-la-delivrance-pour-les-principales-categories-de-visas";"http://www.data.gouv.fr/fr/datasets/2013-01-tableau-synthetique-de-levolution-de-la-demande-et-de-la-delivrance-pour-les-principales-categories-de-visas/";"Ministère de l'Intérieur";"534fff91a3a7292c64a77f53";"Politique de délivrance des visas : Évolution de la demande et de la délivrance de visas (Les orientations de la politique de l’immigration)";"annual";"Licence Ouverte / Open Licence";"2006-01-01";"2010-12-31";"other";"France";False;False;"2013-07-08T16:07:20.345000";"2015-06-12T23:36:56.706000";"";0;0;0;0;0
```

**Comment by abulte** [comment]
Autrement si je reprends :
> => Il manque donc, a priori, au moins 8607 jeux de données

Ca correspond à l'ordre de grandeur du nombre de jeu de données qui seraient "oubliés" actuellement dans l'export à cause d'un glitch dans notre modèle de données : https://github.com/opendatateam/udata/issues/2306

**Comment by pierredittgen** [comment]
En relevant la taille maximale des lignes que csvcut peut gérer, ça fonctionne mieux (cf. https://github.com/pierredittgen/data.gouv.fr-check/issues/2).

Et le script ne relève plus d'erreur :
```bash
Dataset unique ids count in datasets table: 31410
Dataset unique ids number in resources.csv: 29987
Unknown dataset ids number in resources.csv: 0
```

Le problème a donc l'air corrigé côté données :-)

**Comment by abulte** [comment]
Top ! Je pense que le nouvel export a réglé pas mal de chose.
