### ISSUE TITLE
Documenter mieux l'api de publication de JDDs et ressources pour le swagger

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1191]
* Rajouter notamment de manière explicite les valeurs de retour d'erreur qui peuvent avoir lieu
* Enlever les champs non requis (last_update, last_modified, etc.?)

**Comment by ThibaudDauce** [comment]
> * Rajouter notamment de manière explicite les valeurs de retour d'erreur qui peuvent avoir lieu

Je veux bien plus d'information sur ce sujet. Tu aimerais avoir le contenu des réponses (la structure des erreurs de validation) ? Parce que le code d'erreur 400 est bien spécifié pour le moment.

>     * Enlever les champs non requis (last_update, last_modified, etc.?)

Concernant ce problème, c'est corrigé dans la PR https://github.com/opendatateam/udata/pull/2952 mais ça ne résoud pas le problème car, comme expliqué dans la description de la PR, c'est un problème d'upstream avec SwaggerUI.

**Comment by maudetes** [comment]
Je summon @nicolaskempf57 à l'origine de ce retour :)

**Comment by nicolaskempf57** [comment]
Pour les erreurs, il me semble que c'était surtout pour la partie ressource qui actuellement a seulement une documentation sur les 200, notamment la partie upload.

**Comment by maudetes** [comment]
Je pense qu'on peut clore ce ticket suite à https://github.com/opendatateam/udata/pull/2952.
On rouvrira au besoin :)
