### ISSUE TITLE
Recherche des JDD sur une organisation non filtrée sur l'organisation

### ISSUE THREAD

**Issue by AurelienC** [etalab/data.gouv.fr#1192]
## Description du bug
Lorsque je réalise une recherche dans les JDD sur la page d'une organisation, la recherche instantanée est bien filtrée sur l'organisation, mais si je clique ensuite sur "Recherche", le filtre de l'organisation n'est plus présent. 

<img width="427" alt="image" src="https://github.com/etalab/data.gouv.fr/assets/4528670/3b33aadc-2978-4b59-8156-66354ef738fb">

Vidéo : https://www.loom.com/share/858108069c0d41b6b4d6201d26c3f143?sid=cdc58905-53d2-44cb-9725-51d2eaa9db11

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller sur le profil d'une organisation
2. Cliquer sur l'onglet Jeux de données
3. Saisir un texte dans la barre de recherche (sans cliquer sur Recherche)
4. Constater que les résultats sont filtrés sur l'organisation (ou regarder dans l'inspecteur la requête)
5. Cliquer sur "Recherche"
6. Constater que les résultats ne sont plus filtrés sur l'organisation et qu'ils concernent l'ensemble des organisations de datagouv (ou regarder dans l'inspecteur la requête)

## Comportement attendu
La recherche lorsque l'on est sur la page d'une organisation devrait uniquement concerner celle-ci.

**Comment by maudetes** [comment]
Hello !
Merci pour la description du bug détaillé. Ce problème avait déjà été remonté (via https://github.com/etalab/data.gouv.fr/issues/1156) et un fix codé, mais le fix vient juste d'être déployé en production ce matin même.
Ca m'a l'air tout bon maintenant, je me permets donc de clore.

**Comment by AurelienC** [comment]
Parfait, merci ! Désolé pour le doublon.
