### ISSUE TITLE
Enquêter sur le fonctionnement des notifications aujourd'hui (focus sur les notifs des discussions)

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1213]
Notamment mieux comprendre la logique de "nouvelles" notifications

**Comment by quaxsze** [comment]
Résumé du mécanisme des notifications:

Le front query un endpoint dédié du backend toutes les 10 sec. Ce endpoint déclenche une série de fonctions, chacune correspondant à un type de notification. Il y en a actuellement 4 : discussions, demande de membre, demande de transfert, validation d'un moissonneur.
Chaque fonction récolte en base de données par exemple, toutes les discussions ouvertes en rapport avec l'utilisateur loggé lors de l'appel du front.
Le résultat est ensuite passé au front qui l'affiche dans l'onglet notifications.

Le méchanisme est tres simpliste et ne fait pas la différence entre les nouvelles notifications et les anciennes, celles lues ou non. Il compile à chaque appel toutes les notifications et les envois au front, qui écrase simplement l'ancienne liste de notification par la nouvelle. Ce système marche bien pour l'intant mais une refonte est à prévoir si on veut un jour un système plus intelligent.

**Comment by maudetes** [comment]
Pour info @agarrone

**Comment by agarrone** [comment]
Merci 🙏 
Ca demande une refonte oui ...
