### ISSUE TITLE
Mise en prod meteo.data.gouv.fr 🚀

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#1216]
### Data
- [ ] Mettre seulement les nouveaux jeux de données @geoffreyaldebert 
- [x] Supprimer les doublons @Pierlou 
- [ ] Créer les 3 topics @geoffreyaldebert 
- [x] Enlever les extras @maudetes 

### Front
- [x] Rajouter le lien vers le jeu de données dans la recherche guidée @geoffreyaldebert 
- [x] #1220 @Jorek57 @nicolaskempf57 
- [x] #1227 @Jorek57 @nicolaskempf57
- [x] #1221 @geoffreyaldebert 
- [x] #1226 @Jorek57 @nicolaskempf57 
- [x] #1217 @Jorek57 @nicolaskempf57 
- [x] #1223 @Jorek57 @nicolaskempf57 
- [x] #1232
- [x] #1222 @Jorek57 @nicolaskempf57 
- [x] #1228 @agarrone @Jorek57 @nicolaskempf57
- [x] Renommer tout en thématique plutôt que "packs" dans la page recherche guidée @geoffreyaldebert 
- [x] #1236

### Ops
- [ ] Mep changement ansible @jordanguedj 

### Product & com 
- [x] Page à propos : faire une proposition @agarrone https://www.notion.so/apigouv/Page-propos-meteo-data-gouv-fr-cd9f54a887ef48b7af3f9accefc682fe
- [x] Valider article @agarrone https://www.notion.so/apigouv/Communication-meteo-data-gouv-fr-Article-4b88077ba5774b5188387af75d3bf961
- [ ] Publier article @agarrone 
- [ ] Publier annonce réseaux sociaux @agarrone 
- [x] Faire un form de feedback @agarrone https://tally.so/r/wQ7y47
- [ ] Envoyer infolettre @agarrone 

### Front
- [x] Aligner les cartes thématiques @Jorek57 @nicolaskempf57 
- [x] #1225 @Jorek57 @nicolaskempf57 
- [x] #1224 + [figma](https://www.figma.com/file/LXSt7OH4jGh6yJcc8Dsk6O/%F0%9F%86%95-Verticales-data.gouv.fr?type=design&node-id=108-34059&mode=design&t=K5gjxE9pl8FYvEYi-4) @Jorek57 @nicolaskempf57 
- [x] #1231
- [x] #1233
- [x] Alignement de haut de page, différents sur chaque page @Jorek57 @nicolaskempf57 
- [x] #1234
- [x] #1235
- [x] #1230

**Responsive**
- [x] #1238
- [x] #1239

**Home**
- [x]  Hero trop court
- [ ]  Titre à passer en extra bold
- [ ]  Font tagline un peu petite
- [ ]  Tagline à mettre sur deux lignes
- [ ]  Bar de recherche pas alignées sur le cadre
- [x]  Ecart entre titre “thématiques” et les tuiles trop grand
- [ ]  Rajouter un peu de white space après les tuiles
- [x] #1240

**Jeux de données**
- [ ] #1260
- [ ] #1259
- [x] #1251
- [x] #1241
- [x]  Fil d’arianne un tout petit peu trop haut (sur toutes les pages)
- [ ] #1258

**Jeu de données**
- [ ] #1246
- [ ] #1245
- [x] #1252
- [x] #1244
- [x] #1247
- [x] #1248
- [x] #1250
- [ ] #1253
- [ ] #1254

**Recherche guidée**
- [ ]  Normal les intitulés de type “SQR” “SIM” “LSH” ?
- [x] #1249

**Page À propos**
- [ ]  Lien sont lourd à la lecture
- [ ]  *adresser à Météo-France en commentant le jeu de données concernant votre demande (onglet discussion de la page du jeu de donnée)*. (pourquoi tout en italique ?)

**Comment by streino** [comment]
> > [ ] Mettre un titre et sous titre sur chacune des pages @agarrone @Jorek57 @nicolaskempf57
> 
> Pour la page A propos, pour enlever l'italique, il faut modifier le gist de @geoffreyaldebert pour enlever les `***` de `# ***À propos de meteo.data.gouv.fr***`

Sinon maintenant vous pouvez mettre le .md dans le repo. Cf https://github.com/ecolabdata/ecospheres-front/blob/main/configs/ecospheres/config.yaml#L63
