### ISSUE TITLE
Wording home

### ISSUE THREAD

**Issue by nicolaskempf57** [etalab/data.gouv.fr#1227]

**Comment by agarrone** [comment]
@geoffreyaldebert prefere le wording actuel donc je pense qu'on peut clore ?

**Comment by agarrone** [comment]
On reste sur le titre en préprod "La météo et le climat en Open Data"
 
 Retours de MF cependant sur la tagline : 
- "meteo.data.gouv.fr centralise et structure les données publiques de Météo-France relatives à la météo et au climat.
Vous y trouverez des données téléchargeables et utilisables de manière libre et gratuite."
