### ISSUE TITLE
Problème d'ajout d'une nouvelle ressource sur un jeu de données depuis le frontend

### ISSUE THREAD

**Issue by romtal** [etalab/data.gouv.fr#123]
## Description du bug

Impossibilité de créer une nouvelle ressource !
Lorsque je clique sur "Ajouter une ressource" il fait apparaître un écran de glisser-déposer qui disparaît aussitôt. Ceci sur Firefox et également sur Chrome.

**Comment by abulte** [comment]
Hello,

Plus d'info ? Un message ou un identifiant d'erreur ? Je ne reproduis pas sur data.gouv.fr sous Chrome.

A quel moment tu crées une ressource ? Lors de la création d'un JDD ou lors de l'édition ?

**Comment by abulte** [comment]
Reproduction
- page JDD sur frontend
- bouton "ajouter une ressource"
- on arrive dans l'admin et à la fin du chargement de la page, la popup disparait
