### ISSUE TITLE
Indicateur de disponibilité erroné

### ISSUE THREAD

**Issue by flacombe** [etalab/data.gouv.fr#125]
## Description du bug
Plusieurs ressources de plusieurs jeux de données mènent à des 404 mais l'indicateur de disponibilité reste à Disponible.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à https://www.data.gouv.fr/fr/datasets/close-data-ipe/
2. Essayer de télécharger la première ressource associée à ce jeu de données.
3. Constater un 404 sur le site du partenaire
4. Pourtant l'indicateur de disponibilité est vert

## Comportement attendu
L'indicateur de disponibilité devrait être à l'état "Indisponible".

**Comment by abulte** [comment]
Bonjour,

Merci pour votre signalement.

Le problème se situe au niveau de la réponse à une requête `HEAD` de la plateforme data.paysdelaloire.fr : on récupère un statut HTTP `200` alors que le `GET` est bien en `404`.

Nous maintenons une liste d'exclusions pour les plateformes qui n'implémentent pas correctement le `HEAD`, nous allons certainement y ajouter cette plateforme.

**Comment by flacombe** [comment]
Merci pour l'explication, je comprends le soucis.

Ainsi cette liste d'exclusion provoque l'appel d'un GET et pas d'un HEAD ?
Les administrateurs seront-ils prévenus ?

**Comment by abulte** [comment]
En effet, pas de HEAD mais un GET. Nous n'avons pas de système de notification des administrateurs à ce sujet.

**Comment by flacombe** [comment]
Ok c'est noté merci
J'attends de voir passer le statut du fichier à indisponible suite à la mise du fournisseur dans la liste d'exclusions

**Comment by abulte** [comment]
Ce jeu de données a visiblement été supprimé, je ferme l'issue.

**Comment by flacombe** [comment]
Merci Alexandre pour le support en tout cas
