### ISSUE TITLE
Bandeaux discussions pas tout à fait le même que sur data.gouv.fr

### ISSUE THREAD

**Issue by Jorek57** [etalab/data.gouv.fr#1250]

**Comment by Jorek57** [comment]
@agarrone Tu saurais me détailler l'attendu sur cette demande ?

**Comment by agarrone** [comment]
Je parle de ce bandeau 
<img width="1163" alt="image" src="https://github.com/etalab/data.gouv.fr/assets/60264344/68ce6db2-0a34-4a1b-8d82-56bd624a3d89">
Que Geoffrey a refait mais on dispose d'un composant que @nicolaskempf57 pourra te pointer :)

**Comment by nicolaskempf57** [comment]
Hello ! C'est moi qui ait fait le bandeau. Il est pas "composantisé" encore mais normalement il est conforme aux Figma des verticales et de Système U (en dehors de la marge qu'il faut augmenter pour tous les sites).

Par contre, effectivement, la police Spectral parait plus petite que la police Marianne qu'on a sur data.gouv.fr (sur le parcours de publication en step 2 par ex).
