### ISSUE TITLE
Reintialiser la recherche de la barre de recherche du header ne reanitialise pas la page

### ISSUE THREAD

**Issue by Jorek57** [etalab/data.gouv.fr#1259]

**Comment by Jorek57** [comment]
@agarrone  Si je comprend bien, tu souhaiterais un rechargement de la page lors d'un clic sur la croix ?
![Capture d’écran 2024-01-02 à 16 06 11](https://github.com/etalab/data.gouv.fr/assets/43407933/82cf4890-7eb1-4d66-862d-d105c1621d2d)

**Comment by agarrone** [comment]
Yes comme sur data.gouv.fr
