### ISSUE TITLE
[transport.data.gouv.fr] Recherche ? projet d'homogénisation avec data.gouv ?

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#126]
## La barre de recherche sans critères ne renvoie à aucun datasets
Le lancement de la recherche pourrait amener à la liste des datasets "transport". toutes les **datasets transport**
Un utilisateur novice trouver perturbant le comportement actuel, pour l'instant zéro résultat (sans aucun critère) et un mot clé comme Bourgogne ou Comté ne renvoie aucun résultat.
Par contre **belfort** amène aux fiches **d'Optymo**
Hors pour prendre connaissance, d'initiatives locales , on pourrait avoir tendance à passer par un ensemblier géo

## Les alternatives possibles, l'autocomplétion filtré sur la **thématique Transport.**
Harmoniser les comportement avec la barre de recherche de data.gouv.fr.
Une autocomplétion sur les datasets (title) mais également sur les zones géographiques (territoires) et organisation concernant les données transport.

Notre besoin est de nous permettre de retrouver facilement les données ouvertes du transport concernant la région BFC.
Comme les données ouvertes (style GTFS) sont déposées par les entreprises :+1: 
Ex : 
https://www.data.gouv.fr/fr/datasets/arrets-circuits-et-horaires-du-reseau-optymo-de-belfort/

Notre optique est d'y voir plus clair en tant qu'utilisateur.

D'avance Merci,

**Comment by Tristramg** [comment]
Bonjour,

Merci pour ce retour. On a créé une issue pour le bug de la recherche vide https://github.com/etalab/transport-site/issues/638

Pour ce qui est de la recherche par région, c’est un chantier en cours, vous pouvez suivre le ticket sur : https://github.com/etalab/transport-site/issues/623

Il y a une astuce cachée pour avoir les jeux de données d’une région, c’est d’aller sur https://transport.data.gouv.fr/stats, cliquer sur la région et on obtient un lien : https://transport.data.gouv.fr/datasets/region/1

C’est clairement pas optimal, et on y travaille :)
