### ISSUE TITLE
Ajouter un lien vers les portails moissonnés sur la page des jeux de données qui ont été moissonnés.

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#127]
## L’amélioration que vous avez en tête

Quand je suis sur la page d'un jeu de données moissonnée depuis une autre plateforme, je souhaiterais pouvoir avoir un lien qui me renvoie vers le portail en question.

Par exemple, sur la page [Indicateurs de résultat des lycées d'enseignement général et technologique ](https://www.data.gouv.fr/fr/datasets/indicateurs-de-resultat-des-lycees-denseignement-general-et-technologique-1/#_), je voudrais pouvoir aller directement à la page [Indicateurs de résultat des lycées d'enseignement général et technologique ](https://data.education.gouv.fr/explore/dataset/fr-en-indicateurs-de-resultat-des-lycees-denseignement-general-et-technologique/information/) sur data.education.gouv.fr afin de voir comment la donnée est présentée sur cette plateforme.

Je découvre à l'instant que je peux avoir le lien en cliquant sur la boîte détail dans la barre de droite. Je trouve que ce serait pas intéressant de montrer ce lien par défaut et surtout de le rendre clicable.

![detail data gouv](https://user-images.githubusercontent.com/3227753/54746946-c9f27600-4bcd-11e9-84a2-6e8ca0ba7181.png)

Ce serait intéressant aussi d'afficher que le jeu de donnée a été moissonné.

**Comment by taniki** [comment]
problème traité dans la PR ci-dessus
