### ISSUE TITLE
Traduction des message d'erreur en français

### ISSUE THREAD

**Issue by mikoa9** [etalab/data.gouv.fr#1275]
Nous avons eu un ticket support d'une personne se plaignant de messages en anglais, notamment lorsqu'on lui retourne une erreur de son mdp sur la page de connexion https://www.data.gouv.fr/fr/login

ça vaudrait le coup de faire une repasse rapide sur ces différents messages d'erreurs/champs et les traduire :)

Merci,
Clarisse

**Comment by mikoa9** [comment]
pour info @agarrone

**Comment by maudetes** [comment]
C'est corrigé, et la correction est bientôt déployé en prod!
Voir aussi : https://github.com/etalab/data.gouv.fr/issues/1131
