### ISSUE TITLE
Rajouter dans les extras udata l'information de l'APIfication hydra

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1284]
A la fin d'une APIfication hydra, pinger udata pour rajouter l'info dans les extras.
Il faut choisir quelle info indiquer, et quel wording. Exemple d'infos qu'on pourrait indiquer :
* la date de mise en base
* l'URL vers API tabular  /data et /profile ?
* .. ?

**Comment by Pierlou** [comment]
Initiated in https://github.com/etalab/udata-hydra/pull/91, now we have to agree on the syntax

**Comment by maudetes** [comment]
Fait dans https://github.com/etalab/udata-hydra/pull/91
