### ISSUE TITLE
Encodage de la description d'une organisation

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#129]
## Description du bug
Des caractères spéciaux sont échappés sur une page de jeu données : la description d'une organisation

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à https://www.data.gouv.fr/fr/datasets/audiences-quotidiennes-des-principaux-sites-web-gouvernementaux/#_
2. Regarder la description de l'organisation
3. Constater la présence du symbole `&gt;`

**Comment by ThomasG77** [comment]
Plus reproductible. Soit parce que disparu soit parce que `>` ou `&gt;` n'est plus utilisé dans l'exemple.

**Comment by maudetes** [comment]
Indeed. Please reopen if relevant again.
