### ISSUE TITLE
Calendrier de la zone A - date manquante

### ISSUE THREAD

**Issue by FredMa01** [etalab/data.gouv.fr#1292]
Dans le calendrier de la zone disponible à l'adresse suivante : https://fr.ftp.opendatasoft.com/openscol/fr-en-calendrier-scolaire/Zone-A.ics, il manque la date des Vacances d'Été (prérentrée Enseignants ) : 30/08/2020 au 31/08/2020 

A voir si cela peut être corrigé car cette absence est source d'erreurs pour certains scripts.
Il en est peut-être de même pour les autres zones.

**Comment by maudetes** [comment]
Bonjour,
Ce canal de support est dédié aux demandes relatives à la plateforme data.gouv.fr elle-même. L'équipe de [data.gouv.fr](http://data.gouv.fr/) n'est pas responsable des données publiées sur la plateforme.

Nous vous conseillons de contacter directement le producteur des données (en bas de la page du [jeu de données concerné](https://www.data.gouv.fr/fr/datasets/le-calendrier-scolaire)). Les producteurs seront capables de répondre à votre question.
