### ISSUE TITLE
Correction, investigation réuses 404

### ISSUE THREAD

**Issue by mikoa9** [etalab/data.gouv.fr#1296]
Suite à notre point :

- [x] Voir pourquoi les exports ne remontent plus dans mattermost (canal  datagouv-curation) depuis le 15/01
- [x] Voir si les réuses 404, 403, etc sont bien prises en compte dans les 5949 reuses et pas les 4XXX
- [x] Enlever dans l’extract les réuses archivées
- [ ] dans extract, exclure les 403 qui redirigent bien vers des URL fonctionnelles (pb de l'user agent?)
- [x] Vérifier la différence entre les réuses qui renvoient vers des pages d’erreur (base airtable) vs réuses de l’extract (canal mattermot) pour les rebasculer si besoin dans l’extract curation. Car actuellement env 150 réuses dans extract vs 770 (airtable). Exemples de réuses non remontées sur l’extract du canal :
- https://www.data.gouv.fr/fr/reuses/base-officielle-des-codes-postaux-croisee-avec-les-donnee-geofla-r-communes/ (404)
- https://www.data.gouv.fr/fr/reuses/carte-de-la-qualite-de-vie-dans-les-territoires/
- https://www.data.gouv.fr/fr/reuses/route-du-rhum-une-carte-interactive-du-port-avant-le-depart/
- ...

Base airtable : https://airtable.com/appuaB2XsPhF7vMNx/tblq1PDSiRxK2ezac/viwRqmNTEI1CH0Tn9?blocks=hide
Tableau recap https://airtable.com/appuaB2XsPhF7vMNx/pagkEk1aDHqqozE7N

Merci !

Clarisse

**Comment by mikoa9** [comment]
@Pierlou pour les réuses archivées, c'est ce qu'on avait constaté ensemble au niveau de l'export... mais là en les checkant une par une impossible d'en trouver. Peut-être en regénérant l'export, ça a fait sauter ces cas ? En tout cas oui il faut bien exclure les réuses archivées :)
OK pour les 4526 réuses au total, du coup effectivement pas synchro avec les réuses retournées sur la home. Mais ce ticket n'est pas déjà clos : https://github.com/etalab/data.gouv.fr/issues/1262 ?
Clarisse

**Comment by Pierlou** [comment]
[Ce patch](https://github.com/etalab/datagouvfr_data_pipelines/pull/164) résout une bonne partie du problème (le contourne en réalité), en parcourant les reuses par batch (toujours en asynchrone) pour pallier les inconsistances qui apparaissaient en utilisant de l'asynchrone sur la liste complète. Ca nous donne un peu plus de 1000 reuses qui ne répondent pas correctement.

**Comment by Pierlou** [comment]
La différence avec la homepage peut s'expliquer car le nombre indiqué sur la home ne prend pas en compte les reuses privées et celles qui n'ont pas de JdD associé.
