### ISSUE TITLE
Améliorer l'environnement de dev udata-front

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1298]
Notamment le hot-reload anormalement long, l'absence d'extension VueJS, etc.

**Comment by nicolaskempf57** [comment]
Lien vers la doc vite sur l'utilisation avec un back-end existant : https://vitejs.dev/guide/backend-integration.html (notamment le point 2. pour les fichiers en env de dev)

**Comment by nicolaskempf57** [comment]
Une configuration `vite` de dev a été ajoutée (https://github.com/etalab/udata-front/pull/372). Elle fonctionne toujours grâce à un build à chaque changement de fichier (`vite build --watch)` et non via le serveur de vite (`vite dev`).

Les différences de configuration sont les suivantes :
- pas de build legacy : gain de temps sans changement en environnement de dev avec navigateur récent
- copie des fichiers `dist` des librairies au lieu de les intégrer à vite : gain de temps sans changement en environnement de dev avec navigateur récent
- utilisation de `vue.esm-browser.js` au lieu de `vue.esm-browser.prod.js` : permet l'activation de vue-devtool
