### ISSUE TITLE
Correctifs des liens dans le footer

### ISSUE THREAD

**Issue by nicolaskempf57** [etalab/data.gouv.fr#1299]
* Corriger lien feedback
* Remplacer « Open Data University » par « defis.data.gouv.fr avec le liens vers https://defis.data.gouv.fr/

**Comment by nicolaskempf57** [comment]
Corriger également les traductions pour Github et Mastodon

**Comment by agarrone** [comment]
![image](https://github.com/etalab/data.gouv.fr/assets/60264344/14187dfc-5413-49bc-b9ca-00f95f866868)
Corrections prévues
