### ISSUE TITLE
Pouvoir télécharger tous les fichiers d'une page d'un coup

### ISSUE THREAD

**Issue by noirbizarre** [etalab/data.gouv.fr#13]
_From @letailli on November 28, 2013 16:0_

Pour des pages avec de nombreux fichiers. Exemple :
http://www.etalab2.fr/fr/dataset/effectifs-d-etudiants-inscrits-dans-les-etablissements-et-les-formations-de-l-enseignement-superieur

_Copied from original issue: etalab/etalab-support#4_

**Comment by jdesboeufs** [comment]
On peut fermer non ? Ça parait sévèrement obsolète.

**Comment by bboulesteix** [comment]
Je suis d’accord pour dire que cette fonctionnalité serait utile, notamment pour les jeux de données qui contiennent beaucoup de ressources. À titre d’exemple, GitHub permet de télécharger l’intégralité d’un dépôt sous la forme d’un dossier zippé (`.zip`).

<img width="432" alt="capture d ecran 2018-12-17 16 42 56" src="https://user-images.githubusercontent.com/3286488/50097827-fdaeb000-021a-11e9-88ae-7845cf34a3bf.png">

**Comment by abulte** [comment]
A voir si les [data packages](https://frictionlessdata.io/data-packages/) peuvent être intéressant ici.

**Comment by jdesboeufs** [comment]
Honnêtement je pense que la structure du fichier de sortie n'a pas une grande importance à ce stade.

Côté des données déversées par geo.data.gouv.fr, nous en sommes toujours à publier 3/4 liens par ressources, car nous proposons différents formats à notre écosystème assez fragmenté.

Ne pourrions-nous pas déjà renforcer notre modèle de ressources et l'outillage du front avant de proposer de zipper en masse sans savoir ce qui est pertinent à mettre dedans ?
