### ISSUE TITLE
Rajouter des badges sur les organisations

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1306]
A l'image de ce qui est fait pour le badge service public https://github.com/opendatateam/udata/blob/8aad1a8a647e19406d63dc510b6a3674c539de81/udata/core/organization/models.py#L37.

* Collectivité territoriale
* Association
* Entreprise

**Comment by geoffreyaldebert** [comment]
proposition : 

 alors pour les badges à rajouter sur les orgas : 
- Collectivité territoriale : 
```
{
    "kind": "local-authority"
}
```
- entreprise : 
```
{
    "kind": "company"
}
```
- association : 
```
{
    "kind": "association"
}
```
