### ISSUE TITLE
Bug : image cassée dans l'encart « Blog »

### ISSUE THREAD

**Issue by risseraka** [etalab/data.gouv.fr#131]
Bonjour,

Une image est cassé dans l'encart « Blog » du site https://www.data.gouv.fr/fr/

Screenshot :

![image](https://user-images.githubusercontent.com/363324/55556138-20d86f00-56e7-11e9-81c8-0bfde99a3dd7.png)

Code HTML défectueux :

```html
<img src="" alt="Open Data Day : les membres d’Etalab présentent leurs jeux de données préférés">
```

Bonne journée.

**Comment by abulte** [comment]
Merci ! On regarde ça.
