### ISSUE TITLE
Erreur sur la dernièrre page de l'API sur les moissonneurs

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#132]
https://www.data.gouv.fr/api/1/harvest/sources/?page=4 -> 200
https://www.data.gouv.fr/api/1/harvest/sources/?page=5 -> 500

Il y a 107 moissonneurs.

**Comment by abulte** [comment]
https://sentry.data.gouv.fr/etalab/www-datagouvfr/issues/683753/

**Comment by noirbizarre** [comment]
Bizarre:
- la requête complète fonctionne: https://www.data.gouv.fr/api/1/harvest/sources/
- l'erreur sentry fait référence a un dataset qui n'existe pas: ObjectId('5878ee2fa3a7291484cac7d2')
Il doit manquer un `try...except` dans la pagination

**Comment by noirbizarre** [comment]
OK, apparement il tire tout le graph pour rien, je corrige ça

**Comment by taniki** [comment]
la requête complète ne fonctionne pas : elle ne renvoie que 20 sources. changer le `page_size` provoque la même erreur.

**Comment by noirbizarre** [comment]
Yep, j'ai vu. J'avais oublié qu'on avait passé cette API en pagination seulement.
J'ai un fix, je teste juste ça sur la dernière version de la base
