### ISSUE TITLE
Etre plus résilient sur le moissonnage du DCT.spatial

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#1325]
[Nouvelle erreur Sentry](https://errors.data.gouv.fr/organizations/sentry/issues/136372/?project=3) apparue suite à https://github.com/opendatateam/udata/pull/2991.

A l'image de ce qui est fait pour `temporal_from_rdf`, mettre le parsing de DCT.spatial dans un try catch englobant et logger les éventuelles exceptions qui peuvent avoir lieu. Cela évitera de faire échouer le moissonnage tout en permettant des investigations futures.

**Comment by ThibaudDauce** [comment]
Fix via https://github.com/opendatateam/udata/pull/2998

Mais ça m'a posé question sur le remplacement de l'info par le moissonnage en cas de modification manuelle ? Aujourd'hui on écrase l'info même si elle est présente et plus précise (remplacement d'une entité nommée par le producteur par un polygon par exemple)
