### ISSUE TITLE
Pb Moissonage instance CKAN -Remontée partielle d'informations

### ISSUE THREAD

**Issue by pigma** [etalab/data.gouv.fr#136]
Je viens de créer un point de moissonnage avec mon compte data.gouv : Sébastien DIAS. Le point de moissonnage « Moissonneur NVA Mobilites/PIGMA » a été créé pour le compte de l’organisation Nouvelle-Aquitaine-Mobilités avec l'url suivant: https://www.pigma.org/ckan/dataset

Je remarque plusieurs problèmes: 

- seulement 10 jeux de données sont remontées alors qu'il devrait y en avoir 34.
 Cf > https://www.pigma.org/ckan/dataset?organization=nouvelle_aquitaine_mobilit_s

- pour chacun de ces jeux de données, il y a deux ressources de notre côté: une ressource GTFS + une ressource Netex. Je constate que seule la ressource netex est remontée.

- le champ "Fréquence de mise à jour" est renseigné de notre côté avec une valeur à "hebdomadaire" et ne remonte pas > update_frequency":"weekly" (exemple: https://www.pigma.org/ckan/api/3/action/package_show?id=arrets-horaires-et-parcours-theoriques-des-reseaux-naq_yeg-n) X

- le champ "Granularité spatiale" est également renseigné de notre côté via le champ 'granularity' et ne remonte pas > "granularity":"epci"

Comment faire en sorte que le moissonage remonte toutes les infos et surtout tous les jeux de données?

**Comment by abulte** [comment]
Le point "10 jeux de données" est réglé depuis peu https://github.com/opendatateam/udata-ckan/blob/master/CHANGELOG.md#122-2019-05-24.

Nous regardons pour les autres problèmes.

**Comment by pigma** [comment]
> Le point "10 jeux de données" est réglé depuis peu https://github.com/opendatateam/udata-ckan/blob/master/CHANGELOG.md#122-2019-05-24.

Ok merci pour ce changement. Parmis les points restant à traiter, le point suivant est prioritaire
> pour chacun de ces jeux de données, il y a deux ressources de notre côté: une ressource GTFS + une ressource Netex. Je constate que seule la ressource netex est remontée.

**Comment by abulte** [comment]
> pour chacun de ces jeux de données, il y a deux ressources de notre côté: une ressource GTFS + une ressource Netex. Je constate que seule la ressource netex est remontée.

Cette défaillance est due au format de l'`id` retournée par votre API. Pour une ressource GTFS, il est du type `e09ee736-ae5e-48c8-ac13-3839e3f2f74a-naq_yeg`, qui n'est pas un UUID valide comme attendu dans une API CKAN standard. Pour une ressource Netex, l'`id` est en revanche correctement formaté, eg `7c1d4b8a-cf41-4321-9146-814701e7cd46`.

**Comment by abulte** [comment]
> le champ "Fréquence de mise à jour" est renseigné de notre côté avec une valeur à "hebdomadaire" et ne remonte pas > update_frequency":"weekly" (exemple: https://www.pigma.org/ckan/api/3/action/package_show?id=arrets-horaires-et-parcours-theoriques-des-reseaux-naq_yeg-n)

Nous attendons une valeur pour `frequency` dans le champ `extras` sous la forme suivante :
```
'extras': [{'key': 'frequency', 'value': 'weekly'}]
```

**Comment by abulte** [comment]
> le champ "Granularité spatiale" est également renseigné de notre côté via le champ 'granularity' et ne remonte pas > "granularity":"epci"

A date, nous ne traitons pas le champ `granularity`.

**Comment by pigma** [comment]
> Cette défaillance est due au format de l'id retournée par votre API. Pour une ressource GTFS, il est du type e09ee736-ae5e-48c8-ac13-3839e3f2f74a-naq_yeg, qui n'est pas un UUID valide comme attendu dans une API CKAN standard. Pour une ressource Netex, l'id est en revanche correctement formaté, eg 7c1d4b8a-cf41-4321-9146-814701e7cd46.

Je généré moi-même un suffixe s'uuid afin d'éviter les doublons mais Ckan se débrouille trés bien tout seul lorsqu'on ne mentionne aucun uuid important les jeux de données via package_create. les uuid sont généré tout seul.

Je vais supprimer et recréer l'intégralité des fiches. La suppressions se fera automatiquement sur data.gouv via moissonnage si les fiches ne sont plus présentes côté PIGMA  ou faut-il les supprimer à la main ?

**Comment by pigma** [comment]
> Nous attendons une valeur pour frequency dans le champ extras sous la forme suivante :
'extras': [{'key': 'frequency', 'value': 'weekly'}]

ok, je vais voir ce qu'on peut faire pour être compatible avec vous.

> A date, nous ne traitons pas le champ granularity.
En est-il de même avec le champ étendue géographique ?

**Comment by mkazmiers** [comment]
suite à des échanges avec Alexandre, je crois qu'il est attendu pour la facette spatiale le même type de syntaxe que pour la fréquence à savoir : 
    "extras": [
        { "key": "spatial", "value": "{\"coordinates\": [[[-9.86, 41.15], [10.38, 41.15], [10.38, 51.56], [-9.86, 51.56], [-9.86, 41.15]]], \"type\": \"Polygon\"}" }
    ]

Or dans votre API CKAN comme le nôtre, nous déclarons pour l'instant la clé spatial directement dans la liste "results", et pas dans la liste "extras"...

**Comment by pigma** [comment]
> Nous attendons une valeur pour frequency dans le champ extras sous la forme suivante :
'extras': [{'key': 'frequency', 'value': 'weekly'}]

@abulte quelle est la liste de valeur attendues par data.gouv pour la key frequency afin que nous puissions utiliser la même liste.

**Comment by abulte** [comment]
@pigma elles sont ici : https://github.com/opendatateam/udata/blob/28fe147fca87ab1436f6281bbc312f310207ed3c/udata/core/dataset/models.py#L31

**Comment by abulte** [comment]
Faute d'activité je ferme, n'hésitez à pas à rouvrir si besoin.
