### ISSUE TITLE
Prise en charge du format DXF ?

### ISSUE THREAD

**Issue by fccl-vandoeuvre** [etalab/data.gouv.fr#137]
Bonjour,

Dans le cadre de la publication progressive d’intérieurs de plans de bâtiments de la municipalité de Vandœuvre-lès-Nancy en OpenData, je souhaite téléverser sur la plateforme des fichiers au format .dxf (Drawing eXchange Format).
Il s'agit d'un format ouvert (contrairement au très répandu DWG par exemple), cependant je reçois un message d'erreur sur data.gouv.fr, visiblement la plateforme n'accepte pas ce format.

> Erreur d'envoi sur mediatheque_jules_verne_rdc_2019-04-27.dxf a une extension invalide. Extension(s) valide(s): .

Pouvez-vous remédier à cette problématique ?

Cordialement.

**Comment by abulte** [comment]
Il sera possible d'ajouter des ressources `dxf` à la prochaine livraison en production (`udata 1.6.11` dans le pied de page de data.gouv.fr).
