### ISSUE TITLE
Permettre aux organisations de répondre dans les discussions

### ISSUE THREAD

**Issue by bboulesteix** [etalab/data.gouv.fr#141]
Ticket lié à #7.

## Contexte

Aujourd’hui, quand une organisation (l’INSEE par exemple) publie un jeu de données sur [data.gouv.fr](https://www.data.gouv.fr/fr/) et que le jeu de données [fait l’objet d’une discussion](https://doc.data.gouv.fr/reutilisations-et-discussions/ouvrir-une-discussion/), l’organisation interpellée ne peut pas répondre en son nom — seuls ses membres peuvent répondre à titre individuel. Dit autrement, seuls les _individus_ (par exemple Michel Durand) peuvent ouvrir et contribuer à des discussions, les _organisations_ (par exemple l’INSEE) n’en ont pas la possibilité.

## Problème

Les membres de certaines organisations acceptent de répondre aux commentaires suscités par leurs données, mais pas à titre individuel, pas avec leur compte [data.gouv.fr](https://www.data.gouv.fr/fr/) personnel. Ils créént donc de « faux profils », des profils individuels anonymes, qu’ils utilisent pour répondre au nom de leur organisation.

### Cas de l’INSEE

Pour rester anonymes dans les discussions suscitées par des jeux de données publiés par [l’organisation INSEE](https://www.data.gouv.fr/fr/organizations/institut-national-de-la-statistique-et-des-etudes-economiques-insee/), les membres de l’organisation ont créé un [faux profil individuel](https://www.data.gouv.fr/fr/users/diffusion-sirene-insee/), qui leur permet de répondre aux commentaires sans s’exposer. Je pense qu’on peut voir là le début d’une solution, plutôt qu’une entorse au bon usage de [data.gouv.fr](https://www.data.gouv.fr/fr/).

1. [Profil institutionnel de l’organisation de l’INSEE](https://www.data.gouv.fr/fr/organizations/institut-national-de-la-statistique-et-des-etudes-economiques-insee/) ;
2. [Profil de l’individu « Diffusion Sirene Insee » que l’INSEE utilise dans les discussions](https://www.data.gouv.fr/fr/users/diffusion-sirene-insee/).

![Screenshot_2019-06-24 Base Sirene des entreprises et de leurs établissements (SIREN, SIRET) - data gouv fr](https://user-images.githubusercontent.com/3286488/60023212-a724a180-9695-11e9-816b-61553c3b296a.png)

_Capture écran montrant un profil individuel anonyme répondant à un vrai profil individuel._

## Solution proposée

En tant que membre d’une organisation enregistrée sur [data.gouv.fr](https://www.data.gouv.fr/fr/), un utilisateur individuel devrait pouvoir choisir de répondre dans une discussion :

1. Sous son propre nom, à titre individuel, nominatif ;
2. Pour le compte de l’organisation qu’il représente, de manière anonyme.

### Cas de Facebook

Facebook permet aux gens qui gèrent des pages Facebook de répondre aux commentaires publiés sur une page, soit à titre individuel (profil), soit au nom de la page (organisation).

<img width="510" alt="Capture d'écran 2019-06-24 15 13 25" src="https://user-images.githubusercontent.com/3286488/60022644-83149080-9694-11e9-8f1b-abffa7da784b.png">

_Capture écran montrant le menu déroulant Facebook qui permet de choisir sous quelle banière répondre à un commentaire publié sur une page Facebook._

**Comment by taniki** [comment]
#7 c'est de pouvoir discuter SUR les pages d'organisation

**Comment by odtvince** [comment]
Toute décision prise par une administration comporte la signature de son auteur ainsi que la mention, en caractères lisibles, du prénom, du nom et de la qualité de celui-ci.
Article L212-1 du Code des Relations entre le Public et l'Administration
https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000034114657&cidTexte=LEGITEXT000031366350&dateTexte=20190624

**Comment by taniki** [comment]
Il me semble que le consensus était de trouver un moyen d'afficher un badge ou un signe pour indiquer que la personne qui répond fait parti de l'organisation qui a produit le jeu de données.

**Comment by taniki** [comment]
Voire aussi l'[article L111-2](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=792EA4775DF2AC1D3A4C4B97C01D3ECD.tplgfr27s_2?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031367321&dateTexte=20190624&categorieLien=id#LEGIARTI000031367321)

>Toute personne a le droit de connaître le prénom, le nom, la qualité et l'adresse administratives de l'agent chargé d'instruire sa demande ou de traiter l'affaire qui la concerne ; ces éléments figurent sur les correspondances qui lui sont adressées. Si des motifs intéressant la sécurité publique ou la sécurité des personnes le justifient, l'anonymat de l'agent est respecté.

**Comment by bboulesteix** [comment]
> #7 c'est de pouvoir discuter SUR les pages d'organisation

Oui, nous sommes d’accord sur ce point. C’est la raison pour laquelle je dis que ce ticket est lié à #7. Dans les deux cas il s’agit de donner voix au chapitre aux organisations : #7 propose qu’on puisse leur écrire directement ; cette issue propose qu’elles puissent répondre, sur les pages de leurs jeux de données ou ailleurs.

> Article L212-1 du Code des Relations entre le Public et l'Administration

Je ne remets pas en cause la loi. Je dis juste que concrètement, dans les faits, au niveau du sol, ça ne marche pas, en tout cas pas pour pour tout le monde — comme le cas de l’INSEE le montre. À partir de là, que faut-il donc faire ? Appliquer la loi, ce qui impliquerait sans doute de fermer les faux profils ? Proposer une solution intermédiraire, en permettant aux membres d’une organisation de répondre au nom de leur organisation ?

**Comment by odtvince** [comment]
La solution intermédiaire est justement la solution actuelle.

**Comment by bboulesteix** [comment]
> La solution intermédiaire est justement la solution actuelle.

Il me semblerait plus propre, plus élégant, de distinguer les réponses individuelles des réponses institutionnelles, en séparant les profils individuels des profils d’organisations dans les discussions. La solution actuelle — qui est plus un _hack_ qu’une solution d’ailleurs — ne permet pas de faire cette distinction, hélas. Cela dit, je suis d’accord pour dire que le _hack_ qui consiste à créer un faux profil commun à plusieurs agents, permet à certaines organisation de continuer à jouer le jeu des discussions, sans trop se mouiller pour autant. Si tout le monde est content avec ce _hack_, alors moi aussi.
