### ISSUE TITLE
Rajouter les nouvelles licences dans le sélecteur

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#142]
INPI et IGN

**Comment by abulte** [comment]
Other ne suffit pas ? Avec ce qu'il faut dans la description.

**Comment by taniki** [comment]
Vu qu'on les a rajouter là https://www.data.gouv.fr/fr/licences autant aller jusqu'au bout. Faut voir avec @odtvince en fait (:

**Comment by abulte** [comment]
Vu que ça va concerner 10 JDD à tout casser (?), je ne suis pas sûr que le jeu en vaille la chandelle.

**Comment by jdesboeufs** [comment]
Seuls la BAN et l'INPI peuvent utiliser ces licences, pour les jeux de données en question.

**Comment by taniki** [comment]
Tant qu’il y a un lien vers ces licences sur les jeux de donnés idoines ca me va (:
