### ISSUE TITLE
Vider le cache après une édition

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#144]
Nous avons introduit dans les dernières versions du cache plus agressif. Par exemple une page de jeu de données est mise en cache pendant 5 minutes.

Le comportement peut être perturbant pour un producteur : il doit attendre 5 minutes (max) avant de voir les modifications qu'il a faites.

Proposition d'amélioration : vider le cache de l'objet après son édition.

A faire sur :
- dataset
- organisation
- topic

**Comment by quaxsze** [comment]
Les topics sont deprecated et on ne met pas en cache le display d'une organisation.
En revanche les cartes d'organisations, de reuses, de datasets et d'utilisateurs sont mises en cache. Doit-on l'invalider aussi?
