### ISSUE TITLE
Dates incohérentes

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#146]
https://www.data.gouv.fr/fr/datasets/catalogue-des-donnees-de-data-gouv-fr/#resource-community-d82bc374-2346-4d56-bbc6-b428286ca01f

![Screenshot from 2019-07-03 23-49-59](https://user-images.githubusercontent.com/27315/60627115-62afa900-9ded-11e9-9c26-5b6396daaa61.png)

La date de publication est antérieure à la date de création. De plus, j'ai l'impression que toutes les dates de publication sur le site sont sans la partie horaire et bloqué sur "00:00"

**Comment by abulte** [comment]
La date de publication peut être forcée manuellement par le producteur il me semble...

**Comment by taniki** [comment]
Ah oui effectivement, il peut être renseigné manuellement. En fait je me demande si c'est un champ qu'on devrait pas supprimer. Je ne vois pas trop l'intérêt comme il n'y a pas non plus de statut "privé/public" pour les ressources communautaires. J'ai l'impression que c'est une information qui ne correspond à pas grand chose et n'a pas d'utilité.

**Comment by abulte** [comment]
Quelques notes sur l'utilisation de `resource.published` (en général, pas que pour les ressources communautaires) dans notre code :
- pas (bien) utilisé par `udata-ckan`
- pas utilisé par `udata-ods`
- correctement utilisé dans RDF/DCAT https://github.com/opendatateam/udata/blob/master/udata/core/dataset/rdf.py#L374, au moissonnage et à l'exposition du flux
- exposé dans JSON-LD et probablement pertinent (si la date elle-même est pertinente...)
