### ISSUE TITLE
Intégration du plugin Data-Fair

### ISSUE THREAD

**Issue by nicolas-bonnel** [etalab/data.gouv.fr#147]
## L’amélioration que vous avez en tête
Nous avons réalisé un [portail opendata pour l'ADEME](https://data.ademe.fr/), qui souhaite avoir ses données publiées automatiquement sur data.gouv.fr. Ce portail est basé sur logiciel opensource [Data Fair](https://github.com/koumoul-dev/data-fair) que nous maintenons.

Data Fair permet de visualiser de différentes manières les jeux de données, et nous souhaiterions proposer à notre client de rendre ces visualisations accessibles depuis les pages de ses jeux de données sur data.gouv.fr, via le mécanisme de *preview* :
 * Parcour des données volumineuses à l'aide d'une table utilisant la pagination.
 * Visualisation des données géolocalisées sur une carte
 * Affichage d'une galerie d'images
 * Moteur de recherche dans des fichiers joints au données
 * Consultation du schéma de métadonnées
 * Accès à une documentation d'API interactive

Pour ce faire nous avons développé un [plugin pour udata](https://github.com/koumoul-dev/udata-data-fair). Serait-il possible de déployer ce plugin sur data.gouv.fr ?

## Les alternatives possibles
Je ne pense pas qu'il y en ait, notamment pour des raisons de sécurité et pour éviter les abus.

**Comment by abulte** [comment]
Bonjour,

Nous allons tester ça, merci. En revanche ça risque de prendre un peu de temps avec la période estivale, n’hésitez pas à nous relancer !

**Comment by abulte** [comment]
Bonjour,

Le plugin est installé sur next.data.gouv.fr. Pouvez-vous me pointer vers un jeu de données où la prévisualisation est censée être disponible ?

Merci.

**Comment by nicolas-bonnel** [comment]
Bonjour,

Merci pour votre retour.

Les jeux de données publiés par l'ADEME depuis mi-juillet devraient avoir la prévisualisation. Par exemple celui-ci : http://next.data.gouv.fr/fr/datasets/les-aides-financieres-de-lademe-1/

Je ne voit cependant pas les boutons de prévisualisation que nous avons sur notre environnement de recette : 
![Capture du 2019-08-16 16-18-06](https://user-images.githubusercontent.com/708403/63174206-c4e10800-c041-11e9-8775-c5e1551efa8f.png)

Bien cordialement

**Comment by abulte** [comment]
Il y avait un cache un peu agressif à vider. Nous avons le bouton mais aussi une erreur :

<img width="589" alt="Capture d'écran 2019-08-16 16 51 19" src="https://user-images.githubusercontent.com/119625/63176417-2a36f800-c046-11e9-83d0-ad50cd26ec82.png">

**Comment by abulte** [comment]
J'utilise Chrome sans configuration particulière en ce qui concerne les cookies.

**Comment by nicolas-bonnel** [comment]
C'est bon de mon coté, merci !

Nous avons ce message qui apparaît quand on utilise des plugins chrome comme ghostery. A moins que vous ayez une version de Chrome plus récente que la mienne et qui a un bloquage intégré pour ce genre de cookie ?

Dans tous les cas ce problème est de notre coté et ne concerne pas le déploiement du plugin.

**Comment by abulte** [comment]
Pas d'extension de ce genre, non. `Version 75.0.3770.142 (Build officiel) (64 bits)`. Je vous laisse regarder et revenir vers nous pour que nous puissions tester.

**Comment by nicolas-bonnel** [comment]
Il y a effectivement un problème de notre coté sur la vue carte.

Mais pour la vue tabulaire il n'y a pas de problème et le plugin fonctionne : http://next.data.gouv.fr/fr/datasets/diagnostics-de-performance-energetique-pour-les-logements/

**Comment by nicolas-bonnel** [comment]
Nous avons fait des modifications de notre coté et le problème devrait être corrigé. Est il possible de refaire un test (le plugin ne semble plus déployé sur next.data.gouv.fr) ?

**Comment by abulte** [comment]
C'est de nouveau sur next.data.gouv.fr. La carte fonctionne. Si c'est bon pour vous, nous devrions être en mesure de déployer ça en prod cette semaine ou la semaine prochaine.

**Comment by nicolas-bonnel** [comment]
Merci, c'est bon pour nous !

**Comment by abulte** [comment]
Le plugin est déployé en prod mais ne semble pas fonctionner correctement. Le bouton "Prévisualiser" ne provoque ni action ni erreur visible : https://www.data.gouv.fr/fr/datasets/marches-et-emploi-de-lefficacite-energetique-et-des-enr-transport-2019/#_. Avez-vous une idée ? Sinon nous creuserons de notre côté.

**Comment by nicolas-bonnel** [comment]
En fait il a l'air de marcher pour certains jeux de données, mais pas d'autres. Celui la fonctionne : https://www.data.gouv.fr/fr/datasets/les-aides-financieres-de-lademe-1/
Nous allons regarder quelles sont les différences entre ces datasets.

**Comment by abulte** [comment]
Ok merci. Pour les aides financières, la carte ne s’affiche pas sur Safari iOS : bandeau rouge « pas de session active ».

**Comment by nicolas-bonnel** [comment]
Merci pour votre retour,

Après investigations de notre coté, il apparait que le problème sur safari IOS vient du fait que les cookies des sites webs intégrés en iframe ne sont pas acceptés par défaut. Nous avons fait quelques ajustements et la carte semble s'afficher correctement dans ces navigateurs maintenant.

**Comment by abulte** [comment]
Est-ce que vous avez pu voir pourquoi le bouton ne fait rien sur https://www.data.gouv.fr/fr/datasets/marches-et-emploi-de-lefficacite-energetique-et-des-enr-transport-2019/#_ par exemple ? C'est un problème pour nous de laisser en production des choses qui ne marchent pas.

Je confirme que la carte fonctionne sous Safari iOS 👏

**Comment by nicolas-bonnel** [comment]
J'avais oublié ce problème.

Je miserais sur l'URL (https://data.ademe.fr/datasets/marches-et-emploi-de-l'efficacite-energetique-et-des-enr-transport-(2019)) qui contient un `'` et qui doit générer un problème de parsing ou de construction d'url du coté de udata.

**Comment by maudetes** [comment]
La prévisualisation semble fonctionnelle pour jour.
