### ISSUE TITLE
Cohérence du catalogue de données de data.gouv.fr

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#148]
## Description du bug

Dans le [catalogue des données de data.gouv.fr](https://www.data.gouv.fr/fr/datasets/catalogue-des-donnees-de-data-gouv-fr/) en date du 22 juillet 2019, 233 jeux de données apparaissent dans le fichier des réutilisations sans apparaître dans le fichier des datasets.

Par exemple : 

Pour l'id "536991c4a3a729239d203d49", on trouve un dataset sur la plateforme : https://www.data.gouv.fr/fr/datasets/536991c4a3a729239d203d49/ mais on ne le trouve pas dans le fichier des datasets.

## Comment reproduire le bug

Étapes à suivre pour faire apparaître le bug :

1. Cloner le repo : https://github.com/pachevalier/exploreDataGouv
2. Lancer le script : https://github.com/pachevalier/exploreDataGouv/blob/master/catalogue-data-gouv-anomalies.Rmd
3. Naviguer jusqu’à la section "Datasets réutilisés mais non exportés dans le fichier de référence"
4. On peut aussi aller directement consulter le résultat ici : https://pachevalier.github.io/exploreDataGouv/catalogue-data-gouv-anomalies.html 

## Comportement attendu

En théorie, tous les jeux de données présents dans le fichier des réutilisations devraient apparaître dans le fichier des datasets, donc l'opération `anti_join()` entre les id de datasets du fichier des reuses et le fichier des datasets devrait avoir 0 lignes.

**Comment by abulte** [comment]
Est-ce que ce n’est pas dû au fait que l’export des datasets est plus récents que celui des reuses (cf la date dans le nom du fichier) ?

Évidemment c’est un problème. C’est dû au fait que le script consomme pas mal de mémoire et s’arrête au milieu ou plante complément. Il faut optimiser ça.
