### ISSUE TITLE
Gestion des données temps réel ou historisées

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#149]
## besoin

- Permettre un cycle de vie plus fluide pour les jeux données avec une fréquence rapide de mise à jour
- Permettre l'utilisation de ces jeux de données

## contexte

Aujourd'hui, on a des jeux de données dont la fiche n'est plus consultable car le producteur rajoute régulièrement une nouvelle ressource à jour. Par exemple, [le jeu de données sur la qualité de l'air](https://www.data.gouv.fr/fr/datasets/donnees-temps-reel-de-mesure-des-concentrations-de-polluants-atmospheriques-reglementes-1/) est mis à jour plusieurs fois par heure.

Il y a des besoins similaires sur les sujets transports.

## Solution

Interface utilisateur qui permette facillement de :

- Trouver facilement une ressource utilisable pour utilisation à l'instant t
- Navigation dans les différentes versions/mises à jour
- Ne plus afficher toutes les ressources si elles sont typées "temps réel"

## Implémentation

Je pense qu'on peut s'en sortir en touchant minimalement le back-end  en rajoutant ce qu'il faut pour profiter du fait qu'on ne supprime jamais les ressources non-distantes.

**Comment by taniki** [comment]
Pour info, j'ai l'impression qu'il y a deux interprétations de la notion de temps réel qui se recouvrent partiellement

1. Des données qui sont valables maintenant
2. Des données qui correspondent à un à un avec ce qu'il y a dans la base de donnée source

**Comment by taniki** [comment]
autre comprehension du temps reel : prochain passage du bus.

**Comment by abulte** [comment]
Côté transport ils ont maintenant une solution custom pour l'historisation.

**Comment by abulte** [comment]
Fermé pour le moment, sujet à garder en tête.
