### ISSUE TITLE
Supprimer son profil sur data.gouv.fr

### ISSUE THREAD

**Issue by noirbizarre** [etalab/data.gouv.fr#15]
_From @ColinMaudry on April 16, 2014 22:6_

Hello,

Aujourd'hui je me suis créé un profil sur data.gouv.fr alors que je m'en étais créé un il y a bien longtemps.

A cette occasion je le suis rendu compte qu'li n'y avait pas d'options pour supprimer son compte. Ou ai-je mal cherché ?

_Copied from original issue: etalab/etalab-support#19_

**Comment by ColinMaudry** [comment]
Par contre je ne me souviens plus de l'identifiant de ce vieux compte.

**Comment by noirbizarre** [comment]
C'est en cours:
- [x] Développez les fonctionnalités d'inscription et de suppresion de compte dans udata
- [ ] Attendre la release  de Flask-Security permettant la traduction et merger opendatateam/udata#958
- [ ] Importer les identifiants de id.data.gouv.fr
- [ ] Importer les avatars de id.data.gouv.fr
- [ ] Supprimer id.data.gouv.fr de l'architecture

**Comment by taniki** [comment]
Je viens de vérifier dans la dernière release, cela fonctionne :

- admin
- me
- la petite flêche à côté d'edit > delete
- confirm

**Comment by bboulesteix** [comment]
Il est désormais possible de supprimer un compte data.gouv.fr depuis l’interface administrateur.

Pour supprimer un compte :

1. [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
2. Rendez-vous sur [votre tableau de bord](https://www.data.gouv.fr/fr/admin/), en cliquant sur votre nom et prénom, en haut à droite de votre écran, puis sur **Administration** ;
3. Allez sur [la page de suivi de votre compte](https://www.data.gouv.fr/fr/admin/me/edit), en cliquant sur **Moi**, dans la colonne de gauche ;
4. Cliquer sur la flèche située à côté du bouton **Éditer**, en haut à droite de votre écran, puis sur **Supprimer le profil** dans le menu déroulant qui apparaît alors ;
5. Confirmez la suppression de votre compte en cliquant sur le bouton **Confirmer** qui figure dans la boîte de dialogue rouge.

Je ferme le ticket.
