### ISSUE TITLE
Mauvais affichage du mode citation

### ISSUE THREAD

**Issue by marion-paclot** [etalab/data.gouv.fr#152]
## Description du bug
La mise en forme d'une citation (paragraphe précédé de ">") ne se fait pas lors de la rédaction d'un texte de présentation d'un jeu de données.
Exemple sur cette description d'un jeu : https://www.data.gouv.fr/fr/datasets/base-carbone-complete-de-lademe/
\> Aujourd'hui, elle est la base de données de référence de l'article 75 de la loi Grenelle II et est entièrement homogène avec l'article L1341-3 du Code des Transports et les valeurs par défaut du système d'échange des quotas d'émissions européen. 

au lieu de
> Aujourd'hui, elle est la base de données de référence de l'article 75 de la loi Grenelle II et est entièrement homogène avec l'article L1341-3 du Code des Transports et les valeurs par défaut du système d'échange des quotas d'émissions européen.

Merci

**Comment by abulte** [comment]
Vérifier si c'est réglé par https://github.com/opendatateam/udata/pull/2341

**Comment by AntoineAugusti** [comment]
Lié avec #169 ?

**Comment by abulte** [comment]
Celle-ci est réglée ! Reste le problème soulevé dans #169 en effet, mais on a jamais pu tester le rendu vu que ce n'était pas supporté avant 😛.
