### ISSUE TITLE
Résolution du logo de compte utilisateur trop faible

### ISSUE THREAD

**Issue by DavidLacroix** [etalab/data.gouv.fr#153]
## Description du bug
Je viens de mettre à jour le logo de l'entreprise sur le compte de réutilisateur:
https://www.data.gouv.fr/fr/reuses/explorateur-de-biens-vendus/
Bien que l'image initiale soit de bonne qualité (1000x1000 en 300DPI) elle semble être réduite systématiquement à une image 100x100. Le rendu final du logo n'est pas très flatteur.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Créer un nouveau compte utilisateur
2. Changer l'avatar avec une image de taille et de résolution web raisonnable
3. Constater que l'affichage de l'image de 100x100 dans un container de taille supérieur à 100x100 détériore la qualité du logo.

En image:
![image](https://user-images.githubusercontent.com/1530493/68874825-1f9e0480-0702-11ea-9567-c85aaefe8f84.png)

## Comportement attendu
Un logo non pixélisé.

**Comment by quaxsze** [comment]
Merci, cela a été fixé.
Le changement sera visible au prochain déploiement de data.gouv.fr.
