### ISSUE TITLE
Question de pertinence des dates

### ISSUE THREAD

**Issue by quaxsze** [etalab/data.gouv.fr#154]
Suite à la question sur la pertinence de la date de publication des ressources, je fais un petit récapitulatif afin de permettre de se repencher sur le problème.

data.economie.gouv.fr, qui utilise ODS, ne renseigne qu'une date de modification et une date de dernier traitement comptabilisée comme une métadonnée, mais ne semble pas utiliser de date de publication.
![Capture d’écran 2019-11-18 à 11 22 04](https://user-images.githubusercontent.com/57526019/69059315-8c244680-0a15-11ea-9d0d-4ea2d98f2169.png)

CKAN utilise une date de publication mais elle correspond à la date de création de la dernière ressource du jeu de données ça semble assez peu pertinent.

DCAT utilise deux dates, au travers des classes dct:issued (que l'on utilise pour la date de publication) et dct:modified.
![Capture d’écran 2019-11-18 à 11 52 32](https://user-images.githubusercontent.com/57526019/69059336-99d9cc00-0a15-11ea-8dda-66c4f40421e2.png)

A voir ce que l'on garde ou non parmi les dates de création, de modification et de publication, et ce que l'on montre à l'utilisateur.
Certaines dates peuvent être peut-être considérées comme des métadonnées et rester internes à l'application.

Par ailleurs, sur le jeu de données, l'onglet détails semble faire doublon au niveau des dates avec ce qui est affichés sur la page principale. A voir aussi donc.

**Comment by abulte** [comment]
Cf https://github.com/opendatateam/udata/issues/1018 for details

**Comment by maudetes** [comment]
Will be done in https://github.com/etalab/data.gouv.fr/issues/720.
