### ISSUE TITLE
Permettre aux producteurs de supprimer des discussions

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#156]
_Historiquement_, la suppression de discussions n'est pas possible pour un producteur de peur (ou suite à des situations vécues ?) que les producteurs suppriment des questions "gênantes". Par conséquent, aujourd'hui seuls les administrateurs de la plateforme peuvent supprimer des discussions.

Cet état de fait pose des problèmes à des producteurs bienveillants qui sont obligés de passer par l'équipe data.gouv.fr pour supprimer des discussions problématiques : données perso, hors sujet complet, spam... Cela génère également une charge de travail pour l'équipe data.gouv.fr.

Peut-être est-il temps de remettre en cause le dogme historique ? Le cas échéant, comment peut-on s'assurer que la fonctionnalité soit bien utilisée ? Je vois plusieurs axes :
- monitoring : être capable de suivre les discussions supprimées et couper la feature en cas de besoin
- incentive/nudge : designer la fonctionnalité de manière à ce qu'on en "abuse" pas
- limitation : établir une whitelist de producteurs qui ont accès à cette fonction

**Comment by davidbgk** [comment]
Ça pourrait être pertinent de conserver une mention explicite de la suppression avec une raison, par exemple :

<img width="969" alt="Capture d’écran, le 2019-12-19 à 12 01 14" src="https://user-images.githubusercontent.com/3556/71192978-4bf3f600-2257-11ea-8e85-0b6861ea3212.png">

**Comment by abulte** [comment]
J’aime pour le côté nudge 👌 ca responsabilise le producteur parce que son action laisse des traces publiques. On peut aussi envisager de ne l’afficher que pendant un certain temps et de garder la discussion dispo pour les admin pendant ce temps, ce qui permet de monitorer.

**Comment by taniki** [comment]
La proposition de david me semble pas mal (:

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
