### ISSUE TITLE
Moissonneurs : gestion des données supprimées sur la plateforme distante

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#157]
Aujourd’hui le processus de moissonnage ne supprime jamais aucun jeu de données ou ressources. Cette approche conservatrice permet de ne pas supprimer des jeux de données qui ne devraient pas l’être, par exemple si la plateforme distante ne répond pas ou répond mal.

Toutefois, cela pose un problème lorsque les données sont _vraiment_ supprimées sur le portail distant. Elles ne sont alors plus accessibles. Les producteurs font rarement l’effort de supprimer à la main ces jeux de données, d’autant que l’opération est fastidieuse puisque rien n’identifie les jeux de données à supprimer.

Je vois trois solutions:
- implémenter une suppression automatique des éléments non présents sur le portail distant : efficace mais dangereux 
- implémenter un archivage automatique
- implémenter une vue dans la gestion des moissonneurs permettant au producteur et aux admins d’identifier et de gérer les jeux de données qui devraient être supprimés, un par un ou en masse

A faire dans un premier temps : compter les jeux de données concernés à date.

**Comment by odtvince** [comment]
La majorité des producteurs qui utilisent des moissonneurs ne veulent pas avoir à venir faire de la curation sur data.gouv.fr. Ils pourraient être intéressés par un choix de mode de fonctionnement à la création initiale du moissonneur (archivage automatique ou pas, par exemple), mais ne seront probablement pas utilisateurs d'une interface de gestion de l'archivage au fil de l'eau.

**Comment by odtvince** [comment]
Le choix entre suppression et archivage me semble plus devoir être une décision politique de la plateforme data.gouv.fr que laissée au choix des producteurs. À ce jour, on a toujours préféré éviter de faire disparaitre des données, potentiellement obsolètes mais pas pour autant inutiles ou inintéressante. Tous les producteurs ne partagent pas ce souci, sur la donnée transport par exemple.

**Comment by taniki** [comment]
À mon avis, c'est aussi le moment de se rapprocher à un modèle mental orienté utilisateur. Garder la logique de moissonnage mais parler de synchronisation de catalogue tiers (compris comme une liste de jeux de données cataloge+filtres).

Le premier temps d'identification peut aussi s'accompagner par un affichage dans le front. On a rien qui permet de faire l'aller-retour actuellement ?

Plutôt partisan d'un archivage automatique avec opt-out par jeux de données.

**Comment by taniki** [comment]
Pas certain que « catalogue » soit dans le langage des producteurs/diffuseurs. Je pense que c'est une influence de DCAT. On peut même garder le terme de « moissonage » en disant que c'est un dispositif permettant de synchroniser des portails. Je pense que la phrase « moissoner un portail » provoque facilement un petit moment d'étonnement.

**Comment by abulte** [comment]
La liste des jeux de données concernés par un archivage automatique : https://csvapi-front.now.sh/?url=https://gist.githubusercontent.com/abulte/10ac773b73917cabdaa3020485472f7e/raw/a6c0a09991981d86e699a331ba69bf122efc6c1c/harvest_autoarchive.csv

**Comment by jdesboeufs** [comment]
geo.data.gouv.fr fonctionne actuellement de la même manière. Pas de suppression.
Le système de cache prend souvent le relais des sources officielles, sauf pour certains types de services.
