### ISSUE TITLE
Territoires non accessibles (geozones ?)

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#159]
Les pages territoires suivantes ne sont pas accessibles, peut-être à cause d'un problème côté modélisation Geozones :

- https://www.data.gouv.fr/fr/territories/commune/30339@latest/Valleraugue/
- https://www.data.gouv.fr/fr/territories/commune/30190@latest/Notre-Dame-de-la-Rouviere/
- https://www.data.gouv.fr/fr/territories/commune/50133@latest/Chevreville/
- https://www.data.gouv.fr/es/territories/commune/33063@latest/Bordeaux/
- https://www.data.gouv.fr/fr/territories/commune/14366@latest/Lisieux/
- https://www.data.gouv.fr/fr/territories/commune/78400@latest/Meudon/
- [...]

cf https://sentry.data.gouv.fr/etalab/www-datagouvfr/issues/130700/events/5738661/ pour la liste complète.

**Comment by abulte** [comment]
Lié à https://github.com/etalab/geozones/issues/47 ?

**Comment by abulte** [comment]
Le `@latest` semble être un facteur, cf https://www.data.gouv.fr//fr/territories/commune/33063@1965-02-22/Bordeaux/ qui marche alors que https://www.data.gouv.fr//fr/territories/commune/33063@latest/Bordeaux/ non.

**Comment by abulte** [comment]
Issue still happening on:
- https://www.data.gouv.fr/fr/territories/commune/30190@latest/Notre-Dame-de-la-Rouviere/
- https://www.data.gouv.fr/fr/territories/commune/50133@latest/Chevreville/
- https://next.data.gouv.fr/fr/territories/commune/78400@latest/Meudon/

**Comment by agarrone** [comment]
Les pages territoires sont dépréciées see #384
