### ISSUE TITLE
Rajouter un lien vers le catalogue geo-ide quand c'est possible

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#160]
Comme pour les données provenant d'ODS, il serait intéressant de proposer un lien vers la source geo-ide. Le problème c'est que le champ `inspire:resource_identifier` me semble relativement pété. Ex : `7df2d45f-40fc-450a-b561-489608059e23http://catalogue.geo-ide.developpement-durable.gouv.fr`

https://www.data.gouv.fr/fr/datasets/ppri-loire-aval-dans-lagglomeration-nantaise-zones-reglementees-en-loire-atlantique/

![Screenshot from 2020-01-14 11-23-50](https://user-images.githubusercontent.com/27315/72336104-5d96b500-36c0-11ea-86d3-114a88441ec0.png)

**Comment by abulte** [comment]
Si geo.data.gouv.fr remplit `extras.remote_url` ça devrait marcher tout seul.

**Comment by agarrone** [comment]
Plus d'actualité depuis l'extinction
Je close @abulte n'hésite pas à rouvrir si besoin :)
