### ISSUE TITLE
Date de dernière mise à jour de ressource

### ISSUE THREAD

**Issue by lou-dupont** [etalab/data.gouv.fr#161]
Sur la page d'un jeu de données, à quoi correspond, dans le cadre latéral droit, la date nommée **"Dernière mise à jour de ressource"** (qui, étrangement, est associée à un logo de téléchargement et non pas de téléversement) ?

Quand on utilise le menu "**Éditer**" et "**Remplacer le fichier**" pour téléverser une nouvelle version d'une ressource, le champ "**Modifiée le**" de la ressource semble mis à jour correctement (ainsi que l'URL de téléchargement qui contient la date de téléversement), mais l'indicateur au niveau du jeu de données ne semble pas changer.

C'est très perturbant et cela incite à faire des manipulations étranges pour "forcer" la mise à jour, comme détruire la ressource et en recréer une (ce qui a sûrement des effets indirects néfastes sur le décompte des téléchargements, ou la persistance d'URL pérennes de téléchargement de la ressource).

**Comment by abulte** [comment]
Effectivement, la date n'est pas mise à jour au remplacement d'une ressource (en tout cas lors de l'upload d'un nouveau fichier, ce que j'ai testé). Il me semble pourtant qu'elle devrait l'être. Merci pour le signalement @lou-dupont !

**Comment by abulte** [comment]
**Pro tip** : cette date (Dernière mise à jour de ressource) est mise à jour en fonction de la _date de publication_ des ressources du jeu de données (la date la plus récente est remontée).

Il est donc possible de la mettre à jour sans supprimer/ajouter une ressource. En revanche tout ceci est loin d'être clair, comme le prouve cette conversation. Nous gagnerions certainement à supprimer cette notion de date de publication sur les ressources pour utiliser la date de modification calculée automatiquement à chaque changement.

**Comment by abulte** [comment]
_NB : penser à prévenir l'ONISEP (cf zammad) si nous modifions le comportement, il leur a été décrit tel qu'actuellement implémenté et ils vont en dépendre._

**Comment by lou-dupont** [comment]
Merci, cela fonctionne effectivement.

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
