### ISSUE TITLE
Recherche : l'acronyme ne fait pas remonter une organisation

### ISSUE THREAD

**Issue by mathildehg** [etalab/data.gouv.fr#162]
## Description du bug
Lorsque je recherche "DGCL" dans le moteur de recherche, c'est l'organisation Observatoire des Finances et de la Gestion publique Locale qui m'est proposé. 

Pourtant, le sigle de la DGCL est bien indiqué dans l'administration Direction générale des collectivités locales. 

## Comment reproduire le bug
Entrer DGCL dans le moteur de recherche de datagouv

## Comportement attendu
Apparition de l'organisation Direction générale des collectivités locales dans l'onglet organisation.

**Comment by AntoineAugusti** [comment]
Je penche plutôt pour un problème d'indexation, le problème n'apparait pas plusieurs semaines après

![image](https://user-images.githubusercontent.com/295709/82060900-fc92e400-9695-11ea-9b32-ed5432c01fa7.png)
