### ISSUE TITLE
Impact de la suppression d'un jeu de données

### ISSUE THREAD

**Issue by bjperson** [etalab/data.gouv.fr#164]
Avant la suppression d'un jeu de données, il serait utile que l'utilisateur soit notifié de l'impact potentiel sur d'autres ressources. 

Voire que cette suppression soit soumise à modération s'il y a des données liées, ajoutées par la communauté, des réutilisations ou bien que ce jeu de données soit populaire (pérennité des liens sur sites externes).

cf : https://twitter.com/Politologue_com/status/1224842298292350981

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
