### ISSUE TITLE
Erreur lors de la création d'un moissonneur

### ISSUE THREAD

**Issue by eprouteau** [etalab/data.gouv.fr#165]
Bonjour,

Lors de la création d'un moissonneur j'ai une erreur et impossible de passer à l'étape suivante.

![image](https://user-images.githubusercontent.com/1401902/74228780-6da2b400-4cc1-11ea-8dbe-fefb36126256.png)

Cordialement,

**Comment by abulte** [comment]
Bonjour,

Nous sommes désolés du problème que vous rencontrez.

L'identifiant fourni est relatif à une erreur lors de la suppression d'une ressource sur un jeu de données, et non à la création d'un moissonneur.

Avez-vous pu créer votre moissonneur depuis ?

Le cas échéant, pouvez-vous nous copier coller le code d'erreur plutôt qu'une capture d'écran ?

Merci.

**Comment by eprouteau** [comment]
Bonjour,

Je n'ai toujours pas réussi a créer de moissonneur le code erreur reçu est : a3d6b3869eb54c6aa1fadc2efa776201

Cordialement,

**Comment by abulte** [comment]
Il semblerait que ce soit un problème de permissions. Etes-vous bien administrateur de l'organisation à laquelle vous souhaitez rattacher le moissonneur ?

**Comment by eprouteau** [comment]
Effectivement le changement de editor à admin a résolu le problème. Un message d'alerte plus parlant serait une évolution intéressante ou alors informer l'utilisateur en amont.

Merci pour l'aide apportée

**Comment by abulte** [comment]
Vous avez raison ! Nous avons documenté le problème ici https://github.com/opendatateam/udata/issues/2071.
