### ISSUE TITLE
Se désinscrire des notifications de discussion d'un jeu de données

### ISSUE THREAD

**Issue by bzg** [etalab/data.gouv.fr#167]
## L’amélioration que vous avez en tête

En tant qu'éditeur associé à une organisation, je reçois une notification email pour toute discussion ayant lieu sur tout jeu de données de l'organisation.

Je souhaite pouvoir me désinscrire des notifications pour tel ou tel jeu de données, voire pour toutes les notifications de tous les jeux de données (en cas d'absence prolongée, par exemple, pour éviter les bounces trop nombreux.)

**Comment by bzg** [comment]
Hello ! Juste un heads-up pour savoir si cette issue est quelque part dans le radar.  Je pense que c'est un irritant assez fort... je ping @mathildehg qui a dû recevoir pas mal de notifications ces deux derniers mois :)

**Comment by bzg** [comment]
J'ai l'impression que l'issue est résolue mais je la vois toujours ouverte - si quelqu'un peut vérifier, c'est cool !

**Comment by abulte** [comment]
Hum non, rien n'a changé là-dessus à ma connaissance.

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.

**Comment by bzg** [comment]
OK, merci !  La « note » est publique quelque part ? (Pas grave si elle ne l'est pas, c'est juste pour info.)

**Comment by agarrone** [comment]
Rien de publique pour l'instant mais on a commencé à drafter des cinématiques de mails pour refondre le système en profondeur :)
