### ISSUE TITLE
Taille de la police pour une citation en Markdown

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#169]
## Description du bug
La taille de la police semble anormalement élevée lorsqu'on met une citation dans une description de JDD.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Modifier la description d'un JDD en mettant une citation en Markdown
2. Sauvegarder
3. Constater le bug

## Comportement attendu
La police est de taille normale.

![image](https://user-images.githubusercontent.com/295709/77649872-f0659280-6f40-11ea-8045-7e2da78874e0.png)

**Comment by abulte** [comment]
Cf https://getbootstrap.com/docs/4.4/content/typography/#blockquotes
