### ISSUE TITLE
[Validation d'un moissonneur CKAN] fréquence

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#170]
## Description du bug
Bonjour, j'ai souhaité déclarer un point de moissonnage sur notre nouvelle instance CKAN :
https://trouver.ternum-bfc.fr/dataset, avec un filtrage sur une organisation dreal-bourgogne-franche-comte.
A l'enregistrement, la plateforme a renvoyé le message d'erreur suivant 
_L'identifiant de l'erreur est b73aa7ff0bbb43e98d14187bc5768854_
D'aprés les autres tickets similaire comme https://github.com/etalab/data.gouv.fr/issues/165, le profil de mon compte n'est pas "suffisant", de simple editeur, il devrait être à admin.
Je viens de changer le rôle d compte.
Le point de moissonnage a bien été crée, il vous reste à le valider.
https://www.data.gouv.fr/fr/admin/harvester/5e96b5ff3993a18939709f0b

Une fois validé, c'est à partir de ce moment que la fréquence de moissonnage sera déterminée ?
D'avance Merci,

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à `…`
2. Cliquer sur `…`
3. Naviguer jusqu’à `…`
4. Constater le bug

## Comportement attendu
Décrivez-nous ce à quoi vous vous attendiez. Exemple : « Je pensais que mon action allait déboucher sur… or à cause du bug je constate que… »

**Comment by abulte** [comment]
Bonjour,

Pouvez-vous nous contacter sur support@data.gouv.fr à ce sujet ?

Merci.
