### ISSUE TITLE
Afficher l'appartenance à une orga dans les commentaires

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#172]
## L’amélioration que vous avez en tête
Actuellement, en répondant à des commentaires en tant que membre d'une organisation, il est difficile de savoir qui appartient à une organisation et qui n'en est pas membre.

Certaines organisations contournent ça en :
- utilisant un compte unique pour l'organisation
- utilisant leur logo en tant qu'avatar
- indiquant le nom de l'orga en signature du message

![image](https://user-images.githubusercontent.com/295709/81573558-a3177600-9372-11ea-9887-f5f852b1a8d4.png)

## Les alternatives possibles
Envisager l'ajout d'un badge, comme sur GitHub ? Indiqué comme "Member"

![image](https://user-images.githubusercontent.com/295709/81573545-a01c8580-9372-11ea-95be-c7655024ca2d.png)

**Comment by abulte** [comment]
J'aime bien l'idée du badge. On devrait pouvoir :
- tester si la personne est membre de l'organisation qui publie le jeu de données sur lequel on est ou en est le propriétaire
- le cas échéant, afficher un badge `member` ou `owner`
- peut-être afficher un badge `admin` pour les admin

Idem sur les réutilisations.
