### ISSUE TITLE
Documentation API discussions

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#173]
## L’amélioration que vous avez en tête
Dans la documentation actuelle de l'API pour les discussions, il n'est pas indiqué :
- que le commentaire sera rendu en tant que Markdown dans l'interface
- comment renseigner le champ `subject`. Il faut un nom de modèle et un identifiant. Quels sont les noms de modèles autorisés ? Au pluriel, au singulier ?

Le code indique juste le type `string` et non Markdown
https://github.com/opendatateam/udata/blob/f2459ad64a235f559ebb3e3a869cc8fc2ae3753c/udata/core/discussions/api.py#L49-L50

La documentation de l'API ne donne pas d'indice sur ces questions
https://doc.data.gouv.fr/api/reference/#/discussions/create_discussion

**Comment by AntoineAugusti** [comment]
Sur le même sujet, l'interface utilisateur n'indique pas le support du Markdown ou ne propose pas un éditeur Markdown. Peut-être changer ceci ?

![image](https://user-images.githubusercontent.com/295709/81601892-a07c4700-9399-11ea-8bcd-bd47044b7cef.png)

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
