### ISSUE TITLE
Documentation API : erreur dans le Swagger

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#177]
## Description du bug
Il y a une erreur dans le Swagger, au moins sur l'opération `get_dataset`, GET 
​/datasets​/{dataset}​/

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à https://doc.data.gouv.fr/api/reference/#/datasets/get_dataset
1. Constater le bug

![image](https://user-images.githubusercontent.com/295709/84898499-5d3a8580-b075-11ea-974c-ac2799e4be3c.png)

**Comment by abulte** [comment]
https://github.com/etalab/doc.data.gouv.fr/issues/85
