### ISSUE TITLE
Si le nom d'un fichier include un point, le format du fichier montre une partie du nom avec l'extension

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#182]
## Description du bug
Si le nom d'un fichier include un point, par exemple "test.1.csv", le format du fichier montre une partie du nom avec l'extension, par exemple "1.csv"

https://www.data.gouv.fr/fr/datasets/covid-2020-etudes-et-consequences-sur-laction-des-acteurs-de-la-solidarite/

![IMG_8880DF9435EE-1](https://user-images.githubusercontent.com/51122275/92602764-de896900-f2ae-11ea-9f5b-9c231e59547f.jpeg)
![Capture d’écran 2020-09-09 à 15 12 55](https://user-images.githubusercontent.com/51122275/92602828-f234cf80-f2ae-11ea-919a-e034c8145344.jpg)

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller sur la page d'un jeux de données que include un fichier avec un point dans le nom ;
2. Constater le bug.

J'ai aussi essayé à réproduire le bug en publiant un nouveau jdd et ajoutant un fichier avec des points dans son nom :
https://www.data.gouv.fr/fr/admin/dataset/5f58d546abd5f962a9e4d3eb

![Capture d’écran 2020-09-09 à 15 17 44](https://user-images.githubusercontent.com/51122275/92603607-ca923700-f2af-11ea-96bb-bba7b51fd90f.jpg)

## Comportement attendu
Le format ne devrait pas inclure partie du nom avant l'extension du fichier

**Comment by maudetes** [comment]
Will be done in https://github.com/etalab/data.gouv.fr/issues/632.
