### ISSUE TITLE
Ajouter un champ pour indiquer l'encodage d'une ressource

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#183]
## L’amélioration que vous avez en tête

Pas mal d'utilisateurs de données ont déjà perdu un temps significatif à détecter l'encodage d'un fichier pour l'ouvrir proprement dans un logiciel. Certains administrations utilisent des encodages difficiles à détecter (par exemple CP850). Ce serait utile de permettre au producteur de préciser l'encodage dans les métadonnées de la ressource.

## Les alternatives possibles

On pourrait aussi imaginer une méthode de détection automatique via un script.

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
