### ISSUE TITLE
Intégration à la liste des schémas : Base Adresse Local

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#186]
## Description du bug
Suite aux dernières nouveautés, j'ai voulu par curiosité éditer un dataset d'un partenairre, la BAL de Grand Besançon Métropole, 
https://www.data.gouv.fr/fr/datasets/base-adresse-locale-de-grand-besancon-metropole-1/
pour attribuer le schéma BAL (puisque GBM a publié au format BAL)

## Comment reproduire le bug
1.Je suis donc allé sur éditer le jeux de données, 
2. éditer la ressource, le csv 
3. Cliquer sur la liste déroulante pour attribuer le schéma Base Adresse Locale
4. Pas trouvé dans la liste :(

## Comportement attendu
La valeur devrait être sélectionnable, comme dans l'image 
https://www.etalab.gouv.fr/wp-content/uploads/2020/09/selection-schema.d958a2c6.png

## Questions
Peut être qu'il y une problématique de "gouvernance" pour le schéma BAL ?
Est ce que l'attribution d'un schéma pour des données déja publiées est déconseillée ?

**Comment by jerbou** [comment]
Voici l'imprime écran pour les étapes 3 et 4
![image](https://user-images.githubusercontent.com/7600693/95297002-081bbd00-087a-11eb-9770-ca8cec1181dc.png)

**Comment by abulte** [comment]
Bonjour,

Le schéma référencé n'était pas celui effectivement utilisé pour alimenter la BAN à partir des BAL. Nous allons travailler à intégrer le bon schéma, plus de détails ici https://github.com/etalab/schema.data.gouv.fr/issues/122. Poke @jdesboeufs.

**Comment by jerbou** [comment]
Merci @abulte et @jdesboeufs  les échanges du moment sur https://github.com/etalab/schema.data.gouv.fr/issues/122
nous sont trés interressants.

Une fois, la décision de prise, on appliquera dans d'éventuels datasets BAL qui passeront par nous.
