### ISSUE TITLE
Moissonnage "descendand" par utilisation de l'API

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#189]
## L’amélioration que vous avez en tête
Est-il possible d'obtenir un "moissonnage" descendant, c'est à dire récupérer la liste des jeux de données d'un organisation via l'API dans un format compatible DCAT (voir CKAN) ?
Notre objectif est de moissonner certaines organisations ayant déposées des données sur data.gouv.fr et faire apparaitre ces jeux de données sur une plateforme régionale.
(Le complément de ce que l'on fait en poussant de notre CKAN vers data.gouv.fr).

Ex : A partir d'un appel à l'API, comme l'exemple suivant :
https://www.data.gouv.fr/api/1/datasets/?organization=5943987b88ee381f30d196f7&page=0&page_size=20

Est-il possible d'échanger par courriel sur ce sujet, pour mieux expliciter notre besoin ?

## Les alternatives possibles
Je n'ai pas l'impression que l'API sert les réponses au "format" DCAT, ou le format DCAT-AP selon :
https://www.europeandataportal.eu/mqa/catalogues/plateforme-ouverte-des-donnees-publiques-francaises/?locale=fr
mais je peux me tromper :)

D'avance Merci,

Jérôme Boutet

**Comment by abulte** [comment]
@quaxsze Peux-tu vérifier qu'on exporte (ou pas) un catalogue DCAT pour le organisations ? Merci !

**Comment by quaxsze** [comment]
On traduit les organisation en RDF  [ici](https://github.com/opendatateam/udata/blob/267555b6ab7c2f375f619ccec2f9220e23934ab4/udata/core/organization/rdf.py#L13) mais uniquement pour intégrer le résultat au rendu RDF d'un dataset [là](https://github.com/opendatateam/udata/blob/267555b6ab7c2f375f619ccec2f9220e23934ab4/udata/core/dataset/rdf.py#L203).
Il n'existe pas de feature similaire à celle des datasets permettant d'avoir le catalogue DCAT d'une organisation.

**Comment by abulte** [comment]
@jerbou on peut échanger plus en détail sur votre besoin sur support[at]data[point]gouv[point]fr.

**Comment by jerbou** [comment]
Merci, @abulte  je vais vous faire un courriel sur support pour identifier d'éventuels contournements possibles pour atteindre l'objectif de moissonner ce qui est déposé sur data.gouv et de le rendre visible sur ideo.ternum-bfc.fr.

**Comment by abulte** [comment]
L'export DCAT par organisation est désormais disponible, par exemple https://www.data.gouv.fr/fr/organizations/ministere-de-l-interieur/catalog.xml.
