### ISSUE TITLE
Afficher la taille des ressources distantes

### ISSUE THREAD

**Issue by JulienPalard** [etalab/data.gouv.fr#190]
Il y a beaucoup d'informations déjà sur les fichiers (format, qutre dates, nombre de téléchargements, ...), mais pas la taille.

Je comprend que quand on sait quelle donnée on veut, peu importe sa taille, on la veut, donc ça ne paraît pas pertinent.

Cependant j'enseigne Python et la culture Unix, et deux fois (une fois dans chaque cours), j'ai eu besoin d'un fichier d'exemple, intéressant, pas trop gros (on était en Wi-Fi), pas mais trop petit (faut que la démo envoie du paté quand même).

C'est aussi arrivé à un élève, qui voulait "jouer avec Jupyter", qui s'est retrouvé à télécharger un fichier de 12GB sans le savoir (c'est dommage pour votre bande passante, pour le temps qu'il a perdu à le télécharger, et pour le message d'erreur de numpy lui expliquant qu'il n'avait pas du tout 12GB de RAM sur sa machine).

À force de rencontrer le problème ... me voilà à ouvrir un ticket oui j'ouvrirai bien une PR, mais pas ce soir, il faut que je finisse de rédiger ce cours…).

**Comment by abulte** [comment]
Bonjour,

Merci pour votre retour.

Nous affichons bien la taille (cf exemples ci-dessous)... quand nous la connaissons. Ce qui n'est pas toujours le cas, notamment pour des fichiers distants où le producteur n'a pas rempli la métadonnée correspondante.

<img width="629" alt="Capture d’écran 2020-11-15 à 21 05 51" src="https://user-images.githubusercontent.com/119625/99195491-69db1b00-2786-11eb-9c59-d89e35897a36.png">
<img width="580" alt="Capture d’écran 2020-11-15 à 21 05 57" src="https://user-images.githubusercontent.com/119625/99195493-6a73b180-2786-11eb-8412-23e5272c1b95.png">

**Comment by JulienPalard** [comment]
OK, je n'avais complétement pas ouvert les yeux sur le fait que j'étais à chaque fois tombé sur de la donnée hébergée ailleurs (du moins : à chaque fois où je me suis fait la remarque que ça manquait).

Je pense que ça peut être récupéré à peu de frais dans certains cas, l'entête HTTP le donnant :

    $ curl -I  http://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.csv
    HTTP/1.1 200 OK
    Server: nginx/1.10.3
    Date: Sun, 15 Nov 2020 22:32:52 GMT
    Content-Type: text/csv
    Content-Length: 3164494299

Peut être que forcer la requête en HTTP/1.0 peut motiver les serveurs à ne pas trop proposer de `Chunked`, pas testé.

**Comment by abulte** [comment]
C'est quelque chose qu'on a commencé à faire grâce à https://github.com/etalab/croquemort. On récupère la taille quand elle est exposée via une requête HEAD. 

En revanche aujourd'hui on la garde dans une métadonnée interne qu'on utilise dans certains de nos traitements, mais on ne remplace pas la "vraie" métadonnée. C'est toujours délicat d'aller remplir des informations (qui peuvent être fausses) à la place du producteur. De plus, se poserait alors la question de "qui a raison" : comment permettre au producteur de reprendre la main sur cette métadonnée et éviter que croquemort revienne régulièrement remplir une taille qui serait fausse ?

D'ailleurs bizarrerie sur ce fichier, curl retourne bien un `Content-Length` via un HEAD mais pas `requests` (que nous utilisons sur croquemort) 🤔. On a donc pas la taille en stock pour ce fichier. Peut-être parce que requests propose le support gzip par défaut.

```
% curl -X HEAD -I http://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.csv
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Mon, 16 Nov 2020 07:32:41 GMT
Content-Type: text/csv
Content-Length: 3164494299
Last-Modified: Tue, 13 Oct 2020 02:37:14 GMT
Connection: keep-alive
ETag: "5f8512da-bc9e59db"
Strict-Transport-Security: max-age=63072000
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
```

```
>>> import requests
>>> r = requests.head('http://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.csv')
>>> r.headers
{'Server': 'nginx/1.10.3', 'Date': 'Mon, 16 Nov 2020 07:26:11 GMT', 'Content-Type': 'text/csv', 'Last-Modified': 'Tue, 13 Oct 2020 02:37:14 GMT', 'Connection': 'keep-alive', 'ETag': 'W/"5f8512da-bc9e59db"', 'Strict-Transport-Security': 'max-age=63072000', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding': 'gzip'}
```

**Comment by abulte** [comment]
Effectivement en supprimant le support gzip de requests on récupère bien le content-length:

```
>>> r = requests.head('http://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.csv', headers={'accept-encoding': None})
>>> r.headers
{'Server': 'nginx/1.10.3', 'Date': 'Mon, 16 Nov 2020 07:55:22 GMT', 'Content-Type': 'text/csv', 'Content-Length': '3164494299', 'Last-Modified': 'Tue, 13 Oct 2020 02:37:14 GMT', 'Connection': 'keep-alive', 'ETag': '"5f8512da-bc9e59db"', 'Strict-Transport-Security': 'max-age=63072000', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'Accept-Ranges': 'bytes'}
```

**Comment by JulienPalard** [comment]
> De plus, se poserait alors la question de "qui a raison"

Une première étape simple : Si aucun humain n'a renseigné la taille, au lieu de ne rien afficher, on affiche la taille donnée par croquemort ?

**Comment by abulte** [comment]
C'est une piste mais on se retrouve vite bloqué : quand le champ est vide (premier passage de croquemort) c'est effectivement facile, mais au 2e passage de croquemort (la taille peut avoir changé) on ne saura pas quoi faire (ie est-ce un humain ou croquemort qui a rempli la taille ?).

Mais en fait je viens de penser à une solution qui devrait marcher : on garde la taille de croquemort dans sa métadonnée interne, et sur le front on affiche `resource.size or resource.extras.croquemort_size`. Comme ça si le producteur rentre une taille, elle est prioritaire.

**Comment by JulienPalard** [comment]
> Effectivement en supprimant le support gzip de requests on récupère bien le content-length:

Je serais curieux, une fois gzip supprimé, et votre DB mise à jour, de savoir combien il reste de fichiers dont on ne connaît pas la taille, et quelques URL. Je suspecte que ces cas sont des réponses `Chunked`, mais je doute qu'on puisse y faire grand chose.

Je pense que ceux qui répondent en `Transfer-Encoding: Chunked` le font parce qu'ils ne connaissent pas la taille à l'avance, ils ne peuvent donc pas nous la donner même si on insiste, donc ça risque de ne pas marcher.

J'ai fait 2mn de tests sur des serveurs qui répondent en Chunked (j'en ai pas non plus cherché 200), c'est fort peu concluent :

    printf "HEAD / HTTP/1.0\r\nHost: aaaaaa.fr\r\n\r\n" | netcat aaaaaa.fr 80
    # Pas de Content-Length

    printf "HEAD / HTTP/1.0\r\nHost: aaam.fr\r\n\r\n" | netcat aaam.fr 80
    # Pas de Content-Length

Ce qui est tout à fait autorisé par la [RFC 1945](https://tools.ietf.org/html/rfc1945#section-7.2.2) :

> Otherwise, the body length is determined by the closing
> of the connection by the server.

**Comment by abulte** [comment]
Oui pour tout ce qui est stream on n'aura pas d'info, sauf si le serveur est particulièrement intelligent au niveau du traitement du HEAD (ce qui est rarement le cas).

On a d'autres chantiers plus costaud en cours pour télécharger les fichiers (datalake), ce qui nous permettrait de calculer de manière fiable la taille de certains fichiers.

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
