### ISSUE TITLE
ADD a CTA for the newletter to the data.gouv.fr/posts page

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#191]
## Context :
- Since we add the “actualités” tab on data.gouv.fr homepage we have traffic on data.gouv.fr/posts (700 hits/week)
- We had lots of inscription to the newletters when the CTA banner was on for a week (approx 15/day)

I feel that a component under the search area would be nice. The possibility for users to enter their email adress directly (without leaving this page) would be optimal. 
🙏
 
## alternatives
We could have a more direct call to action in the footer, [example](https://www.cnil.fr/)

**Comment by abulte** [comment]
What I would probably do:
- define a block at the top in `posts/list` template in `udata` 
- override it in `udata-gouvfr` with a CTA to the newsletter signup, with a configurable URL

**Comment by agarrone** [comment]
Sounds good 😃
