### ISSUE TITLE
Code transparent dans la documentation de l'API

### ISSUE THREAD

**Issue by mdamien** [etalab/data.gouv.fr#192]
## Description du bug
La réponse JSON est affichée blanc sur blanc dans la documentation de l'API

![image](https://user-images.githubusercontent.com/1469823/99893395-f3578500-2c7f-11eb-83e8-9c285c8eebb4.png)

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à https://doc.data.gouv.fr/api/reference/#/discussions/get_discussion
2. Descendre un peu plus bas dans "Responses"
3. Constater le bug

## Comportement attendu

Je m'attend a pouvoir lire le texte affiché

**Comment by abulte** [comment]
Related to https://github.com/etalab/doc.data.gouv.fr/issues/85

**Comment by ThomasG77** [comment]
Code block background color is inherited from https://github.com/etalab/template-jekyll/blob/master/assets/css/template.css#L190

As we prefer not touching the template.css file from repo https://github.com/etalab/template-jekyll, we can play at main.css level e.g https://github.com/etalab/doc.data.gouv.fr/blob/master/assets/css/main.css#L64 by adding at the end a CSS with more specificity on `<code>` block

To change `background-color`

```
.swagger-ui .code, .swagger-ui code {
  background-color: var(--darker-grey);
}
```

Overview of the `background-color` change

![Background option](https://user-images.githubusercontent.com/642120/158019947-b7b17d28-856a-466c-bdc5-c893e8a86588.png)


or to change font `color`

```
.swagger-ui .code, .swagger-ui code {
  color: var(--darker-grey);
}
```

Other with font `color` change
![Font color option](https://user-images.githubusercontent.com/642120/158019962-9e323f1b-31fb-4f79-aee4-f1a97600fdf2.png)

Color variable I've used is borrowed from https://github.com/etalab/doc.data.gouv.fr/blob/master/assets/css/customvariables.css#L7 Any other color could fit. A choice to do. I can make a PR after discussion (3 lines...)
