### ISSUE TITLE
Add a redirection page between doc.data.gouv.fr and guides.etalab.gouv.fr

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#193]
## Context :  
Etalab's guides are hard to find (through etalab.gouv.fr only). 

## Proposition 
In order not to overload the number of tab on data.gouv.fr home page we could propose a redirection page on the model of https://guides.etalab.gouv.fr/ with two CTA. 

When users clic on the documentation tab they would land on a redirection page where they could either go to guides.etalab.gouv.fr or to doc.data.gouv.fr.

In the meantime, I made a [issue](https://github.com/etalab/doc.data.gouv.fr/issues/99) to propose modifications on the doc.data.gouv.fr homepage  

## Alternatives : 
- Add the guides to data.gouv.fr footer ? 
- Add the guides as a tab on data.gouv.fr
- Replace documentation by the guide and put the documentation in the footer

**Comment by abulte** [comment]
Maybe the redirection page should live on doc.data.gouv.fr, serving as the home page.

> Replace documentation by the guide and put the documentation in the footer

Not favorable to this, doc.data.gouv.fr is truly the doc of data.gouv.fr, it needs to be easily discoverable.

PS: we can speak French here ;-)

**Comment by agarrone** [comment]
> Maybe the redirection page should live on doc.data.gouv.fr, serving as the home page.

Yes that's what I was thinking.

> Not favorable to this, doc.data.gouv.fr is truly the doc of data.gouv.fr, it needs to be easily discoverable. Guides are much more generic.

Agreed.

> PS: we can speak French here ;-)

Ok cool ^^

**Comment by agarrone** [comment]
Hello,
J'avais proposé des modifs sur la home de doc.data.gouv.fr pour rediriger vers les guides : https://github.com/etalab/doc.data.gouv.fr/issues/99
après réflexion je me dis que le mieux serait sûrement de disposer d'un menu déroulant sur l'onglet "documentation" qui propose :
- Documentation de data.gouv.fr 
- Les guides de l'open data 

Est-ce envisageable / souhaitable selon toi ?

**Comment by abulte** [comment]
Ca me parait être une bonne solution, pas trop compliquée à mettre en oeuvre. @quaxsze tu mets ça dans ton backlog ?
