### ISSUE TITLE
Position erratique des membres d'une organisation

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#2]
Dans l'administration, les bulles représentant les membres d'une organisation sont placés de manière assez étrange.

<img width="492" alt="capture d ecran 2017-09-06 a 15 53 36" src="https://user-images.githubusercontent.com/1231232/30119763-124732da-9327-11e7-9af7-e1b3c9aeff88.png">

C'est perturbant.

**Comment by abulte** [comment]
Plus ou moins lié à https://github.com/opendatateam/udata/issues/934. Refactor de ce bloc, flexbox ? /cc @oncletom @thimy

**Comment by thimy** [comment]
Lié au fait que certaines photos ne soient pas carrées, il faudrait forcer leur taille en les croppant.

**Comment by noirbizarre** [comment]
Lié au changement sur les vignettes (`avatar` vs. `avatar_thumbnail`).
Corrigé dans opendatateam/udata#1115

**Comment by noirbizarre** [comment]
Correctif livré aujourd'hui
