### ISSUE TITLE
Pb moissonnage Ckan

### ISSUE THREAD

**Issue by sfichet** [etalab/data.gouv.fr#200]
## Description du bug
Nous essayons de créer un moissonnage de notre plateforme Ckan.
Pas d'erreur particulière lors de la saisie des paramètres et le robot reste en attente de validation.
Mais lorsqu'on clique sur Prévisualiser, des échecs sont affichés sur tous les jeux pré moissonnés 
![image](https://user-images.githubusercontent.com/82090436/113848825-26b33000-9799-11eb-86be-5ad51c1e935a.png)
![image](https://user-images.githubusercontent.com/82090436/113848945-49454900-9799-11eb-8fdb-d131023e4e4b.png)

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à Datagouv/administration
2. Cliquer sur le Robot de moissonnage/Editer/Prévisualiser

## Comportement attendu
Validation et prévisualisation du moissonnage

**Comment by abulte** [comment]
Bonjour,

Si ce problème est toujours d'actualité, vous pouvez nous contacter sur https://support.data.gouv.fr.
