### ISSUE TITLE
Ajouter une notion de "message de commit" sur les mises à jour de ressource

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#201]
Il pourrait être intéressant de laisser la possibilité de rajouter un commentaire ou un message lors de la mise à jour d'une ressource. Cela pourrait permettre d'ajouter des indications méthodologiques (ex : changement dans la nature d'un calcul) ou des indications sur les changements (ex : nouvelle colonne).

Cela pourrait aider les réutilisateurs à comprendre le contenu des ressources et réduire la friction lors d'un usage continu d'un jeu de données.

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
