### ISSUE TITLE
Les cartes des jeux de données n'affichent pas le bon nombre de réutilisations

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#202]
Capture d'écran d'un oembed :

<img width="952" alt="Screenshot 2021-05-02 at 15 06 46" src="https://user-images.githubusercontent.com/27315/116814260-4818f900-ab58-11eb-9d21-b56ab6e3bb7d.png">

La source :

https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/

Il manque également l'icône.

**Comment by maudetes** [comment]
Il me semble que ça a été corrigé par #317. Tu valides?

**Comment by taniki** [comment]
Nope.

<img width="992" alt="Screenshot 2021-07-22 at 09 30 57" src="https://user-images.githubusercontent.com/27315/126603906-4c57006b-c8a4-4c92-b48a-b89028715b15.png">

D'ailleurs, le nombre n'est pas bon non plus directement sur la page d'une réutilisation : https://www.data.gouv.fr/fr/reuses/visualiser-les-indicateurs-departementaux-sous-forme-de-timechart/

**Comment by taniki** [comment]
Sur la home, la plupart des jeux de données indiquent 0 réutilisation alors qu'il y en a bien quelques unes quand même.

<img width="1333" alt="Screenshot 2021-07-22 at 11 31 53" src="https://user-images.githubusercontent.com/27315/126618321-8209f166-85c3-4642-95f9-ad621c25ac7d.png">

**Comment by taniki** [comment]
À froid, je dirai qu'il reste encore des `dataset.metrics.reuses` à divers endroits https://github.com/etalab/udata-gouvfr/search?q=%22metrics.reuses%22

**Comment by maudetes** [comment]
Il me semble que c'est bon de mon côté. Tu valides @taniki ?
![image](https://user-images.githubusercontent.com/28541902/132357832-ca999a8f-0f74-48f9-87ea-56bd8d23435d.png)

**Comment by taniki** [comment]
yes, je confirme 👍  https://observablehq.com/@taniki/datagouvfr-oembed

**Comment by taniki** [comment]
Chelou, les nombres de réutilisations n'est plus à jour sur les cartes en embed. Par exemple, ici https://observablehq.com/d/b53f29df0a15b1a4.

Également vrai pour l'affichage sur la homepage de data.gouv.fr

<img width="441" alt="Screenshot 2021-09-29 at 12 02 41" src="https://user-images.githubusercontent.com/27315/135248312-66994731-bc36-4e3d-87a9-b76028e3a708.png">

**Comment by maudetes** [comment]
@abulte After a short investigation, I think that we should either add a signal to update dataset reuses metrics or schedule the `update-datasets-reuses-metrics` job added [here](https://github.com/opendatateam/udata/pull/2531).

In the meantime @taniki, the reuse count has been recomputed for this particular dataset.

**Comment by quaxsze** [comment]
Le job `update-datasets-reuses-metrics` a été planifié et les choses devrait rentrer dans l'ordre. Concernant cette métrique un job a été créé plutôt qu'une fonction cachant le signal car la purge de reuss à sa suppression nous empêche de catcher le signal `delete` et donc d'updates les métriques du dataset correspondant.
