### ISSUE TITLE
Extraire les chaines à traduire

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#208]
- Ecrire un script qui extrait les chaines en `@@` depuis les fichiers JS et les intégrer dans un `.po` traduisible via Crowdin
- Ecrire un script qui extrait les chaines en `@@` depuis les fichiers python et les intégrer dans un `.po` traduisible via Crowdin

⚠️ 🗣️ Nos chaines `@@` sont en français, et la langue d'origine est censée être l'anglais dans notre système de traduction. Comment faire cette bascule ?

**Comment by maudetes** [comment]
Pas de string @@ à extraire dans les .py, mais à extraire dans les template .html.
Les extractions de string en .js se font dans le format key-value vue-i18n.

Possibilité d'utiliser `python setup.py compile_catalog` et `npm run i18n:extract` respectivement pour l'extraction de strings.

Il reste la question de la bascule de la langue d'origine français vers anglais.
