### ISSUE TITLE
Impossible de complètement renommer un utilisateur

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#21]
Bien qu'étant une mauvaise pratique, de nombreux utilisateurs "Administrateur XX" sont créé par des organisations.
Lorsque l'organisation change de nom, l'administrateur change le nom de l'organisation et de l'utilisateur sur data.gouv.fr.

Il semblerait que le renommage des utilisateurs soit incomplet :

Auto-complétion (nouveau nom souhaité) :
<img width="504" alt="capture d ecran 2017-09-11 a 15 31 51" src="https://user-images.githubusercontent.com/1231232/30276854-6a608222-9706-11e7-965e-428182cdb573.png">

Pop-in ajout membre (ancien nom) :
<img width="327" alt="capture d ecran 2017-09-11 a 15 32 00" src="https://user-images.githubusercontent.com/1231232/30276877-83ed952c-9706-11e7-918b-90e83b6c9470.png">

Page profil (ancien nom) :
<img width="428" alt="capture d ecran 2017-09-11 a 15 31 10" src="https://user-images.githubusercontent.com/1231232/30276992-ccf03964-9706-11e7-9242-b2fd3efb6e8c.png">

**Comment by oncletom** [comment]
Ça sent le délai d'indexation dans ElasticSearch ça :-)

**Comment by jdesboeufs** [comment]
Peut-être, mais l'admin que j'ai eu au téléphone semblait dire que ça fait un moment.

**Comment by oncletom** [comment]
Je plaiderais pour le fait qu'elle n'est jamais réindexée dans ce cas ;-)

**Comment by agarrone** [comment]
@quaxsze Je peux fermer ?

**Comment by agarrone** [comment]
Ne pas hésiter à rouvrir si le pb persiste
