### ISSUE TITLE
"Latest url" correspond à "URL Stable" en anglais

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#215]
<img width="596" alt="Screenshot 2021-05-19 at 23 18 28" src="https://user-images.githubusercontent.com/27315/118885869-90763c00-b8f8-11eb-81fe-6bc54dd4f451.png">

<img width="598" alt="Screenshot 2021-05-19 at 23 16 30" src="https://user-images.githubusercontent.com/27315/118885879-91a76900-b8f8-11eb-8616-09f2f53b5a4f.png">

Sur le moment ça ne me paraît pas logique et intuitif.

**Comment by maudetes** [comment]
Il me semble que maintenant le terme utilisé en anglais est Permalink. Est-ce que ça te semblerait correct?

**Comment by taniki** [comment]
yes ça me va :)
