### ISSUE TITLE
Migrer le contenu des pages statiques existantes en markdown

### ISSUE THREAD

**Issue by sabinesafi** [etalab/data.gouv.fr#216]
pages hardcodées à passer en markdown dans github

|page|décision|
|-----|--------|
|https://www.data.gouv.fr/fr/suivi|A migrer en markdown ⚠️ iframe + redirection nginx |
|https://www.data.gouv.fr/fr/reference|A migrer en markdown avec inclusions de jeux de données en frontmatter + redirection ginx|
|https://www.data.gouv.fr/fr/licences|A migrer en markdown + redirection nginx|
|https://www.data.gouv.fr/fr/terms/|A migrer markdown + utilisation du mécanisme intégré pour récupérer du md sur datagouvfr-pages|
|https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/c3.html|?|
|https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/dataconnexions-5.html|?|
|https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/dataconnexions-6.html|?|
|https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/nec_mergitur.html|?|
|https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/openfield16.html|?|
|https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/redevances.html|A migrer en markdown + redirection nginx|

### Actions :

- Passer les pages HTML en Githubpages
- Plus tard on verra pour faire dans le CMS [data.gouv.fr](http://data.gouv.fr)
- Il faut être capable de gerer les dossier dans le repo pages

- Pages statiques convertir en markdown dans le dépot : avant fin juin
- Gérer les redirection : Alexandre (typiquement page licence)
- Itérer sur le gabarit durant l'été pour mettre les embed de jeux de données au milleu (not tableau de suivi au millieu ?)

**Comment by restuccia** [comment]
Fun fact, terms are *already* in markdown https://github.com/opendatateam/udata/pull/1285

**Comment by restuccia** [comment]
https://github.com/etalab/datagouvfr-pages/pull/22

**Comment by restuccia** [comment]
Les pages statiques en HTML ont été réécrites en markdown avec la même structure des pages inventaires.

Pour les pages statiques des hackathons (c3, nec-mergitur, dataconnexions-5, dataconnexions-6, openfield16), je propose de ne pas les garder vu qu'elles n'ont reçu presque aucune visite au cours de l'année dernière.

Prochaines étapes **à court terme** :
- Tester les nouvelles pages statiques en markdown
- Améliorer l'organisation et la gestion du repo [etalab/datagouvfr-pages ](https://github.com/etalab/datagouvfr-pages/)
- Gérer les redirection : Alexandre (typiquement page licence)

**À moyen terme** : 
- Itérer sur le gabarit durant l'été pour mettre les embed de jeux de données au milleu (notamment tableau de suivi au millieu, page SPD)
- Considerer la possibilité de générer des pages statiques à partir du CMS data.gouv.fr

**Comment by agarrone** [comment]
FYI j'ai changé les mailto sur les pages en markdown migrées par @restuccia en faveur des deeplink pertinents du support ainsi que sur la page licence en html actuellement en prod.
