### ISSUE TITLE
Suivi des discussions du point de vue des usagers

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#217]
Petit retour usager :)

- Il n'y a pas d'autre endroit que la page profil pour retrouver mes fils de discussion
  - si celle-ci disparaît le seul moyen de retrouver sera si jamais quelque se passe dans le fil de discussion et que j'en suis notifié
- J'aimerai savoir si ~~ma question a été lue au moins une fois par une personne membre de l'organisation productrice~~ j'ai une réponse, si je vais en avoir ou bien quand je vais en avoir une
  - indicateur lu/non lu par une personne de l'organisation productrice
  - délai moyen de réponse de l'organisation

**Comment by abulte** [comment]
Bien vu, on pourrait le mettre là https://www.data.gouv.fr/fr/admin/me/

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
