### ISSUE TITLE
API : permettre de filtrer les discussions par dates

### ISSUE THREAD

**Issue by fchabouis** [etalab/data.gouv.fr#218]
## L’amélioration que vous avez en tête

J'aimererais pouvoir récupérer les discussions liées à un dataset, ayant été postées après une datetime donnée. Par exemple : `https://www.data.gouv.fr/api/1/discussions/?for=536997fea3a729239d204e35&after=2021-05-31T15:00:00Z`

J'ai appris l'existence de ce endpoint de l'API permettant de récupérer tous les commentaires liés à un dataset, ce qui est très pratique. (J'ai par contre l'impression qu'il n’apparaît pas dans la documentation de l'API, je ne sais donc pas s'il est "officiel").

## Les alternatives possibles
Un peu de contexte : nous avons développé pour transport.data.gouv.fr un worker sur notre site qui va quotidiennement récupérer tous les commentaires postés sur les datasets que nous référençons sur notre site. Il envoie un mail récapitulatif à l'équipe afin que nos chargés de déploiement soient prévenus des discussions en cours sur les datasets que nous suivons.
En l'état notre worker fonctionne. Par contre il doit télécharger quotidiennement tout l'historique des discussions qui nous intéressent. Un petit filtre rendrait la tâche beaucoup plus légère des 2 côtés de l'appel.

Une autre alternative serait d'avoir la possibilité de s'abonner à un jeu de données, et d'être prévenu par mail en cas de nouveaux commentaires .

Un exemple de mail envoyé :
![image](https://user-images.githubusercontent.com/15341118/120323642-fd6cd700-c2e5-11eb-919f-52bcc0a9b0d4.png)

**Comment by thbar** [comment]
Points bonus si:
- On peut passer plusieurs ids de dataset à la fois
- Et que la réponse est éventuellement paginable

Ce sont deux caractéristiques qui peuvent aider à faire des exports "en volume" facilement.

**Comment by abulte** [comment]
Voilà les arguments existants sur ce endpoint (pas de before ou since malheureusement) :

```
parser = api.parser()
parser.add_argument(
    'sort', type=str, default='-created', location='args',
    help='The sorting attribute')
parser.add_argument(
    'closed', type=boolean, location='args',
    help='Filters discussions on their closed status if specified')
parser.add_argument(
    'for', type=str, location='args', action='append',
    help='Filter discussions for a given subject')
parser.add_argument(
    'page', type=int, default=1, location='args', help='The page to fetch')
parser.add_argument(
    'page_size', type=int, default=20, location='args',
    help='The page size to fetch')
```

**Comment by abulte** [comment]
Je sais que c'est pas propre mais pour faire ça j'utilise soit un timestamp stocké en local pour connaitre la dernière date de synchro et je remonte jusqu'à cette date, soit je pars du principe que l'intervalle est stable et je compare au now() - intervalle.

**Comment by fchabouis** [comment]
Merci @abulte pour les précisions. La stratégie que tu décris (stockage du dernier timestamp) est effectivement ce que nous avons mis en place. La solution now() - interval nous a paru plus fragile, car les timestamps que nous recevons de data.gouv sont en local time (pas de timezone associée), ce qui m'a fait craindre de soustraire des choux UTC à des carottes françaises (par exemple).

Pour le moment ça ne pose pas de problème, mais cela signifie que chaque jour nous re-téléchargeons l'ensemble de l'historique des discussions, dont le volume ne va faire qu'augmenter. Je préfère lancer la discussion avant de rencontrer le problème :)

**Comment by fchabouis** [comment]
Merci @abulte pour les précisions. La stratégie que tu décris (stockage du dernier timestamp) est effectivement ce que nous avons mis en place. La solution now() - interval nous a paru plus fragile, car les timestamps que nous recevons de data.gouv sont en local time (pas de timezone associée), ce qui m'a fait craindre de soustraire des choux UTC à des carottes françaises (par exemple).

Pour le moment ça ne pose pas de problème, mais cela signifie que chaque jour nous re-téléchargeons l'ensemble de l'historique des discussions, dont le volume ne va faire qu'augmenter. Je préfère lancer la discussion avant de rencontrer le problème :)

**Comment by fchabouis** [comment]
Autant la garder ouverte alors non ? Ca nous permet d'être notifié si vous vous y intéressez :)

**Comment by agarrone** [comment]
> Autant la garder ouverte alors non ? Ca nous permet d'être notifié si vous vous y intéressez :)

Hello, les deux approches se défendent mais je préfère prioriser la lisibilité du backlog ce qui devient complexe à + 200 issues. :)
