### ISSUE TITLE
les abonnés d'une réutilisation ne s'affichent pas bien

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#219]
<img width="350" alt="Screenshot 2021-06-02 at 16 42 14" src="https://user-images.githubusercontent.com/27315/120501161-af2d0600-c3c1-11eb-937c-eefa01787013.png">

https://www.data.gouv.fr/fr/reuses/hubblo/

**Comment by abulte** [comment]
Sanitizing probably
