### ISSUE TITLE
Discussion : stratégie d'implémentation des pages statiques

### ISSUE THREAD

**Issue by sabinesafi** [etalab/data.gouv.fr#221]
aujourdh'ui : 
- système des actu : CMS dans udata (markdown)
- licence, spd, cgu : pages statiques en HTML en dur dans udata.fr
- pages inventaires : récupère du markdown sur repo github pour afficher une page statique

=> est-ce qu'on passe tout en markdown ? et si oui comment on le fait ?

cf #216

**Comment by restuccia** [comment]
#216
