### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#225]
## Affichage

xxx

## Nettoyage

Entre 2015 et 2016, des différentes pages pour des hackathons ont été créées sur data.gouv.fr. Il s'agit de pages statiques avec des informations et des liens vers les jeux de données concernés :

- https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/c3.html
- https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/dataconnexions-5.html
- https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/dataconnexions-6.html
- https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/nec_mergitur.html
- https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/templates/openfield16.html

Si j'ai bien compris, des badges ont été créés aussi pour signaler ces jeux de données, par exemple à l'occasion de l'hackathon Nec Mergitur https://www.data.gouv.fr/fr/nec-mergitur, 54 jeux de données ont reçu le badge correspondant https://www.data.gouv.fr/fr/search/?badge=nec 

Quoi faire avec ces badges ? Peut-on les supprimer ?

**Comment by maudetes** [comment]
Je ferme ce ticket, voir https://github.com/etalab/data.gouv.fr/issues/248 pour la supression des badges obsolètes.
