### ISSUE TITLE
Traiter la question du menu header : quoi et comment

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#228]
Actuellement le header comprend les éléments suivants :

| Données | Réutilisations | Organisations | Tableau de bord | Documentation | Actualités | Support |
|---|---|---|---|---|---|---|

La voix "Documentation" est un dropdown avec les sous-sections "Documentation de la plateforme" et "Guides de l'Open Data".

Décisions à prendre :
- Les éléments à inclure dans le nouveau header (Tableau de bord va disparaître) ;
- Garder le dropdown ou avoir deux éléments différents pour documentation et guides ;

**Comment by restuccia** [comment]
Proposition de header, à tester : 

| Données | Réutilisations | Organisations | À propos| Documentation | Guides | Actualités | Support |
|---|---|---|---|---|---|---|---|

**Comment by taniki** [comment]
Plutôt "nous contacter" (ou quelque chose dans ce goût là) que "support". Perso, je trouve que c'est trop chargé. Je pense que Documentation peut sauter et vivre sa vie dans le footer.

**Comment by alicerou** [comment]
je mettrais le à propos et nous contacter en dernier. Est ce que le "à propos" mérite un header aussi visible ? pour moi il peut être dans le footer + une redirection vers ça en page d'accueil , et potentiellement avec nous contacter et/ou actualités ?

**Comment by restuccia** [comment]
Ok, du coup :
- On enleve "à propos" et on reporte le débat sur cette page ;
- On change "Support" en "Nous contacter" et on vire la doc (et les guides ?) (qui seront dans le footer #230 ainsi que référencées dans le support)

| Données | Réutilisations | Organisations  | Actualités | Nous contacter |
|---|---|---|---|---|

![Screenshot 2021-06-18 at 10-28-14 Accueil - data gouv fr](https://user-images.githubusercontent.com/51122275/122531556-ea654100-d01f-11eb-9d50-ad5fdea2c9d1.png)

**Comment by taniki** [comment]
![](https://media.giphy.com/media/dwFdpMQSqG0SUCAP9O/giphy-downsized.gif)

**Comment by gmougeolle** [comment]
C'est doublé tamponné ?

**Comment by abulte** [comment]
![](https://media.giphy.com/media/l2JHVUriDGEtWOx0c/giphy.gif)
