### ISSUE TITLE
Convertir schema-gouvfr ainsi que les autres plugins aux nouvelles views

### ISSUE THREAD

**Issue by quaxsze** [etalab/data.gouv.fr#229]
Les plugin schema_gouvfr, udata_recommendations, ect. appellent `from udata import theme` ce qui ne peut marcher en raison du déplacement du thème.
Il faut patcher ce plugin pour qu'il aille chercher le theme dans udata-gouvfr et (si necessaire) changer son attribut `udata.views` en `udata-gouvfr.views` dans le `setup.py`.

- [ ] Check intégration des plugins (#323)
- [ ] Merge des PR
- [ ] Release
- [ ] Deploy
- [ ] Test

**Comment by abulte** [comment]
List of plugins by priority

## Need to have

- [ ] gouvfr
- [ ] piwik
- [ ] metrics
- [ ] ckan
- [ ] dkan
- [ ] ods
- [ ] dcat
- [ ] maaf
- [ ] schema-gouvfr @geoffreyaldebert do you confirm that? or we can live without it for a while?

## Very very nice to have

- [ ] tabular

## Nice to have

- [ ] data-fair
- [ ] recommendations
- [ ] geoplatform

**Comment by geoffreyaldebert** [comment]
Yes I confirm, schema-gouvfr in the right category
