### ISSUE TITLE
Définir le contenu du bloc au dessus du footer

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#230]
Le contenu actuel du giga bloc au dessus du footer n'est pas encore défini.

En lien avec #228, définir le contenu de ce bloc.

Pour l'instant, les infos qui s'y trouvent sont:
- les thématiques 
- les données de référence
- les liens réseaux sociaux 
- les liens vers etalab et la DINUM

**Comment by restuccia** [comment]
**Contenus actuels du footer data.gouv.fr :** 

![Capture d’écran 2021-06-14 à 11 10 31](https://user-images.githubusercontent.com/51122275/121868331-24bd9e00-cd01-11eb-9243-bcf2978880db.jpg)

**La refonte aura trois sections de footer :**

![Capture d’écran 2021-06-14 à 11 11 33](https://user-images.githubusercontent.com/51122275/121868438-4880e400-cd01-11eb-8ff4-0758a11b8676.jpg)

Si le contenu de la deuxième section (giga Marianne, stuff.gouv, bouton langue) est décidé, il nous faut également choisir quels liens seront placés dans la dernière sections et quels plus "en évidence" dans la première.

Voici mes propositions.
Sans doute dans la dernière section :
- SPD (car également dans le _venti_ button)
- Licences
- API
- CGU
- Suivi et cookies
- Catalogue des données

À mettre plus en évidence et donc dans la première section :
- Actualités
- Thématiques à la une (+ liste de thématiques peut-être ?)
- Twitter, GitHub, feed RSS
- logo Etalab
- Versions udata et udata-gouvfr

Enfin, les thématiques traditionnelles vont disparaître, non ?

**Comment by restuccia** [comment]
Ajouter un lien vers data.europa.eu (aussi pour la traduction des descriptions des jdd)

**Comment by restuccia** [comment]
## Proposition 1
### Premier header

| data.gouv.fr                                                                                             | L'Open Data                                                                                            | Réseaux sociaux                                                                                                  | Logo Etalab                                                                  |
|----------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------|
| - Licences<br>- API du portail<br>- Conditions générales d'utilisation<br>- Politique de confidentialité | - Actualités<br>- Données de référence<br>- Catalogue des données<br>- Portail des données européennes | - Twitter<br>- LinkedIn<br>- Facebook (?)<br>- RSS<br>- Infolettre<br>- GitHub<br><br>Sauf mention contraire etc | Une mission de la DINUM<br>numerique.gouv.fr<br><br>trucs udata udata-gouvfr |

### Dernier header
???

## Proposition 2
### Premier header

| L'Open Data                                                                                            | Réseaux sociaux                                                                                                  | Logo Etalab                                                                  |
|--------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------|
| - Actualités<br>- Données de référence<br>- Catalogue des données<br>- Portail des données européennes | - Twitter<br>- LinkedIn<br>- Facebook (?)<br>- RSS<br>- Infolettre<br>- GitHub<br><br>Sauf mention contraire etc | Une mission de la DINUM<br>numerique.gouv.fr<br><br>trucs udata udata-gouvfr |

### Dernier header
| Licences | API du portail | Conditions générales d'utilisation | Politique de confidentialité | © République Française |
|----------|----------------|------------------------------------|------------------------------|------------------------|

**Comment by restuccia** [comment]
## Proposition 3
### Premier header
| L'Open Data                                                                                                                                                                                                        | Réseaux sociaux                                                                                                                                                             | Logo Etalab                                                                              |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------|
| - Actualités<br>- Données de référence<br>- Thématiques à la une<br>- Catalogue des données<br>- Guides de l'open data<br>- Documentation de data.gouv.fr<br>- Nous contacter<br>- Portail des données européennes | - Twitter<br>- LinkedIn<br>- Facebook (?)<br>- RSS<br>- Infolettre<br>- GitHub<br><br>Sauf mention contraire, tous les contenus de ce site sont sous licence <br>etalab-2.0 | Un département de la DINUM<br>numerique.gouv.fr<br><br>udata 3.0.0<br>udata-gouvfr 3.0.0 |

### Dernier header
| Licences | API du portail | Conditions générales d'utilisation | Politique de confidentialité | 
|----------|----------------|------------------------------------|------------------------------|

**Comment by restuccia** [comment]
## Proposition 4
### Premier header
| L'Open Data                                                                                                                      | Support                                                                         | Réseaux sociaux                                                                                                                                                             | Logo Etalab                                                                              |
|----------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------|
| - Actualités<br>- Données de référence<br>- Thématiques à la une<br>- Catalogue des données<br>- Portail des données européennes | - Documentation de la plateforme<br>- Guides de l'Open Data<br>- Nous contacter | - Twitter<br>- LinkedIn<br>- Facebook (?)<br>- RSS<br>- Infolettre<br>- GitHub<br><br>Sauf mention contraire, tous les contenus de ce site sont sous licence <br>etalab-2.0 | Un département de la DINUM<br>numerique.gouv.fr<br><br>udata 3.0.0<br>udata-gouvfr 3.0.0 |

### Dernier header
| Licences | API du portail | Conditions générales d'utilisation | Politique de confidentialité | 
|----------|----------------|------------------------------------|------------------------------|

**Comment by restuccia** [comment]
(je voulais dire footer, pas header bien sûr)

**Comment by restuccia** [comment]
Yes merci ! On peut aussi écrire directement data.europa.eu, comme tu préfères
