### ISSUE TITLE
Fix les champs de recherche non fonctionnels

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#233]
Les champs de recherches avancés `Zone géographique` et `Granularité géographique` ne sont pas fonctionnels : impossibilité de filtrer sur une zone géographique ou une granularité (ou pas trouvé les bons mots clés, ex: Bretagne, paris, etc.).
De plus, un symbole `multiselect-spinner` s'affiche en continu, de même pour le champ `Licenses` (lui fonctionnel).

Soit fixer les champs, soit les enlever pour l'instant si non implémentés derrière.

**Comment by gmougeolle** [comment]
Pour les deux champs géographiques, le soucis vient de l'API qui fait des 404 : https://staging.data.gouv.fr/api/1/spatial/granularities/
et
https://staging.data.gouv.fr/api/1/spatial/zones/suggest/?q=e
En local, ces APIs fonctionnaient quand j'ai fait la recherche, mais elles semblent être cassées également aujourd'hui.
Du coup c'est plutôt à voir avec @quaxsze 🤕 

Pour le champs "Licenses", le bug vient de la lib, en fait le spinner ne s'affiche que si on ouvre le dropdown et qu'on le referme sans rien choisir. Très difficile voire impossible à régler en l'état, et étant assez minime je propose qu'on le laisse tomber dans l'immédiat 😉
