### ISSUE TITLE
Page user cassée

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#238]
L'affichage des pages users est cassé.

![user page](https://user-images.githubusercontent.com/28541902/122211880-81f35400-cea7-11eb-846c-2c44d73e2380.png)

**Comment by gmougeolle** [comment]
Il me semble qu'on avait dit que c'était une page qui devait disparaître @abulte @taniki ?

**Comment by gmougeolle** [comment]
La carte utilisateur fait toujours un lien vers la page 😅

**Comment by abulte** [comment]
Ca faut changer pour MVP pour le coup :-)

**Comment by abulte** [comment]
(le lien sur la carte pas la page user)

**Comment by gmougeolle** [comment]
(voir commit ci-dessus référencé)

**Comment by maudetes** [comment]
On peut encore y accéder depuis les discussions où les avatars sont cliquables.
