### ISSUE TITLE
Lors d'un clic sur mot clé d'une réutilisation, redirection vers une page https://staging.data.gouv.fr/fr/search/ qui renvoie une 500

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#239]
Exemple de la réutilisation https://staging.data.gouv.fr/fr/reuses/france-elections-io/, lorsqu'on clique sur l'un des mots clés, on est redirigé vers une page https://staging.data.gouv.fr/fr/search/?tag=<tag> qui retourne une erreur 500.

Sans le param tag, une 500 est quand même retournée: https://staging.data.gouv.fr/fr/search/

**Comment by quaxsze** [comment]
De meme sur tous les tags.
L'utilisateur est redirigé vers la page `search/?tag=assurance-maladie` par exemple. Hors dans la refonte graphique cette page n'existe plus. Un équivalent actuel semble etre :
`http://dev.local:7000/fr/datasets/?keywords=assurance-maladie`
