### ISSUE TITLE
Appeler une taille de vignette de réutilisations plus grande dans les listes (si possible), pour l'instant c'est flou

### ISSUE THREAD

**Issue by gmougeolle** [etalab/data.gouv.fr#244]

**Comment by gmougeolle** [comment]
On utilise la version `-100` des vignettes, il ne semble pas exister de version plus grande. Le seul fix que je vois dans l'état c'est de ne pas utiliser la vignette mais l'image elle-même, sachant qu'on affiche rarement plus de 5 réutilisations (sauf sur la page de liste où il y en a 20), et là ça rend beaucoup plus joli.

**Comment by abulte** [comment]
il faudrait quelle taille de vignette ? pas trop compliqué à rajouter normalement je crois @quaxsze

**Comment by abulte** [comment]
Je vois aussi `IMAGE_MAX_SIZE = 800` donc au pire on sera pas hyper giga lourdaud.

**Comment by abulte** [comment]
Donc go pour full size en MVP (sauf si tu te rends compte qu'on explose les 800 en réalité).

**Comment by abulte** [comment]
+ carte dans le backlog avec la "bonne" taille de vignettes à générer.
