### ISSUE TITLE
Ajouter une taille de vignette pour les réutilisations

### ISSUE THREAD

**Issue by gmougeolle** [etalab/data.gouv.fr#245]
Suite de #244 : pour les cartes des réutilisations, les tailles de vignettes existantes sont 25 de large, 50 de large ou 100 de large. Malheureusement c'est trop peu pour les nouvelles cartes qui sont donc floues.

Il faudrait donc créer une taille de vignette de 300 ou 400 de large (on affiche environ en 300 de large mais beaucoup plus de hauteur donc se laisser un peu de marge peut être bénéfique).

Linked #370

**Comment by maudetes** [comment]
Vignette 500*500 ajoutée pour les réutilisations.
