### ISSUE TITLE
Supprimer les badges obsoletes

### ISSUE THREAD

**Issue by quaxsze** [etalab/data.gouv.fr#248]
Les badges suivants : 
 - c3 
 - Dataconnexions 5 candidate
 - Dataconnexions 5 laureate
 - Dataconnexions 6 candidate
 - Dataconnexions 6 laureate
 - Nec Mergitur
 - openfield16
 
sont obsolètes.
Il faut les supprimer des modèles, des tests ainsi que les vues correspondantes.
Une migration est à faire possiblement concernant les JDD existants avec ces badges.

**Comment by restuccia** [comment]
Autres badges :

- spd
- covid-19
- bal

Même s'ils ne sont pas obsolètes, ils ne sont pas maintenus : pour spd et covid il y a les pages, pour les bal on utilise plutôt le tag.

**Comment by quaxsze** [comment]
On garde SPD après discussion. Pour BAL voir combien de JDD sont badgés avec.

**Comment by restuccia** [comment]
https://www.data.gouv.fr/fr/datasets/?badge=bal

**Comment by maudetes** [comment]
Côté Adresse, c'est bon pour enlever BAL.
