### ISSUE TITLE
Les liens des pages inventaires sur `staging` renvoient vers `www`

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#249]
https://staging.data.gouv.fr/fr/pages/donnees-cles-par-sujet

**Comment by gmougeolle** [comment]
Toutes les pages statiques sont codées en dur en markdown : https://github.com/etalab/datagouvfr-pages/blob/master/pages/donnees-cles-par-sujet.md

Du coup les adapter devient un peu complexe, cela dit le sujet était déjà un peu présent sur ces pages statiques avec la question des oembed pour facilement insérer des jeux de données, orga ou réutilisations au sein du contenu.
Sans aller jusqu'à créer un DSL pour ça, on peut tout à fait imaginer pouvoir également lier des pages du site via un shortcode ou autre au lieu de coder les liens en dur (ça ouvre la porte à 1000 autres problèmes mais c'est à réfléchir), ce qui réglera ce genre de problème.

**Comment by abulte** [comment]
Pour ce cas précis des URLs relatives dans le markdown devraient faire le taf, non ?

**Comment by gmougeolle** [comment]
Dans le cas précis absolument, je laisse qui de droit faire la modif sur le markdown !
Pour le long terme en revanche ça laisse pas mal de problèmes : liens qui deviennent morts et enfer de 301, et pas de support pour les traductions par exemple, je sais pas si c'est bloquant ?

**Comment by abulte** [comment]
Pas de traduction de pages statiques :-) Liens morts oui mais pas plus qu'avec des URLs relatives. J'assigne à nos éditeurs !

**Comment by abulte** [comment]
Solution : 

```
- [Les données relatives au COVID-19](https://www.data.gouv.fr/fr/pages/donnees-coronavirus)
```

--> 

```
- [Les données relatives au COVID-19](/fr/pages/donnees-coronavirus)
```

**Comment by restuccia** [comment]
_\*cracks knuckles\*_
_\*prepares a quick regex\*_
