### ISSUE TITLE
Certaines lettres "g" sont coupées

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#250]
<img width="66" alt="Screenshot 2021-06-24 at 10 47 08" src="https://user-images.githubusercontent.com/27315/123232703-b5eafc80-d4d9-11eb-8fbf-dd7658eadec7.png">
<img width="74" alt="Screenshot 2021-06-24 at 10 47 00" src="https://user-images.githubusercontent.com/27315/123232710-b7b4c000-d4d9-11eb-8cdd-d356afede7be.png">
<img width="173" alt="Screenshot 2021-06-24 at 10 46 55" src="https://user-images.githubusercontent.com/27315/123232716-b84d5680-d4d9-11eb-9a65-900539f95245.png">

**Comment by gmougeolle** [comment]
J'attends pour fixer celui-ci car j'ai peur des effets de bord : suite au changement pour la Marianne, la `line-height` que l'on utilise doit être augmentée pour éviter de couper le jambage de ces lettres, et cette opération présente un risque élevé de décaler du texte (en changeant la hauteur et donc les espacements) dans plein d'endroits et de recoins.

**Comment by alicerou** [comment]
le g de "organisation" dans le bandeau
![image](https://user-images.githubusercontent.com/82669567/124779533-26fecb00-df42-11eb-9683-296e88ab2665.png)

**Comment by alicerou** [comment]
![image](https://user-images.githubusercontent.com/82669567/124782252-5f070d80-df44-11eb-8d73-3f8448aa245f.png)
