### ISSUE TITLE
Champ de recherche des réutilisations

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#253]
Le champ de recherche dans la page reuses n'affiche pas le mot recherché.

### Comment reproduire le bug :
- Aller sur réutilisations (/reuses/)
- Rechercher un truc
- Appuyer sur Enter

### Comportement attendu :
- Le mot recherché devrait apparaître dans le champ de recherche

### Comportement actuel :
- Le champ de recherche est vide 

![Capture d’écran 2021-06-24 à 11 07 28](https://user-images.githubusercontent.com/51122275/123235668-5fcb8880-d4dc-11eb-8129-008a7522b7de.jpg)

**Comment by gmougeolle** [comment]
Good catch !
(not so) Fun fact : sur le site actuel, le fait de remplir la barre de recherche est fait en javascript.
