### ISSUE TITLE
Visuel "Merci de vous connecter"

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#255]
## Description du bug
Lorsque on essaye de faire quelque chose pour laquelle il est nécessaire de se connecter (e.g. commenter un jeu de données, ajouter une ressource communautaire, etc.), la login view qui s'affiche a un petit bandeau pas trop joli

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Ne pas être connecté·e
2. Aller dans un jeu de données
3. Essayer de ajouter une ressource communautaire
4. La login view apparaît 

## Comportement attendu
Une login view sans le bandeau "Merci de vous connecter pour accéder à cette page"

![Capture d’écran 2021-06-24 à 11 14 41](https://user-images.githubusercontent.com/51122275/123237192-b9808280-d4dd-11eb-9e0f-9c3af87ebbb2.jpg)

**Comment by gmougeolle** [comment]
Ce message vient de ce code qui concerne les `get_flashed_messages()` : https://github.com/opendatateam/udata/blob/86173677392abedc532aabf1b78e842496c81f2e/udata/templates/base.html#L9-L18

Je ne connais pas les implications de ce code, soit on peut le supprimer (@abulte ?), soit je peux proposer un habillage générique tel que voici :
![Capture d’écran 2021-06-24 à 17 20 03](https://user-images.githubusercontent.com/9059861/123289551-d8e4d300-d510-11eb-87a9-c479e7710d78.png)

**Comment by abulte** [comment]
L'habile habillage me parait seoir. On devrait avoir des flashs un peu partout (baked in Flask).
