### ISSUE TITLE
Logos des organisations qui ne sont pas carrés

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#257]
<img width="342" alt="Screenshot 2021-06-24 at 17 37 04" src="https://user-images.githubusercontent.com/27315/123291992-e8fdb200-d512-11eb-9d35-ef65894e89f3.png">

Possibilités :
- Laisser tel quel 🤷‍♂️ (et voir ce que ça donne avec des logo avec de la transparence ?)
- Rajouter un fond blanc et centrer

**Comment by gmougeolle** [comment]
I did this, ça rend OK sur les trucs petits comme Sciences Po, et ça rend bien sur les placeholders et autres ministères :
![Capture d’écran 2021-06-29 à 15 37 06](https://user-images.githubusercontent.com/9059861/123807142-e4a90e80-d8ef-11eb-95a5-fe0961efaf71.png)
![Capture d’écran 2021-06-29 à 15 36 20](https://user-images.githubusercontent.com/9059861/123807149-e541a500-d8ef-11eb-971b-c5ccb8d63e3e.png)
![Capture d’écran 2021-06-29 à 15 37 50](https://user-images.githubusercontent.com/9059861/123807270-00141980-d8f0-11eb-93f2-955f5bb3faae.png)
