### ISSUE TITLE
Wording dans le cartouche de recherche "jamais réutilisé"

### ISSUE THREAD

**Issue by schignard** [etalab/data.gouv.fr#26]
Tout en bas du cartouche de recherche de datagouvfr figurent les facettes suivantes: "jamais réutilisé / peu réutilisé / assez réutilisé / souvent réutilisé".
Il me semble que le wording retenu induit en erreur nos utilisateurs (et les observateurs). Ainsi on vient de nous faire remarquer que "95% des jeux de données ne sont jamais réutilisés". 
Or ce n'est pas vrai, sauf à considérer que les réutilisations publiées sur datagouvfr représentent l'intégralité des réutilisations... Dans ce cas il faudrait expliquer comment 5000 téléchargements de Sirene par mois se traduisent en seulement 27 réutilisations publiées depuis janvier... 
C'est même un peu contre-productif (amha). 

<img width="353" alt="cartouche-datagouvfr" src="https://user-images.githubusercontent.com/5797215/31072607-d8c24260-a768-11e7-8825-072e6db8c5dd.png">

**Comment by oncletom** [comment]
Est-ce que l'idée qui veut être véhiculée serait : "Contributions de la communauté" ?

Une réutilisation (publique) sous-entend de réutiliser les données mais y'a aussi des contributions de communautés attachées à des jeux de données, qui sont des données transformées — de la documentation, des articles.

Ça permettrait de mettre les contributions sous une même étiquette et libeller le tout :

**Contributions de la communauté** :

- Sans contribution
- Quelques contributions
- Nombreuses contributions

?

**Comment by schignard** [comment]
Si c'est une solution que l'on peut facilement mettre en place, je vote pour !

**Comment by noirbizarre** [comment]
Hum, après c'est un peu le problème partout sur datagouv avec la notion de réutilisations: c'est de l'opt-in et nous ne sommes capables de présenter à l'utilisateur que celles que nous connaissons.

Du coup, sur cette logique, il faudrait aussi corriger les autres références absolue à "réutilisations".

"Contributions" me dérange vu qu'il sous entent un ajout au contenu initiale. Peut-être "réutilisations connues" et "aucune réutilisation connue" ?

**Comment by oncletom** [comment]
> "Contributions" me dérange vu qu'il sous entent un ajout au contenu initiale.

Wiktionary a cette définition de contribuer :

> Aider, de quelque manière que ce soit, à l’exécution, au succès d’un dessein, d’une entreprise ; avoir part à un certain résultat.

La notion d'ajout n'est pas systématique de ce que j'en comprends.
Bon et puis on demande déjà aux gens de _contribuer_ donc ça devrait se comprendre ;-)

<img width="409" alt="screen shot 2017-10-03 at 16 21 50" src="https://user-images.githubusercontent.com/138627/31130189-fb427e42-a856-11e7-9a61-ebf414ccb35b.png">

**Comment by schignard** [comment]
Je plussoie sur le terme "contributions". Il y a bien une discussion à avoir sur les réutilisations et ce qu'elles donnent à voir du potentiel de l'open data, mais pour le moment si on peut déjà changer le wording - et éviter de se prendre dans les dents que "95% des jeux de données ne sont pas réutilisés" - on aura un peu amélioré la situation.

**Comment by noirbizarre** [comment]
Hum, du coup est-ce que ça veut dire qu'on change le terme réutilisations partout pour être cohérent ?? Ou est-ce qu'on assume d'utiliser "contributions" uniquement en recherche alors que partout contribution défini un apport de l'utilisateur:
- sur la page d'un JDD ça regroupe réutilisation, discussions et ressource communautaires
- sur la home, contribuer = ajouter du contenu

Autre point, on a utilisé le terme "réutilisation" dans toutes nos communications depuis 4 ans, on l'a défini...  à tel point que d'autres plateforme le reprenne (ODS utilise le terme réutilisations aussi, CKAN aussi maintenant). Est-ce vraiment une bonne idée d'en changer ?

Bref mon point c'est que même si "contributions" est alléchant, changer de terme va perdre plus de personnes qu'autre chose là où le besoin est de préciser le périmètre (réutilisation recensées, enregsitrées, sur data.gouv.fr ....), c'est pas les qualificatifs qui manquent (95% des jeux de données n'ont pas de réutilisation recensée, 95% des jeux de données n'ont pas de réutilisations sur datagouv...)

@oncletom oui, on est d'accord, contribuer à datagouv => ajouter du contenu sur datagouv. C'est justement le fait le terme contribuer/contribution a déjà une signification différente sur datagouv et l'utiliser là avec un autre sens est précisement ce qui me dérange.

Prêt à en discuter...

**Comment by noirbizarre** [comment]
@schignard Je te réponds ici en français

Il a été décidé d'y répondre en 2 temps:
- quick-win: simplement préciser le contexte dans l'entête de la facette "Reutilisations connues"
- moyen terme: revoir de façon transverse la cohérence du wording et des facettes sur les réutilisation et les réappropriations

L'issue a été automatiquement fermée par le commit qui corrige ça (le quick-win)
