### ISSUE TITLE
Ajouter un bouton `trier par` sur la page de recherche dataset réutilisations & orga

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#260]
À défaut d'avoir un tri, je pense que ça permettrait d'avoir une information sur la pertinence d'un jeu de données

**Comment by maudetes** [comment]
How about this proposal ? @agarrone

![image](https://user-images.githubusercontent.com/28541902/131689508-f4abddd7-6c88-4adc-8c84-fbb3f6d3209b.png)

**Comment by agarrone** [comment]
It seems all right to me but it could probably be done better. The research bar trigger me somehow. I'll try to make proposition but do not wait for me in the meantime.

**Comment by agarrone** [comment]
Take advantages of this to reorganize this search see : https://www.notion.so/apigouv/Liste-au-p-re-no-l-Design-2774887b3eb94afc8d056c189912934c#078de60fb14240bea1faf5a3a7467df4
