### ISSUE TITLE
Besoins de traduction sur la version française

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#264]
- Les métadonnées des jeux de données qui aparraissent au survol sont en anglais 
- Footer marque de l'Etat (certains mots) 
- Barre de recherche reuse : "Search"
- Logout 
- Sur la recherche : "Licences"

**Comment by alicerou** [comment]
* sur la page Organisations, le titre "@@Organizations" est en anglais

**Comment by alicerou** [comment]
* bandeau "participez", certains éléùents ne sont pas marqués à traduire vers l'anglais : "créez ou trouvez une organisation" + boutons "publiez un jdd" et "publiez une réutilisation"

**Comment by maudetes** [comment]
Je crois que tout a été traité depuis.
Il reste le cas de Licences qu'on peut orthographier Licences (UK) ou Licenses (US) en anglais.
