### ISSUE TITLE
Cohérence entre `/datasets` et `/reuses`

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#265]
| ![Capture d’écran 2021-06-25 à 14 24 29](https://user-images.githubusercontent.com/51122275/123424491-2f114f00-d5c1-11eb-9e77-81fce558ce52.jpg) | ![Capture d’écran 2021-06-25 à 14 24 43](https://user-images.githubusercontent.com/51122275/123424493-30427c00-d5c1-11eb-9a82-20eb5ee1d180.jpg) |
|---|---|

Il y a plusieurs incohérences entre les deux pages `/datasets` et `/reuses` :
- Il y a un breadcrumb dans la page reuses et pas dans la page données ;
- La loupe 🔍 est bleue pour les reuses et grise pour les données ;
- La barre de recherche me semble plus grande pour les données ;
- Les filtres sont présentés de façon différente.

**Comment by maudetes** [comment]
En lien avec: https://github.com/etalab/data.gouv.fr/issues/286
