### ISSUE TITLE
Make sure all lorem ipsum has been removed

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#266]
Notamment : 
- Description jdd et reuse dans la recherche

**Comment by alicerou** [comment]
* texte des embed des jdd

**Comment by maudetes** [comment]
* texte des pages de connexion et d'inscription

**Comment by maudetes** [comment]
# Proposition

- Description jdd et reuse dans la recherche : Rechercher (un jeu de données | une réutilisation) sur la plateforme -> l'impression que ce texte n'est pas très utile en réalité
- Texte des embed des jdd : Vous pouvez facilement intégrer (ce jeu de données | cette réutilisation) sur votre site en intégrant cet extrait de code dans votre page
- Texte des pages de connexion et d'inscription : Vous n'avez pas besoin de vous connecter pour parcourir les différentes ressources du site. Par contre, (avoir un compte | vous connecter) vous permet de publier des jeux de données ou réutilisation, de créer ou trouver votre organisation, de poster des commentaires, etc. -> si on a quelque part une page sur l'intérêt de se connecter, ça peut juste être un lien "pourquoi se (connecter | créer un compte) ?"

**Comment by agarrone** [comment]
Sur la création du compte il y a : https://guides.etalab.gouv.fr/data.gouv.fr/creer-compte-utilisateur/

Il y a aussi du lorem ipsus ici : 
![image](https://user-images.githubusercontent.com/60264344/124155575-ed881480-da96-11eb-804d-7e0547cd4499.png)

Je propose : 
sous jdd : Les jeux de données sont un recueil de données, c’est-à-dire des informations structurées, facilement lisibles par une machine.
sous reuse : Les réutilisations désignent l’utilisation des données à d’autres fins que celle de la mission pour laquelle les données ont été produites.

**Comment by agarrone** [comment]
Je n'en voit plus perso 🔍

**Comment by maudetes** [comment]
Ah yes parfait, merci pour les suggestions !

Pour le lorem ipsum que tu mentionnes, c'est bien ce que tu avais signalé en premier "Description jdd et reuse dans la recherche" ou il s'agissait d'un autre ?
