### ISSUE TITLE
Faible contraste du bouton […] / [x] des filtres de recherche

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#268]
![Capture d’écran 2021-06-25 à 14 45 59](https://user-images.githubusercontent.com/51122275/123426734-10608780-d5c4-11eb-996f-7839505c87df.jpg)

![Capture d’écran 2021-06-25 à 14 37 37](https://user-images.githubusercontent.com/51122275/123426022-2752aa00-d5c3-11eb-88bf-363cd15622a7.jpg)

Le bouton […] pour afficher plus de filtres, et sa version transformée [x] pour en montrer moins, ont un contraste très faible par rapport au fond (et une couleur différente de celle des filtres)

**Comment by agarrone** [comment]
Pris en compte dans https://github.com/etalab/data.gouv.fr/issues/584
