### ISSUE TITLE
Syntax markdown de la description visible depuis la recherche

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#269]
`###` :(

![Capture d’écran 2021-06-25 à 14 56 35](https://user-images.githubusercontent.com/51122275/123427947-8addd700-d5c5-11eb-87e3-9186f20d1406.jpg)

**Comment by gmougeolle** [comment]
J'attendais que quelqu'un remonte ce bug car je n'avais vraiment pas envie de devoir m'en occuper, damned

**Comment by abulte** [comment]
On avait un `mdstrip` ou quelque chose comme ça dans l'ancien JS.

**Comment by gmougeolle** [comment]
I'm currently toying with this : https://github.com/stiang/remove-markdown
