### ISSUE TITLE
Avatar et lisibilité des discussions

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#27]
Lorsque des utilisateurs n'ayant pas d'avatar échangent, cela devient très compliqué de savoir qui dit quoi.
Un mécanisme d'avatar par défaut basé sur un algorithme apporterait un plus significatif.

Exemples :

http://avatars.adorable.io/
https://robohash.org/

<img width="853" alt="capture d ecran 2017-10-02 a 15 55 03" src="https://user-images.githubusercontent.com/1231232/31080816-25dd1c02-a78a-11e7-9907-44a4754eef79.png">

**Comment by noirbizarre** [comment]
Proposition ici: https://github.com/opendatateam/udata/pull/1193
