### ISSUE TITLE
Activer la prévisualisation des ressources en staging

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#271]
![Capture d’écran 2021-06-25 à 15 41 12](https://user-images.githubusercontent.com/51122275/123433526-d8f5d900-d5cb-11eb-9268-597b7ce3378b.jpg)

![Capture d’écran 2021-06-25 à 15 41 19](https://user-images.githubusercontent.com/51122275/123433520-d7c4ac00-d5cb-11eb-9168-276cf33032a2.jpg)

I <3 csvapi

**Comment by gmougeolle** [comment]
![Capture d’écran 2021-06-25 à 15 43 28](https://user-images.githubusercontent.com/9059861/123433811-24a88280-d5cc-11eb-9847-aed9b5f29620.png)

C'est pas activé sur staging en revanche, c'est donc entre les mains de @quaxsze

**Comment by maudetes** [comment]
Voir #229, les prévisualisations ont été activées par @quaxsze.
