### ISSUE TITLE
La recherche par mots clés ne filtre pas sur les mots clés

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#277]
Ex, voir https://staging.data.gouv.fr/fr/datasets/?keywords=irve qui retourne des datasets sans ce mot clé (les même résultats que sans filtre sur mots clés).

**Comment by gmougeolle** [comment]
Le mot clé part bien dans la requête à l'API mais les résultats ne sont pas bons : https://staging.data.gouv.fr/api/1/datasets/?q=&keywords=irve&page_size=20.
D'ailleurs je vois aussi que cette API ne renvoie pas le champs `public_service` des `organizations` et donc du coup les macarons `certified` ne s'affichent pas.
