### ISSUE TITLE
Changer le favicon ?

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#279]
Le design system propose une jolie Marianne https://gouvfr.atlassian.net/wiki/spaces/DB/pages/577930274/Ic+nes+de+favoris+-+Favicons

**Comment by restuccia** [comment]
Il n'y a toujours pas de favicon :(

**Comment by agarrone** [comment]
Je me permet de clore ce ticket car on ne veut pas la Marianne pour l'instant j'ouvrirai de nouveaux si besoin :)
