### ISSUE TITLE
Enquêter sur les tests python qui échouent aléatoirement

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#280]
Certains tests échouent de manière aléatoire et réussissent lorsqu'on les relance.
Voir https://app.circleci.com/pipelines/github/etalab/udata-gouvfr/454/workflows/415ce257-0930-4820-8e40-0cf163351ce7/jobs/4055/tests#failed-test-0.

Quelques pistes (peut-être totalement HS):
- https://github.com/jarus/flask-testing/issues/21
- tous les tests qui échouent sont en lien avec des csv

**Comment by abulte** [comment]
Upgrading to Flask >= 1.1.0 should do the the trick: https://github.com/pallets/flask/pull/3157 from https://github.com/pytest-dev/pytest-flask/issues/42
