### ISSUE TITLE
Les pages statiques avec un trailing `/` renvoient une 404

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#282]
Ex: https://staging.data.gouv.fr/fr/pages/donnees-des-elections/

**Comment by alicerou** [comment]
Je ne pense pas que ce soit le même problème mais la page données de référence ne marche pas : "Le serveur a rencontré une erreur interne et n'a pas été capable de compléter votre requête. Soit le serveur est surchargé ou il y a une erreur dans l'application.

L'identifiant de l'erreur est fe9b92e305ed41e0ad21e0324e9d3275"

**Comment by abulte** [comment]
@alicerou ça c'est lié à https://github.com/etalab/data.gouv.fr/projects/4#card-62947782
