### ISSUE TITLE
double chargement de la page recherche de jeux de données

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#286]
Quand j'arrive sur la page https://staging.data.gouv.fr/fr/datasets/ ou que je la recharge, il y a d'abord une première liste qui se charge et décharge en quelques instants avant de laisser la place à l'écran de chargement puis liste effective.

(j'aurai bien fait un gif mais je ne comprends plus comment quicktime fonctionne 👴)

**Comment by gmougeolle** [comment]
En fait, la page doit fonctionner sans JS en mode dégradé d'où la première "version" que tu vois de la liste, puis le JS prend le relai et charge la vraie liste interactive d'où l'impression de double chargement.
Malheureusement les deux listes n'ayant pas la même structure, on ne peut pas pré-remplir la liste JS depuis le Jinja, donc je vois mal comment éviter ça dans l'immédiat 🤕

**Comment by taniki** [comment]
Y a toujours `<noscript>` mais ça peut vite dégénérer. (pas prio/mvp je pense)

**Comment by gmougeolle** [comment]
Je pense qu'à long terme il faut faire converger l'API qu'utilise le JS et celle qui crée la liste en Jinja, comme ça le JS peut être pré-charger et juste prendre le relais sur les filtres et autres, mais je pense que c'est un poil complexe à cause des filtres par exemple. Effectivement si on peut s'en passer en MVP et prendre le temps de se pencher là-dessus, ça vaut le coup !
