### ISSUE TITLE
Doublons dans l'autocomplétion couverture spatiale

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#29]
Beaucoup trop de choix pour apparemment la même chose :)
À noter la différence de casse entre le premier et les deux autres.

<img width="579" alt="capture d ecran 2017-10-03 a 00 16 32" src="https://user-images.githubusercontent.com/1231232/31101950-38b837d0-a7d0-11e7-87af-6dc2e8fc4216.png">

**Comment by noirbizarre** [comment]
Oui, problème identifié. C'est un effet de bord de la gestion de l'historique.

Il faut prendre une décision: doit on fournir toutes les zones possibles ou uniquement la dernière correspondant à un identifiant ?

Etant donné que lors qu'n ajout de jeu de donnée, en général il porte sur la zone actuelle, je pense que c'est la bonne solution. La possibilité de fournir un geoid complet devrait rester pour contourner lors des exceptions (je suis chercheur et je publie des données historique sur une zone qui 10 ans par exemple).

Globalement, il y a plusieurs choix ergonomique à faire lié à la gestion de l'historique

**Comment by oncletom** [comment]
Le correctif le plus rapide serait d'indiquer la date/version de la couverture, non ?

J'évalue peu le coût de ces actions mais ça peut se combiner avec le tri décroissant par date, ou l'affichage de la dernière date de la zone seulement.

**Comment by taniki** [comment]
Correctif possible en deux temps :+1: 

1. n'afficher que la dernière zone correspondant à un identifiant
2. optionnel en amélioration : introduire un moyen d'accéder à l'historique au cas où. Ex : une flêche collée sur la droite qui remplacerait le contenu du menu déroulant par une liste de l'historique de la zone

**Comment by taniki** [comment]
Je viens de voir que cette PR devrait temporiser ce problème https://github.com/opendatateam/udata/pull/2140

**Comment by abulte** [comment]
Réglé avec nouvelle version de géozones normalement 🤞
