### ISSUE TITLE
Dépliage des ressources communautaires

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#292]
https://staging.data.gouv.fr/fr/datasets/repertoire-national-des-associations/

Quand j'essaie de déplier les métadonnées d'une ressource communautaire, ce sont celles de la première qui se déplient. J'arrive pas très bien à cerner la source problème.

**Comment by gmougeolle** [comment]
Il y a une petite collision d'ID, en fait je pensais que chaque ressource avait un ID unique mais en réalité il semblerait que non. Je vais utiliser des IDs plus costauds sur cette partie

**Comment by abulte** [comment]
Les ressources communautaires ont bien des ids différents (cf liens ci-dessous) — par ailleurs je ne reproduis pas (Safari).

https://staging.data.gouv.fr/fr/datasets/repertoire-national-des-associations/#resource-9c07453b-d119-4d3f-94d0-e46f58d8e7dd
https://staging.data.gouv.fr/fr/datasets/repertoire-national-des-associations/#resource-315eef3f-e3a3-4d7f-8c17-4ae0b2765cbe

**Comment by taniki** [comment]
Je reproduis sur safari. Ca marche bien sur la première moitié des ressources communautaires et ça bugge sur la seconde moitié.

**Comment by abulte** [comment]
@taniki exact 🧐
