### ISSUE TITLE
Bandeau "beta"

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#296]
Faire:
- le wording
- la Créa 
- l'Intégration

**Comment by abulte** [comment]
@agarrone peut-être prévoir un lien vers l'article introductif ?

**Comment by abulte** [comment]
Et legacy.data.gouv.fr le cas échéant

**Comment by restuccia** [comment]
Mettre un lien vers l'ouverture d'une issue sur git ou vers support.data.gouv dans le bandeau peut-être ?
