### ISSUE TITLE
Sur les chiffres, il y a une seule barre verte, les autre sont bleu

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#297]

**Comment by gmougeolle** [comment]
It's art 🎨 
<img width="1067" alt="Capture d’écran 2021-06-30 à 17 59 19" src="https://user-images.githubusercontent.com/9059861/123993712-f57b8200-d9cc-11eb-8b32-94496b1e94cb.png">

Blague à part, je crois que l'idée était de rappeler la couleur du bandeau des réutilisations vs celle des datasets, c'est peut-être pas une si bonne idée

**Comment by maudetes** [comment]
Ahah qu'est-ce qu'on peut répondre à ça? Mais yes pas forcément évident comme couleur en tout cas
