### ISSUE TITLE
Vérifier qu'une organisation n'existe pas : voie sans issue

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#3]
Lorsque j'utilise cet écran, et que je trouve l'organisation que je voulais créer, je ne sais pas quoi faire.
Je ne peux pas cliquer sur l'organisation, aucune action ne m'est proposée.

<img width="857" alt="capture d ecran 2017-09-06 a 15 45 47" src="https://user-images.githubusercontent.com/1231232/30119805-30774542-9327-11e7-9d99-10bfa7988eb0.png">

**Comment by abulte** [comment]
En effet ça peut être un peu perturbant. Le truc c'est qu'il n'y a pas vraiment d'action logique après ça, tu arrêtes ton process et puis... ? Une suggestion quant à quoi faire ? 

Par exemple :
- Un clic sur l'organisation te ramènes quelque part, mais où ? Sur la home de l'admin c'est certainement violent
- Affichage d'une modale "super votre organisation existe déjà, maintenant créez un dataset !". Avec deux boutons : accueil admin et créer dataset.

**Comment by noirbizarre** [comment]
Si c'est un manque, l'action logique quand il y a une orga qui existe c'est d'envoyer une demande d'adhésion. Prb: aujourd'hui les demandes d'adhésion sont encore dans le front :/

**Comment by oncletom** [comment]
J'y verrais 2 steps:

- l'utilisateur n'est pas membre de l'organisation : proposer de la rejoindre (ou que le lien emmenant vers l'org trigger ce qu'il faut pour la rejoindre à ce moment là);
- effectivement aller vers l'admin de l'organisation elle-même si on est déjà membre de celle-ci (sauf si un autre action serait davantage logique).
