### ISSUE TITLE
Divergence autocomplétion et recherche

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#30]
Lorsque je tape `cadastre` dans la barre de recherche, voici ce que je trouve :

<img width="873" alt="capture d ecran 2017-10-03 a 00 19 10" src="https://user-images.githubusercontent.com/1231232/31102012-7fab012c-a7d0-11e7-90a8-23e40f6436e6.png">

Lorsque je laisse l'autocomplétion s'afficher, c'est une autre histoire :

<img width="582" alt="capture d ecran 2017-10-03 a 00 18 30" src="https://user-images.githubusercontent.com/1231232/31101996-72d82330-a7d0-11e7-9568-1f67c63cdbd6.png">

Peut-on améliorer ça ou est-ce intrinsèquement lié au fait que les résultats sont considérés comme similaires ?

**Comment by oncletom** [comment]
@jdesboeufs ça va être amélioré 🙂 je m'y attaque dès que j'en ai fini avec l'interface des projections géographiques.

**Comment by noirbizarre** [comment]
Bon, je **RE**synthétise le prb ici complétion et recherche étant 2 choses différentes, les résultats rémonté ne peuvent pas être identiques:

- l'hypothèse de base de la completion est que l'utilisateur est en train de taper donc que le terme recherché est à la fois incomplet et correspond au début ou un mot complet. La contrainte de temps de réponse est très forte donc les calculs lourds sont exclus (pas de pondération, gaussienne ou autre)
- l'hypothèse de la recherche est que la requête est complète, les mots sont entiers (si on exclue un erreur possible de 1 caractère == recherche "`fuzzy`") et le temps de réponse est secondaire par rapport à la pertinence d'où la possibilité d'utiliser un pondération complexe (composite de plusieurs facteurs)

En gros, renvoyer les mêmes résultats ne donnerait pas non plus les bonnes complétions jusqu'à ce que le mot complet soit tapé et le temps de réponse serait un peu plus important ce qui enlèverait l’intérêt de la complétion.

Par contre, nous avons identifié lors de la dernière workweek que ce qui perturbe l'utilisateur n'est pas tant que les résultats soient différents mais que ceux qui remontent ne sont pas les plus pertinents.
Une solution simple consisterait à simplement faire disparaître le bruit (ie. les jeux de données locaux qui passent au dessus des nationaux) et ne faire remonter que les JDD nationnaux. Pour la majorité des cas, le problème disparaît. Cette possibilité est techniquement réalisable.

Si cette solution ne convient, la seule autre alternative et de supprimer la complétion.

**Comment by jdesboeufs** [comment]
Je comprends la différence d'approche, mais ça n'explique pas que les résultats de l'autocomplétion soient dans ce cas des titres de jeux de données, et pas des mots ou des mots-clés.

Si je tape "cadastr" je m'attends plus à voir en premier quelque chose qui ressemble à "Cadastre" que "Assemblage des feuilles cadastrales...".

À titre personnel, en l'état, je trouve que l'autocomplétion gagnerait à être désactivée.
