### ISSUE TITLE
Impossible de distinguer les discussions ouvertes et fermées

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#31]
Les trois dernières discussions sont en fait fermées.

<img width="853" alt="capture d ecran 2017-10-09 a 19 03 41" src="https://user-images.githubusercontent.com/1231232/31349716-a34889d4-ad24-11e7-96e6-1ad96f327271.png">

**Comment by noirbizarre** [comment]
Ça demande un peu de recherche ergo pour avoir quelque chose de visuel, mais dans un premier temps est-ce que remplacer "Dicussion démarrée le..." par "Discussion fermée le..." permettrai d'améliorer la situation ?

**Comment by jdesboeufs** [comment]
L’info sera là en effet, mais ça risque d’être trop discret.
Un quick-win cela dit.

**Comment by noirbizarre** [comment]
Oui, c'est un peu ça l'idée:
- **1.2.0**: quick win en ne changeant que le texte
- **plus tard mais rapidement**: distinction visuelle
