### ISSUE TITLE
Publish the feedback form on data.gouv.fr

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#313]
https://datagouv.evalandgo.com/s/index.php?id=JTk4ciU5N28lOUElQTk%3D&a=JTk3cCU5M2glOTklQUU%3D

**Comment by alicerou** [comment]
Texte : "Vous avez 2 minutes ? Donnez nous votre avis sur data.gouv.fr ici " Ou "Partagez votre avis sur data.gouv.fr en 2 minutes"
