### ISSUE TITLE
Intégration matomo

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#319]
Peut-être en lien: `error uData is not defined` dans la console

**Comment by abulte** [comment]
https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=185&period=day&date=yesterday&updated=1#?idSite=185&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1

**Comment by abulte** [comment]
https://gitlab.com/etalab/data.gouv.fr/infra.data.gouv.fr/-/commit/5ffb15fe8caf81770bae6f0322f8983ea411353d

**Comment by abulte** [comment]
Deploy done ✅

**Comment by abulte** [comment]
remove the goal part that we don't use anyway and create errors https://github.com/opendatateam/udata-piwik/blob/baf1ea751d49fcfb762cce0d40bdc407affbfff8/udata_piwik/templates/piwik.html#L38
