### ISSUE TITLE
Mettre à jour le calcul des metrics (pour "mieux" trier les jdd, orgas etc.)

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#321]
`https://staging.data.gouv.fr/fr/datasets/` vs `https://staging.data.gouv.fr/fr/datasets/?sort=-created`

Concerne surtout les liens dans le header par ci par là.

**Comment by maudetes** [comment]
## Affinage du ticket
Il s'agit de trier les JDD et reuses par date de création (les plus récentes d'abord):
- quand on arrive sur https://www.data.gouv.fr/fr/datasets/
- quand on arrive sur https://www.data.gouv.fr/fr/reuses/
- sur les pages orgas https://www.data.gouv.fr/fr/organizations/etalab/ au niveau des datasets et des reuses
- sur les pages d'un jeu de données, trier les réutilisations par les plus récentes d'abord

Est-ce que tu avais d'autres cas en tête @taniki ?

Est-ce qu'on pourrait garder un tri par défaut par pertinence si on recalculait les metrics @quaxsze ? Comme ça a été le cas sur staging par exemple (voir https://staging.data.gouv.fr/fr/organizations/, https://staging.data.gouv.fr/fr/organizations/), etc.

**Comment by taniki** [comment]
Il n'y a pas d'autres cas qui me reviennent en tête. J'ai l'impression que par défaut, le tri par date est déjà appliqué à divers autres endroits

**Comment by maudetes** [comment]
Un recalcul des metrics a été effectué. La différence de résultats entre staging et la data.gouv.fr nous amène à créer un ticket pour enquêter sur le calcul de ces métriques: #458.
