### ISSUE TITLE
Possibilité d'indiquer "jamais" comme fréquence de mise à jour

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#328]
Aujourd'hui ce n'est pas possible d'indiquer une fréquence de mise à jour de « jamais », la solution plus proche est d'indiquer une fréquence inconnue ou sans régularité.

Serait-il possible de changer la métadonnée de la fréquence pour inclure cette possibilité ?

**Comment by agarrone** [comment]
On peut ne pas remplir de date : il existe une solution de contournement.
