### ISSUE TITLE
Pluriel/singulier sur les éléments avec un nombre devant

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#329]
<img width="321" alt="Screenshot 2021-07-06 at 15 51 00" src="https://user-images.githubusercontent.com/27315/124612181-6bbb3100-de72-11eb-8d90-9b63b470fa0b.png">

**Comment by maudetes** [comment]
Yep, plurals are not supported yet in JS translations: https://github.com/etalab/data.gouv.fr/projects/4#card-63934591.

**Comment by maudetes** [comment]
Dupliqué de #395
