### ISSUE TITLE
Auto-complétion : impossible d'associer un jeu de donnée

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#33]
J'essaie d'associer un jeu de données à un post.
Pour ce faire je dois le faire remonter via un formulaire avec auto-complétion.
Le jeu de données s'appelle "Cadastre", et il n'apparait jamais dans la liste.

<img width="578" alt="capture d ecran 2017-10-19 a 11 38 30" src="https://user-images.githubusercontent.com/1231232/31764661-22ffce4a-b4c2-11e7-887a-1e6f2755a2ce.png">

**Comment by abulte** [comment]
A retester sur next aujourd'hui suite à https://github.com/opendatateam/udata/pull/1222.

**Comment by abulte** [comment]
Je crois que c'était OK maintenant @jdesboeufs, n'hésite pas à rouvrir si besoin.
