### ISSUE TITLE
El catálogo de datos está en español

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#342]
## Description du bug
Dans la version en français de data.gouv.fr, le lien vers le catalogue des données dans le footer renvoie vers `https://www.data.gouv.fr/es/datasets/catalogue-des-donnees-de-data-gouv-fr/`

**Comment by restuccia** [comment]
Prize for the weirdest bug ever that cannot be reproduced today

**Comment by abulte** [comment]
Probably a template cache key that does account for `g.lang_code`

**Comment by maudetes** [comment]
En lien: https://github.com/etalab/data.gouv.fr/issues/350
