### ISSUE TITLE
Fix erreur en lien avec oauth

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#344]
Voir https://sentry.data.gouv.fr/organizations/sentry/issues/12043/?project=5&query=is%3Aunresolved

**Comment by quaxsze** [comment]
Scopes `ListField` field in `OAuth2Token` was changed to a scope `StringField` in this [PR](https://github.com/opendatateam/udata/pull/2510).

**Comment by quaxsze** [comment]
Cela vient visiblement d'objets `OAuth2Token` non migrés, la migration semble n'avoir affectée que les objets `OAuth2Client`

**Comment by quaxsze** [comment]
Suppression des `OAuth2Token` ayant l'ancien attribut.
