### ISSUE TITLE
Fix erreur en lien avec l'api discussions

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#345]
Voir https://sentry.data.gouv.fr/organizations/sentry/issues/8/?project=5&query=is%3Aunresolved

**Comment by quaxsze** [comment]
Survient lors de la suppression à la main en DB d'un utilisateur. Lors de la sérialisation des discussions la référence vers l'utilisateur sera manquante.
Suppression des discussions initiées par l'utilisateur supprimé à la main.
Il faut faire attention à ne pas supprimer un utilisateur de cette façon mais à travers l'admin, ce qui le flag plutôt que de le supprimer en base.
A voir pour surcharger la fonction `delete()` du document mongoDB afin de mettre un warning ou une confirmation?
