### ISSUE TITLE
Filtres de recherche de jdd vide ( mots clef et formats)

### ISSUE THREAD

**Issue by alicerou** [etalab/data.gouv.fr#347]
mention 'aucun résultat' dans le menu déroulant

**Comment by maudetes** [comment]
Il s'agit plus d'un soucis d'UX, c'est un champ en auto-complete, si tu commences à taper il va te proposer des suggestions.

(Je le laisse en bug car contre-intuitif)

**Comment by alicerou** [comment]
si c'est facilement modifiable, on peut remplacer le texte 'aucun résultat' par 'tapez ve mot/le format recherché'
