### ISSUE TITLE
Nombre de membres erroné

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#35]
Problème peut-être lié à #34.

Le nombre de membres n'est pas cohérent entre le cartouche et l'onglet.

Cartouche :

<img width="308" alt="capture d ecran 2017-11-13 a 11 42 25" src="https://user-images.githubusercontent.com/1231232/32721738-cfc351a2-c867-11e7-91fd-32f8a2aae359.png">

Onglet :

<img width="808" alt="capture d ecran 2017-11-13 a 11 42 20" src="https://user-images.githubusercontent.com/1231232/32721739-d2419fec-c867-11e7-8660-03b897f8993d.png">

**Comment by bboulesteix** [comment]
Le problème semble corrigé [pour Strasbourg](https://www.data.gouv.fr/fr/organizations/strasbourg-eurometropole/). J’ai consulté la page d’autres organisations et je n’ai pas constaté d’écart entre le nombre de membres affiché dans le cartouche et celui affiché au niveau des onglets. Je ferme donc le ticket. Si le problème refait surface, il suffira d’ouvrir le ticket à nouveau.
