### ISSUE TITLE
Vérifier les snippets de google search sur les organisations

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#352]
Exemple sur la recherche `asp data.gouv.fr` : "Bienvenue sur la nouvelle version beta de data.gouv.fr! En savoir plus, retournez à l'ancienne version ou envoyez-nous vos retours."

**Comment by maudetes** [comment]
L'impression que les meta n'ont quasi pas bougé entre legacy et la refonte.

En particulier, `<meta name="description" content="L&#39;Agence de services et de paiement (ASP) est un…" />` n'a pas bougé.

Seul tag qui disparaît: `<meta name="sentry"...>`, qui est peut-être être lié à https://github.com/etalab/data.gouv.fr/issues/358.

**Comment by maudetes** [comment]
Le snippet a évolué et est devenu: "Elle mène des missions pour le compte de plus de 130 donneurs d'ordre : l'Union européenne - elle est le premier payeur européen d'aides".

Mais le bandeau beta apparaît encore sur la recherche `insee data.gouv.fr` qui a pour snippet: "Bienvenue sur la nouvelle version beta de data.gouv.fr! ... L'Institut national de la statistique et des études économiques (Insee) collecte, ..."

A voir si ça évolue là aussi dans le temps.

**Comment by maudetes** [comment]
La requête "open data agriculture" retourne des résultats peu pertinents:
- le troisième est un jdd nul https://www.data.gouv.fr/fr/datasets/agriculture/
- en dessous du résultat data.gouv il y a des liens un peu inutiles ?
- pas de lien vers l'orga du ministère de l'agriculture

**Comment by agarrone** [comment]
Je peux close @maudetes ?
