### ISSUE TITLE
Pas de scroll sur le suggest sur mobile

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#359]
Ce qui rend le suggest inutilisable car on ne peut pas scroller sur les résultats

**Comment by abulte** [comment]
FF only, right @gmougeolle ?

**Comment by gmougeolle** [comment]
Possibly FF only, cannot reproduce on iOS devices nor on Firefox Desktop (macOS). I'll get my hands on an Android device to confirm
