### ISSUE TITLE
Comme saisir le champ Couverture spatiale ?

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#36]
Bonjour,

Pour un utilisateur novice, la saisie du champ couverture spatiale n'est pas aisée.
De ce que j'ai compris, elle s'appuie sur le champ d'aprés Granularité spatiale, une fois choisie cette granularité, l'autocomplétion nous inviterai à saisie un vocabulaire controlée.
Dans mon cas présent, je souhaite saisir la bourgogne-franche-comté (id=27), mais l'autocomplétion ne semble pas fonctionner pour cette granulo (région).
#
On aurait tendance à présenter le champ granulo avant la couverture spatial, qui permettra de mieux comprendre ce qui est attendu en saisie.

D'avance Merci,
![couv_spat](https://user-images.githubusercontent.com/7600693/32957341-b86e46a4-cbbb-11e7-96ff-117957973788.jpg)

**Comment by noirbizarre** [comment]
Bonjour,

Je vous remet la même réponse que sur `udata-gouvfr`, il y avait effectivement un bug que j'ai corrigé vendredi.

Vous devriez trouver votre résultat maintenant.

Votre navigateur a peut-être gardé la réponse précédente en cache, vous pouvez essayer d'allonger la longueur de votre requête pour le forcer à récupérer de nouveaux résultats (Essayez de saisir `bourgogne-fra` ou encore `Bourgogne` avec une majuscule ou bien son code nuts2 `FR26`).

**Comment by jerbou** [comment]
Merci !

**Comment by bboulesteix** [comment]
Comme le problème semble résolu, je ferme le ticket, si ça convient à tout le monde. J’ai noté de mon côté que nous gagnerions à définir ce que signifient les termes **couverture spatiale** et **granularité spatiale**. J’en ai tenu compte dans : https://github.com/etalab/doc.data.gouv.fr/issues/36. 👀
