### ISSUE TITLE
Fixer readthedocs (ex: https://udata.readthedocs.io/en/v3.0.0)

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#361]
La doc d'une version spécifique renvoie une erreur (https://udata.readthedocs.io/en/v3.0.0) mais pas latest (https://udata.readthedocs.io/en/latest).

**Comment by abulte** [comment]
Ajout d'une intégration GitHub 🤞 https://readthedocs.org/dashboard/udata/integrations/163290/

**Comment by maudetes** [comment]
Good news, it seems to work now with new releases: https://udata.readthedocs.io/en/v3.1.0/ :)

**Comment by abulte** [comment]
🎉
