### ISSUE TITLE
Améliorer le layout des tableaux dans les descriptions de JDD en markdown

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#368]
Voir description de https://www.data.gouv.fr/fr/datasets/ma-connexion-internet/

**Comment by agarrone** [comment]
On est pas mal là dessus non @nicolaskempf57 @maudetes ?

**Comment by maudetes** [comment]
C'était lié à la taille des colonnes lors de l'affichage des tableaux en markdown, ex:
![image](https://user-images.githubusercontent.com/28541902/154223649-20d1cf35-6a3a-4a9b-bc2e-243a0a5b4306.png)

**Comment by nicolaskempf57** [comment]
Avec `word-break: keep-all;` pour le tableau, on arrive à un meilleur résultat. Par contre, ça peut entrainer des débordements sur des mots très longs.

<img width="1145" alt="Capture d’écran 2022-02-16 à 09 34 35" src="https://user-images.githubusercontent.com/8336712/154226194-1d065fe8-f981-4192-aeaf-f45ee4288af6.png">

**Comment by nicolaskempf57** [comment]
Problème corrigé : https://github.com/etalab/udata-front/pull/99
