### ISSUE TITLE
 "revendiquer" les territoires?

### ISSUE THREAD

**Issue by mkazmiers** [etalab/data.gouv.fr#37]
Bonjour,

On explore au CRIGE PACA la fonctionnalité "Territoire" de data.gouv (- bravo, d'ailleurs 👍 )
Dans cette section, une petite question sur la fonctionnalité "Revendiquer" ; est-ce que plusieurs organisations peuvent le faire (Région, DREAL, CRIGE)? Ou une seule? Dans le dernier cas, ce sont les Conseils Régionaux qui sont plus légitimes ou les DREAL ou...? Bref, dans quel esprit est-ce que cela a été conçu?

![image](https://user-images.githubusercontent.com/16324693/33026246-4d027334-ce10-11e7-9fb7-25291f3e008a.png)

Merci par avance.
Bien cordialement

**Comment by oncletom** [comment]
@mkazmiers dans les derniers prototypes de cette fonctionnalité, on s'avançait vers _afficher les données qui concernent le territoire_. Il n'y aura pas besoin de "revendiquer" mais "juste" de renseigner la granularité des jeux de données ainsi que la couverture territoriale.

**Comment by mkazmiers** [comment]
merci pour la réponse @oncletom !
Nous sommes à une réflexion similaire sur le futur catalogue regionpaca/crigepaca : cette granularité de jeu de données à renseigner et couverture territoriale, ça se présenterait comment? une liste fermée de territoires/type de territoires à sélectionner?
Ca nous intéresse particulièrement dans la mesure où le portail régional paca aurait vocation à voir ses datasets moissonnés par data.gouv (en DCAT?)+geo.data.gouv (via CSW)

**Comment by mkazmiers** [comment]
bonjour, je me permets une relance @oncletom : quelles codelists/référentiels utilisez-vous (le cas échéant)  pour la granularité des territoires et les couvertures territoriales?
bonne journée,merci

**Comment by abulte** [comment]
Bonjour, nous utilisons GeoZones dont vous trouverez la description et les données ici https://www.data.gouv.fr/fr/datasets/geozones/, ainsi que les liens vers les différents dépôts GitHub.
