### ISSUE TITLE
Trouver une meilleure solution pour les MIME Type rdf

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#374]
Un fix a été fait pour éviter de dumper en json les sorties rdf depuis le passage côté API: https://github.com/opendatateam/udata/pull/2631.

Essayer de trouver une solution plus propre.

**Comment by maudetes** [comment]
Le fix actuel (voir https://github.com/etalab/data.gouv.fr/issues/356) n'est pas entièrement satisfaisant car oblige les utilisateurs à utiliser les bons headers.
De plus, `application/json` ou `application/xml` non fonctionnels (alors que référencés [dans la doc](https://github.com/opendatateam/udata/blob/master/docs/rdf.md#content-negotiation)).

**Comment by abulte** [comment]
Après un rapide coup d'oeil, je dirais que le plus simple serait de bouger le RDF côté udata-gouvfr. Je continue de creuser pour voir si on peut faire mieux (parce que c'est effectivement plus logique côté API).
