### ISSUE TITLE
L'alignement du nombre de favori sur les réutilisations n'est pas centré

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#376]
Created by @agarrone

**Comment by maudetes** [comment]
Je crois que ça a été résolu par https://github.com/etalab/data.gouv.fr/issues/274. @agarrone tu confirmes que c'était bien le même soucis et qu'il a été corrigé depuis ?

**Comment by agarrone** [comment]
Je parlais plutôt de 
![image](https://user-images.githubusercontent.com/60264344/126129999-09404271-9655-4f4d-bd50-e5adc87d77e6.png)

**Comment by maudetes** [comment]
Will probably fixed by #449.
