### ISSUE TITLE
créa oembed orgas

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#377]
Créé par @sabinesafi

**Comment by maudetes** [comment]
@taniki tu confirmes qu'il n'y a pas besoin de créa d'orga, il y en a déjà une qui existe ?

**Comment by taniki** [comment]
à mon avis, il y a besoin d'une créa comme il n'y a rien qui ressemble à une carte facilement adaptable comme pour les reuses et les jdd. pas urgent ou fondamental par contre.

**Comment by agarrone** [comment]
Au regard des usages actuels, le principe d'oembed sera repensé dans une roadmap plus long terme sur la place de data.gouv.fr dans son ecosysteme.
