### ISSUE TITLE
Lien jeux de donées, membres, abonnées inopérants dans le cartouche ?

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#38]
Bonjour,

Les onglets jeux de données, membres, abonnées, dashboard (le vocable tableau de bord ne vous plait pas ;) amènent aux différents listes (listes des jeux de données, membres , abonnées).
Dans le cartouche, les chiffres et les mots sont cliquables, on (l'utilisateur novei) s'attend à un même comportement, un clic amène à afficher l'onglet correspondants.

Est-ce que c'est un bug ou autre chose ?

Cordialement,

**Comment by abulte** [comment]
Bonjour,

Effectivement il faudrait :
- soit lier vers les onglets
- soit supprimer les liens dans le cartouche

Merci pour votre feedback !

**Comment by abulte** [comment]
Je ferme cette anomalie en faveur de https://github.com/etalab/data.gouv.fr/issues/38
