### ISSUE TITLE
Adapter le système de follow au nouveau parti pris graphico-fonctionnel

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#382]
Créé par @abulte
A date, 2 types de fonctionnalités attendues
- PRIO pouvoir retrouver facilement des jdd/réutilisations ( le texte 'favoris' pourrait renvoyer vers une page personnelle de favoris, comme dans le 'profil public' de legacy) OU avoir un bouton "mes datasets/ mes favoris"
- être informé des mises à jour (tous les utilisateurs ne recherchent pas le même niveau d'information/ ça pourrait être une option à activer/personnaliser)
cf tests Quentin N., Esri France, Lery J. , Matthieu S., acordyn+ mail support de Bastien et Laure "
![image](https://user-images.githubusercontent.com/82669567/127822430-b583a237-3090-4cbd-a96c-753cfbdd3de3.png)

**Comment by alicerou** [comment]
A date, 2 types de fonctionnalités attendues
* pouvoir retrouver facilement des jdd/réutilisations ( le texte 'favoris' pourraoit renvoyer vers une page personnelle de favoris)
* être informé des mises à jour (tous les utilisateurs ne recherchent pas le même niveau d'information/ ça pourrait être une option à activer/personnaliser)

**Comment by agarrone** [comment]
Sera traité dans un EPIC dedié
