### ISSUE TITLE
Cannot reset schema research filter

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#388]
## Description du bug
Le filtre par schéma ne peut pas être réinitialisé à partir de la vue recherche

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller dans la page d'un schéma sur schema.data.gouv, e.g. [le schéma des hautes rémunérations](https://schema.data.gouv.fr/etalab/schema-hautes-remunerations/latest.html) ;
2. Cliquer sur le lien qui permet de rechercher les jdd sur data.gouv qui respectent le schéma https://www.data.gouv.fr/fr/datasets/?schema=etalab/schema-hautes-remunerations ;
3. La page des résultats montre les jdd respectant le schéma ;
4. Il n'y a pas de moyen pour réinitialiser le filtre schéma, la seule manière de le faire c'est de rechercher un terme qui n'apparaît pas -> le bouton pour réinitialiser les filtres va apparaître
![Capture d’écran 2021-07-15 à 10 09 40](https://user-images.githubusercontent.com/51122275/125753644-d963ae11-af1c-4cd8-8c31-d9ccf7edba2c.jpg)

## Comportement attendu
Les autres filtres peuvent être réinitialisés facilement de façon graphique

![Capture d’écran 2021-07-15 à 10 17 05](https://user-images.githubusercontent.com/51122275/125753929-dde07d82-c039-413d-bcc2-e059a47e2007.jpg)

**Comment by agarrone** [comment]
Je close car existe ailleurs [Ajouter un filtre schéma à la recherche](https://github.com/etalab/data.gouv.fr/issues/610)
