### ISSUE TITLE
Renommage de udata-gouvfr en udata-front

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#393]

**Comment by maudetes** [comment]
Complexité maximale à y passer : 4 (équivaut 2j)

**Comment by quaxsze** [comment]
Conformement à https://www.python.org/dev/peps/pep-0423/#how-to-rename-a-project

- [ ] faire une branche legacy
- [ ] metadata [Obsoletes-Dist](https://www.python.org/dev/peps/pep-0345/#obsoletes-dist-multiple-use) sur la PR
- [ ] merger la PR sur master
- [ ] ajouter `Development Status :: 7 - Inactive` dans le script de setup
