### ISSUE TITLE
Problème avec blason

### ISSUE THREAD

**Issue by noirbizarre** [etalab/data.gouv.fr#4]
_From @Cyrille37 on September 22, 2016 6:11_

Bonjour,
pour la commune [37158 Montreuil-en-Touraine](https://www.data.gouv.fr/fr/town/37158/) le blason n'apparait pas alors qu'il est bien sur [wikipedia](https://fr.wikipedia.org/wiki/Montreuil-en-Touraine).
La seule différence que je vois avec les autres blasons qui fonctionnent sur data.gouv.fr est qu'il est sous licence CC0 ...
Cheers.

_Copied from original issue: etalab/etalab-support#22_

**Comment by Cyrille37** [comment]
Nous allons bientôt pouvoir fêter les 1 an de ce ticket ;-)
Courage :-)

**Comment by oncletom** [comment]
@noirbizarre le lien Wikipédia est vide — serait-ce lié ?

**Comment by Cyrille37** [comment]
@oncletom Pour ma part, je ne crois pas avoir accès à cette donnée pour la compléter (même connecté sur data.gouv.fr).

**Comment by abulte** [comment]
A noter sur cette même page : erreur JS suivante suite au parsing de https://next.data.gouv.fr/api/1/spatial/zones/fr:commune:37158%401961-06-22 -> `{"features": [{"geometry": {"coordinates": null, "type": null}, "id": "fr:commune:37158@1961-06-22", "properties": {"area": null, "code": "37158", "keys": {"insee": "37158"}, "level": "fr:commune", "logo": "", "name": "Montreuil-en-Touraine", "parents": ["country:fr", "country-group:ue", "country-group:world", "fr:departement:37@1860-07-01", "country-subset:fr:metro", "fr:epci:200043065@2014-01-01", "fr:epci:200043065@2015-01-01", "fr:epci:200043065@2016-01-01", "fr:epci:200043065@2017-01-01", "fr:epci:243700713@1999-01-01", "fr:epci:243700713@2000-01-01", "fr:epci:243700713@2001-01-01", "fr:epci:243700713@2002-01-01", "fr:epci:243700713@2003-01-01", "fr:epci:243700713@2004-01-01", "fr:epci:243700713@2005-01-01", "fr:epci:243700713@2006-01-01", "fr:epci:243700713@2007-01-01", "fr:epci:243700713@2008-01-01", "fr:epci:243700713@2009-01-01", "fr:epci:243700713@2010-01-01", "fr:epci:243700713@2011-01-01", "fr:epci:243700713@2012-01-01", "fr:epci:243700713@2013-01-01"], "population": 817, "slug": "Montreuil-en-Touraine", "validity": {"end": "9999-12-31", "start": "1961-06-22"}}, "type": "Feature"}], "type": "FeatureCollection"}`

```
Uncaught (in promise) Error: Invalid GeoJSON object.
    at Function.geometryToLayer (leaflet-src.js?6144**:6203)
    at e.addData (leaflet-src.js?6144**:6112)
    at e.addData (leaflet-src.js?6144**:6102)
    at e.initialize (leaflet-src.js?6144**:6089)
    at new e (leaflet-src.js?6144**:229)
    at Object.l.geoJson (leaflet-src.js?6144**:6361)
    at LeafletMap.geojson (territory.js:9277)
    at Watcher.run (common.js:7)
    at runBatcherQueue (common.js:6)
    at Array.flushBatcherQueue (common.js:6)
    at nextTickHandler (common.js:7)
    at <anonymous>
```

**Comment by taniki** [comment]
À vérifier après merge de https://github.com/opendatateam/udata/pull/2140
