### ISSUE TITLE
Suggérer un mot clef

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#401]
Créé par @abulte

**Comment by agarrone** [comment]
Késaco @maudetes ?

**Comment by abulte** [comment]
👻 

Dans l'ancienne version on pouvait cliquer sur "suggérer un mot clé" et ça démarrait une conversation via un template pour demander au producteur de rajouter le dit mot clé.

Je pense que ça vient d'une liste de "trucs qu'on a pas réimplémenté pendant la refonte". Je vous laisse voir si c'est encore utile :)

**Comment by agarrone** [comment]
Thanks. 
Je clos pour pour l'instant :)
