### ISSUE TITLE
Maintenance sur les capacités de moissonage descendants (data.gouv => plateforme territoriale)

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#403]
## Description du bug
Bonjour,

Comme évoqué dans un ticket fermé, https://github.com/etalab/data.gouv.fr/issues/189
la fonctionnalité de permettre un moissonnage descendant a été accomplie 👍 
avec des urls du style 
https://www.data.gouv.fr/organizations/grand-besancon-metropole/catalog.xml

Qu’est-ce qui cloche ? 
Ces urls particulières renvoie des 404 avec la refonte graphiques..
On pourra s'en sortir avec des urls legacy :
https://legacy.data.gouv.fr/organizations/grand-besancon-metropole/catalog.xml
Mais ces url legacy ne seront pt pas maintenues à terme, je pense.

Décrivez le bug en quelques phrases. Si possible, ajoutez des captures ou des enregistrements de votre écran pour nous aider à visualiser le problème. Si un message d’erreur est apparu sur votre écran, ajoutez-le ici.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à `…`
2. Cliquer sur `…`
3. Naviguer jusqu’à `…`
4. Constater le bug

## Comportement attendu
Des urls sans le sous domaine legacy ;)
Avez vous une visibilité pour remettre cette feature ? (dans un ou qq mois...), le but du jeu pour les plateformes territoriales est de se preparer pour le moissonnage : 
tester les urls avec legacy... voir si les moissonnages sont ok.
Etalab @abulte  communique sur une date de bascule sur des urls pérennes de type 
https://www.data.gouv.fr/organizations/grand-besancon-metropole/catalog.xml
les plateformes font la bascule pour maintenir le moissonnage.

Décrivez-nous ce à quoi vous vous attendiez. Exemple : « Je pensais que mon action allait déboucher sur… or à cause du bug je constate que… »
Si pas clair, on peut se programmer un bref point téléphonique, à programmer avec ces courriels.

**Comment by maudetes** [comment]
Bonjour,

Merci beaucoup de votre retour. Suite à la refonte, de nombreuses modifications ont été effectuées, et notamment la route pour le moissonnage (#356). Une redirection va être mise en place prochainement.

En attendant vous pouvez soit utiliser les urls legacy, soit changer la route en utilisant celle de l'api: https://www.data.gouv.fr/api/1/organizations/ministere-de-l-interieur/catalog.xml. Dans ce cas, il faut pour l'instant rajouter un header pour le MIME type d'intéret (voir: https://github.com/opendatateam/udata/blob/master/docs/rdf.md#content-negotiation).

**Comment by jerbou** [comment]
Bonjour,

Merci de votre retour rapide.
j'ai testé avec legacy et cela fonctionne de notre côté 👍
https://trouver.ternum-bfc.fr/organization/communaute-dagglomeration-de-nevers (l'ensemble de fiches moissonnées).

Je regarderai pour creuser l'API et le header.
On attends de vos nouvelles pour la route du moisonnage :)

Merci et à bientôt,

**Comment by agarrone** [comment]
Fixed : #356 #374
