### ISSUE TITLE
Assainir les champs de texte en entrée pour éviter les injections

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#409]
Voir https://github.com/etalab/data.gouv.fr/issues/402 où l'un des champs comporte des accolades: `{{default.description}}`, qui fait sauter le JS.

**Comment by maudetes** [comment]
Voir la page https://www.notion.so/Vue-XSS-injections-611567f3db7a49468e14db4530ea440b.

A discuter avec @gmougeolle :)

**Comment by abulte** [comment]
Petite préférence pour ma part sur la solution "composants indépendants", avec peut-être en fail-safe la désactivation des delimiters.

**Comment by maudetes** [comment]
Je passe ce ticket en Done.
Voir la page https://www.notion.so/Vue-XSS-injections-611567f3db7a49468e14db4530ea440b et les tickets https://github.com/etalab/data.gouv.fr/issues/495 et https://github.com/etalab/data.gouv.fr/issues/496 pour la suite.
