### ISSUE TITLE
Soucis de chargement de https://www.data.gouv.fr/fr/datasets/datatourisme-la-base-nationale-des-donnees-du-tourisme-en-open-data/ ?

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#410]
La page prend longtemps à charger et charge mes CPU à 100%.

Les 2097 ressources y sont peut-être pour quelque chose.

**Comment by abulte** [comment]
@geoffreyaldebert 😬 

👋

**Comment by geoffreyaldebert** [comment]
Purge done. Files save here : https://files.data.gouv.fr/datatourisme/
I sent an email to Datatourisme to avoid this recurrent problem in the future
