### ISSUE TITLE
Le fitre "Jeux de données de référence" sur la homepage ne fonctionne pas

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#411]
![donneesdereference](https://user-images.githubusercontent.com/3227753/126448346-b9c80b73-3a0c-49b4-b9db-f7e9122bd337.png)

## Description du bug

Sur la homepage, il y a un filtre "Données de référence" mais quand on clique dessus, aucune donnée n'apparaît.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à `https://www.data.gouv.fr/fr/`, descendre à la section "Données"
2. Cliquer sur `Jeux de données de référence`
3. Constater le bug : rien ne s'affiche

## Comportement attendu
Je pensais voir les 9 jeux de données de référence.

**Comment by maudetes** [comment]
Merci du retour. Je ferme ce ticket car c'est un duplicate de #333.
