### ISSUE TITLE
Ajouter un lien vers la liste des issues dans le footer du site

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#412]
## L’amélioration que vous avez en tête
Depuis l'interface de data.gouv.fr, on trouve des liens vers https://pypi.org/project/udata/3.0.2/ et https://github.com/etalab/udata-gouvfr/, le code source de l'application mais on ne trouve pas de lien vers le dépôt qui fait office de gestion des bugs et améliorations : https://github.com/etalab/data.gouv.fr/issues.

Est-ce qu'il ne serait pas pertinent d'ajouter un lien vers https://github.com/etalab/data.gouv.fr/issues en dessous des liens vers le code source ?
 
## Les alternatives possibles
Si possible, décrivez d’autres façons de parvenir au résultat que vous espérez atteindre.

**Comment by maudetes** [comment]
Et en profiter pour modifier le lien github du footer vers https://github.com/etalab/data.gouv.fr plutôt que https://github.com/etalab/.
