### ISSUE TITLE
Permettre la recherche d'une organisation

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#413]
## L’amélioration que vous avez en tête

Dans l'ancienne version, on pouvait rechercher une organisation depuis le moteur de recherche. Dans la nouvelle version, on peut rechercher un jeu de données ou une réutilisation mais on ne peut pas directement rechercher une organisation. Même si ça n'est pas un usage majoritaire ça peut être une fonctionnalité utile pour les utilisateurs avertis.

On peut actuellement le faire directement depuis l'url https://www.data.gouv.fr/fr/organizations/?q=Etalab mais quand on tape Etalab dans la barre de recherche on n'a pas le même résultat que quand on tape "Etalab" dans la barre de recherche.

Je suggère d'ajouter une vignette dans le résultat de la recherche pour rechercher dans les organisations.

## Les alternatives possibles
Si possible, décrivez d’autres façons de parvenir au résultat que vous espérez atteindre.

**Comment by pachevalier** [comment]
Ah, j'avais pas vu qu'il y a une barre de recherche spécifique organisation directement depuis : https://www.data.gouv.fr/fr/organizations/. Du coup ça fait le job.

**Comment by maudetes** [comment]
Yes, ça a été rajouté avec #354 :)

**Comment by samgoeta** [comment]
Ah je la cherchais ! @pachevalier ça le fait le job mais encore faut-il y penser, ce serait bien d'indiquer la possibilité de chercher par organisation dans la recherche des jeux de données.

**Comment by maudetes** [comment]
Il est possible de rechercher des dataset par organisation en utilisant les filtres de recherche :
![image](https://user-images.githubusercontent.com/28541902/134380991-ca73ebd0-8922-4885-a96a-ed48fa4e4081.png)

**Comment by samgoeta** [comment]
C'est bon de le savoir. Je n'y avais pas pensé, je pense que d'autres usagers ont eu le même comportement.

**Comment by maudetes** [comment]
Oui, merci pour votre retour. Pour information, la recherche est un des gros sujets des semaines et moi à venir.
