### ISSUE TITLE
Découvrir l'univers data.gouv.fr

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#414]
## L’amélioration que vous avez en tête

cada.data.gouv.fr,, annuaire-entreprises.data.gouv.fr, transport.data.gouv.fr, adresse.data.gouv.fr, cadastre.data.gouv.fr, geo.data.gouv.fr/fr/, ouverture.data.gouv.fr : l'univers data.gouv.fr est complexe et pas toujours facile à découvrir.

On pourrait créer une page sur découvrir l'univers data.gouv.fr : https://github.com/etalab/datagouvfr-pages

## Les alternatives possibles

Ajouter les liens vers les différents site de l'univers data.gouv.fr dans le footer.

**Comment by taniki** [comment]
Pour info, la maquette de page ici : https://www.notion.so/Vitrine-catalogue-de-produits-data-8eb235534b2f42bab346d56e4a978766 (accès restreint)
