### ISSUE TITLE
Modification de wording home page

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#415]
Modifications marginales de wording sur la home suite aux test utilisateurs : 

- Connexion : "Se connecter / S'inscrire" - "Log in / Sign up"
- Barre de recherche :  "Recherche" : "Rechercher des données" / " Search for data"
- Thématiques mises en avant / "featured topics"
### Données 
- Se débarrasser des "jeux" pour laisser juste "données" / "data" à la place de datasets
- "Jeux de la données à la une" : "Données mises en avant" / "featured data"
### Réutilisations
- Titre : "Réutilisations" : "Réutilisations de données" / "Reuses"
- "Sélection Etalab" : Réutilisations mises en avant / "Featured reuses"

**Comment by maudetes** [comment]
@agarrone, comme ça (en Anglais pour commencer) ?
![image](https://user-images.githubusercontent.com/28541902/129030075-cd8be376-65a6-4c2e-96c8-8415ef18b3f6.png)


J'ai pas modifié "datasets" dans la partie indicateurs (`data.gouv.fr is ... Datasets`) ni dans le bloc Participate, je modifie pour data ? A terme, on privilégierait `data` plutôt que `datasets` sur l'ensemble du site ?
`Reuses` serait traduit par `Réutilisation de données` en Français, est-ce qu'il ne faudrait pas utiliser `Data reuses` en anglais ?

**Comment by maudetes** [comment]
Après discussion, on garde `datasets` partout (sauf pour les données en général, à l'image de ce qui est fait sur les portails anglophones, ex: https://opendata.cityofnewyork.us/data/).
On garde `data reuses`, qui a l'air d'être utilisé: https://www.google.com/search?q=%22data+reuse%22&hl=fr.
