### ISSUE TITLE
Changer les views pour un affichage paginé des ressources

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#418]
Les pages avec trop de ressources sont trop lourdes à charger

Voir https://github.com/etalab/data.gouv.fr/issues/410 par exemple.

Même avec 208 ressources, la page me semble encore assez lourde. Sur legacy, la page semblait bien plus rapide à charger.

**Comment by abulte** [comment]
AMAH défaut de design de l'API : il faudrait pouvoir paginer les ressources plutôt que récupérer l'ensemble du dataset et ses ressources systématiquement.

**Comment by maudetes** [comment]
En complément ou en alternative à la solution de pagination des ressources :
Après enquête, il semblerait que le JS soit principalement responsable du long temps de chargement. En effet, lorsqu'on désactive le JS, elle se charge relativement rapidement.
Si au lieu de monter Vue sur l'entièreté de la page, on monte les composants précis (voir https://github.com/maudetes/udata-gouvfr/tree/xss-alt-4), cela semble accélérer considérablement le chargement de la page.

**Comment by maudetes** [comment]
Need to adapt the view to use the pagination introduced in https://github.com/etalab/data.gouv.fr/issues/485.
