### ISSUE TITLE
Type curseur souris lors de la sélection d'un texte sur un JDD

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/data.gouv.fr#419]
PAS PRIORITAIRE

## Description du bug

Lorsque l'on veut sélectionner (par exemple pour un copier/coller) un texte sur la description, le curseur n'apparait pas correctement (on reste sur une flêche au lieu d'un curseur de sélection)

## Comment reproduire le bug

1. Aller sur un dataset (par exemple : https://www.data.gouv.fr/fr/datasets/demandes-de-valeurs-foncieres-geolocalisees/)
2. Sélectionner un texte dans la description

## Comportement attendu

Changement de curseur

**Comment by agarrone** [comment]
C'est peut-être qu'on peut fix très facilement @nicolaskempf57 ?

**Comment by nicolaskempf57** [comment]
Oui ! On peut le complètement le prendre au prochain sprint.
