### ISSUE TITLE
Impossible d'éditer un article

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#42]
Quand j'essaie d'éditer un article déjà créé dans la partie éditorialisation et que je clique sur le bouton `éditer` en haut à droite,  ça ne produit aucune action

![capture d ecran 2017-12-08 a 14 15 09](https://user-images.githubusercontent.com/3227753/33767521-3a953b4e-dc22-11e7-80bd-4328225b4c25.png)

Ci-dessous les messages d'erreur dans ma console Javascript 

![capture d ecran 2017-12-08 a 14 16 25](https://user-images.githubusercontent.com/3227753/33767574-6961e418-dc22-11e7-9bb0-39fb516d1c54.png)

**Comment by taniki** [comment]
@pachevalier merci pour le report. C'est corrigé mais pas encore déployé.

**Comment by noirbizarre** [comment]
Corrigé et maintenant déployé :confetti_ball:
