### ISSUE TITLE
Nombre de réutilisations du figaro différent du total

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#420]
Voir sur https://www.data.gouv.fr/fr/organizations/le-figaro/.

Sur legacy, il y a aussi 4 réutilisations seulement alors que 6 sur l'admin.
L'api retourne 4 réutilisations aussi https://www.data.gouv.fr/api/1/reuses/?organization=59f0335ac751df2a1a48b301.

![image](https://user-images.githubusercontent.com/28541902/126768182-ef401f15-afdf-4df4-83fa-82f09c1598ef.png)

**Comment by taniki** [comment]
https://www.data.gouv.fr/api/1/organizations/59f0335ac751df2a1a48b301/reuses/ y a ce point d'api aussi (certainement utilisé par l'admin)

**Comment by maudetes** [comment]
Les deux autres réutilisations n'apparaissent pas car ne sont pas visibles (publics mais sans JDD associé). Ils apparaissent sur legacy, dans l'onglet `2 réutilisations privées`. Sera fixé par https://github.com/etalab/data.gouv.fr/issues/421.

**Comment by taniki** [comment]
hum c'est le même scope de problème mais maintenant qu'on en parle, je viens de me souvenir que la rêgle, c'est plutôt si une réutilisation n'est pas associé à au moins un jeu de données, alors elle n'est pas indexé dans la recherche (pour éviter le spam) mais est bien public (et non pas privé). Ça peut être pratique pour le référencement des réutilisations qui sont intéressantes mais dont la donnée n'est pas (encore) disponible sur notre site.

**Comment by taniki** [comment]
https://github.com/opendatateam/udata/blob/86173677392abedc532aabf1b78e842496c81f2e/udata/core/reuse/search.py#L117-L121

**Comment by taniki** [comment]
Je pense que `is_indexable` c'est bien de savoir que ça existe pour débugger des cas d'indexation. Par exemple, je viens de voir que les jeux de données sans ressource ne sont pas indexés.

**Comment by maudetes** [comment]
Yes, en effet pour l'indexation, merci pour l'info !
