### ISSUE TITLE
Enquêter sur les users supprimés dans les discussions

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#423]
Voir https://github.com/etalab/data.gouv.fr/issues/345.

Des utilisateurs référencés dans des discussions n'existent pas dans la DB.

L'erreur sentry (https://sentry.data.gouv.fr/organizations/sentry/issues/8/?project=5) a l'air d'être récurrente, car corrigé suite à l'issue précédente, mais reproduite par la suite (alors qu'aucune suppression d'user manuelle n'a eu lieu).

**Comment by abulte** [comment]
@agarrone le problème des discussions ? maybe 💡

**Comment by abulte** [comment]
Maybe related to #474

**Comment by agarrone** [comment]
Oui exactement, excuse du manque de contexte, je voulais savoir s'il fallait créer un ticket, merci :)

**Comment by maudetes** [comment]
Fixed by https://github.com/opendatateam/udata/pull/2644.
