### ISSUE TITLE
Quand je saisis qqe chose dans la search bar, le bouton Entrée ne marche pas (on reste avec une "preview" des résultats)

### ISSUE THREAD

**Issue by sabinesafi** [etalab/data.gouv.fr#430]
L'utilisateur s'attend à avoir accès à l'intégralité des résultats quand il fait "Entrée", hors rien ne se passe. Il faut chercher pour trouver tous les résultats

Comportement attendu : en cours de saisie du texte, des premiers résultats de recherche s'affichent ("preview"). Quand j'appuie sur entrée, ça m'envoie sur une page avec tous les résultats.

cf test Léry j.

**Comment by maudetes** [comment]
duplicate de https://github.com/etalab/data.gouv.fr/issues/371. J'y ai remis cette description.
