### ISSUE TITLE
Pour les jdd avec beaucoup de ressources, il est difficile de trouver celle recherchée

### ISSUE THREAD

**Issue by alicerou** [etalab/data.gouv.fr#435]
quand il ya 10 ressources ou plus, il est difficile pour l'utilisateur de trouver celle qu'il recherche.
Pistes de résolution : tri des ressources, catégorisation, recherche parmi les ressources, moins d'espacement entre les resssources

cf test Esri france, entretien Brice LB et Matthieu L., Thomas P. , Matthieu S.

**Comment by maudetes** [comment]
En lien avec #485.
