### ISSUE TITLE
Page 'utilisateur' à cleaner / arbitrer ce qui est affiché

### ISSUE THREAD

**Issue by alicerou** [etalab/data.gouv.fr#439]
Lorsque l'on clique sur le nom d'un utilisateur ( hyperlink bleu en haut du jdd/ reuse, on atterrit sur une page peu lisible.
C'est là où l'on pouvait avant voir le 'fil d'activité'
Comportement attendu : arriver sur une page lisible et claire. Il faudra décider les informations qui seront visibles ou pas.

![image](https://user-images.githubusercontent.com/82669567/127503431-8b189b84-e813-4421-946b-fa7328be3105.png)
![image](https://user-images.githubusercontent.com/82669567/127503479-000147c0-cdf3-4e61-9999-d1942dfeaee0.png)

**Comment by maudetes** [comment]
Oups, on ne devrait plus pouvoir tomber dessus, voir la discussion #238.

En attendant, il faut enlever le lien vers ce user sur la page réutilisation (il me semble que c'est déjà désactivé sur les JDD). J'ai rajouté ce ticket: #440.

**Comment by agarrone** [comment]
En attendant la refonte des pages users les liens ont été enlevés.
