### ISSUE TITLE
Information sur l'user data

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#44]
Bonjour,

Un de nos partenaire nous ai fait remarquer que l'utilisateur data-bot
https://www.data.gouv.fr/fr/users/data-bot/
est considéré comme admin sur l'organisation (CD71) et de nombreuses organisation
https://www.data.gouv.fr/fr/admin/organization/534fff68a3a7292c64a77d8d/

Vu l'activité, est-ce que c'est un "ancien" robot ou quelque chose comme cela ?

D'avance Merci,

**Comment by jdesboeufs** [comment]
Oui c’est ancien bot qui n’est plus utilisé.
Il faut qu’on fasse le ménage mais vous pouvez le retirer sans problème.
