### ISSUE TITLE
Enlever lien restant vers un utilisateur sur les pages de réutilisation

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#440]
Voir https://github.com/etalab/data.gouv.fr/issues/439

**Comment by maudetes** [comment]
Les profils sont aussi accessibles depuis l'admin (à partir des membres d'une organisation par exemple).

**Comment by nicolaskempf57** [comment]
Close by https://github.com/etalab/udata-front/pull/31
