### ISSUE TITLE
Problème du filtre "couverture spatiale" France

### ISSUE THREAD

**Issue by alicerou** [etalab/data.gouv.fr#442]
![image](https://user-images.githubusercontent.com/82669567/127662135-99a46ed7-bb0d-4873-bd56-5aa5acb05ae6.png)
exemple de résultats obtenus avec le filtre France + granularité communes = 
![image](https://user-images.githubusercontent.com/82669567/127662504-369a178a-5e75-4314-980d-cfd192f4d2f6.png)

**Comment by maudetes** [comment]
Il me semble que la question ne relève pas d'un bug, mais plutôt d'un soucis UX de la recherche par granularité et couverture spatiale, voir aussi #452.
