### ISSUE TITLE
Pouvoir trouver et extraire/ "découper" des jdd à l'échelle régionale (même s'ils ont une couverture nationale)

### ISSUE THREAD

**Issue by alicerou** [etalab/data.gouv.fr#443]
## L’amélioration que vous avez en tête
Beaucoup d'utilisateurs cherchent des données au niveau local, et trouvent trop volumineux les fichiers nationaux.
L'exemple utilisé par les utilisateurs est celui d'opendatasoft , où il est possible d'extraire les fichiers à l'échelle régionale, même si ce sont des jdd nationaux.

## Les alternatives possibles
En lien avec le problème de distinction national/local

cf entretien Boris M. et tickets supports (Ticket# 6029167 et Ticket# 6031310 et Ticket# 6029366 )

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
