### ISSUE TITLE
Faire une fenêtre de preview plus grande

### ISSUE THREAD

**Issue by alicerou** [etalab/data.gouv.fr#444]
## L’amélioration que vous avez en tête
La fenêtre de preview est un petit popup, peu pratique pour bien voir le contenu d'un fichier avec beaucoup de colonnes.
cette fonctionnalité est essentielle pour savoir ce que contient le jdd avant le téléchargement 
Il faudrait que ce soit une fenêtre plus grande, qui prenne tout l'écran

## Les alternatives possibles
avoir une fenêtre dédiée, cf portail opendatasoft

Voir test matthieu S. et Boris M.

**Comment by agarrone** [comment]
Will be taken care off by #729
