### ISSUE TITLE
Proposer 2 parcours différenciés : experts de la donnée Vs citoyens non experts

### ISSUE THREAD

**Issue by alicerou** [etalab/data.gouv.fr#446]
## L’amélioration que vous avez en tête
Mettre en avant la partie réutilisation pour les citoyens, l'interface complète pour les experts de la donnée, pour limiter les citoyens "perdus" dans des fichiers csv etc.

cf tests Matthieu S. et ?Boris M.?

**Comment by agarrone** [comment]
Je close ce ticket car il fait partie d'une réflexion UX plus large sur les parcours
