### ISSUE TITLE
Dev : Changer la forme des cartes des réutilisations

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#449]
Plusieurs utilisateurs font remonter une frustration : pas possible de mettre une joli image d'illustration
- et les anciennes images ne sont pas au bon format
idée de fix : mettre un cadre blanc ou noir automatique pour s'adapter au format de l'image
cf test Acordyn et messages support

**Comment by nicolaskempf57** [comment]
Retours de review :
- remettre la bordure
- mettre les images en `cover`

**Comment by nicolaskempf57** [comment]
Implémenté https://github.com/etalab/udata-front/pull/110
