### ISSUE TITLE
Page proposer une amélioration, lien inopérant

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#45]
Bonjour,

La page suivante est en 404
https://github.com/etalab/udata-gouvfr/edit/master/udata_gouvfr/templates/faq/producer.html
à partir de https://www.data.gouv.fr/fr/faq/producer/
Cela empêche légèrement aux producteurs de faire des suggestions :)

D'avance Merci,

**Comment by jerbou** [comment]
Pour les réutilisateur aussi :)
https://github.com/etalab/udata-gouvfr/edit/master/udata_gouvfr/templates/faq/reuser.html

**Comment by noirbizarre** [comment]
Bonjour,

Nous sommes en ce moment même en train de déplacer le contenu de la FAQ pour faciliter son édition.
Vous pouvez proposer des modifications directement sur le nouveau dépôt de documentation https://github.com/etalab/doc.data.gouv.fr/

Ce changement devrait être mis en production sous peu.

**Comment by noirbizarre** [comment]
(Re)Bonjour

Vous l'aurez peut-être constaté, mais la nouvelle documentation est maintenant en ligne. :tada:
