### ISSUE TITLE
Ajouter le champ "code source" aux réutilisations

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#453]
## L’amélioration que vous avez en tête
J'aimerais avoir la possibilité de référencer le code source d'une réutilisation. Ajouter un champ `Code source` aux métadonnées des réutilisations pourrait permettre d'ajouter un bouton à la page d'une réutilisation pour renvoyer par exemple au repo git.

## Mockup de la page réutilisation :

![Screenshot 2021-08-06 at 13-37-45 Tableau de bord de suivi de l'épidémie de coronavirus en France - data gouv fr](https://user-images.githubusercontent.com/51122275/128505264-d4599128-3dc4-47fd-89bd-e7485d5dbb4b.png)

## Mockup de l'admin :

![Capture d’écran 2021-08-06 à 13 42 08](https://user-images.githubusercontent.com/51122275/128505453-e8513c28-1ecc-48ab-91b1-8aac6868b844.jpg)

**Comment by maudetes** [comment]
Est-ce qu'il s'agit d'une demande de feature récurrente par les réutilisateurs ?

**Comment by restuccia** [comment]
Je ne crois pas, c'est une demande plutôt à titre personnel ici, mais ça a du sens dans un contexte d'ouverture de données + publication des réutilisations + ouverture des codes sources des administrations

**Comment by maudetes** [comment]
Dac, je change le label par celui de la thématique Communauté et Réutilisation :)

**Comment by agarrone** [comment]
Pas prévu pour l'instant
