### ISSUE TITLE
Améliorer l'organisation des pages inventaire et proposer des breadcrumbs

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#454]
Aujourd'hui les pages inventaires sont référencées dans la page [`/pages/donnees-cles-par-sujet/`](https://www.data.gouv.fr/fr/pages/donnees-cles-par-sujet/), mais leurs URLs suivent la même structure, i.e. [`/pages/donnees-coronavirus/`](https://www.data.gouv.fr/fr/pages/donnees-coronavirus/) : les pages inventaires ne sont pas organisées comme des sous-pages de la page `donnees-cles-par-sujet`.

Je propose de changer la structure des pages inventaires de la façon suivante :
- Une page e.g. `/thematiques/` où il y a la liste des thématiques à la une (i.e. le contenu de la page actuelle [`/pages/donnees-cles-par-sujet/`](https://www.data.gouv.fr/fr/pages/donnees-cles-par-sujet/))
- Une sous-page pour chaque thématique, e.g. :
  -  `/thematiques/covid-19`
  - `/thematiques/elections`
  - etc.

Cela nous permettra aussi d'ajouter des _breadcrumbs_ en haut de page, comme c'est déjà le cas pour [la page d'un jeu de données](https://www.data.gouv.fr/fr/datasets/cuisses-de-grenouille-et-escargots-frogs-legs-and-snails/).

**Mockup :**

![Capture d’écran 2021-08-06 à 16 20 02](https://user-images.githubusercontent.com/51122275/128524444-2295745a-8a8a-44c5-8a1c-d0706785e004.jpg)

**Comment by restuccia** [comment]
En lien avec #455

**Comment by agarrone** [comment]
Il me semble que c'était relou à faire @nicolaskempf57 ?

**Comment by nicolaskempf57** [comment]
La problématique, c'est qu'actuellement l'information n'existe pas vraiment.

Il est possible de faire des pages dans des dossiers sur Github et de les afficher (comme `spd/reference` par ex) mais il faudrait faire un petit développement pour récupérer l'information et utiliser ces dossiers pour faire le fil d'ariane.

Ça suppose aussi de trouver une façon d'ajouter des titres aux dossiers (via frontmatter par ex) pour afficher des fils d'ariane avec des noms compréhensibles, accentués, etc.

**Comment by agarrone** [comment]
Merci. Je pense en not planned for now :)
