### ISSUE TITLE
Création page A propos

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#455]
- [x] page md sur datagouvfr-pages
- [ ] lien depuis data.gouv.fr : avant nous contacter dans le header

**Comment by agarrone** [comment]
Page à propos ici : https://github.com/etalab/datagouvfr-pages/blob/master/pages/about/a_propos.md

Page à quoi sert l'open data ici : https://github.com/etalab/datagouvfr-pages/blob/master/pages/about/a_quoi_sert_opendata.md
