### ISSUE TITLE
Enquêter sur le calcul des métriques

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#458]
Enquêter sur le fait que le re-calcul des métrics diffère des métrics mis à jour au fur et à mesure.

Enquêter aussi sur la différence de résultats entre la réindexation des metrics sur staging et sur la prod (voir https://github.com/etalab/data.gouv.fr/issues/321).

**Comment by maudetes** [comment]
Peut-être en lien avec la différence staging vs prod: https://gitlab.com/etalab/data.gouv.fr/infra.data.gouv.fr/-/blob/master/group_vars/datagouv-staging/config.yml#L156

**Comment by agarrone** [comment]
Refacto totale des metrics ticket plus d'actu
