### ISSUE TITLE
Bug d'affichage en bas de la page organisation

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#46]
En bas de la page [organisation](https://www.data.gouv.fr/fr/organizations/), j'ai un bug d'affichage : 
 
![bug_affichage](https://user-images.githubusercontent.com/3227753/34035015-ec7e4fd6-e180-11e7-9407-5d848565ee1b.png)

**Comment by abulte** [comment]
@pachevalier je ne reproduis pas. Tu as toujours le problème ? Quel navigateur ?

**Comment by abulte** [comment]
Reproduit, c'est pas forcément en bas de page:

<img width="652" alt="capture d ecran 2018-01-16 16 24 36" src="https://user-images.githubusercontent.com/119625/34996435-e8152a74-fad9-11e7-9f1c-82820589d2ca.png">

**Comment by abulte** [comment]
Ca marche aussi sur les jeux de données :

<img width="649" alt="capture d ecran 2018-01-16 16 26 06" src="https://user-images.githubusercontent.com/119625/34996455-f7ee2a7c-fad9-11e7-8bdd-26e2b696f883.png">

**Comment by pachevalier** [comment]
En bas de la page : https://www.data.gouv.fr/fr/reuses/

![screenshot from 2018-01-16 17-02-22](https://user-images.githubusercontent.com/3227753/34998320-11759ec6-fadf-11e7-893a-422b929ac691.png)

**Comment by taniki** [comment]
Il n'y a plus de bug d'affichage avec les "nouvelles" cartes maintenant ce qui dépasse est caché. Ce n'est pas forcément satisfaisant mais ça devient une autre histoire.
