### ISSUE TITLE
<div data-udata-dataset="568295edc751df0aeec664bd"></div><script data-udata="https://www.data.gouv.fr/" src="https://static.data.gouv.fr/static/oembed.js" async defer></script>

### ISSUE THREAD

**Issue by ABDO53** [etalab/data.gouv.fr#462]
## L’amélioration que vous avez en tête
Décrivez ce que vous aimeriez pouvoir faire. Exemple : « J’aimerais avoir la possibilité de… ». Si possible, ajoutez des captures ou des enregistrements de votre écran pour nous aider à visualiser la fonctionnalité.

## Les alternatives possibles
Si possible, décrivez d’autres façons de parvenir au résultat que vous espérez atteindre.

**Comment by maudetes** [comment]
Bonjour @ABDO53, pouvez-vous détailler le problème rencontré ?
