### ISSUE TITLE
Ajouter un bandeau sur les pages utilisateurs cassées

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#463]
Il reste pour l'instant des liens pour accéder aux pages utilisateurs: https://github.com/etalab/data.gouv.fr/issues/440.

Expliciter sur la page user qu'elle est en jachère.

**Comment by nicolaskempf57** [comment]
Les liens ne sont plus présents depuis les changements de haut de page. Par exemple: https://www.data.gouv.fr/fr/reuses/finances-locales-1/ n'a plus de lien vers la page utilisateur.

Nous pouvons toujours ajouter le bandeau sur la page utilisateur pour les liens directs et les personnes qui ont une page profil en favori.
