### ISSUE TITLE
Page oauth relookée

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#466]
- [x] Logique d'override côté udata-front
- [x] Maquette de la page oauth
- [x] Implémentation du front selon la maquette

Page actuelle:

![image](https://user-images.githubusercontent.com/28541902/134354081-7816c9ce-be8d-491d-8616-53c77a4983e7.png)

**Comment by thbar** [comment]
J'ai upvoté, pas tant pour l'esthétique que pour le fait qu'un utilisateur tiers (ex: producteur de données) sur une application tierce (type transport data) peut avoir l'impression que quelque chose est simplement cassé ou "pas fiable", en tout cas se poser une question.

Si c'est gros à faire de votre côté, une première petite CSS type "texte centré + fonte basique en place" pourrait faire un quick fix ? (juste une idée).

Merci !

**Comment by thbar** [comment]
(pour clarifier: je n'ai pas entendu de personnes se plaindre directement de ça à mon niveau, c'est juste un ressenti personnel à ce stade)

**Comment by maudetes** [comment]
@nicolaskempf57 the logic to override the oauth template has been implemented in https://github.com/etalab/udata-front/pull/29 using hooks.
