### ISSUE TITLE
Bug affichage des onglets dans la page organisation

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#47]
Dans les pages [organisations](https://www.data.gouv.fr/fr/organizations/ministere-de-l-interieur/), les intitulés des onglets n'apparaissent plus : 

![affichageonglets](https://user-images.githubusercontent.com/3227753/34035232-acf39064-e181-11e7-9332-5dec84ff784d.png)

**Comment by abulte** [comment]
Fixed by https://github.com/opendatateam/udata/issues/1320
