### ISSUE TITLE
Deeplink depuis les mails de discussion cassé ?

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#474]
les questions des usagers qui nous sollicitent sur le RNA ou les ARUP ou les FRUP n'apparaissent pas dans le fil de discussion de la nouvelle version de DATA.GOUV mais seulement dans l'ancienne : cela oblige à plusieurs manipulations qui sont :
Se rendre sur DATA.GOUV via le lien dans le mail intitulé "VOIR LA DISCUSSION"
Se connecter avec le compte ***
Vérifier que la discussion est présente en bas de la page
Lorsque ce n'est pas le cas (c'est-à-dire à chaque fois), revenir sur l'ancienne version de DATA.GOUV
Se connecter à nouveau
Aller au bas de page pour répondre à la discussion

**Comment by maudetes** [comment]
Sur les commentaires qu'ont reçoit sur les jeux de données Etalab, les liens ont l'air corrects. Exemple pour un mail sur une nouvelle discussion par Jean-Laurent LIBES, le lien du mail : https://www.data.gouv.fr/fr/datasets/donnees-relatives-au-fonds-de-solidarite-mis-en-place-dans-le-cadre-de-lepidemie-de-covid-19/#discussion-612cc8c2d248521483024b06.
Cependant, l'ancre ne semble pas fonctionnelle lorsqu'on se rend sur la page la première fois (probablement à cause du délai de chargement javascript).

**Comment by gmougeolle** [comment]
Je crois juste qu'il manque la ligne pour scroller vers le module de discussions dans le cas où on charge un thread particulier. Je peux m'en occuper rapidement c'est vraiment une ligne ;)

**Comment by maudetes** [comment]
Yes, pour le scroll !
J'attends un retour pour savoir si c'est vraiment le soucis rencontré sur le RNA ou ARUP par contre.

**Comment by gmougeolle** [comment]
Effectivement, je vais ajouter la ligne mais ce n'est qu'une histoire de confort : le message mentionne l'absence du bloc de discussions alors qu'il devrait être présent donc peut-être un autre problème ?

**Comment by maudetes** [comment]
Après retour, il s'agissait sûrement d'un soucis de scroll, résolu par https://github.com/etalab/data.gouv.fr/issues/510.
