### ISSUE TITLE
A quoi correspondent `last_modified` et `last_updated` dans le json d'un dataset ?

### ISSUE THREAD

**Issue by amirouche** [etalab/data.gouv.fr#48]
Pour un dataset donnée avec plusieurs fichiers dedans. Il y a dans le json envoyé deux dates `last_modified` et `last_update`.

A quoi correspondent les deux dates associées à `last_modified` et `last_updated`?

En particulier est ce que l'une de ses deux dates est mise à jour quand un fichier est ajouté/modifié ou supprimé?

Respectivement pour les `resources` presentent dans ce même fichier à quoi correspondent `last_modified` et `last_updated`?

[101.json.txt](https://github.com/etalab/data.gouv.fr/files/1584205/101.json.txt)

Merci d'avance, et joyeux noel :snowman_with_snow:  :santa: :snowflake:

**Comment by abulte** [comment]
Bonjour,

Selon la doc de l'API dispo ici : https://www.data.gouv.fr/fr/apidoc/#!/datasets/get_dataset, les deux champs sont :

```
last_modified (string): The dataset last modification date ,
last_update (string): The resources last modification date ,
```

Sur une ressource vous devriez seulement avoir `last_modified`.
