### ISSUE TITLE
Transférer les projets Crowdin vers un compte partagé

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#480]
We should move our crowdin projects to a shared account to avoid losing ownership when the owner leaves. How to below.

- https://crowdin.com/project/udata-ckan
- https://crowdin.com/project/udata-gouvlu
- https://crowdin.com/project/udata-ods
- https://crowdin.com/project/udata
- https://crowdin.com/project/udata-gouvfr
- https://crowdin.com/project/udata-front

> At the moment there is no easy way to transfer the project from one account to another. Since you cannot reach the owner (one of the possible solutions would be sharing the credentials of the main account) the other solution would be recreating projects in this way:
> 
> 1) Download source files (via Project Settings -> Files tab or probably you have them locally, so you can skip this step);
> 2) Download existing translations (Project Settings -> Build&Download);udata-
> 3) Download TM (Resources tab from the owner's account-> Translation memory -> Choose the needed one -> Download)
> 4) If necessary, create a list of participants' usernames/permissions locally and then re-invite into another project;
> 5) Re-create a project (https://crowdin.com/createproject) under the preferred account;
> 6) Re-upload sources, translations, and TM into the new project (if necessary you can run pre-translate via TM to auto-translated the strings).
> 
> But mind that in this way all the data will be moved by you to another account except the reports, comments to the strings, messages in the account etc.

Adress to use: udata@data.gouv.fr

**Comment by maudetes** [comment]
De-prioritize since I've gained access to https://crowdin.com/profile/opendatateam, Manager in all udata projects (but not owner)
