### ISSUE TITLE
Gérer le slug d'un utilisateur supprimé

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#486]
Aujourd'hui, un utilisateur qui supprime son compte voit les infos de son profil (nom, prénom) remplacés par DELETED.
Cependant, son slug (ex: `estelle-maudet`) garde encore ses infos personnelles, et sa page https://www.data.gouv.fr/fr/users/estelle-maudet/ serait encore référencée par les moteurs de recherche.

Possibilités de résolution:
- supprimer les slugs et ne garder que la possibilité d'intérroger par id 
- directement remplacer le slug par l'id

**Comment by agarrone** [comment]
Je peux close @maudetes ?

**Comment by maudetes** [comment]
Je pense qu'on peut close car les pages utilisateurs sont désindexées des moteurs de recherche, donc le slug n'est plus problématique.
Voir aussi https://github.com/etalab/data.gouv.fr/issues/513.
