### ISSUE TITLE
Ajouter un bouton voir tous sur les jeux de données sur les pages organisation

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#487]
sur la page data.gouv.fr/orga

**Comment by agarrone** [comment]
De plus, la recherche de jeux de données est complexe depuis une page organisation depuis la refonte. 
Quick win : rajouter un bouton "Voir tout" qui renvoi vers data.gouv.fr/datasets/*nom_de_l'orga

**Comment by nicolaskempf57** [comment]
Peut-on se contenter du quick win dans la mesure où il y a déjà un bouton de tri sur la page de recherche des datasets ?
