### ISSUE TITLE
Mots cléfs récupérés (avec traduction en anglais) par l'utilisation de l'API data.gou

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#49]
Bonjour,

Nous avons remarqué avec notre portail expérimentale www.databfc.fr que le moissonnage de données ouvertes à partir de geo.data.gouv entrainent la traduction des mots clés (thèmatique Inspire).

C'est flagrant avec l'exemple suivant : 
Fiche "originelle" sur idéobfc
https://www.ideobfc.fr/geonetwork/srv/fre/catalog.search#/metadata/afc5eb6d-800d-4cb2-ba45-a71357193728

Fiche de geo.data.gouv
https://geo.data.gouv.fr/fr/datasets/9b66adef3c201f14e241c7446152a60f300f1ed3

Fiche sur data.gouv
https://www.data.gouv.fr/fr/datasets/stations-velocite-de-besancon/

Fiche recueillie par databfc
http://databfc.fr/bfc/visualisation?id=a985ed09-bf25-4daf-938a-dacf1395ea64&serveur=https://www.databfc.fr:8900

Le mot clé transportation a été ajouté...

Pouvez vous nous expliquer cela ?
D'avance Merci !

**Comment by jdesboeufs** [comment]
Bonjour,

Le tag `transportation` est en fait issu du thème INSPIRE.
À l'avenir ce tag sera traduit en français.

**Comment by jerbou** [comment]
Merci !
