### ISSUE TITLE
Hiérarchie de l'information - Itérer sur les différents éléments d'une page Dataset & Réutilisation

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#490]
Suite aux différents quickfix qui ont été fait sur la page dataset https://github.com/etalab/data.gouv.fr/issues/488, mener une réflexion plus large sur l'organisation et la navigation entre les différents éléments (informations, ressources, réutilisations, discussions, ressources communautaires).

Voir notamment ces maquettes : https://www.figma.com/file/yTDQCrOXlm9ygocRgi1oDb/Recherche%2FEvolutions?node-id=909%3A14721

A garder en tête pour ce travail : 
 - Penser à inclure dans la reflexion l'onglet activité
 - Penser à la previz
 - Penser à la potentielle possibilité future d'éditer via le front

**Comment by agarrone** [comment]
Penser notamment à inclure dans la reflexion l'onglet activité
