### ISSUE TITLE
Cohérence du vocabulaire

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#5]
![screenshot from 2017-09-07 09-21-49](https://user-images.githubusercontent.com/3227753/30168026-7feaff1c-93e8-11e7-9790-5fe56bdeb33f.png)

Sur le même écran, il y a à la fois le terme "réappropriation" et le terme "réutilisation". 

Je ne sais pas ce qui a été décidé en équipe mais perso, je trouve le terme de réutilisation plus clair.

**Comment by pachevalier** [comment]
En fait, j'ai compris la différence entre une réappropriation et une réutilisation

**Comment by yohanboniface** [comment]
Fais-en profiter les copains ;)

**Comment by oncletom** [comment]
@pachevalier yes, c'est un point qui est remonté dans un des entretiens utilisateurs justement. C'est le seul endroit où on voit le mot "réappropriation".

**Comment by pachevalier** [comment]
L'idée c'était de faire une distinction entre les réutilisations générées par les jeux de données publiées par une organisation (ie les réappropriations) et les réutilisations publiées directement par l'organisation elle-même.

**Comment by schignard** [comment]
Un journaliste d'un journal satirique paraissant le mercredi nous a posé la question. Personnellement je trouve cela très confusant et le rapport intérêt de la distinction / compréhension me semble pas évident...

**Comment by oncletom** [comment]
Vous avez des idées ou des débuts d'idées de ce qui paraitrait plus clair à présenter ?

**Comment by schignard** [comment]
Réutilisation, c'est tout !

**Comment by noirbizarre** [comment]
Pour info, initialement c'était "réutilisation" et ça a été changé parce qu'on nous à signalé que c'était "confusant".
Du coup, je pense qu'il faut changer le wording oui, mais revenir à "reutilisation" c'est réintroduire le problème initial.

Je tiens aussi à mettre en avant le fait que sur #26 la suggestion inverse est faite (changer le terme "réutilisation" à un endroit où cela désigne le même concepte.
Si l'on pouvait essayer de ne pas proposer des solutions antogonistes (proposer à la fois d'utiliser le même terme pour 2 concepts différents par cohérence et dans le même temps proposer 2 termes différents pour ce même concept toujours par cohérence) et avoir une approche cohérente sur ces 2 points ça serait pas mal. Je me demande s'il ne faut pas fusionner ces 2 discussions du coup (cohérence du wording lié aux réutilisations).

**Comment by noirbizarre** [comment]
Après, étant donné que ça n'apporte que peu de choses en recherche, peut-être qu'il faut juste le laisser sur la tableau de bord du producteur et le virer de la carte pour ne garder que les réutilisations directes.

**Comment by oncletom** [comment]
> Après, étant donné que ça n'apporte que peu de choses en recherche, peut-être qu'il faut juste le laisser sur la tableau de bord du producteur et le virer de la carte pour ne garder que les réutilisations directes.

Ça me parait être le changement le moins coûteux pour résoudre cette issue. Je vote pour ça 👍

**Comment by jdesboeufs** [comment]
@schignard @pachevalier qu’en pensez-vous ?

**Comment by schignard** [comment]
Effectivement il y a 2 problèmes:
1/ l'usage du terme réappropriation 
2/ la facette de recherche qui précise "jamais réutilisé"

Pour le 1/ je vote pour le supprimer tout court, y compris sur le tableau de bord des producteurs 
Pour le 2/ je vote pour supprimer tout simplement cette facette dont le rapport "intérêt pour l'utilisateur de la plateforme" (qui l'utilise ?) vs. "confusion que cela provoque" n'est pas très bon.

**Comment by bboulesteix** [comment]
Comme le ticket est encore ouvert, je débarque ici plus d’un an après le dernier commentaire pour dire que :

* Je ne vois pas bien la différence entre une **réutilisation** et une *réappropriation**. Comment peut-on réutiliser des données sans se les réappropriai dans un premier temps ? Pas sûr de comprendre. 🤔 
* J’ai été surpris de découvrir le terme **réappropriation** dans l’onglet _Organisations_ des résultats de recherche, terme qui n’apparaît que très rarement sur le site, contrairement au terme *réutilisation*. 👀 

Mon avis partiel :

1. **Cette distinction est byzantine**. — Puisque les _réappropriations_ n’ont aucune existence concrète sur le site (on ne peut pas les voir), contrairement aux _réutilisations_, supprimons ce terme des vues `Recherche > Organisation`, des profils d’organisations, et des facettes de filtrage au niveau des résultats de recherche. Il s’agit d’une distinction trop fine, trop pointue, trop compliquée pour être vraiment opérante.
2. **Cette distinction coupe en deux un ensemble déjà minuscule.** —  Seuls 3,60 % des jeux de données publiés sur data.gouv.fr ont fait l’objet d’au moins une réutilisation (1330 sur 36592). Dans ces conditions, à quoi bon introduire **deux** catégories **différentes** dans un ensemble qui est déjà très limité, qui ne pèse presque rien ? Ce n’est pas comme si nous croulions sous les réutilisations et qu’il était urgent de les distinguer pour permettre aux utilisateurs de mieux s’y retrouver… 

Solution proposée : faisons simple, appelons **réutilisation** tout ce qui consiste à faire des choses avec des données publiées sur data.gouv.fr. Simplifions le vocabulaire, simplifions les filtres, simplifions le produit. Je rejoins en cela @schignard.

**Comment by taniki** [comment]
Je ferme l'issue. Le problème est résolue : on ne fait plus la distinction et on n'affiche plus non plus l'étiquette dans les résultats de recherche.

**Comment by taniki** [comment]
fausse alerte l'onglet "organisations" n'a pas bougé
