### ISSUE TITLE
Compléments d'information sur les dates (modification, mise à ressources) ?

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#50]
Bonjour,

Comme évoqué lors du dernier atelier geodata, nous moissonnons data.gouv.fr pour alimenter data.bfc.fr, et ainsi permettre des visualisations.
La copie locale est faite en différentiel, basé sur les dates de mise à jour.

Hors l'exemple de cette donnée nous montre une complication :
https://www.data.gouv.fr/fr/datasets/descriptif-des-stations-depurations/

La date de dernière mise à jour de la ressource est noté ce jour le 21/12.
Hors l'organisation a bien efface et redéposé les datasets le 11/01/2017.

Donc on s'attend à ce que la date de mise à jour (dans la métadonnée) soit modifiée, hors ce n'est pas le cas... non ?

Pourriez vous donc expliciter les termes de dates de modifications, date de dernière mise à jour de la ressource. Cela nous est important pour mieux spécifier l'algorithme de moissonnage.

D'avance Merci,

**Comment by abulte** [comment]
Bonjour,

La date de dernière mise à jour des ressources est aujourd'hui le 16/01/18, ce qui parait cohérent. Constatez-vous toujours un problème ?

**Comment by jerbou** [comment]
Bonjour,

Merci, je constate la résolution.
