### ISSUE TITLE
Ajouter un formattage des nombre au format français dans le bandeau de chiffres clés sur la home

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#511]
## L’amélioration que vous avez en tête

Sur la home, il y a des chiffres clés relatifs à la plateforme : 39 298 jeux de données, 211 101 ressources, etc. Pour la lisibiité de ces nombres, ce serait pas mal d'ajouter une mise en forme des nombres à la française avec un espace pour séparer les miliers.

## Les alternatives possibles
Si possible, décrivez d’autres façons de parvenir au résultat que vous espérez atteindre.

**Comment by nicolaskempf57** [comment]
@agarrone @maudetes Est-ce qu'on en profite pour supprimer la couleur vert du liseré dans le cas d'une reutilisation ? Comme il n'y a plus vraiment de distinction de couleur entre dataset et reuse et sachant qu'avec la mise en accessibilité on a du mal à faire la distinction entre les 2.

**Comment by agarrone** [comment]
Yes please , merci pour ta vigilance ;) il y a même un ticket haha #297

**Comment by restuccia** [comment]
I am reopening the issue as the numbers do not seem to be formatted in any way for me, but maybe it's due to my unique config.

I am on Firefox 98.0.2 (64-bit), with the following locale parameters:
- `extensions.ui.locale.hidden` is `false`
- `intl.locale.requested` is `en-us`
- `intl.regional_prefs.use_os_locales` is `false`

![Capture d’écran 2022-03-31 à 10 28 39](https://user-images.githubusercontent.com/51122275/161013399-8560946f-2579-455d-96dd-05aebfb0b85b.jpg)

**Comment by nicolaskempf57** [comment]
Formatting is based on `/fr/` or `/en/`in URL so our locale settings can't conflict with it. But for some reason, Firefox doesn't render our space between numbers even if it's in the HTML page. I'll see if we can use a non-breaking space instead of the default one.

**Comment by nicolaskempf57** [comment]
After more digging :
- our i18n library is using a narrow non-breaking space in French, that's correct ✅ 
- this is not altered during rendering ✅ 
- Marianne font has this glyph ✅
- this is not rendered in some firefox version (mine and @restuccia but ok for @maudetes) for Marianne but works for other fonts

I don't think we can do something about it ourself that's not a workaround.

**Comment by restuccia** [comment]
Cheers ! We could report the issue to Mozilla but I spent 10 minutes searching how to open a ticket and couldn't find a way to do so. I guess we can close this?
