### ISSUE TITLE
Enquêter sur le référencement des pages `users` sur Google

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#513]
Suite à un retour utilisateur sur le support dont sa page utilisateur (compte supprimé depuis) été référencé sur Google.

Exemple: https://www.google.com/search?q=alexandre-bulte+data.gouv.fr&rlz=1C5CHFA_enFR918FR918&oq=alexandre-bulte+data.gouv.fr&aqs=chrome..69i57.18937j0j15&sourceid=chrome&ie=UTF-8

**Comment by maudetes** [comment]
>  For the `noindex` directive to be effective, the page must not be blocked by a robots.txt file, and it has to be otherwise accessible to the crawler. If the page is blocked by a robots.txt file or the crawler can't access the page, the crawler will never see the noindex directive, and the page can still appear in search results, for example if other pages link to it.

**Comment by abulte** [comment]
Still failing, maybe ask google crawler to force reindex?

**Comment by maudetes** [comment]
I think it's currently reindexing. As an example there are "only" 2790 results with the user url: https://www.google.com/search?q=site:https://data.gouv.fr/fr/users/&filter=0 and some users have been removed from the index already (yours and mine apparently).
We can see the coverage going down as well.
![image](https://user-images.githubusercontent.com/28541902/142903399-774369f7-6574-459f-a7f8-3efd8b84a75d.png)

I think that if we want to force reindex on multiple urls, we should submit a sitemap (see https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl).
