### ISSUE TITLE
Ajouter la possibilité de choisir quels emails recevoir

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#514]
## Retours utilisateurs

Plusieurs producteurs se plaignent de la grande quantité d'emails reçus lorsqu'ils appartiennent à une organisation. Le problème augmente lorsqu'un usager appartient à une grande organisation telle que un ministère : l'utilisateur reçoit des emails concernant tous les jeux de données de l'orga, même s'il n'est responsable que d'un seul jeu de données.

## Solution possible
Ajouter des paramétrages d'email, avec la possibilité de choisir quels emails recevoir. Désactiver l'envoi de mails par défaut.

**Comment by agarrone** [comment]
Retravaillé dans la refonte de l'admin.
