### ISSUE TITLE
Tags de mots cléfs entraine la saisie badge nec mergitur ?

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#52]
Bonjour,

Un partenaire me demande pourquoi certains de ses datasets apparaissent comme tagué 
https://www.data.gouv.fr/fr/datasets/appels-recus-au-18-et-112-od71/
Ici le badge nec mergitur : https://www.data.gouv.fr/fr/search/?badge=nec

Je n'arrive pas à trouver la documentation sur les badges (et leurs différence avec les mots clefs)...
Help ?!

Est-ce que c'est déja la livraison de ce qui avait été abordé lors du dernier atelier geo.data :) ?
Prise en compte de catégorie à partir de mots cléfs ?

Merci,

**Comment by jdesboeufs** [comment]
Hello!

Les badges sont liés à des événements de type hackathon. Ils sont mis manuellement par l’équipe Etalab pour présélectionner des données intéressantes dans le contexte de l’événement.

**Comment by jerbou** [comment]
Merci pour la réponse !
