### ISSUE TITLE
Remplacer les pages de recherche par défaut de datasets, reuses et orga par des listes édito

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#528]
Plutôt que les résultats de recherche sans mot de recherche non pertinent, proposer une liste arbitraire (basé sur les `featured`) pour pouvoir débrancher la recherche sur ces pages par défaut.

**Comment by maudetes** [comment]
@agarrone pouvons-nous modifier le guide de publication des jeux de données pour rajouter un lien vers la création de compte et l'administration ? :)

**Comment by agarrone** [comment]
Sera traité dans un EPIC dedié
