### ISSUE TITLE
Maquette : Résoudre critère Couleurs 3.2

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#535]
Dans chaque page web, le contraste entre la couleur du texte et la couleur de son arrière-plan est-il suffisamment élevé (hors cas particuliers) ?

![image](https://user-images.githubusercontent.com/28541902/133801877-eb384df0-d505-4107-bcc0-8cae2ac54bc2.png)

Voir aussi https://github.com/etalab/data.gouv.fr/issues/304

**Comment by nicolaskempf57** [comment]
Contraste du nouveau bleu (#1778CF) par rapport aux précédents retours de l'audit :
✅ #1778CF sur fond blanc #fff
✅ blanc #fff sur fond #1778CF
❌ #1778CF sur fond gris #f9f9f9, ex: lien en footer
❌ #1778CF sur fond beige #f9f8f6, ex: sommaire, description de la page dataset

**Comment by agarrone** [comment]
Fixed avec les nouvelles couleurs ? @nicolaskempf57

**Comment by nicolaskempf57** [comment]
Yes !
