### ISSUE TITLE
Maquette : Résoudre critère Couleurs 3.3

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#536]
Dans chaque page web, les couleurs utilisées dans les composants d’interface ou les éléments graphiques porteurs d’informations sont-elles suffisamment contrastées (hors cas particuliers) ?

![image](https://user-images.githubusercontent.com/28541902/133802052-764e7be6-dfbe-4881-8400-c325491a07ef.png)

**Comment by nicolaskempf57** [comment]
Contraste du nouveau bleu (#1778CF) par rapport aux précédents retours de l'audit :
✅ #1778CF sur fond blanc #fff
❌ #1778CF sur fond gris #f9f9f9, ex: lien en footer
❌ #1778CF sur fond beige #f9f8f6, ex: sommaire, description de la page dataset

**Comment by agarrone** [comment]
Fixed avec les nouvelles couleurs ? @nicolaskempf57

**Comment by nicolaskempf57** [comment]
Oui oui
