### ISSUE TITLE
[Meta] Résoudre critère Scripts 7.1

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#537]
Chaque script est-il, si nécessaire, compatible avec les technologies d’assistance ?

![image](https://user-images.githubusercontent.com/28541902/133802321-74175fb1-247e-4b52-af98-a54961f447ae.png)

- [x] https://github.com/etalab/data.gouv.fr/issues/747

- [x] https://github.com/etalab/data.gouv.fr/issues/748
- [ ] #751

**Comment by nicolaskempf57** [comment]
Je vais faire différents commentaires sur certains points problématiques de notre code afin de clarifier les changements à apporter quand ils ne sont pas exclusivement techniques.

Je commence par le suggest. Le comportement actuel est le suivant :
- sur mobile, un bouton cliquable lance le suggest
- sur desktop, un formulaire lance le suggest au focus. Le formulaire comporte un bouton cliquable qui envoie le formulaire vers `/datasets`. Il est possible, à la fermeture du suggest de cliquer sur le bouton pour envoyer le formulaire.

Ce fonctionnement bloque le parcours dans la page. Soit le focus se trouve avant le formulaire et dans ce cas on peut accéder au moment. Soit le focus est après le formulaire et on peut accéder au contenu de la page. Une fois le formulaire passé, il n'est plus possible de revenir en arrière (le focus sur le formulaire ouvre le suggest).

Afin de résoudre cette problématique, je propose d'harmoniser le fonctionnement desktop avec le fonctionnement mobile. De cette façon, une action sur l'input ou le bouton déclenche le suggest et le fallback sans javascript est préservé. Le seul point qui reste incohérent avec cette approche est l'input de texte qui ne fonctionne pas du tout comme un input mais c'est déjà le cas actuellement.

Qu'en pensez-vous ?

**Comment by nicolaskempf57** [comment]
Les autres retours concernent principalement :
- nos multiselect : à voir s'il est possible de faire la mise en conformité. Le composant est très personnalisable, c'est assez encourageant
- nos modales : ne nécessite pas forcément le passage aux modales du DSFR mais ça peut être l'occasion de faire les 2 en même temps
