### ISSUE TITLE
Comment fait on pour changer l'email d'un compte

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#54]
Bonjour,

Notre compte admin est basé sur notre ancienne adresse contact[at]geob ...
Je ne vois comment refédinir l'adresse mail de ce compte ?

Est-ce possible ?

Merci,

**Comment by bboulesteix** [comment]
Bonjour @jerbou, merci d’avoir pris le temps de créer un ticket. 

Pour vous répondre :

> Est-ce possible ?

Non, à ce stade, il n’est pas possible de changer l’adresse e-mail associée à un compte utilisateur depuis l’interface de [data.gouv.fr](https://www.data.gouv.fr/fr/).  Cela dit, si vous avez **vraiment** besoin de changer l’adresse e-mail associée à votre compte, vous pouvez nous écrire à `info@data.gouv.fr`, en nous indiquant votre adresse e-mail actuelle et celle par laquelle vous souhaitez la remplacer, et nous ferons le changement à la main de notre côté.

Est-ce que cela répond à votre question ?

**Comment by bboulesteix** [comment]
Si je ne dis pas de bêtise, l’affaire est close. Je ferme donc l’issue.
