### ISSUE TITLE
Résoudre critère Présentations 10.5

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#540]
Dans chaque page web, les déclarations CSS de couleurs de fond d’élément et de police sont-elles correctement utilisées ?

![image](https://user-images.githubusercontent.com/28541902/133802841-7879f639-4584-48bd-a9b7-8e127156aad7.png)

**Comment by nicolaskempf57** [comment]
Le seul retour était le manque d'une couleur de fond sur le body. Nous en avons maintenant une qui vient du DSFR.
Cela a été corrigé par https://github.com/etalab/udata-front/pull/18, https://github.com/etalab/udata-front/pull/45 ou https://github.com/etalab/udata-front/pull/56.
