### ISSUE TITLE
Améliorer le scroll sur les ancres en responsive

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#546]
Soucis d'ancre du scroll en responsive, ex: https://www.data.gouv.fr/fr/datasets/jours-feries-en-france/#discussion-5fb3d009eba9f41919ffd766

![image](https://user-images.githubusercontent.com/28541902/133997087-479ae2f5-9ec4-4aa9-ae50-c3af9b48738d.png)

**Comment by agarrone** [comment]
Le pb sera résolue avec le nouveau header #747
