### ISSUE TITLE
Filtres par facette disparaissent dans la recherche en page 1

### ISSUE THREAD

**Issue by samgoeta** [etalab/data.gouv.fr#549]
Bonjour, 

je ne retrouve pas les filtres en faisant une recherche : 
![Capture d’écran 2021-09-22 à 12 16 53](https://user-images.githubusercontent.com/2378397/134353674-f6616bda-da3b-4313-b6e6-3e048c59fc50.png)

En passant en page 2, ils apparaissent. 

J'étais en formation ce matin et j'étais bien embêté. 

Merci de votre retour

**Comment by maudetes** [comment]
Bonjour,

Merci de nous avoir contacté et merci du signalement de ce soucis.
Nous avons identifié la source de ce problème, qui est en cours de résolution.

Bien à vous
