### ISSUE TITLE
Rendu markdown dans la description des ressources

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#55]
![rendu-ressources](https://user-images.githubusercontent.com/3227753/35436954-b864cfc8-0290-11e8-8db3-818a99606732.png)

Il semble qu'il y ait un problème de rendu du markdown dans l'affichage de la description d'une ressource.

**Comment by pachevalier** [comment]
Le rendu est différent dans l'admin. Il suffirait d'harmoniser les deux.
![rendu_admin](https://user-images.githubusercontent.com/3227753/35442585-15e51538-02a8-11e8-84c8-8ea70df8634d.png)

**Comment by Stanislas-Poisson** [comment]
Je confirme que  le rendu est bien différent, le changelog du projet est bien rendu dans l'admin _Fig 1_ mais pas du tout dans l'affichage de la ressource _Fig 2_
![admin data gouv fr](https://user-images.githubusercontent.com/3681410/41020210-3988a42a-6962-11e8-8f6f-bff223f5f0d8.png)

![regions departements villes et villages de france et d outre mer data gouv fr](https://user-images.githubusercontent.com/3681410/41020129-fe542a32-6961-11e8-85c3-d3d81a7929ed.png)

**Comment by abulte** [comment]
Bonjour @Stanislas-Poisson, très bientôt ! Le fix est ici https://github.com/opendatateam/udata/pull/1547
