### ISSUE TITLE
Indiquer le nombre de jeux de données par facette

### ISSUE THREAD

**Issue by samgoeta** [etalab/data.gouv.fr#551]
## L’amélioration que vous avez en tête
Dans la précédente version, il était possible de connaitre le nombre de jeux de données par organisation sur une recherche de données
![image](https://user-images.githubusercontent.com/2378397/134354987-4159694f-6a96-4120-86ca-357166dfe38e.png)

Cette information a disparu dans la nouvelle version et il semblerait que les organisations ne sont pas triées par nombre d'occurrences. 
<img width="295" alt="Capture d’écran 2021-09-22 à 15 42 32" src="https://user-images.githubusercontent.com/2378397/134355189-b2eb03b6-6eb7-4745-8380-d512345c6400.png">

Mon amélioration : remettre le nombre de jeux de données dans les filtres

## Les alternatives possibles
?

**Comment by agarrone** [comment]
Pas de logique de facettes pour l'instant. Mais investigation en cours dans le cadre des travaux avec Ecosphere.
