### ISSUE TITLE
Questionnaire découvrabilité

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#552]
- [x] Définir contenu du questionnaire découvrabilité
- [ ] Implémenter une Modale/un bandeau pour le questionnaire de découvrabilité

[Voir le questionnaire](https://app.evalandgo.com/s/index.php?id=JTk5aiU5QWglOTclQUQ%3D&a=JTk3cCU5M2glOTklQUU%3D)

[Voir le notion pour contexte](https://www.notion.so/apigouv/Questionnaire-d-couvrabilit-sur-data-gouv-fr-9ea10eeab6be4a34821adeea33dd6fff)

**Comment by abulte** [comment]
TODO : mettre le lien vers l'eval and go dans le bandeau "habituel" et voir si ça convertit.

**Comment by maudetes** [comment]
On préfère mettre l'accent sur la mesure des indicateurs de recherche en particulier et on dépriorise un questionnaire plus général. Ce dernier peut être lors d'une nouvelle itération sur la découvrabilité.
