### ISSUE TITLE
Stocker les résultats des questionnaires découvrabilité

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#555]

**Comment by maudetes** [comment]
_Switching to English for this documentation_

# Storing surveys results in Matomo

We compile here some results for a study to store survey results in Matomo.

Features list can be found [here](https://matomo.org/features/).

Features that may be used to store arbitrary results could be _Custom Dimensions_ and _Custom Variables_.

## Custom dimensions

[Reference](https://matomo.org/docs/custom-dimensions/)
> With Custom Dimensions you can assign any custom data to your visitors or actions (like pages, events, site search, …).

You can use a _Visit_ or _Action_ scope. The first one being associated with a specific visitor (having only one value set per dimension), while the second would be associated with an action (page view, download). We could probably use a _Visit_ scope and having multiple dimensions set for a visitor, in order to cross-check information.

Dimensions can't be deleted but they can be renamed.

### Limits
Values of custom dimensions are limited to 255 chars ([can be changed](https://github.com/matomo-org/matomo/issues/16150)).
Which means that we can't have huge text area, but it seems a pretty reasonable constraint for our survey.
By default, only 5 dimensions can be used per website.

## Custom variables - will be deprecated

[Reference](https://matomo.org/docs/custom-variables/)

Will be deprecated in the future.
> The only use case where it would make sense to use Custom Variables instead of Custom Dimensions is when a given dimension can have multiple values for a same visitor or page.

The limits are very similar to Custom Dimensions.
The differences between Custom Dimensions and Custom Variables can be found [here](https://matomo.org/faq/general/faq_21117/). 

## Conclusion

We could probably go for Custom Dimensions in our use case if we want to use Matomo.

We could create dimensions such as _found-search-result_ (with possible values _True_, _False_), _looking-for_ (with possible values _specific-dataset_, _explore-dataset_, _specific-reuse_, ...).

We could use _Visit_ scope in order to cross dimensions per user (20% of people who didn't find what they were looking for were looking for a specific dataset, etc.).

The limits can be parametrized and are not a hindrance in our use case.

However, the tool is not made for storing surveys by default and even if possible, parametrizing it won't be as straight-forward as a survey tool. Additionally, analysis and visualization may require more work than with a dedicated tool.

**Comment by abulte** [comment]
Evalandgo dans un premier temps.
