### ISSUE TITLE
Enquêter sur cas de réutilisation sans propriétaire

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#566]
La réutilisation apparaît sans propriétaire: https://www.data.gouv.fr/fr/reuses/place-des-entreprise-le-service-public-des-tpe-pme-pour-un-conseil-personnalise-et-de-proximite/
Le transfert d'organisation ne fonctionne pas non plus pour cette réutilisation.
![image](https://user-images.githubusercontent.com/28541902/136062908-4c75f3a4-c888-4770-87fc-34be521b5454.png)

Erreur Sentry concernée: https://sentry.data.gouv.fr/organizations/sentry/issues/13851/?project=5&query=is%3Aunresolved

**Comment by abulte** [comment]
(Situation corrigée manuellement via le shell mais l'erreur doit pouvoir être reproduite)

**Comment by maudetes** [comment]
Une trentaine de cas de réutilisations sans propriétaire.
Reproduit en local lors d'un transfert d'une réutilisation d'une organisation vers un user.
:warning: un seul cas où la réutilisation est le sujet d'un transfert : https://www.data.gouv.fr/en/reuses/echeances-des-actions-de-la-feuille-de-route-data-interministerielle/.
Il y a probablement d'autres raisons qui peuvent amener à ce problème.

Dans ce cas là, le problème vient du signal pre-save qui est appelé deux fois (lors du premier save puis lors du recalcul des metriques), sans que les changed_fields soient cleared: https://github.com/opendatateam/udata/blob/a5fba3e160abe3e1bd4ba8c36ff036153d179a22/udata/models/owned.py#L38

**TODO**
- Reproduire le problème avec un test unitaire
- Corriger le problème
- Enquêter sur les autres cas
- S'assurer que ce problème ne peut pas se reproduire par la suite
