### ISSUE TITLE
Recommandation vide sur le jeu de données RPLS

### ISSUE THREAD

**Issue by pachevalier** [etalab/data.gouv.fr#57]
![reco_rple](https://user-images.githubusercontent.com/3227753/35446086-f3297fdc-02b3-11e8-9096-c6de1f2747ea.png)

Sur le jeu de données [RPLS](https://www.data.gouv.fr/fr/datasets/repertoire-des-logements-locatifs-des-bailleurs-sociaux-rpls/), la section "Voir aussi" est vide.

**Comment by abulte** [comment]
Effectivement on reçoit `{"5a1dd4e5c751df02b116a0d6": [["plan-cadastral-informatise-pci", "19"]]}` dans le JSON des recommendations. `plan-cadastral-informatise-pci` devrait être un UUID, pas un slug. @pachevalier tu peux jeter dans le notebook ?

Le JSON est ici : https://raw.githubusercontent.com/etalab/datasets_reco/master/reco_json/5a1dd4e5c751df02b116a0d6.json

**Comment by abulte** [comment]
En attendant j'ai corrigé à la main, si quelqu'un peut merger @pachevalier @FloSugar  https://github.com/etalab/datasets_reco/pull/1
