### ISSUE TITLE
Enquêter sur une ressource manquante sur les serveurs

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#570]
La ressource de : https://www.data.gouv.fr/fr/datasets/caracteristiques-techniques-des-sites/ est manquante.

Hypothèse de @abulte:
Purge des ressources quand on a mis en place la suppression des fichiers ?

**Comment by abulte** [comment]
Found in backups, so probably removed by the purge.

**Comment by maudetes** [comment]
Could we restore it?

**Comment by abulte** [comment]
Yes! But I need to see if there are any other impacted files before, based on URL pattern I guess.

**Comment by abulte** [comment]
Done!
