### ISSUE TITLE
Enquêter sur vulnérabilité XSS

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#572]

**Comment by nicolaskempf57** [comment]
La vulnérabilité est liée à la version de Vue.js v3.0.5 utilisée en production.

Il s'agit un bug du framework qui a été corrigé à partir de la version v3.1.0-beta.6.

Suite à la montée de version de Vue.js réalisée en septembre (https://github.com/etalab/udata-front/pull/9/commits/3b99f02c1c3afcfa16194ddb56f133786a064aa3), nous utilisons maintenant Vue.js v3.2.11 qui n'est plus vulnérable.

Il est possible de tester la différence entre les versions sur des exemples simples : https://codepen.io/collection/jbPYvY
