### ISSUE TITLE
Bug affichage bouton "schema" sur la page du dataset

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/data.gouv.fr#573]
## Description du bug

Sur certain jeu de données, constat d'un bug sur le bouton schema

![image](https://user-images.githubusercontent.com/3721168/136954944-e3d60a35-fa27-4e4d-a4e7-968e91d3df7c.png)

Je pense que cela est dû au fait que la ressource possède une métadonnée schéma remplie et son nom est très long

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller sur https://www.data.gouv.fr/fr/datasets/plan-departemental-des-itineraires-de-promenade-et-de-randonnee-pdipr-puy-de-dome/
2. Regarder la première ressource
3. Constater le bug

## Comportement attendu

Bouton schéma claire comme à son habitude 
Ex :
![image](https://user-images.githubusercontent.com/3721168/136955110-a8355402-d4a1-43cb-bde6-9650af0e2f5a.png)

**Comment by abulte** [comment]
Pas reproduit pendant la démo, le jdd n'existe pas sur staging.
