### ISSUE TITLE
Dev : Harmoniser les blocs supérieurs

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#576]
Les bloc supérieurs des pages réutilisations et organisation doivent être harmonisé sur le modèle de la page jeux de données

[Voir le Figma](https://www.figma.com/file/kfpGHDywdXEr0phdHfjTMc/Live-Fixes?node-id=437%3A10257)

- [x]  Maquettage
    - [x]  Page jeux de données
    - [x]  Page organisation
    - [x]  Page réutilisations
- [x]  Développement
    - [x]  Page jeux de données
    - [x]  Page réutilisation
    - [x]  Page organisation

**Comment by maudetes** [comment]
All done :)
