### ISSUE TITLE
Bug de scroll horizontale infinie vers la droite sur la homepage sur mobile sur Chrome & Safari

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#581]

**Comment by nicolaskempf57** [comment]
Le bug a l'air de venir de la liste de réutilisations en mode responsive. Il est notamment présent sur la page de détails des réutilisations : https://staging.data.gouv.fr/fr/reuses/evolution-des-immatriculations-et-radiations-des-societes/
