### ISSUE TITLE
co-existence deux users identiques avec rôles différents dans dashboard d'une organisation 

### ISSUE THREAD

**Issue by mkazmiers** [etalab/data.gouv.fr#59]
Bonjour,

dans l'idée de débloquer **https://github.com/etalab/geo.data.gouv.fr/issues/560**, échanges avec @jdesboeufs qui a suspecté pb de droit d'admin du user Mathieu Kazmierski.

Hier, dans le dashboard data.gouv.fr de l'organisation CRIGE-PACA, deux users membres Mathieu Kazmierski liés à la même adresse email coexistaient : l'un avec un rôle admin, l'autre avec un rôle editor.
J'ignore si c'est un bug, mais je suppose que oui.

J'ai essayé de supprimé le user Mathieu Kazmierski avec le rôle editor via l'interface proposée. Une fois validée, la suppression a supprimé le user Mathieu Kazmierski avec le rôle admin. Raté.

Pourriez-vous repasser le user Mathieu Kazmierski en admin?

d'avance, merci
(je ne savais pas quel titre donner à cette issue, qui est plutôt un report qu'autre chose - désolé)

**Comment by abulte** [comment]
Bonjour,

Je viens de repasser Mathieu Kazmierski en admin.

Nous avions déjà rencontré ce bug de membre en doublon et nous croyions avoir corrigé le problème ici https://github.com/opendatateam/udata/issues/1111. Malheureusement je vois que ce n'est pas le cas.

**Comment by abulte** [comment]
@mkazmiers si vous avez une idée de comment reproduire l'anomalie du membre en doublon, je suis preneur.

**Comment by mkazmiers** [comment]
@abulte no idea, c'est vieux (2015-2016)
Mais des pistes : 
* ce n'est pas moi qui ai crée l'organisation mais un autre user, qui était admin
* je me suis inscrit et rattaché à l'organisation
* quand le user a quitté la structure, je me suis passé en admin et l'ai repassé en editor ; c'est peut-être là que deux users se sont créés?
* j'ai tenté de publié des données dans inspire.data.gouv.fr entre temps
* mais je n'ai détecté le problème que hier...

**Comment by abulte** [comment]
@mkazmiers merci pour les pistes, on va regarder ça.

**Comment by agarrone** [comment]
Ca semble fixed, on refera un ticket si c'est de nouveau remonté
