### ISSUE TITLE
Ressource communautaire : pouvoir uploader un Geopackage

### ISSUE THREAD

**Issue by jbdesbas** [etalab/data.gouv.fr#60]
Bonjour,

Il est actuellement impossible d'uploader un fichier au format GPKG. Celui-ci est pourtant bien pratique pour les gros lots de données.

> 
>  Erreur d'envoi sur fichier.gpkg
> fichier.gpkg a une extension invalide. Extension(s) valide(s): csv, txt, json, pdf, xml, rtf, xsd, ods, odt, odp, odg, xls, xlsx, doc, docx, pps, ppt, tar, gz, tgz, rar, zip, 7z, xz, bz2, jpeg, jpg, jpe, gif, png, dwg, svg, tiff, ecw, svgz, jp2, shp, kml, kmz, gpx, shx, ovr, geojson, grib2, dbf, prj, sql, epub, sbn, sbx, cpg, lyr, owl, rdf, ttl, n3

**Comment by noirbizarre** [comment]
Bonjour,

Merci pour la suggestion, nous allons rajouter cette extension dans la liste des extensions autorisées.
Je reviens vers vous dès que c'est fait.

**Comment by noirbizarre** [comment]
Bonjour,

Ceci est normalement corrigé, vous devriez pouvoir uploader des fichiers `.gpkg`.

**Comment by jbdesbas** [comment]
Bonjour,

Super merci pour votre réactivité ! :-)
