### ISSUE TITLE
Absence de traduction pour la string "License Not Specified"

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#600]
Cf. https://www.data.gouv.fr/fr/datasets/les-sources-dinformations-sur-laide-publique-au-developpement-apd/
![Capture d’écran 2021-10-26 à 19 18 32](https://user-images.githubusercontent.com/51122275/138928872-ab17189b-6f24-4072-b14e-16004533203b.jpg)

**Comment by agarrone** [comment]
@maudetes je me souviens plus de la décision drastique qu'on a pris sur les licences ? Auquel cas ce serait plus d'actu ?

**Comment by maudetes** [comment]
Yes en effet, dans [la proposition qui avait été discutée](https://github.com/etalab/data.gouv.fr/issues/849), on n'aurait plus de "License Not Specified".
