### ISSUE TITLE
Ajouter un lien “Voir sur transport.data.gouv.fr” pour les jeux de données qui sont référencés sur le PAN

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#602]
Cela permettra aux utilisateurs de data.gouv.fr de découvrir la plateforme thématique ainsi que d’accéder à des outils adaptés pour les données transport (visualisation, rapports de validation...).

**Comment by maudetes** [comment]
Une idée pourrait être d'avoir un script qui récupère la liste des datasets de transport et fait le mapping avec datagouv pour rajouter une propriété additionnelle dans les extras. On peut se baser sur le job de [recommendations](https://github.com/opendatateam/udata-recommendations/) en inspiration.

**Comment by AntoineAugusti** [comment]
Merci la team datagouv ! @quaxsze @maudetes @abulte au nom de @etalab/transport
