### ISSUE TITLE
Chargement de Vue qui échoue sur une page dataset

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#604]
Voir les logs sur la page https://www.data.gouv.fr/fr/datasets/theses-financees-par-lademe-de-1992-a-2020/.

**Comment by nicolaskempf57** [comment]
L'erreur vient du bouton "prévisualiser" d'une ressource.

Il utilise une `preview_url` pour afficher la modale en VueJS. Cette URL n'est pas encodée et sur cette page, elle est égale à `https://koumoul.com/data-fair/embed/dataset/theses-financees-par-l'ademe-de-2005-a-2019/table`. 

Le point bloquant de cette URL est l'apostrophe `'` qui n'est pas échappée et qui crée une erreur de syntaxe pour le reste de l'appel `@click.prevent`.

**Comment by nicolaskempf57** [comment]
Après investigations, il semblerait que l'erreur soit liée au plugin `udata-data-flair` qui n'échappe pas systématiquement la `preview_url`. Il serait intéressant de proposer une solution systématique coté `udata`.

**Comment by nicolaskempf57** [comment]
Ce problème est résolu grâce aux changements techniques induits par la pagination des ressources (https://github.com/etalab/data.gouv.fr/issues/418)

**Comment by abulte** [comment]
Pas reproduit pendant la démo, le jeu de données n'existe plus sur staging.
