### ISSUE TITLE
S'assurer de la scalabilité du search par rapport au suggest

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#606]

**Comment by quaxsze** [comment]
Benchmark of search url `/api/1/datasets/?q=` 
<img width="839" alt="image" src="https://user-images.githubusercontent.com/57526019/141794367-17a27fea-ebb3-421e-8d26-9f2849a74979.png">

Benchmark of search url `/api/1/datasets/suggest/?q`
<img width="815" alt="image" src="https://user-images.githubusercontent.com/57526019/141794604-d175fcc1-c5ea-48a8-aadf-f18d5f8acc57.png">

**Comment by abulte** [comment]
Interesting! 

Did you try with a different query at each iteration? To bypass any cache thingy that could get in the way.

Also, did you try on a production-grade index (ie lots of documents)?

**Comment by quaxsze** [comment]
Queries were made with a random different string each time on the staging prod instance.
Suggest seems to have handled twice as much requests as standard search.

**Comment by abulte** [comment]
Nice 👏 

To be clear, are we talking about the Mongo search vs the Elastic Search suggest or the Elastic Search search (sic) vs Elastic Search Suggest?

**Comment by quaxsze** [comment]
The benchmark tests the Elastic Search search vs Elastic Search Suggest. The goal was to see if removing the suggest and using only the standard search is a good option.

**Comment by maudetes** [comment]
Additional benchmark made on dev-02 udata-search-service: `api/1/datasets/?q=`
```
     checks.........................: 100.00% ✓ 16464      ✗ 0    
     data_received..................: 2.8 MB  94 kB/s
     data_sent......................: 1.8 MB  59 kB/s
     http_req_blocked...............: avg=84.62µs min=44.48µs med=78.56µs max=2.38ms   p(90)=113.21µs p(95)=125.63µs
     http_req_connecting............: avg=55.75µs min=0s      med=47.36µs max=1.92ms   p(90)=79.93µs  p(95)=91.12µs 
     http_req_duration..............: avg=18.09ms min=4.05ms  med=17.87ms max=83.92ms  p(90)=19.46ms  p(95)=20.24ms 
       { expected_response:true }...: avg=18.09ms min=4.05ms  med=17.87ms max=83.92ms  p(90)=19.46ms  p(95)=20.24ms 
     http_req_failed................: 0.00%   ✓ 0          ✗ 16464
     http_req_receiving.............: avg=42.54µs min=10.25µs med=43.33µs max=565.99µs p(90)=53.57µs  p(95)=58.47µs 
     http_req_sending...............: avg=27.98µs min=11.51µs med=25.3µs  max=2.27ms   p(90)=37.72µs  p(95)=45.69µs 
     http_req_tls_handshaking.......: avg=0s      min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=18.02ms min=3.97ms  med=17.79ms max=83.83ms  p(90)=19.39ms  p(95)=20.16ms 
     http_reqs......................: 16464   548.475658/s
     iteration_duration.............: avg=18.22ms min=4.34ms  med=17.99ms max=84.08ms  p(90)=19.6ms   p(95)=20.37ms 
     iterations.....................: 16464   548.475658/s
     vus............................: 10      min=10       max=10 
     vus_max........................: 10      min=10       max=10 
```

For reference, number of queries on `/fr/datasets`, `/api/1/datasets/?q=` and `/api/1/datasets/suggest/?q=` combined are around 15K per hour on a busy day at peak time.

**Comment by abulte** [comment]
@maudetes did you look at the trafic data from last April?
