### ISSUE TITLE
Ajouter un filtre schéma à la recherche

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#610]
Je propose d'ajouter parmi les filtres de recherche, un filtre pour sélectionner un schéma de données, e.g. une solution graphique pour arriver à la sélection https://www.data.gouv.fr/fr/datasets/?schema=etalab%2Fschema-hautes-remunerations 

![Capture d’écran 2021-11-08 à 15 31 39](https://user-images.githubusercontent.com/51122275/140760741-61c44a5b-d742-4053-ac12-49e0f852f299.jpg)

Cette fonctionnalité permettrait également de résoudre le bug #388

**Comment by quaxsze** [comment]
Fait sur cette [PR](https://github.com/opendatateam/udata-search-service/pull/14)
