### ISSUE TITLE
Modification du sigle pas prise en compte

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#611]
## Description du bug
La suppression d'un acronyme des métadonnées d'un jeu de données n'est pas prise en compte

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller dans la page admin d'un dataset, e.g. https://www.data.gouv.fr/fr/admin/dataset/6151bd94bf06b42f321cc18a/
2. Modifier le dataset et supprimer la sigle
3. Enregistrer les modifications
4. Nothing happens

## Comportement attendu
La sigle devrait être supprimée

## Environnement
data.gouv.fr prod
udata 3.2.1
udata-front 1.1.1

**Comment by restuccia** [comment]
Le bug peut être reproduit, e.g. https://demo.data.gouv.fr/fr/datasets/ancora-un-altro-dataset-di-prova/

**Comment by maudetes** [comment]
Merci du signalement!
Est-ce que tu as un cas particulier où tu voudrais qu'on fasse la modif en CLI (ex: les feuilles de routes ministérielles que tu partages en exemple) en attendant une enquête sur ce bug?

**Comment by restuccia** [comment]
En effet "FdR" c'est plutôt moche du coup si tu pourrais l'enlever ça serait bien merci beaucoup !

**Comment by maudetes** [comment]
Done!

**Comment by maudetes** [comment]
Reopened by https://github.com/opendatateam/udata/commit/37de36c89c16ff9b13db0263b6249a03d6dee702.
