### ISSUE TITLE
Enquêter sur l'erreur sentry sur la page /fr/datasets

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#612]
Voir l'erreur sentry: https://sentry.data.gouv.fr/organizations/sentry/issues/12594/?project=5&query=is%3Aunresolved

**Comment by nicolaskempf57** [comment]
J'ai l'impression que l'erreur est lié à l'annulation des requêtes.

Pour gérer ce cas, axios lève une exception mais notre promise n'a pas de catch. Cela se conclut par un évènement `unhandledrejection` qui reçoit un objet `Cancel`. Comme nous faisons un `.cancel()` sans message, la propriété message est undefined.

Pour résoudre ce cas, il faudrait ajouter un catch. On pourrait également en profiter pour ajouter un toast dans le cas d'une erreur avec la requête.

Cela reviendrait à ajouter le code suivant :
```
.catch((error) => {
  if (!this.$api.isCancel(error)) {
    this.$toast.error(this.$t("Error getting search results."));
  }
});
```
