### ISSUE TITLE
Problème de pagination dans l'affichage des résultats

### ISSUE THREAD

**Issue by mquandalle** [etalab/data.gouv.fr#614]
Sur une recherche avec 3 pages, un lien vers une page 4 est affiché. On tombe sur une erreur en cliquant dessus.

![image](https://user-images.githubusercontent.com/1730702/141685818-5ea54783-4fd7-4c40-b853-27b610a4e5e5.png)

Visible par exemple sur : https://www.data.gouv.fr/fr/datasets/?organization=534fff81a3a7292c64a77e5c&page=3

**Comment by abulte** [comment]
Thanks! Fixed on https://staging.data.gouv.fr/fr/datasets/?organization=534fff81a3a7292c64a77e5c&page=3, should be in production soon.
