### ISSUE TITLE
Masquer/griser le bouton prévisualiser pour les CSV trop lourds

### ISSUE THREAD

**Issue by jonathanfallon** [etalab/data.gouv.fr#615]
## Le problème

La prévisualisation des fichiers trop lourds retourne une erreur dans la modale
![image](https://user-images.githubusercontent.com/1656255/141794365-d03154f3-4685-4bf7-b393-1ea235b4c4c9.png)

Pour éviter ce comportement, il serait possible de masquer ou griser (disabled) le bouton de prévisualisation (visible sur l'image ci-dessous)

![image](https://user-images.githubusercontent.com/1656255/141794267-b2c86086-a1cb-4d62-bcf1-01a989e610ee.png)

**Comment by maudetes** [comment]
Merci du signalement. En effet, il me semble préférable de désactiver le bouton de prévisualisation si la ressource est trop lourde. Est-ce qu'il serait possible d'avoir le lien vers le jeu de données en question?

**Comment by ThomasG77** [comment]
Lien vers la ressource qui fait plantée https://www.data.gouv.fr/fr/datasets/les-donnees-contextuelles-des-intercommunalites-et-autres-structures-territoriales/#resources

L'idéal ne serait pas forcément de griser/masquer mais "streamer" ou de faire un "limit" et limiter la prévisualisation aux n premières lignes. Pas bien identifié où cela serait possible entre les briques https://github.com/etalab/csvapi, https://github.com/opendatateam/udata-tabular-preview/, https://github.com/etalab/csvapi. L'approche peut aussi varier si on est capable de passer la taille du fichier à prévisualiser aux autres briques (mais après risque de couplage plus fort)

**Comment by maudetes** [comment]
A voir ce qu'on veut faire en effet, ça me semble pertinent de n'afficher plutôt que les premières lignes. Mais il y a bien une restriction appliquée sur la taille aujourd'hui, qui doit coincer sur cette ressource.
L'affichage de la prévisualisation est dépendante de [ce code](https://github.com/opendatateam/udata-tabular-preview/blob/ef67aa5fd77819fb1322958ceb23825aa58d8c06/udata_tabular_preview/preview.py#L12), qui prend en compte `content-length` ou la taille déclarée.

**Comment by agarrone** [comment]
Je peux clore @nicolaskempf57 non ?

**Comment by nicolaskempf57** [comment]
Normalement on avait déjà une vérification sur la taille sur l'ancienne préviz. Je vérifie si jamais il n'y a pas un décalage entre la taille max de CSVAPI et celle acceptée pour une previz et je te dis.

**Comment by nicolaskempf57** [comment]
Je confirme qu'on a toujours le problème sur dev avec le meme jdd : https://dev.data.gouv.fr/en/datasets/les-donnees-contextuelles-des-intercommunalites-et-autres-structures-territoriales/

**Comment by nicolaskempf57** [comment]
A PR is done on the infra side to fix this.

**Comment by nicolaskempf57** [comment]
C'est finalisé coté infra
