### ISSUE TITLE
Intégration d'une organisation impossible

### ISSUE THREAD

**Issue by jfmorice** [etalab/data.gouv.fr#62]
Bonjour,
En suivant la procédure indiquée sur [https://doc.data.gouv.fr/faq/integrateur.html](url), je pouvais auparavant afficher les jeu de données d'un territoire ou d'une collectivité.

Ce code me renvoie maintenant l'erreur suivante :

`TypeError
columnNumber: 6395
fileName: "https://www.data.gouv.fr/static/widgets.js"
lineNumber: 1
message: "t.map is not a function"
stack: "loadOrganization/<@https://www.data.gouv.fr/static/widgets.js:1:6395\n"
__proto__: Object { stack: "", … }`

Est-ce que le code aurait changé ? Ou y-a-t-il un problème sur le service ?
Merci

**Comment by abulte** [comment]
Bonjour,

Je viens de tester l'intégration suivante et elle fonctionne correctement pour moi. Quel navigateur utilisez-vous ?

```
<div data-udata-dataset-id="58e53811c751df03df38f42d"></div>
<script src="https://www.data.gouv.fr/static/widgets.js" id="udata" async defer onload="udataScript.loadDatasets()"></script>
```

**Comment by jfmorice** [comment]
Bonjour
Merci pour votre réponse qui m'éclaire sur mon erreur.
L'intégration que vous avez testé fonctionne parfaitement chez moi également.
Cependant il s'agit d'un intégration ponctuelle de jeux de données. Je cherche à afficher les données d'une organisation avec le code

`<div data-udata-organization="IDENTIFIANT DE L’ORGANISATION"></div>
<script src="https://www.data.gouv.fr/static/widgets.js" id="udata" async defer onload="udataScript.loadOrganization()"></script>`

Je dois faire une erreur dans l'identifiant à entrer. J'utilisais auparavant la valeur affichée dans l'url. 
Par exemple:
https://www.data.gouv.fr/fr/organizations/**IDENTIFIANT DE L’ORGANISATION**/
Cela fonctionnait très bien lors de mes premiers tests mais cela n'est plus le cas. J'imagine que je dois me tromper à ce niveau.

La documentation évoque bien ce qu'il faut y placer mais les termes sont assez obscurs pour moi : 
> En remplaçant l’IDENTIFIANT DE L’ORGANISATION par l’identifiant disponible sur sa default dédiée vous devriez voir apparaître sur votre site un cartouche contenant les informations relatives aux jeux de données de cette organisation de la manière suivante : WARNING: il doit manquer qqch ici

Que signifie "default dédiée" ? est ce une coquille ? Le warning qui s'affiche ensuite semble me confirmer qu'il y a un problème...

Qu'en pensez vous ?

**Comment by abulte** [comment]
Effectivement, il y a bien un problème sur l'intégration d'une organisation, j'obtiens la même erreur que vous. Nous allons travailler à la résolution du problème et je vous tiendrai informé.

La documentation est également à clarifier, nous allons aussi nous pencher dessus.

Merci pour votre retour précieux.

**Comment by abulte** [comment]
@jfmorice l'anomalie a été résolue sur notre base de code (https://github.com/opendatateam/udata/pull/1474), le correctif sera appliqué lors de notre prochaine de livraison du site data.gouv.fr que j'espère imminente.
