### ISSUE TITLE
[Meta] Refonte de l'affichage des ressources & ressources communautaire

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#621]
- [x] #579 
- [x] #450

**Comment by nicolaskempf57** [comment]
Je pense qu'on peut sortir https://github.com/etalab/data.gouv.fr/issues/623 de la liste comme il concerne les jeux de données et non les ressources.

**Comment by agarrone** [comment]
Yes c'est une erreur de ma part je pense

**Comment by maudetes** [comment]
Closed by https://github.com/etalab/udata-front/pull/78
