### ISSUE TITLE
Dev : affichage standardisé des cartes et listes jeux de données

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#623]
- [x] Nouveau badge certifié

### Jeu de données

Résultats de recherche Vue :
- [x] Badge certifié à coté du nom
- [x] Suppression du badge autour de l'image
- [x] Carte
- [x] Suppression code legacy
- [x] Lien vers la licence
- [x] Afficher le sigle

Résultats de recherche Jinja :
- [x] Badge certifié à coté du nom
- [x] Suppression du badge autour de l'image
- [x] Carte
- [x] Suppression code legacy
- [x] Lien vers la licence
- [x] Afficher le sigle

### Réutilisation

- [x] Badge certifié à coté du nom
- [x] Suppression du badge autour de l'image
- [x] Carte
- [x] Suppression code legacy

### Organisation

- [x] Badge certifié à coté du nom
- [x] Suppression du badge autour de l'image
- [x] Tuile
- [x] Suppression code legacy

**Comment by nicolaskempf57** [comment]
Retour de review: Problème d'affichage de la liste des datasets sur la page orga

**Comment by maudetes** [comment]
Suggestion de review: Rajouter un élément qui explicite qu'il s'agit d'une carte JDD (et reuse de la même manière). Ex: une icône à côté du titre, un filigrane sur l'image, etc.
