### ISSUE TITLE
panne fonctionnalité récupération de mot de passe?

### ISSUE THREAD

**Issue by mkazmiers** [etalab/data.gouv.fr#63]
Bonjour,

La fonctionnalité de récupération de mot de passe semble down. J'ai fait une demande il y a une heure, sur un compte DataGouv existant ( en @crige-paca.org) et n'ai rien reçu.
De mon côté, spam mailbox checké, filtres anti-spam checké : rien.

C'est comme si le mail n'avait pas été envoyé.

Cordialement,

**Comment by mkazmiers** [comment]
Je ne sais pas si il y a une intervention, mais mail de réinitialisation reçu.
Je ferme.

**Comment by odtvince** [comment]
Non, pas d'intervention particulière, mais il est bien prévu des travaux pour réduire les délais d'envoi du mail, parfois un peu trop long.
