### ISSUE TITLE
Cleaner les formats disponibles

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#632]
Le but est de clarifier et de cleaner les formats disponibles.

Exemple, pour un format détecté `14.08.20.csv`, le remplacer par `csv` et fixer la détection.

Il est aussi important de documenter les formats disponibles dans le formulaire de l'admin.

**Comment by AntoineAugusti** [comment]
Le moissonneur ODS indique actuellement un format de `json` pour les formats JSON et GeoJSON.

https://github.com/opendatateam/udata-ods/blob/168ec81c097ffa06a362aaff977b79317329996b/udata_ods/harvesters.py#L70-L71

Les extensions acceptées pour geojson sont [geojson et json](https://en.wikipedia.org/wiki/GeoJSON) d'après l'usage. Côté @etalab/transport on serait preneur de pouvoir distinguer mieux ces formats car on propose de la visualisation de GeoJSONs dès lors que le format est `geojson`.

Exemple :
- https://transport.data.gouv.fr/datasets/zfe-zone-a-faibles-emissions/ ➡️  possibile de visualiser
- https://transport.data.gouv.fr/datasets/zone-a-faibles-emissions-zfe/ qui est moissoné depuis ODS, pas possible de visualiser

Il parait étonnant d'avoir un même format pour 2 ressources "Export au format json" et "Export au format GeoJSON".

**Comment by maudetes** [comment]
Je consigne ici plusieurs points relatifs à la problématique des formats.

La création de ce ticket s'est fait avant le changement de suggest de tag.
En effet, le suggest se base aujourd'hui sur une liste finie de formats basée sur les extensions autorisés lors d'upload de ressources. Voir [la liste par défaut](https://github.com/opendatateam/udata/blob/fab505fd9159c6a9f63e3cb55f0d6479b7ca91e2/udata/settings.py#L258).

Lors d'une recherche sur la page https://www.data.gouv.fr/fr/datasets/, le filtre de tag retourne donc maintenant des propositions d'extensions autorisées. Voir par exemple https://www.data.gouv.fr/api/1/datasets/suggest/formats/?q=js&size=8.
Ce soucis de détection est donc moins visible qu'avant.

Cependant, si le format est mal détect pour une ressource (ex: 2.csv au lieu de csv), l'erreur sera visible sur la page dataset et ce JDD ne sera donc pas retourné lors d'une recherche avec un filtre sur le format csv.

Si on veut investir pour améliorer la détection, plusieurs possibilités:
- on peut se limiter à la dernière extension seulement ;
- on peut se limiter à la dernière extension, sauf dans les cas particuliers de type .zip, .tar.gz, où on regarde l'avant-dernière seulement ;
- on peut se limiter aux extensions successives ne dépassant pas une taille maximale (ex: 10 chars). C'est arbitraire mais pourrait résoudre une partie des problèmes

Exemples de formats mal détectés:
- 06.20-deliberations-cm-30.06.20-2020-86-jeunesse-dev-social-fixation-part-forfait-frais-scolarite.pdf
- gouv.fr-20210706.json
- gouv.csv
- e.s.csv
- png.pdf
- -site-internet.pdf

**Comment by agarrone** [comment]
Est-ce qu'on peut avoir une idée de ce que ça represente en terme de volume de jeux de données ?

**Comment by maudetes** [comment]
hmm le nombre de datasets avec des ressources qui contiennent des extensions multiples (avec le séparateur `.`) sont de l'ordre de 1% des JDD.

Calculé avec `len([dat for dat in Dataset.objects() if any('.' in res.format for res in dat.resources if res.filetype == 'file' and res.format)])`

**Comment by maudetes** [comment]
[Ci-joint](https://github.com/etalab/data.gouv.fr/files/8523249/formats_alternative.csv) un exemple de traitement des format sur le stock (les ressources ayant un `fs_filename`) avec différentes heuristiques. Seules les ressources détectées différemment sont extraites dans le fichier, et au maximum 10 ressources par JDD.
- `format` est remplie avec le format existant.
- `format_last` garde uniquement la dernière extension.
- `format_last_but_zip` garde uniquement la dernière extension, sauf s'il s'agit d'une extension de compression (limitée à `['zip', 'xz', 'gz', 'rar', '7z', 'tgz', 'tar']` arbitrairement), dans ce cas l'avant dernière extension est conservée.
- `format_last_but_known` ne garde l'avant dernière extension que dans le cas où elle est connue car dans [ALLOWED_RESOURCES_EXTENSIONS](https://github.com/opendatateam/udata/blob/fab505fd9159c6a9f63e3cb55f0d6479b7ca91e2/udata/settings.py#L258).
- `format_last_but_zip_and_known` croise les contraintes des deux détections précédentes.

Je n'ai pas trouvé de solutions génériques (avec lib ou autres) existantes.
Etant donné qu'on envisage de détecter de manière plus intelligente les formats des ressources (locales et distantes) (voir [cette discussion mattermost](https://mattermost.incubateur.net/betagouv/pl/bmcffg8zcfbfzqxmradj9ru6sw)), on peut aussi partir pour la première solution (la plus simple), avec une correction ultérieure lors de l'analyse des ressources?

**Comment by maudetes** [comment]
[Ci-joint](https://github.com/etalab/data.gouv.fr/files/8523249/formats_alternative.csv) un exemple de traitement des format sur le stock (les ressources ayant un `fs_filename`) avec différentes heuristiques. Seules les ressources détectées différemment sont extraites dans le fichier, et au maximum 10 ressources par JDD.
- `format` est remplie avec le format existant.
- `format_last` garde uniquement la dernière extension.
- `format_last_but_zip` garde uniquement la dernière extension, sauf s'il s'agit d'une extension de compression (limitée à `['zip', 'xz', 'gz', 'rar', '7z', 'tgz', 'tar']` arbitrairement), dans ce cas l'avant dernière extension est conservée.
- `format_last_but_known` ne garde l'avant dernière extension que dans le cas où elle est connue car dans [ALLOWED_RESOURCES_EXTENSIONS](https://github.com/opendatateam/udata/blob/fab505fd9159c6a9f63e3cb55f0d6479b7ca91e2/udata/settings.py#L258).
- `format_last_but_zip_and_known` croise les contraintes des deux détections précédentes.

Je n'ai pas trouvé de solutions génériques (avec lib ou autres) existantes.
Etant donné qu'on envisage de détecter de manière plus intelligente les formats des ressources (locales et distantes) (voir [cette discussion mattermost](https://mattermost.incubateur.net/betagouv/pl/bmcffg8zcfbfzqxmradj9ru6sw)), on peut aussi partir pour la première solution (la plus simple), avec une correction ultérieure lors de l'analyse des ressources?

**Comment by abulte** [comment]
> format_last_but_zip_and_known croise les contraintes des deux détections précédentes.

J'aime celle-ci ❤️ 

D'une manière plus générale, même si on détecte ailleurs mieux le type des ressources, ça restera de la responsabilité de udata de voir quoi stocker dans `format`. Ca ne parait donc pas idiot d'investir dans un peu de logique dès maintenant.
