### ISSUE TITLE
Le bouton d'édition des ressources communautaires n'apparaît pas quand pertinent

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#647]
Voir https://mattermost.incubateur.net/betagouv/pl/6rmyoirrfjrzpquyq4xxa1ufzc

L'affichage du bouton est basé sur `can_edit` qui dépend du producteur du jeu de données et non pas de la ressource communautaire en fonction

**Comment by nicolaskempf57** [comment]
Pour corriger https://github.com/etalab/data.gouv.fr/issues/684, je suis passé sur l'utilisation de l'API pour accéder aux ressources communautaires. Y-a-t-il une possibilité pour récupérer les droits d'édition de l'utilisateur via API ou faut-il reprendre le calcul des droits coté JS ?
