### ISSUE TITLE
Incohérence de la timeline d'une organisation

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#65]
Comme c'est un flux d'activité, je m'attends à un ordre chronologique.
Ce n'est apparemment pas le cas !

<img width="1156" alt="capture d ecran 2018-03-03 a 22 24 03" src="https://user-images.githubusercontent.com/1231232/36939454-af694c7e-1f31-11e8-8f16-cf79259666fb.png">

**Comment by jdesboeufs** [comment]
Screenshot à jour :
<img width="1104" alt="capture d ecran 2018-03-07 a 15 38 20" src="https://user-images.githubusercontent.com/1231232/37098236-b29a8edc-221d-11e8-8db6-4c0b8c1486c3.png">

**Comment by taniki** [comment]
With a different user. Same without credentials (or unlogged)

![screen shot 2018-03-07 at 15 45 02](https://user-images.githubusercontent.com/27315/37098632-a8fdc0aa-221e-11e8-90ea-10749f2d2363.png)
