### ISSUE TITLE
Lorsqu'une API est proposée à partir d'api.gouv.fr, l'image est déformée

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#661]
Lorsq'une API d'un jeu de données est proposée via le référencement de api.gouv.fr, l'image du producteur est déformée.

api.gouv.fr accepte des logos dans des formats autres que le carré, nous on force un carré https://github.com/etalab/udata-front/blob/master/udata_front/theme/gouvfr/templates/api/card.html

Cf. https://www.data.gouv.fr/fr/datasets/annuaire-de-leducation

![Capture d’écran 2022-01-05 à 12 07 54](https://user-images.githubusercontent.com/51122275/148208066-8f013dc3-1a38-4e5f-8caf-857b765327ac.jpg)

**Comment by agarrone** [comment]
Wont fix for now most images are squared anyway

**Comment by maudetes** [comment]
(happens also on https://www.data.gouv.fr/fr/datasets/boamp/)
![image](https://user-images.githubusercontent.com/28541902/158223379-c14ad821-8d07-4d1d-ace6-65c6419ecd44.png)
