### ISSUE TITLE
Autoriser l'upload de fichiers `parquet` et `jsonl`

### ISSUE THREAD

**Issue by Timost** [etalab/data.gouv.fr#665]
Bonjour,

Tout d'abord merci pour data.gouv 👍 

## L’amélioration que vous avez en tête
En essayant d'uploader un fichier [JSONL](https://jsonlines.org/) sur data.gouv je me suis rendu compte que ce n'était pas autorisé.
En creusant un peu, j'ai l'impression que la liste des extensions valides est configurable, et que la liste actuelle peut être récupérée en appelant: https://www.data.gouv.fr/api/1/datasets/extensions/

La Mission Data de la Haute Autorité de Santé aurait besoin de pouvoir uploader des fichiers JSONL et parquet pour ces projets:
- https://gitlab.com/has-sante/public/alpha/scope-sante-data
- https://gitlab.com/has-sante/public/alpha/open_snds

## Les alternatives possibles
Je vois dans le cataogue qu'il y'a des fichiers avec d'autres extensions que celles actuellement acceptées, est-ce qu'il y a d'autres moyens d'uploader du parquet/jsonl actuellement ?

Merci pour votre aide ! 🙏

**Comment by Timost** [comment]
Bonjour,

Si possible ça nous aiderait beaucoup de rajouter `jsonl` et `parquet` dans les extensions supportées 🙏 
Nous n'avons pas de stockage public pour le moment.

Merci !

**Comment by Timost** [comment]
Bonjour,

Si c'est trop compliqué pour vous de le faire, dîtes le moi, Je regarderais pour mettre en place une resource distante.

Merci.

**Comment by maudetes** [comment]
Bonjour,

Nous allons effectuer l'ajout de `parquet` et `jsonl` à la liste des formats autorisés prochainement.

**Comment by Timost** [comment]
Super ! Merci beaucoup ! 🙏

**Comment by abulte** [comment]
Déployé sur demo.data.gouv.fr

**Comment by Timost** [comment]
Merci beaucoup ! ❤️

**Comment by abulte** [comment]
@Timost encore un peu de patience pour la mise en production :-)
