### ISSUE TITLE
Dernière ligne de la description coupée

### ISSUE THREAD

**Issue by nicolaskempf57** [etalab/data.gouv.fr#667]
Voir https://www.data.gouv.fr/fr/datasets/base-des-lieux-et-equipements-culturels-basilic/.

**Comment by restuccia** [comment]
Le problème se manifeste chez moi également, mais je n'arrive pas à le reproduire de manière systématique

e.g. https://www.data.gouv.fr/fr/datasets/transition-s-2050-quatre-scenarios-pour-atteindre-la-neutralite-carbone/#description

![Capture d’écran 2022-01-31 à 16 56 35](https://user-images.githubusercontent.com/51122275/151827845-2a43363e-3a77-4ad2-ba9e-8dafc19fcdcc.jpg)
