### ISSUE TITLE
Pouvoir changer l’adresse e-mail associée à un compte

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#67]
Bonjour,

Notre accés admin sur data.gouv.fr est basé sur une ancienne adresse (contact[at]geob..).

Je n'ai pas trouvé comment changer l'adresse mail (le mot de passe ok), est-ce qu'il vous est possible de faire le changement "manuellement"
Est-ce qu'il faut recréer un autre compte contact[at]ideo ave transfert des tout les privilèges.. ?

D'avance Merci,

**Comment by eric8514** [comment]
Salut, 
j'aimerais savoir comment je peux changer mon adresse Github?
Par exemple, le mien est eric8514.github.io et j'aimerais qu'il soit ericonguene.github.io

**Comment by abulte** [comment]
Bonjour @eric8514, sauf erreur de ma part il faut voir ça avec Github, rien à voir avec data.gouv.fr.

**Comment by eric8514** [comment]
Ok merci pour l'information .

**Comment by abulte** [comment]
Closing this in favour of duplicate https://github.com/opendatateam/udata/issues/1589
