### ISSUE TITLE
Investiguer les cas particuliers étranges sur le nouveau moteur de recherche

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#674]
Voir les retours remontés ici: https://www.notion.so/apigouv/Moteur-de-recherche-V2-3f34052e20594cfaaf326b42da55c8d9

Voir les résultats sur Orga et Reuse remontés sur https://github.com/etalab/data.gouv.fr/issues/656

**Comment by maudetes** [comment]
Tous les cas particuliers relevés ont été traités dans les PR liées ci-dessus.
