### ISSUE TITLE
Avoir une notion de hiérarchie dans les organisations

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#68]
Bonjour,

J'aimerais beaucoup qu'une notion de hiérarchie soit possible pour les organisations. Ce cas d'usage arrive souvent dans les ministères qui comportent plusieurs directions.

Il serait (peut-être) souhaitable d'avoir une organisation par direction, rattachée à un ministère par exemple.

Merci

**Comment by odtvince** [comment]
Il serait effectivement souhaitable d'avoir une organisation par direction (voire dans certains cas des organisations encore plus granulaires).

C'est parfaitement faisable aujourd'hui et déjà mis en œuvre dans certains ministères sans nécessairement demander de hiérarchie dans les organisations.

Nous continuons néanmoins à réfléchir au sujet.

**Comment by AntoineAugusti** [comment]
> C'est parfaitement faisable aujourd'hui et déjà mis en œuvre dans certains ministères sans nécessairement demander de hiérarchie dans les organisations.

Je peux avoir un exemple ? Ceci veut-il dire qu'il y a des organisations qui sont des directions de ministères mais qu'il n'est pas possible de voir à quel ministère elles sont rattachées sur data.gouv.fr ?

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
