### ISSUE TITLE
Améliorer le processus de publication en accompagnant à choisir la bonne licence

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#683]
Lors de la publication d'un nouveau jeu de données, à l'utilisateur est demandé de choisir une licence. Néanmoins, aucune information sur quelle licence choisir est présentée, et plusieurs licences sont proposées, même certaines qui ne sont pas autorisées pour les administrations publiques.

![Capture d’écran 2022-01-26 à 11 03 05](https://user-images.githubusercontent.com/51122275/151143188-ef852393-254c-4744-947b-8f1e83095e5a.jpg)

### Je propose des quick-wins :

- Supprimer la Licence Ouverte parmi les licences proposées lors de la publication (car il y a la LO 2.0) ;
- Supprimer les "Other" ;
- Mettre la LO2.0 par défaut (et pas "Licence not specified") ;
- Ajouter un lien vers https://www.data.gouv.fr/fr/pages/legal/licences/ ;
- Changer le texte de l'infobulle (et le traduire :) ), e.g. "La licence de réutilisation des données. La Licence Ouverte 2.0 est conseillée".

---

En lien avec #114 où des meilleures solutions sont proposées

**Comment by agarrone** [comment]
Traité en partie par #114 sera traité plus en détail dans le futur parcours.
