### ISSUE TITLE
Envoyer des e-mails aux producteurs pour leur demander de mettre à jour leurs données

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#69]
Bonjour,

Lors de formations aux portail databfc, des utlisateurs finaux nous ont demandé si le portail national pourrait se doter d'un reminder par mail pour rappeler aux comptes dépositaires de mettre à jour leurs données.
Ex : dépots de data MArché publics avec une fréquence annuelle.
La plateforme envoie qq jours avant la date anniverisaire un petit courriel au compte pour lui sugérer de mettre à jour sa données (avec un lien qui va bien amenant directement à la donnée ouvert à MAJ.

Ca serait possible pour vous ?

D'avance Merci

**Comment by abulte** [comment]
Bonjour,

Cette suggestion est effectivement intéressante, merci. Nous la prendrons en compte lors de l'élaboration de notre roadmap.

**Comment by agarrone** [comment]
Je clos cette issue pour épurer le backlog mais je la garde en note pour le chantier correspondant.
