### ISSUE TITLE
Creation user/orga/moissonnage par api

### ISSUE THREAD

**Issue by mkazmiers** [etalab/data.gouv.fr#70]
Bonjour,

Suite à des discussions engagées avec data.gouv pour la plateforme idgo/datasud, à propos du moissonnage du ckan datasud par l'udata datagouv (et pour garder trace de la discussion ici :)), 

est-il prévu de pouvoir créer des users, des organisations et renseigner des endpoint de moissonnage par push dans l'API uData ?

Merci

**Comment by odtvince** [comment]
Bonjour Mathieu,

https://www.data.gouv.fr/fr/apidoc/#!/users/create_user
https://www.data.gouv.fr/fr/apidoc/#!/organizations/create_organization
https://www.data.gouv.fr/fr/apidoc/#!/harvest/create_harvest_source

Il reste potentiellement une question de droits à gérer sur le premier, le deux suivants sont utilisables par n'importe quel utilisateur de l'API.

**Comment by odtvince** [comment]
> Il faudrait aussi inclure une mécanique qui évite de créer des organisations déjà existantes...Est-ce que l'API ou datagouv gère ça d'une manière ou d'une autre ?

Non, c'est aujourd'hui un processus humain. Je ne suis pas sur que ce soit  automatisable  d'une  quelconque  façon. On est intéressés si vous avez des idées pour faire ça en pratique.

**Comment by jdesboeufs** [comment]
On pourrait entrer le SIRENE d’une structure et rendre ça unique ?

**Comment by mkazmiers** [comment]
c'est envisageable chez nous. On peut demander un sirene de notre côté pour conditionner le moissonnage ou non vers data.gouv. Et le moissonnage apparie les organisations avec le même SIRENE.

Le delta, qui concerne peut-être 5% des dataset, ça va être pour un certain nombre de jeux de données multi-producteurs où la seule solution actuelle chez nous est de créer une organisation "fictive" donc sans code sirene ; ex. groupements de commande d'ortho où il y a IGN, départements, région, idg...ou une organisation "INSEE DREAL" qui a coproduit un jeu de données stats par ex. Pour celles-là, le sirene est pas optimale.

**Comment by odtvince** [comment]
Un dédoublonnage automatique sur le SIREN, qui pourrait peut-être fonctionner pour l'Etat déconcentré, ne fonctionne pas du tout pour l'Etat central, où la maille SIREN (en gros la maille ministère) est beaucoup beaucoup plus large que ce que nous visons comme maille optimale (la direction, voire le bureau).

Ce n'est donc pas une option pour automatiser le dédoublonnement sur data.gouv.fr.

**Comment by mkazmiers** [comment]
Je vois que l'issue a été ajouté à la feuille de route récemment !
:+1: 
Merci !

**Comment by ChrisBarriere** [comment]
> Bonjour Mathieu,
> 
> https://www.data.gouv.fr/fr/apidoc/#!/users/create_user
> https://www.data.gouv.fr/fr/apidoc/#!/organizations/create_organization
> https://www.data.gouv.fr/fr/apidoc/#!/harvest/create_harvest_source
> 
> Il reste potentiellement une question de droits à gérer sur le premier, le deux suivants sont utilisables par n'importe quel utilisateur de l'API.

Concernant, la possibilité de créer un utilisateur via l'api (https://www.data.gouv.fr/fr/apidoc/#!/users/create_user), ce n'est pas fonctionnel. Pour deux raisons:
1) L'attribut email n'est pas utilisé par l'opération API alors qu'il est obligatoire pour un enregistrement de l'utilisateur dans Mongo => on reçoit une erreur 500 "Internal server error"
2) pas d'attribution de mot de passe à l'utilisateur => le compte ne peut pas être utilisé

**Comment by abulte** [comment]
Je ferme pour l'instant, pas de solution complètement intégrée à court terme et datasud est en prod ;-)
