### ISSUE TITLE
Via l'API, lorsque l'on met à jour une ressource, son .title est modifié

### ISSUE THREAD

**Issue by ColinMaudry** [etalab/data.gouv.fr#706]
## Description du bug

Lorsque je mets à jour le fichier d'une ressource via l'API, le `title` de la ressource est modifié avec une chaîne de caractères dérivée du nom du fichier (les "_" sont remplacés par des "-").

## Comment reproduire le bug

```python
    response = requests.post(url=f'https://www.data.gouv.fr/api/1/datasets/{dataset_id}/resources/{resource_id}/upload',
                             headers={'X-API-KEY': api_key},
                             files={'file': ('etablissements_inscrits.csv', df.to_csv())})
```

Le `title` de ma ressource devient 'etablissements-inscrits.csv'.

## Comportement attendu

Je m'attends à ce que seuls l'URL de téléchargement, le contenu de ma ressource, sa date de mise à jour et son empreinte soient modifiés. Pas son `title`.

**Comment by maudetes** [comment]
Changement le comportement risque de casser des scripts qui se basent sur cette 'feature', notamment pour les données Covid. On préfère donc faire un update ensuite pour réassigner le titre comme voulu.

**Comment by maudetes** [comment]
Remonté à nouveau par https://support.etalab.gouv.fr/#ticket/zoom/40701
