### ISSUE TITLE
Données différentes entre dump et API

### ISSUE THREAD

**Issue by pierredittgen** [etalab/data.gouv.fr#71]
Bonjour,

Je m'interroge sur la meilleure manière de récupérer les données statistiques sur jeux de données (datasets) disponible sur data.gouv.fr. Je n'obtiens pas les même résultats en utilisant 
- le dump : https://www.data.gouv.fr/datasets.csv
- l'API : https://www.data.gouv.fr/api/1/datasets/?sort=-created&organization=id (en interrogeant l'URL une fois par identifiant d'organisation obtenu par l'URL https://www.data.gouv.fr/organizations.csv)

En essayant de récupérer le nombre de datasets par organisation, j'obtiens des résultats proches mais différents en fonction de la méthode utilisée. Cf, fichiers joints

[datasets_api_stats.txt](https://github.com/etalab/data.gouv.fr/files/2098494/datasets_api_stats.txt)
[datasets_dump_stats.txt](https://github.com/etalab/data.gouv.fr/files/2098495/datasets_dump_stats.txt)

Pourriez-vous m'indiquer la raison de ces différences afin que je puisse choisir l'une ou l'autre des méthodes en toute connaissance de cause.

Bien à vous
Pierre Dittgen

**Comment by noirbizarre** [comment]
Après études de vos fichiers, il apparaît que vous avez simplement utilisé 2 sources de dates différentes.
Votre CSV date d'avant le 12 juin tandis que vos appels d'API datent d'après.
En prenant l’exemple de cette organisation https://www.data.gouv.fr/fr/organizations/55263369c751df702faec475/
, votre comptage par l'API fait apparaitre 3 jeux de données tandis que celui par le CSV en fait apparaitre 27. Vous pouvez voir sur [le tableau de bord de cette organisation](https://www.data.gouv.fr/fr/organizations/55263369c751df702faec475/#dashboard) qu'il y a bien eu une suppression de 24 jeux de données le 12 juin et que le compte de jeux de données est bien passé de 27 à 3.

Les données changent en permanence au fil des moissonnages, des publications par les producteurs ou des suppressions. Malheureusement, nous ne sommes pas en capacité de garantir des résultats identique à 2 instants différents car ces informations ne sont pas générés à date fixes mais bien à la demande dans les deux cas.
D'une manière générale, la nuit il y a les moissonnages qui passent et donc le probabilité de variation est beaucoup plus élevée à ce moment là.

Le choix entre CSV et API dépend seulement de votre usage étant donné que techniquement, derrière, c'est exactement le même code qui est exécuté par les deux.

Bien à vous.
