### ISSUE TITLE
Définir les critères score qualité

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#712]
- La dimension de popularité sera traité dans la prochaine thématique.
- Dans un soucis d’efficacité et pour pouvoir livrer rapidement **les premières itérations porterons sur les métadonnées des jeux de données.**
- L’approche retenue est d’**établir un score qui peut s’enrichir au fur et à mesure de nouveaux critères en fonction des métadonnées retenues pour effectuer le calcul**

Voir : https://www.notion.so/apigouv/Score-qualit-des-donn-es-sorties-de-l-atelier-e9fd476e523646fb9e9d0908790a0f14
ainsi que : https://www.notion.so/apigouv/Quels-crit-res-pour-un-jeux-de-donn-es-de-qualit-e0e22a7c2f7f469f9cca9833c1579b0b

**Comment by agarrone** [comment]
Voir notamment ici : https://www.notion.so/apigouv/Indice-de-score-qualit-des-jeux-de-donn-es-e226722370114093898f437808cfc551 (surtout la fin de page)

**Comment by agarrone** [comment]
Les critères sont disponibles ici : https://www.notion.so/apigouv/Indice-de-score-qualit-des-jeux-de-donn-es-e226722370114093898f437808cfc551

**Comment by maudetes** [comment]
A tester ensuite :)
