### ISSUE TITLE
Définir les indicateurs d'impact du label qualité

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#713]
Voir https://www.notion.so/apigouv/Indicateurs-th-matique-qualit-67c7a81d9e3a423cb5c809631fea60f3

**Comment by agarrone** [comment]
Cet epic sera mesuré par des tests qualitatifs pour répondre aux deux problématiques identifiées : 
    - Les réutilisateurs identifient facilement les jeux de données de qualité
    - Les producteurs sont davantage incités et accompagné à améliorer la qualité de leurs données

**Comment by maudetes** [comment]
Voir aussi : https://www.notion.so/apigouv/Indicateurs-th-matique-qualit-67c7a81d9e3a423cb5c809631fea60f3
