### ISSUE TITLE
Confronter les critères du score qualité avec usagers

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#715]
- [x] Exporter le détail du score qualité actuel sur les jeux de données
- [ ] Tester auprès des usagers

**Comment by maudetes** [comment]
[Ci-joint, un export des métriques de qualité utilisées pour les datasets](https://github.com/etalab/data.gouv.fr/files/8688240/quality.csv).
L'export est basé sur un dump local de la prod datant de septembre, donc ne représente pas à 100% la prod mais donne une bonne idée du paysage.

Les différents champs sont calculés [ici](https://github.com/opendatateam/udata/blob/0ad78b3b8ee0da428ec7bedf2bc8e2e8160e416f/udata/core/dataset/models.py#L590).
Le calcul du score est calculé [juste en dessous](https://github.com/opendatateam/udata/blob/0ad78b3b8ee0da428ec7bedf2bc8e2e8160e416f/udata/core/dataset/models.py#L627) à partir de ces critères.

**Comment by agarrone** [comment]
Thanks !
