### ISSUE TITLE
Indicateur « nb_uniq_visitors »

### ISSUE THREAD

**Issue by pierredittgen** [etalab/data.gouv.fr#72]
Bonjour,

Je télécharge les informations de jeux de données via l'URL https://www.data.gouv.fr/datasets.csv
J'accède ainsi à un certain nombre d'indicateurs par jeu de données :
- metric.discussions
- metric.followers
- metric.reuses
- metric.issues
- metric.views

Par contre, je ne trouve pas l'indicateur du *nombre unique de visiteurs* présent lorsque l'on récupère les informations sur un dataset via l'API JSON (propriété `nb_uniq_visitors`)

Est-ce une métrique qui n'est disponible que par l'API ou est-elle présente sous une autre forme dans le dump CSV ?

Merci d'avance pour votre éclairage
Pierre Dittgen

**Comment by abulte** [comment]
Bonjour,

`nb_uniq_visitors` n'est pas fiable et déprécié. Pour les statistiques de consultation nous utilisons `views`. Pour des statistiques plus précises vous pouvez consulter https://stats.data.gouv.fr.
