### ISSUE TITLE
Définir les indicateurs d'impact sur la qualité des métadonnées

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#723]
Voir https://www.notion.so/apigouv/Indicateurs-th-matique-qualit-67c7a81d9e3a423cb5c809631fea60f3

**Comment by agarrone** [comment]
Cet EPIC sera mesuré à l'aune de l'évolution du score qualité (complétude des métadonnées des jeux de données)

**Comment by maudetes** [comment]
Voir aussi: https://www.notion.so/apigouv/Indicateurs-th-matique-qualit-67c7a81d9e3a423cb5c809631fea60f3
