### ISSUE TITLE
Définir les indicateurs d'impact de la previz

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#732]
Voir https://www.notion.so/apigouv/Indicateurs-th-matique-qualit-67c7a81d9e3a423cb5c809631fea60f3

**Comment by agarrone** [comment]
Cet epic sera mesuré par le temps moyen passé sur les prévisualisations. 
A condition que sa mesure soit possible @quaxsze ? 
Est-on en mesure de savoir aujourd'hui quelle part du catalogue est prévisualisable aujourd'hui ?

**Comment by maudetes** [comment]
Concernant la part du catalogue prévisualisable, pas de soucis sur une évaluation à date.

Voir https://www.notion.so/apigouv/Indicateurs-th-matique-qualit-67c7a81d9e3a423cb5c809631fea60f3.
