### ISSUE TITLE
Clarifier ce qu'on affiche sur la modale schéma

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#735]
A réfléchir notamment autour des travaux sur la modale de previz: https://github.com/etalab/data.gouv.fr/issues/729

**Comment by johanricher** [comment]
@agarrone m'a demandé mon avis que je copie ici :)

Je pense qu'il y a différentes façons d'améliorer l'intégration des éléments liés aux schémas dans datagouv (autant les informations que les actions).

![image](https://user-images.githubusercontent.com/10212787/170318546-d35248ab-39d3-4891-ab22-f65a43ab9ada.png)

Dans la réflexion sur cette modale je sépare les infos des actions. Certaines infos liées au schéma comme son nom (et un lien vers sa doc) ont pour moi vocation à apparaître dans les "détails de la ressource", ce qui les normaliserait au même titre que d'autres métadonnées :

![image](https://user-images.githubusercontent.com/10212787/170318075-c9e58dd9-1e88-4535-a436-2f868a1a3eaa.png)

L'action "Valider la ressource" qui est dans la modale est la seule chose qui mériterait selon moi d'être mise en avant car utile d'un point de vue utilisateur des données, et à ce titre devrait même remplacer le bouton de la modale "Voir le schéma" (qui ne servirait plus à rien si ces infos sont déplacées dans les détails de la ressource).

(le wording pourrait être repensé à cette occasion car "valider" est ambigu hors du contexte, peut-être quelque chose comme "Voir les erreurs")

Pour moi le bouton de "validation" a vocation à être remplacé par un badge qui indique la validité de la ressource (+ lien vers rapport de validation) mais ça c'est une implé à plus long terme je suppose. :wink: 

La dernière action "Voir les jeux de données associés à ce schéma" n'est plus utile à mon sens puisqu'il est désormais possible de faire une recherche par schéma cf. #610.

**Comment by agarrone** [comment]
Merci bcp !

**Comment by agarrone** [comment]
![Image](https://user-images.githubusercontent.com/60264344/200844691-739fba59-7aa6-45f5-9691-6e959822aedf.png)

**Comment by agarrone** [comment]
![Image](https://user-images.githubusercontent.com/60264344/200845077-d3668ad8-cceb-4ed0-a93e-5ce220cb7d0f.png)

**Comment by johanricher** [comment]
Trop chouette !

![image](https://user-images.githubusercontent.com/10212787/200852509-abbae26e-136e-4206-8d2b-fcb475a3018c.png) Le badge validité est-il cliquable ?

![image](https://user-images.githubusercontent.com/10212787/200852583-5d02619c-08b3-42d0-afe7-7ee9690ab246.png) A quoi sert ce bouton ?
