### ISSUE TITLE
Bandeau moissonage n'apparait pas sur les jeux  qui proviennent de DCAT

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#738]
Le fait de savoir si un JDD est moissonné se base sur la valeur extra `harvest:remote_url`.
Aujourd'hui, les moissonages ODS et CKAN remplissent cet extra (voir https://github.com/opendatateam/udata-ckan/pull/103/files), mais pas le moisonneur DCAT.

**Comment by quaxsze** [comment]
Après recherche, nous n'avons pas l'information de l'URL, à part pour quelques centaines de JJD qui ont cette URL dans leur `identifier`. Il faut soit demander aux producteurs de remplir les bons champs avec, soit moissonner de nouveaux champs afin d'avoir plus d'informations.

**Comment by maudetes** [comment]
Sera traité avec https://github.com/etalab/data.gouv.fr/issues/738.
