### ISSUE TITLE
Traduction du lien vers la page "suivi"

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#74]
![screenshot from 2018-06-16 00-53-53](https://user-images.githubusercontent.com/27315/41492521-e299ca72-70ff-11e8-9450-7871fa158f63.png)

**Comment by bboulesteix** [comment]
Je peux m’en occuper @taniki mais je ne suis pas certain de savoir comment rajouter une clef (aussi appelée _locale_ parfois) dans [Crowdin](https://crowdin.com). Est-ce qu’il suffit d’ajouter quelques lignes dans le fichier [gouvfr.po](https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/theme/translations/fr/LC_MESSAGES/gouvfr.po) ? Ou rien à voir ?

Les lignes que je pensais ajouter :

```
#: __init__.py:46
msgid "Tracking and privacy"
msgstr "Politique de confidentialité"
```

Mais je ne suis pas certain de comprendre à quoi le 46 renvoie, dans `#: __init__.py:46`. 🤔

**Comment by taniki** [comment]
C'est le numéro de ligne où l'occurence apparait

**Comment by bboulesteix** [comment]
D’accord, merci pour ta réponse. Si j’ai bien suivi, le simple fait de rajouter les lignes suivantes dans `gouvfr.po` permet d’ajouter une traduction pour `Tracking and privacy`. C’est bien ça ?

Voici les lignes dont je parle :

```
#: __init__.py:45
msgid "Tracking and privacy"
msgstr "Politique de confidentialité"
```

Je tire le `45` de ce fichier : [udata-gouvfr/udata_gouvfr/theme/__init__.py](https://github.com/etalab/udata-gouvfr/blob/5cd3736398ab1d9b9246c8f5aa025f554f65543e/udata_gouvfr/theme/__init__.py#L45). Je crois qu’il y a un décalage d’une unité entre les lignes auxquelles apparaissent les clef dans `__init__.py` et leur équivalent dans `gouvfr.po`.

**Comment by abulte** [comment]
Les `.po` sont normalement générés et envoyés à Crowdin, et les traductions descendent de là-bas. On intervient pas directement dans les fichiers de trad sur le dépôt.

**Comment by abulte** [comment]
Bref, si la chaine à traduire n'est pas dans Crowing on peut regarder ça ensemble @bboulesteix

**Comment by bboulesteix** [comment]
Merci pour ta réponse @abulte. J’ai vu avec @taniki, qui va ajouter la clef qui va bien dans Crowdin.

**Comment by bboulesteix** [comment]
\o/
