### ISSUE TITLE
Ne pas effacer les extras quand on en rajoute de nouveaux

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/data.gouv.fr#744]
## L’amélioration que vous avez en tête

Actuellement, l'ajout d'un extra sur une ressource (mais je pense que c'est la même chose sur les autres objets data.gouv) oblige à récupérer les extras stockés en base pour ne pas les effacer.

Par exemple, une ressource contient en base l'extra suivant : 
```
extras: {
  "proprieteA": "test"
}
```

Si je veux ajouter un autre extras (par exemple `proprieteB`) il faut que je récupère au préalable les extras actuels pour ne pas les effacer. Donc que je fasse un update avec : 

```
extras: {
  "proprieteA": "test",
  "proprieteB": "test2"
}
```

Si je ne fais que : 
```
extras: {
  "proprieteB": "test2"
}
```
La `proprieteA` sera effacée de la base.

Ce comportement est sujet à des erreurs et des effacements de données involontaires. Je pense donc que ça serait mieux que le put sur les extras soit un `append` plutôt qu'un `replace` 

## Les alternatives possibles

Faire sans car ça marche quand même si on fait attention ;)

**Comment by agarrone** [comment]
La route dédié extra a été ajoutée pour faciliter la màj de l'extra
