### ISSUE TITLE
[Meta] Modifier les filtres de la recherche des jeux de données

### ISSUE THREAD

**Issue by nicolaskempf57** [etalab/data.gouv.fr#748]
- [ ] #774
- [ ] #775
- [ ] https://github.com/etalab/data.gouv.fr/issues/347
- [ ] https://github.com/etalab/data.gouv.fr/issues/610

Voir https://github.com/etalab/data.gouv.fr/issues/260

**Comment by maudetes** [comment]
Stats d'utilisations des différents filtres sur la page `/fr/datasets` sur une période de 10 jours sur dataweb-05:
* tag: 15621
* format: 6621
* license: 3074
* organization: 5503
* temporal_coverage: 16
* geozone: 5346
* granularity: 3226

La requête utilisée est la suivante: `zgrep -Eh "GET /fr/datasets[^ ]*license=" /var/log/nginx/www.data.gouv.fr.access.log.1[0-9].gz | wc -l`

**Comment by agarrone** [comment]
Really puzzling ...
