### ISSUE TITLE
Ressources : date de mise à jour antérieure à la date de création

### ISSUE THREAD

**Issue by pierredittgen** [etalab/data.gouv.fr#75]
Bonjour,

J'ai téléchargé les données de ressources via l'URL https://www.data.gouv.fr/resources.csv.
Je constate que pour quelques ressources (notamment pour l'organisation "BORDEAUX METROPOLE" 534fff64a3a7292c64a77d6f) l'horodatage présent dans la colonne "created_at" est postérieure à l'horodatage présent dans la colonne "modified".

Est-ce dû à une mauvaise récupération des données ou à des données erronées dans la base datagouv ? Vaut-il mieux utiliser les informations d'horodatage au niveau des jeux de données (datasets) ?

Merci d'avance pour votre éclairage
Bien à vous
Pierre Dittgen

**Comment by AntoineAugusti** [comment]
Peut-être similaire à #171

**Comment by agarrone** [comment]
Sera traité dans cette issue : https://github.com/etalab/data.gouv.fr/issues/720
