### ISSUE TITLE
Le bouton "copy permalink to clipboard" ne fonctionne pas

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#755]
Dans les ressources communautaires, il y a bouton pour copier le permalien dans le presse-papier mais cela ne semble pas fonctionner (avec firefox).

**Comment by maudetes** [comment]
Thank you for the feedback! This button should disappear with https://github.com/etalab/udata-front/pull/78.

**Comment by maudetes** [comment]
Closed by https://github.com/etalab/udata-front/pull/78.
