### ISSUE TITLE
Afficher 21 articles au lieu de 20 sur data.gouv.fr/posts

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#756]

**Comment by nicolaskempf57** [comment]
Ce choix est déjà géré par Udata, il suffit que l'on définisse `POST_DEFAULT_PAGINATION` dans nos `udata.cfg`. On peut mettre à jour la valeur par défaut si l'on souhaite également.

**Comment by maudetes** [comment]
Fait dans nos configurations `udata.cfg` seulement.
