### ISSUE TITLE
DCAT: Supporter les ressources sur la métadonnée `dcat:theme`

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#765]
Aujourd'hui, seuls les labels sont supportés dans `dcat:theme` et non pas les ressources

**Comment by juliettefabre** [comment]
Je crois que c'est également le cas pour la balise dct:keyword.

**Comment by maudetes** [comment]
Il semble qu'il ne soit simplement pas possible de récupérer une valeur littérale d'un noeud resource.
En effet, [l'exemple de catalogue geonetwork](https://github.com/opendatateam/udata/blob/master/udata/harvest/tests/dcat/geonetwork.xml) n'est pas un rdf valide à cause des balises `dcat:theme`. Les balises avec attribut `rdf:resources` ne sont pas compatibles avec un contenu littéral.

Concernant la balise `dcat:keyword`, elle est en effet faite pour supporter des littérales uniquement, à la distinction de la balise `dcat:theme`. Voir les discussions menées sur [cette issue](https://github.com/w3c/dxwg/issues/1153), et en particulier [ce commentaire](https://github.com/w3c/dxwg/issues/1153#issuecomment-549738194).
Je propose donc de garder le support de keyword uniquement pour l'instant. On pourra rouvrir ce ticket dans le cas d'un exemple d'un `dcat:theme` utilisé avec [l'un des usages recommandés](https://w3c.github.io/dxwg/dcat/#Property:catalog_themes).

Intéressée pour un avis là-dessus @abulte

**Comment by abulte** [comment]
Très clair @maudetes, merci ! Agreed.

Producteur à prévenir et idéalement lien vers cette issue dans notre doc geonetwork.

Par ailleurs, j'ai l'honneur de te remettre mon badge DCAT 🎖️ 

![Star](https://user-images.githubusercontent.com/119625/158998375-18676eb8-1fac-4409-b882-f90f14469f4f.png)

**Comment by juliettefabre** [comment]
Mais alors comment préciser l'URI d'un mot-clé dans un thésaurus ?
Le RDF suivant est valide me semble-t-il (d'après le validateur RDF) : <dcat:theme rdf:resource="http://inspire.ec.europa.eu/theme/ef"/>mais renvoie une erreur au moissonnage par data.gouv. 
Est-ce que cette écriture pourrait être supportée ?

**Comment by maudetes** [comment]
Il n'est malheureusement pas possible de préciser l'URI d'un mot clé aujourd'hui sur data.gouv.fr.
Seul le label est supporté (de préférence en utilisant les mots clés).
Cette notion d'URI pour un mot clé n'existant pas sur data.gouv.fr, même si nous supportions cette écriture, nous ne conserverions que le label du thème et non pas son URI de notre côté.

**Comment by juliettefabre** [comment]
OK merci !
