### ISSUE TITLE
Mon compte semble HS pour déposer de la data

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#77]
Bonjour,

J'ai souhaité déposer une données avec mon compte, et l'interface "plante" cf printscreen.
![erreur_pk_user_adminideo_18_07_2018](https://user-images.githubusercontent.com/7600693/42888053-ab501726-8aa7-11e8-9ae6-968f2c0a659f.jpg)

![erreur_pk_user_adminideo_18_07_2018_v2](https://user-images.githubusercontent.com/7600693/42888276-314e921c-8aa8-11e8-88ed-30a5955e47af.jpg)

Pourriez vous m'indiquer, voir corriger pour que je puisse déposer une data.

D'avance Merci,

**Comment by abulte** [comment]
Bonjour,

Il s'agit d'une erreur temporaire. Pouvez-vous recharger la page et tester à nouveau ?

**Comment by jerbou** [comment]
OK, j''ai testé sur un autre navigateur et ca marche.

**Comment by jerbou** [comment]
Rebonjour,

Pourriez vous rouvrir le ticket, je retenterai de me connecter plus tard.

Les codes erreurs sont différents au précédent.
![Uploading erreur_pk_user_adminideo_18_07_2018_18h21.jpg…]()

Pour info, j'était sur chrome Version 67.0.3396.99 (Build officiel) (64 bits).

**Comment by abulte** [comment]
Si possible merci de copier coller les codes erreurs, c’est plus facile pour que nous les retrouvions.

**Comment by jerbou** [comment]
L'erreur ne se reproduit pas à ce jour et désolé pour juste les printscreen :(
C'est noté pour une saisie des codes erreurs.

**Comment by abulte** [comment]
Pas de problème ! Merci.
