### ISSUE TITLE
Expliciter le fonctionnement actuel des timestamps

### ISSUE THREAD

**Issue by fchabouis** [etalab/data.gouv.fr#773]
## Description du bug
La documentation de l'API et ses résultats ne sont pas en ligne. La documentation dit que les timestamps renvoyés sont en fuseau UTC, tandis que les réponses effectives sont des timestamps naïfs.

## Comment reproduire le bug
Consulter la doc, par exemple des discussions :
https://doc.data.gouv.fr/api/reference/#/discussions/get_discussion
Réponse attendue :
```
{
  "discussion": {
    "content": "string",
    "posted_by": "string",
    "posted_on": "2022-03-16T13:30:19.161Z"
  }
}
```

Réponse effective :
https://demo.data.gouv.fr/api/1/discussions/?for=5eb3510a4efd8f649ffe1b9f

```
"posted_on":  "2021-06-07T08:54:28.286000"
```
Il n'y a pas de Z.

## Comportement attendu
Idéalement, que les tous les timestamps renvoyés par data.gouv sur son API soient en UTC.
Mais c'est sûrement un gros morceau.

Ça serait déja bien que la doc soit en ligne avec le comportement observé, et que soit expliqué le fonctionnement actuel des timestamps. Est-ce que ce sont des heures de Paris, est-ce que ça change en fonction de l'emplacement de celui qui a posté le commentaire (dans le cas d'une discussion), est-ce qu'on ne sait pas actuellement ce que ça fait, parce que ça depend des endroits ? Le fonctionnement actuel est-il susceptible de changer sans bruit ?

Ça nous aiderait beaucoup côté transport.data.gouv.fr pour nous même gérer proprement les dates !

Issue liée à https://github.com/etalab/data.gouv.fr/issues/171 et https://github.com/opendatateam/udata/issues/1046

**Comment by maudetes** [comment]
Merci pour ce ticket exhaustif.
En effet, on peut à minima s'améliorer sur la documentation de ce champ.

Peut-être profiter de https://github.com/etalab/data.gouv.fr/issues/720 pour faire une passe là dessus.
