### ISSUE TITLE
Eviter l'envoi de deux messages Kafka en cas d'ajout de ressources

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#782]

**Comment by quaxsze** [comment]
Les signaux sont envoyés d'une part par la méthode `save` et d'autre part la méthode `add_resource` :
```
post_save.send(self.__class__, document=self,
               resource_added=resource.id)
```
Les solutions sont les suivantes :
- Discriminer le signal par la présence d'un `ressource_id` dans les `kwargs` et ignorer dans ce cas si besoin.
Ex:
```
def reindex_model_on_save(sender, document, **kwargs):
    '''(Re/Un)Index Mongo document on post_save'''
    if 'ressource_id' in kwargs:
         return
    if current_app.config.get('AUTO_INDEX'):
        reindex.delay(*as_task_param(document))
```
- Ajouter un champ contenant le nom de la fonction émétrice du signal et discriminer sur ce champ là.
Ex:
```
def reindex_model_on_save(sender, document, **kwargs):
    '''(Re/Un)Index Mongo document on post_save'''
    if kwargs.get('sender_fun', None) == 'add_ressource':
         return
    if current_app.config.get('AUTO_INDEX'):
        reindex.delay(*as_task_param(document))
```
- Ajouter un champ non pas dans au niveau du signal mais au niveau du message kafka.
Les consummers pourront ensuite choisir d'ignorer le message ou non.

**Comment by maudetes** [comment]
Je mets ça comme ça, mais étant donné qu'on a déjà les fonctions`add_resource`, `update_resource` et `remove_resource`, est-ce qu'il ne faut pas qu'un signal différent soit envoyé dans ces cas là qui concernent spécifiquement la mise à jour d'une ressource?
Ce qui n'empêche pas de vouloir dédoubler le message d'indexation spécifiquement si on veut cependant.

**Comment by abulte** [comment]
> Ajouter un champ contenant le nom de la fonction émétrice du signal et discriminer sur ce champ là.

Intéressant à creuser. Est-ce qu'on peut quelque chose de générique, par exemple en utilisant le `sender` de `post_save(cls, sender, document, **kwargs)` ?

**Comment by abulte** [comment]
Autre idée : on pourrait aussi ne _pas_ envoyer le `on_update` dans le cas de `resource_added`:

```
        if kwargs.get('created'):
            cls.on_create.send(document)
        elif kwargs.get('resource_added'):
            cls.on_resource_added.send(document,
                                       resource_id=kwargs['resource_added'])
        else:
            cls.on_update.send(document)
```
