### ISSUE TITLE
Bugs graphique recherche mobile

### ISSUE THREAD

**Issue by etiennebrb** [etalab/data.gouv.fr#794]

**Comment by etiennebrb** [comment]
![IMG_4712](https://user-images.githubusercontent.com/29734544/160847950-3332c77c-3c7c-4a37-890b-bb217b29d8bc.PNG)
![IMG_4711](https://user-images.githubusercontent.com/29734544/160847985-772bbb56-e0ff-44f1-a0bf-a9c825073ece.PNG)

**Comment by nicolaskempf57** [comment]
> Quelque arrondis qui sépare la barre de recherche en deux :

C'est sur quel navigateur / OS ? J'arrive à le reproduire sur iOS

**Comment by nicolaskempf57** [comment]
- [ ] Champ de recherche arrondi
- [ ] Barre de recherche sticky décalée avec le haut de l'écran
- [ ] République avec le E à la ligne
