### ISSUE TITLE
Tester les pages statiques d'onboarding

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#796]
Tester les pages d'onboarding producteur, réutilisateurs et à propos

**Comment by agarrone** [comment]
https://www.figma.com/file/VlRfg7lHqsXvRIxV8OdK4M/Parcours-utilisateurs-et-cas-d'usages?node-id=375%3A26322

**Comment by maudetes** [comment]
Page producteur: Tests dirigés et non dirigés avec des producteurs d'une petite collectivité
Page réutilisateur: Tests dirigés non dirigés avec un réutilisateur du covid
