### ISSUE TITLE
Encodage couverture temporelle sur le profil utilisateur

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data.gouv.fr#80]
Ceci est visible sur mon profil https://www.data.gouv.fr/fr/users/antoine-augusti/ et https://www.data.gouv.fr/fr/datasets/operations-coordonnees-par-les-cross/

![screen shot 2018-08-06 at 15 01 26](https://user-images.githubusercontent.com/295709/43718046-b945b804-9989-11e8-881f-bc373613306c.png)
Problème d'affichage de la couverture temporelle sur le profil utilisateur

![screen shot 2018-08-06 at 15 01 38](https://user-images.githubusercontent.com/295709/43718047-b98c02d2-9989-11e8-8825-34c6dd6eb49d.png)
Pas de problème sur le jeu de données

**Comment by noirbizarre** [comment]
Corrigé par https://github.com/opendatateam/udata/pull/1821
