### ISSUE TITLE
URL with anchor does not scroll to the appropriate part of the page

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#801]
The following URL https://www.data.gouv.fr/fr/datasets/fichier-des-personnes-decedees/#discussion-604e44bcf9fac775bbc0aeca is supposed to send a user to the corresponding discussion, but it sends me to the reuses part of the page, as per the screenshot below.

![Capture d’écran 2022-04-01 à 18 06 46](https://user-images.githubusercontent.com/51122275/161301345-99d022e5-8706-4b61-b136-6d52c1ff4d87.jpg)

It is not clear in this case for the user that they have to scroll down (also related to #762 and perhaps #620 and #432).
This specific bug might be due to the fact that the discussion has been closed, but I have not been able to reproduce it ([I tried here](https://demo.data.gouv.fr/fr/datasets/jeu-de-donnees-avec-beaucoup-de-commentaires-tres-interessants/#discussion-62472594c832087b83d9bfcf)).

**Comment by maudetes** [comment]
I think we have a re-scroll after resources have been loaded dynamically, and it seems to fail in your case. @nicolaskempf57
Do you open the page by copy-pasting the url in your browser?
What browser are you using? and which version?

**Comment by restuccia** [comment]
I opened the page by clicking on the link on https://support.data.gouv.fr/ ("Voir un exemple").

I'm on Firefox 98.0.2 on macOS 10.15.7. Feel free to test on my machine

**Comment by agarrone** [comment]
@nicolaskempf57 on peut clore n'est-ce pas ?

**Comment by nicolaskempf57** [comment]
oui, les liens avec des ancres sont pris en compte dans la nouvelle page et amènent sur le bon onglet.
