### ISSUE TITLE
Weird behaviour in the order of search filters elements

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#802]
The following video explains it better than my confusing title:

https://user-images.githubusercontent.com/51122275/161790944-6462c81a-3b49-4bab-8a39-205ea09f2752.mov

The weird behaviour is related to the order of the elements in a search filter (e.g. the organisation one): when you click on the filter you are offered a certain list which makes kinda sense (I was looking for the Ministère de la Santé, which was proposed as the second item), but as soon as you start typing to search in the search filter (or filter the filter or whatever), the order changes (and the Ministère was not in the list or at least not on the top of it anymore). Deleting the search term does not reset the filter but proposes another order.

I'm on Firefox 98.0.2

**Comment by maudetes** [comment]
We need to take this in consideration in https://github.com/etalab/data.gouv.fr/issues/774. Indeed, when we remove the text, the default list should be the same as previously.

The default list is based on followers, whereas the suggest list (when typing) order is based on `created_at`. We could add a param to order by followers on suggest. What do you think @quaxsze?
