### ISSUE TITLE
Enquêter sur les metrics de views surprenantes

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#816]
Les metrics de views sont parfois très surpenantes.
Exemple pour jour:
- le [Ministère de l'Intérieur](https://www.data.gouv.fr/fr/organizations/ministere-de-l-interieur/) a 45 vues
- [IDéO BFC](https://www.data.gouv.fr/fr/organizations/geobourgogne/) a 523 vues
- [Etalab](https://www.data.gouv.fr/fr/organizations/etalab/) a 28 vues.
- le [SIG](https://www.data.gouv.fr/fr/organizations/service-d-information-du-gouvernement/) a 2265 vues.

Pourquoi autant de différence en terme d'ordre de grandeur?

Les nombre de vues très élevés montent artificiellement certaines organisations dans la liste des organisations ordonnées par défaut https://www.data.gouv.fr/fr/organizations/.

**Comment by agarrone** [comment]
Pris en compte dans un futur EPIC mis à plat des métrics
