### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by teolemon** [etalab/data.gouv.fr#82]
![image](https://user-images.githubusercontent.com/1689815/44848518-5b60c180-ac57-11e8-9e78-43c2294e3fd8.png)
Je serai

**Comment by abulte** [comment]
Merci ! La traduction a été corrigée à la source, elle sera corrigée sur le site lors de la prochaine livraison.

**Comment by bboulesteix** [comment]
_Issue_ fermée par cette _pull-request_ : https://github.com/opendatateam/udata/pull/1909. 🎉
