### ISSUE TITLE
Faire le ménage sur les vieux moissonneurs

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#820]
A vérifier s'il y a un archivage automatique des JDD lors d'une suppression d'un moissonneur.
A vérifier s'il y a un archivage automatique des JDD lors d'une désactivation d'un moissonneur.

Repasser sur le stock des JDD moissonnés qui ne sont plus rattachées à une source de moissonnage **active** et les archiver.

**Comment by abulte** [comment]
A ajouter au moment du ménage : `{'extras': {'archived:reason': 'harvesters_cleanup'}}`

**Comment by maudetes** [comment]
* Pas d'archivage automatique lors de la suppression / (ni quand le champ `deleted` est ajouté, ni lors de la purge)
* `active` n'a pas l'air d'être utilisé ou que ce soit, non ?

On peut filtrer les jeux de données qui ont une `source_id` qui ne correspondent à aucun moissonneur actif. Ex:
```
active_sources = [str(source.id) for source in HarvestSource.objects(active=True)]
dangling_datasets = Dataset.objects(**{'extras__harvest:source_id__exists': True ,'extras__harvest:source_id__nin': active_sources}).count()
```

**Comment by abulte** [comment]
Yes, donc :
- migration -> archivé pour les _danglings_
- ajout de l'archivage à la suppression du moissonneur
- `active` n'a effectivement jamais servi à rien je crois, donc soit le supprimer soit en faire une vraie feature (ie le moissonneur ne tourne pas régulièrement) mais qui n'aurait jamais été utile de mon expérience
