### ISSUE TITLE
Ajouter un système de captcha sur la page de création de compte

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#822]
Fait suite à https://github.com/etalab/data.gouv.fr/issues/749

 A voir côté API ce qu'ils ont utilisé.
A prendre en compte:
- accessibilité
-  RGPD

Des recommendations @abulte ?

Exemple: https://api.gouv.fr/les-api/api-captchetat ?

**Comment by abulte** [comment]
A ma connaissance le seul qui coche la case souverain c'est celui de l'AIFE. A regarder plus en détail pour les aspects RGPD et accessibilité.
