### ISSUE TITLE
Améliorer la détection de licences en cas de multiples matchs

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#828]
Fait suite à un retour sur des moissonneurs utilisant la licence "Licence Ouverte v2.0", non détecté par udata (voir [cet exemple](https://www.data.gouv.fr/fr/datasets/sda-adap-etude-schema-daccessibilite-des-transports-points-darrets-routiers-saint-lo-agglo-mars-2021/) sur [ce flux](https://dcat.isogeo.com/7b195c828aa74577afec7d6c223cddaa/RMmVNxgwo1AW7LHH42BuuWFiQGe40), ou encore [cet exemple](https://www.data.gouv.fr/fr/datasets/ilots-de-chaleur-circuit-de-mesures-mobiles-bayonne-juillet-2020/) sur [ce flux](https://dcat.isogeo.com/dfea79f9daa941fbb7fc9248309dc1c4/THU_tcV6SuOT_DsWqcQNzDenuhTV0)).

En effet, si plusieurs alternate titles sont proches de la licence utilisée, aucune licence n'est détectée: https://github.com/opendatateam/udata/blob/fab505fd9159c6a9f63e3cb55f0d6479b7ca91e2/udata/core/dataset/models.py#L221.

**Comment by maudetes** [comment]
En profiter pour fixer https://github.com/opendatateam/udata-ods/issues/196 en rajoutant un `alternate title` sur ODbL.

**Comment by restuccia** [comment]
Même probleme [sur ce jeu de données](https://www.data.gouv.fr/fr/datasets/fichier-des-donnees-theoriques-du-reseau-idelis-au-format-netex/) : côté ods les metadonnées licence sont 
```
"license": "Licence Ouverte v2.0",
"license_url": "https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf"
```

mais côté data.gouv.fr aucune licence est affichée
