### ISSUE TITLE
Impossible d'ajouter un utilisateur à une organisation

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#829]
## Description du bug
Quand on essaie d'ajouter un utilisateur à une organisation depuis l'admin, le champ de recherche ne marche pas, et on reçoit des erreurs.

![Capture d’écran 2022-04-19 à 14 55 02](https://user-images.githubusercontent.com/51122275/164008990-3b8f3be6-7d39-446f-a05d-49b57dcea56f.jpg)

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller dans une page orga dans l'admin `/admin/organization/`
2. Cliquer sur AJOUTER dans l'espace membres
3. Chercher un utilisateur
4. boom !

Env : Firefox 99.0.1 (64-bit)

**Comment by maudetes** [comment]
Merci du signalement. Je marque cette issue comme dupliquée de https://github.com/etalab/data.gouv.fr/issues/803.
Il y a déjà un fix https://github.com/opendatateam/udata/pull/2725, mais pas encore en production.

**Comment by restuccia** [comment]
oooups j'ai pas bien cherché, merci !
