### ISSUE TITLE
Rester sur la page où j'étais quand je me déconnecte de mon compte data.gouv.fr 

### ISSUE THREAD

**Issue by julietabarado** [etalab/data.gouv.fr#830]
## Rester sur la page où j'étais quand je me déconnecte de mon compte data.gouv.fr 
Par exemple, je suis sur la page d'un jdd alors que je suis connectée sur mon compte utilisateur : 
<img width="1289" alt="Capture d’écran 2022-04-20 à 11 49 18" src="https://user-images.githubusercontent.com/90256828/164201398-9f399898-776c-4932-981f-2c5d48f12790.png">

Quand je clique sur "se déconnecter" je suis redirigée vers la page d'accueil : 
<img width="1398" alt="Capture d’écran 2022-04-20 à 11 50 55" src="https://user-images.githubusercontent.com/90256828/164201652-d13bf244-3da0-4b79-b013-a893accf2ed6.png">

Alors que j'aurais voulu rester sur la page où j'étais, même si je me suis déconnectée. 

## Les alternatives possibles
Ne pas être redirigée vers l'accueil quand je me déconnecte de mon compte utilisateur.

**Comment by agarrone** [comment]
Pourquoi aurais tu envie de te déconnecter comme ça ?

**Comment by julietabarado** [comment]
j'avoue, mais même ça fait un peu bizarre, non ? de changer de page alors que je ne l'ai pas demandé, je voulais juste me déconnecter

**Comment by agarrone** [comment]
Je me permets de clore en attendant de voir si cela remonte en test
