### ISSUE TITLE
Finaliser automatisation de l'édito !

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#833]
- [x] ajout de support html dans les posts
- [x] création d'un dag airflow régulier pour génération de posts html

**Comment by maudetes** [comment]
Done! Voir https://mattermost.incubateur.net/betagouv/pl/rb3wttuewpnb88o6z4aneze6rc

**Comment by agarrone** [comment]
Process : https://www.notion.so/apigouv/Proc-dure-de-publication-suivi-des-sorties-b9c3525be3fe48faa901d83e476475df
