### ISSUE TITLE
Search by organisation yields zero results for some queries

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#834]
Si je cherche `autorité marchés` ou `autorite marches` parmi les organisations, la recherche affiche zéro résultats https://www.data.gouv.fr/fr/organizations/?q=autorit%C3%A9%20march%C3%A9s 

Pareil pour `ministere interieur` https://www.data.gouv.fr/fr/organizations/?q=ministere+int%C3%A9rieur ou `ministère solidarités` https://www.data.gouv.fr/fr/organizations/?q=minist%C3%A8res+solidarit%C3%A9s

**Comment by maudetes** [comment]
Oui merci pour le ticket !
C'est un point qu'on avait déjà observé, avec un fix en cours, mais il n'y avait pas encore de ticket ;)
