### ISSUE TITLE
Rajouter des liens profonds sur les éléments sur les pages des jeux de données

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#835]
Demande de @abulte qui permet notamment de renvoyer vers les ressources ou les réutilisations pour le support

**Comment by nicolaskempf57** [comment]
Est-ce qu'il s'agit d'ancres comme https://www.data.gouv.fr/fr/datasets/demandes-de-valeurs-foncieres/#community-reuses et https://www.data.gouv.fr/fr/datasets/demandes-de-valeurs-foncieres/#resources ?

**Comment by agarrone** [comment]
Yes tout à fait il faut voir si on veut rajouter un bouton et où

**Comment by nicolaskempf57** [comment]
Pour l'instant les liens sont accessibles depuis le sommaire mais pas depuis le titre de section directement comme c'est souvent le cas sur les sites de documentation (ex: https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods)

**Comment by agarrone** [comment]
En l'occurence dans ton exemple le petit # permet de faire le lien facilement

**Comment by nicolaskempf57** [comment]
Yes, c'est ça qu'on pourrait rajouter

**Comment by maudetes** [comment]
A l'image de ce qui est fait sur les discussions, faire la même chose sur les fichiers.

**Comment by agarrone** [comment]
@nicolaskempf57 on peut clore aussi ?

**Comment by nicolaskempf57** [comment]
On fait maintenant l'ancien nom du ticket, qui correspond à https://github.com/etalab/data.gouv.fr/issues/180

Par contre on ne permet pas de lien direct vers un fichier en particulier comme indiqué par @maudetes dans le commentaire du dessus ou la demande sur le channel Mattermost.

> A l'image de ce qui est fait sur les discussions, faire la même chose sur les fichiers.
