### ISSUE TITLE
Dumps CSV : Différence dans le nombre de datasets

### ISSUE THREAD

**Issue by pierredittgen** [etalab/data.gouv.fr#84]
Bonjour,

J'utilise le dump CSV des organisations et des datasets pour afficher une liste d'organisations et, pour chaque organisation, le nombre de datasets correspondants.

Dans un premier temps, j'utilisai la valeur de la colonne `metric.datasets` de la table organisations mais me suis rendu compte que la valeur était souvent à 0 alors qu'il y avait des datasets associés dans la table datasets

Je calcule maintenant le nombre de datasets par organisation en requêtant la table datasets. Dernièrement on m'a signalé que pour une organisation donnée (Département d'Eure et Loire), il y avait 14 datasets affichés sur opendatagouv.fr alors qu'il n'y avait aucun datasets correspondants dans la table datasets.

Ce dernier point semble corrigé dans le dump récupéré hier.

Mais je m'interroge sur la manière de faire pour obtenir cette métrique de nb de datasets par organisations. À quelle valeur se vouer ?

Merci d'avance pour votre éclairage
P.S. : ci joint un tableau indiquant les différences rencontrées entre la table organisations et la table datasets :
[organizations_nb_datasets.xlsx](https://github.com/etalab/data.gouv.fr/files/2360345/organizations_nb_datasets.xlsx)

**Comment by pierredittgen** [comment]
Bonjour,

Avez-vous pu vous pencher sur le problème si problème il y a ?

**Comment by pierredittgen** [comment]
Bonjour,

1an après, voici le fichier de stats mis à jour. Il reste des incohérences entre nombre de datasets indiqués dans la table organizations et le nombre de datasets par organisation constatée dans la table organisation mais elles ont drastiquement diminué.

Nombre d'incohérences : passage de 922 à 697
Nombre de dataset nul dans la table organisations mais datasets présents dans la table datasets : passage de 917 à 31 occurrences !

La procédure d'obtention du fichier CSV est dispo ici : https://github.com/pierredittgen/data.gouv.fr-check

Keep up the good work!

[organization_nb_dataset_2019.xlsx](https://github.com/etalab/data.gouv.fr/files/3583334/organization_nb_dataset_2019.xlsx)

**Comment by abulte** [comment]
Merci @pierredittgen pour ce travail de vérification. Nous avons effectivement depuis quelques mois un export plus stable et nous allons pouvoir nous pencher sur les différences constatées.

**Comment by abulte** [comment]
Linked to #148

**Comment by pierredittgen** [comment]
Suite à la [correction](https://github.com/pierredittgen/data.gouv.fr-check/issues/2) du script de détection d'erreur, le nombre d'incohérences entre le nombre de datasets indiqué dans la table organizations et le nombre de datasets par organisation issu de la table datasets a encore diminué : passage de **697** à **360** erreurs aujourd'hui.

**Comment by abulte** [comment]
Bonne nouvelle. On a aussi livré #2306 hier, donc le dump de samedi prochain sera peut-être encore plus propre 🤞

**Comment by abulte** [comment]
Je ferme pour l'instant, n'hésitez pas à rouvrir en cas de besoin.
