### ISSUE TITLE
Ancienne adresse d'API mal géré

### ISSUE THREAD

**Issue by NicolasRolinDGE** [etalab/data.gouv.fr#840]
L'adresse https://api.adresse.data.gouv.fr/ renvoie une page avec seulement le texte "hiya".
Si c'est une ancienne adresse dépréciée, il serait de bon alois de faire une redirection ou de mettre un message explicite.
Si ce n'est plus une adresse IP contrôlée par etalab, il serait bien que l'adresse ne redirige plus dessus.

**Comment by abulte** [comment]
Bonjour, merci pour le signalement. 

Pouvez-vous nous indiquer où vous avez eu connaissance de cette adresse ? L'adresse canonique est https://api-adresse.data.gouv.fr.

**Comment by abulte** [comment]
D'accord, merci. Nous avons supprimé l'enregistrement DNS. N'hésitez pas à nous prévenir si vous trouvez une référence à cette adresse quelque part.
