### ISSUE TITLE
Archivage des jeux de données issus de geo.data.gouv.fr - phase 2

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#847]
Embarquer https://github.com/etalab/data.gouv.fr/issues/852 dans la foulée

Mapping des moissonneurs geo ide : [geo-ide_dgv_20221104.csv](https://github.com/etalab/data.gouv.fr/files/9980857/geo-ide_dgv_20221104.csv)

**Comment by maudetes** [comment]
L'entièreté des jeux de données issus de geo.data.gouv.fr ont été archivés. Voir https://github.com/etalab/data.gouv.fr/issues/1327
