### ISSUE TITLE
[META] Nettoyer la métadonnée licence

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#849]
Aujourd’hui [[data.gouv.fr](http://data.gouv.fr/)](http://data.gouv.fr) propose de choisir parmi les licences suivantes :

- Creative Commons Attribution
- Creative Commons Attribution Share-Alike
- Creative Commons CCZero
- Licence Ouverte / Open Licence
- Licence Ouverte / Open Licence version 2.0
- License Not Specified
- Open Data Commons Attribution License
- Open Data Commons Open Database License (ODbL)
- Open Data Commons Public Domain Dedication and Licence (PDDL)
- Other (Attribution)
- Other (Open)
- Other (Public Domain)

Néanmoins, les seules licences permises par la loi sont :

- Licence Ouverte / Open Licence version 2.0
- Open Data Commons Open Database License (ODbL)

De plus, si aucune licence est indiquée et les données sont publics (crées ou reçues par des administrations), les conditions de réutilisation qui s’appliquent sont celles de la Licence Ouverte 2.0.

## Problématiques

1. Les producteurs ne savent pas toujours quelle licence choisir
2. Les producteurs ne renseignent pas toujours la licence
3. L’interface actuelle laisse imaginer que toutes les licences disponibles soient permises par la loi

## Solution proposée

- Indiquer uniquement LO2.0 et ODbL
- Mettre la LO2.0 par défaut
- Empêcher de publier des données sans licence
- Permettre aux utilisateurs et aux organisations qui ne sont pas des services publics de choisir d’autres licences (ou champ libre ?)

Voir aussi ce ticket : https://github.com/etalab/data.gouv.fr/issues/600

**Comment by maudetes** [comment]
A valider côté juridique que l'on puisse bien mettre LO2.0 si non détectée @restuccia

**Comment by maudetes** [comment]
* Limiter à 3 licences : OdBL, Licence Ouverte (en ignorant la version), une des licences OpenDefinition, champ vide (avec un affichage sur le front ambiguité liberté de réutilisation)
* En cas d'échec de détection dans le cas du moissonnage, LOV2

**Comment by restuccia** [comment]
> En cas d'échec de détection dans le cas du moissonnage, LOV2

Plutôt conditions de réutilisation du CRPA je dirais

**Comment by agarrone** [comment]
Voir aussi #600

**Comment by restuccia** [comment]
For inspiration, data.gov shows the following information

<img width="700" alt="Capture d’écran 2022-08-05 à 14 50 21" src="https://user-images.githubusercontent.com/51122275/183080899-d2087520-333b-4117-87b6-224bb24c2ae1.png">

In the screenshot, **[Public](https://resources.data.gov/resources/dcat-us/#accessLevel)** links to the `accessLevel` field of the dcat-us schema . `accessLevel` can be either public or non-public. (Possible link to our own catalogue project?)

**[U.S. Government Work](http://www.usa.gov/publicdomain/label/1.0/)** links to a page that explains how copyright applies to U.S. government works (which includes exceptions for logos, trademarks, etc.)

**Comment by agarrone** [comment]
Sera traité dans #859
