### ISSUE TITLE
Confirmation changement de rôle : phrase incomplète

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/data.gouv.fr#85]
<img width="338" alt="capture d ecran 2018-10-09 a 11 52 24" src="https://user-images.githubusercontent.com/1231232/46661657-e4094080-cbb9-11e8-9655-f260634770ed.png">

Il manque "administrateur" :)

**Comment by bzg** [comment]
En fait les _placeholders_ pour {user} et {role} sont remplacés par une chaîne vide, donc moins un problème de chaîne de caractère que de code.

**Comment by agarrone** [comment]
C'est corrigé depuis :) 
![image](https://user-images.githubusercontent.com/60264344/156598405-bf0860be-e90d-4408-b0f5-85d6687b3e33.png)

**Comment by bzg** [comment]
Cool, merci !
