### ISSUE TITLE
Décider de la solution technique pour la mise en place du parcours de publication

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#860]
Plusieurs solutions ont été évoquées : simples _pages_, site à part (repartir de publier?) et views additionnelles dans un plugin.

A prendre en compte:
- authentification
- possibilité de header/footer partagés (pour cohérence entre les différents sites) -> varnish SSI/ESI / module npm qui embarque footer/header

Voir exemple de parcours de publication v0: https://www.figma.com/proto/LQ2BrwQkaweODXSLTRvjpo/Embarquement?page-id=0%3A1&node-id=106%3A8223&viewport=1010%2C348%2C0.07&scaling=scale-down-width&starting-point-node-id=106%3A8223

**Comment by agarrone** [comment]
Un arbre de décisions me semble complexe à mettre en place sur des _pages_ vous imaginez quoi ?

**Comment by maudetes** [comment]
Techniquement c'est juste des href sur des pages HTML. Genre dans l'idée:
Dans la première *page* que_souhaitez_vous_publier.html, on aurait 
```
<h1>Que souhaitez-vous publier aujourd'hui ?</h1>
<a href="publier_des_données_ouvertes.html">des données ouvertes</a>
<a href="publier_une_réutilisation.html">une réutilisation</a>
```
Par contre, c'est en effet peu lisible rapport à une solution avec un arbre décrit dans un fichier de config, ce serait juste pour cette première version assez simple.
