### ISSUE TITLE
Mise à jour du DSFR v1.6 & 1.7

### ISSUE THREAD

**Issue by nicolaskempf57** [etalab/data.gouv.fr#865]
### 1.6

- [x] Intégration du composant Bande d’information importante
- [x] vérifier les onglets (`✨ Changement dans la méthode d’affichage des bordures et des éléments.`)
- [x] vérifier breadcrumb (`✨ Passage du breadcrumb en inline pour un affichage sur plusieurs lignes`)
- [x] vérifier header (`🛠️ Ajustement des marges`)
- [x] vérifier liens (`🛠️ Revue du placement des icônes.`)
- [x] vérifier tags (`🛠️ Ajustement des espacements dans un groupe de tags`)
- [x] vérifier sidemenu (`✨ Changement de balise du titre pour un heading au lieu d’un paragraphe`)

### 1.7

- [x] tester le sélecteur de langue et créer une PR (`🎉 Ajout du composant sélecteur de langue`, `🎉 Ajout d’un exemple avec sélecteur de langue`)
- [ ] Met-on le sélecteur de langue dans le header ? (cf. https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/selecteur-de-langue)
- [x] vérifier footer (`🛠️ Correction du snippet du logo main : ajout du prefix fr- sur fr-footer__partners-link`,
`🛠️ Correction de l'attribut ‘title’ du lien de brand et de l’attribut ‘alt’ sur le logo opérateur`)
- [x] vérifier header (`🛠️ Correction de l'attribut ‘title’ du lien de brand et de l’attribut ‘alt’ sur le logo opérateur`)
- [x] vérifier liens (`🛠️ Correction du soulignement au hover`)
- [x] vérifier inputs (`✨ Séparation de input en sous composants : input-base, input-tel, input-email`)
- [x] vérifier pagination (`🛠️ Correction du style des liens en <button>`)

### 1.8

- [x] vérifier formulaires (`✨ Evolution du système de formulaire (fieldset, fieldset__element)`, `✨ Evolution du système de messages de statut, maintenant contenus dans un block fr-messages-group :`, `✨ Ajout des attributs autocomplete sur les formulaires & patterns`)
- [x] vérifier cartes (`✨ le titre devient un h3 par défaut`)
- [x] vérifier checkbox (`✨ Evolution du groupe de checkbox pour utiliser le nouveau système de formulaire (voir form)`)
- [x] vérifier input (`✨ Evolution du groupe de champ de saisi pour utiliser le nouveau système de formulaire (voir form)`, `🎉 Ajout du composant mot de passe`)
- [x] vérifier Sidemenu (`aria-labelledBy`)
- [x] vérifier footer (`🛠️ La bordure supérieur bleue passe à l’intérieur`, `🛠️ Correction d'une régression sur le séparateur bleu`)
- [x] vérifier tag (`🛠️ Correction tag sélectionnable hover`)
- [x] vérifier tuile (`✨ le titre devient un h3 par défaut`)
- [x] vérifier bouton (`🛠️ Correction d'une régression sur les icônes placées à droite (https://github.com/GouvernementFR/dsfr/issues/459)`)

### 1.9

- [x] vérifier checkbox (`🛠️ Correction rendu accessibilité`)
- [x] vérifier que l'analytics est désactivée
- [ ] vérifier footer (`évolution des mentions légales`)
- [x] vérifier header (` feat(header,navigation): fermeture de la navigation au clic sur lien ou bouton`)

### Autres

- [x] vérifier badge (modification des classes des icones)
- [x] vérifier toggle (je n'ai pas noté les modifications)

**Comment by maudetes** [comment]
Use new `fr-hr-or` instead of custom one defined in https://github.com/etalab/udata-front/pull/237/commits/ef7dec6d53d72a5bbc45dfdefd31353e4dadae0c
