### ISSUE TITLE
Investiguer metrics recherche

### ISSUE THREAD

**Issue by etiennebrb** [etalab/data.gouv.fr#869]
Il y a une forte baisse des événements 'Recherches' après la refonte qui ont été divisés par presque 5.

![Image](https://user-images.githubusercontent.com/29734544/175024955-990d3fa7-b60b-4bbf-9ac7-a07544d22099.png)

**Comment by agarrone** [comment]
Je clôt car pris en compte dans le travail de @sixtedemaupeou sur les métriques.
