### ISSUE TITLE
carte id - bug 

### ISSUE THREAD

**Issue by bfab16000** [etalab/data.gouv.fr#878]
## Description du bug
Qu’est-ce qui cloche ? Décrivez le bug en quelques phrases. Si possible, ajoutez des captures ou des enregistrements de votre écran pour nous aider à visualiser le problème. Si un message d’erreur est apparu sur votre écran, ajoutez-le ici.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Aller à `…`
2. carte id - bug  
3. Cliquer sur `…`
4. Naviguer jusqu’à `…`
5. Constater le bug

## Comportement attendu
Décrivez-nous ce à quoi vous vous attendiez. Exemple : « Je pensais que mon action allait déboucher sur… or à cause du bug je constate que… »

**Comment by maudetes** [comment]
Bonjour. Pouvez-vous préciser le problème rencontré en suivant la structure proposée ?
