### ISSUE TITLE
Maquetter les nouvelles cartes annexes

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#884]
- Sur les reuses mettre la nouvelle carte de jeux de données
- Les cartes jeux de données, reuses et api recommandés doivent être repensées (sur le format des nouvelles cartes)
- Les cartes sur la home et les oemed peuvent être revues
- Revoir le lien vers les licences (au profit d'une infobulle ?)

**Comment by agarrone** [comment]
Maquette done https://www.figma.com/file/ZEbbNyIqjemzBshSSVUFj4/data.gouv.fr---Composants-(Next)?node-id=24%3A2314
