### ISSUE TITLE
Maquetter l'explorateur

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#885]
https://www.figma.com/proto/wtx84PJ8OMKDwVLsoRUuTV/S2E11---Exploration?page-id=525%3A3527&node-id=702%3A4006&viewport=-13%2C1049%2C0.43&scaling=min-zoom&starting-point-node-id=702%3A4006

**Comment by maudetes** [comment]
Voir https://www.figma.com/file/wtx84PJ8OMKDwVLsoRUuTV/S2E11---Exploration?node-id=789%3A2023
