### ISSUE TITLE
☠️ opendatateam

### ISSUE THREAD

**Issue by abulte** [etalab/data.gouv.fr#887]
We should remove everything related to `opendatateam` (npm, GitHub, emails...) and migrate everything to `etalab`.

This was designed to allow collaboration on a "commun numérique" distinct from Etalab and with external members, but it's clearly not happening.

It's a daily hassle to have to switch between opendatateam and etalab and handling permissions and stuff on one namespace is already complicated enough.

**Comment by maudetes** [comment]
A list of things to consider for a migration to etalab.
- [ ] migrate github repository
- [ ] try to find out any reference to opendatateam repo everywhre (udata, udata-front, pages, guides, discussions, ... ?)
- [ ] give appropriate rights to etalab on pypi
- [ ] check that CircleCI pipelines are still working
- [ ] check Crowdin projects

Don't hesitate to edit this message to add steps if I'm missing some things.

**Comment by agarrone** [comment]
Won't do for now since data.gouv.fr is no longer within Etalab.
