### ISSUE TITLE
Résoudre les erreurs remontées par lighthouse

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#894]
Fait suite à https://github.com/etalab/data.gouv.fr/issues/483.

L'idée serait de modifier les assertions basées sur des scores minimaux pour des preset (ex: `"preset": "lighthouse:no-pwa"`).

Cela signifie qu'il faudrait améliorer les soucis actuels remontés (ou rajouter des exceptions).

**Comment by nicolaskempf57** [comment]
## Petit retour sur les erreurs Lighthouse

### `Preload key requests`
Le plus gros retour concerne les ressources qui ne sont pas préchargées. Le problème est que Parcel ne gère pas ce cas du coup pour l'instant (seulement pour le js) et que nous n'avons pas non plus de manifest sur lequel nous baser.

### `Enable text compression`, `Use HTTP/2`, `Serve static assets with an efficient cache policy` et `Does not use HTTPS`
Ces points concernent la configuration du serveur qui n'est pas optimisée. Cela semble normal comme `udata serve` n'a pas cette vocation.

### `Eliminate render-blocking resources`
Tout le CSS et tout le JS d’udata-front sont chargés à l’arrivée sur la home, cela représente une talle importante de contenu qui n’est pas utilisé pour l’affichage initial.

Pour diminuer la taille des ressources bloquantes faudrait utiliser un outil comme [critical](https://github.com/addyosmani/critical) pour intégrer dans le code HTML, le CSS minimal requis et retarder le chargement du reste du CSS. Voir également le problème de  `Preload key requests`.

### `Reduce unused JavaScript` et  `Reduce unused CSS`
Pour résoudre le CSS non utilisé du site, nous pourrions utiliser [PurgeCSS](https://purgecss.com/).
Pour diminuer la quantité de CSS et js chargé par page, on peut avoir un fichier CSS / js par page au lieu d’un seul global.

### `Properly size images`

La taille des images des reuses et des articles ne correspond pas à leur utilisation sur la liste. Il faudrait utiliser une version plus petite.
Il est possible d’utiliser les versions 500px/400px respectivement pour les images des reuses et des articles mais celle-ci sont carrées et ne respectent pas le format fourni par le réutilisateur ou l’auteur, ce qui peut impacter négativement le rendu des listes.

### `Serve images in next-gen formats`

Nous utilisons des images en jpeg et png et non en webP. Il pourrait être intéressant de générer des versions WebP et d’utiliser la balise `<picture>` pour fournir des formats utilisables avec fallback pour les navigateurs plus anciens.
Note : `<picture>` ne marchera pas sur IE11

### `Minimize main-thread work` et `Reduce JavaScript execution time

Une partie du temps du thread est utilisé pour l’évaluation des scripts et l’analyse du HTML / CSS qui pourrait être réduite avec des scripts et styles plus petits, cf. `Reduce unused JavaScript` et  `Reduce unused CSS`.

### `Browser errors were logged to the console`

Lighthouse cherche à charger `/en/styles.css`  sans succès comme le fichier n’existe pas, ce qui provoque une erreur dans la console. Pour l’instant je n’ai pas trouvé d’où vient le chargement.

**Comment by maudetes** [comment]
L'étude des erreurs restantes a été copié dans https://github.com/etalab/data.gouv.fr/issues/925.
On peut fermer ce ticket résolu par https://github.com/etalab/udata-front/pull/158.
