### ISSUE TITLE
Demande de suppression de deux comptes utilisateurs (adresse courriel expirés)

### ISSUE THREAD

**Issue by jerbou** [etalab/data.gouv.fr#897]
## Description du bug
Est il possible de s'entretenir par téléphone pour vous faire supprimer deux comptes utilisateurs sur la plateforme data.gouv ?
En tant qu'admin, j'ai retiré ces utilisateurs d'organisations, mais nous ne pouvons pas les supprimer et d'autant que les adresses courriel ne sont plus opérationnelles.

D'avance Merci,

Jérôme Boutet
IDéO BFC

**Comment by maudetes** [comment]
Bonjour,
Je vous invite à nous contacter en utilisant le support https://support.data.gouv.fr/ pour une correspondance directe.
Bien cordialement.

**Comment by jerbou** [comment]
merci, demande envoyée !
