### ISSUE TITLE
Vérifier envoi de messages màj de ressources suite au moissonnage

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#898]
Poser la logique qu'on veut. 

Ex: ne pas envoyer trop de messages pour spammer le crawler au risque de spammer le portail moissonné.

Mais tout de même pouvoir envoyer un message en cas de:
- modification ressource
- nouveau moissonneur
- JDD archivés

Ce serait au crawler hydra basé sur le catalogue la responsabilité de détecter des màj régulièrement.

**Comment by maudetes** [comment]
Some notes on messages being sent.
Messages are never sent on harvesting.

### Resource created
- called in add_resource
	- called in create_resource resource API endpoint
	- called in upload_new_dataset_resource API endpoint

### Resource modified
- called in update_resource
	- called in upload_dataset_resource API endpoint
	- called in update_resource resource API enpoint

### Resource deleted
- called in remove_resource
	- called in delete_resource API endpoint
- called in purge datasets (dataset deletion)

**Comment by maudetes** [comment]
Aucun message n'est envoyé à Hydra aujourd'hui lors du moissonnage.

Comme mentionné plus haut, la tâche revient aujourd'hui au crawler de consulter le catalogue pour ajouter les nouvelles ressources moissonnées. La suppression a aussi lieu lors de la lecture du catalogue où tout est mis à `deleted=false` par défaut, puis remis à `true` dans le cas où la ressource est présente dans le catalogue.

En cas de màj de `harvest.modified_at`, il pourrait être intéressant de re-prioriser le crawling sur cette ressource.

Au-delà de la question de l'update de la DB du crawler, se pose la question de la suppression des éventuelles bases/tables SQL créées ensuite. A voir de quelle manière on met à jour cette logique, peut-être à penser en lien avec https://github.com/etalab/udata-hydra/pull/50?

**Comment by abulte** [comment]
@maudetes https://github.com/etalab/udata-hydra/pull/50/commits/afc5bbd4484490a501f377a7e8ef885cd9d1c052 🚀

**Comment by maudetes** [comment]
Olala, c'est beau! :clap:
Pour moi on peut clore ce ticket, sauf si on veut voir pour la priorisation des données avec une `harvest.modified_at` updatée.
