### ISSUE TITLE
Ajouter une forme géométrique pour la couverture spatiale de Sophia Antipolis

### ISSUE THREAD

**Issue by bboulesteix** [etalab/data.gouv.fr#90]
_Bug signalé par e-mail sur `info@data.gouv.fr`. Test effectué sous Windows avec IE 7 et Firefox 62._

## Description du bug
Pour l’EPCI CASA , la carte proposée correspond à un zoom sur l’Europe occidentale — choix du code INSEE : 240600585, dans le champs couverture spatiale (cf. capture).

![pb dg 2](https://user-images.githubusercontent.com/3286488/47074524-dc215000-d1fa-11e8-8009-d91fac53ac8f.JPG)

Par ailleurs de nombreuses correspondances (code INSEE / Nom de la commune) erronées sont proposées lorsqu’on saisit un code INSEE d’une commune dans le champs couverture spatiale.

## Comment reproduire le bug
Exemple : pour le 06107, le nom de commune « Roquesteron » fait partie des propositions. Ce nom de commune n’existe pourtant plus (cf capture 3).

![pb dg 3](https://user-images.githubusercontent.com/3286488/47074532-e04d6d80-d1fa-11e8-8749-a2899b501f06.JPG)

## Comportement attendu
Ne serait – il pas possible d’implémenter les couvertures spatiales des périmètres de l’ensemble des EPCI de France (à commencer par les EPCI à fiscalité propre), d’ajouter, dans le module édition d’une organisation, la possibilité de définir (de suggérer), voire de corriger une emprise spatiale correspondant à l’ organisation concernée ?

**Comment by bboulesteix** [comment]
Vu avec @noirbizarre :

> Pour l’EPCI CASA (Sophia Antipolis), la carte proposée correspond à un zoom sur l’Europe occidentale.

C’est un bug connu et spécifique à Sophia Antipolis. Nous allons le corriger.

> Pour le 06107, le nom de commune « Roquesteron » fait partie des propositions. Ce nom de commune n’existe pourtant plus.

Si le nom de la commune a été supprimé récemment, il est possible que nous ne soyons pas encore à jour.

> Ne serait-il pas possible d’implémenter les couvertures spatiales des périmètres de l’ensemble des EPCI de France (à commencer par les EPCI à fiscalité propre).

C’est déjà le cas, sauf pour Sophia Antipolis et Lyon, deux cas pour lesquels il y a un pépin.

**Comment by abulte** [comment]
Problème réglé.

![Capture d'écran 2019-11-22 12 21 22](https://user-images.githubusercontent.com/119625/69421936-a9615980-0d22-11ea-9906-c051cc383ab0.png)
