### ISSUE TITLE
Ajouter un tri alphabétique à la page `/datasets`

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#900]
Parmi les options de tri dans la page https://www.data.gouv.fr/fr/datasets/, il manque la possibilité de trier par ordre alphabétique, ce qui pourrait être utile dans certaines situations (e.g. identifier des doublons).

![Capture d’écran 2022-08-02 à 09 41 22](https://user-images.githubusercontent.com/51122275/182319943-27b4a4c0-2dd1-44d1-ad6c-ee7ae125ec75.png)

**Comment by maudetes** [comment]
Il me semble que ça reste un cas d'utilisation assez spécifique, qui ne mérite peut-être pas sa place parmi les tris sur le front data.gouv.fr non ?
En alternative, il est possible de télécharger le catalogue (ou un subset du catalogue (ex: data.gouv.fr/fr/datasets.csv?tag=covid ou https://data.gouv.fr/fr/organizations/etalab/datasets.csv) et de traiter ensuite le CSV pour filtrer comme voulu.

**Comment by restuccia** [comment]
En effet c'est pas du tout prioritaire
