### ISSUE TITLE
Itérérer sur les maquettes de prévisualisation

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#902]
En fonction des retours des tests

**Comment by geoffreyaldebert** [comment]
comportement qui ne sont pas sur la maquette : 

- [] à chaque fois qu'on ajoute un filtre, bleuté la colonne
- [] au lieu de "Réinitialiser les filtres", écrire "Gérer les filtres" avec potentiellement un petit numéro de notif contenant le nombre de filtre actif
- [] au clic du bouton "gérer les filtres", afficher un panel (à droite) contenant la liste des filtres que l'on peut supprimer un par un ou tous d'un coup
- [] remplacer le texte du type de données (ex: siren) par un icone (ex : main qui clique)
- [] tooltip au click d'une donnée, garder les textes de Geoffrey
- [] fix partie ressource lors du scroll (ligne ressource et ligne noms de colonnes)
- [] stick barre noire en bas en permanence
- [] petite barre (avec les sommes) en bas - non prioritaire
- [] non prioritaire : filtre integer avec histogramme de distribution et filtre valeur

**Comment by agarrone** [comment]
>  tooltip au click d'une donnée, garder les textes de Geoffrey
Tu peux m'envoyer ton wording stp ? 

Il faut aussi qu'on explicite aussi le comportement de recherche

**Comment by nicolaskempf57** [comment]
> Tu peux m'envoyer ton wording stp ?

```
Il semblerait que ce champ soit un code commune

Commune : Valserhône
```

Il y a la même chose pour région et département.

Pour les entreprises :

```
Il semblerait que ce champ soit un numéro d'entreprise (numéro Siren)

Entreprise : commune de bonson

[En savoir plus sur cette entreprise]
```
