### ISSUE TITLE
Toutes les options de visualisation de GeoJSON ne fonctionnent pas

### ISSUE THREAD

**Issue by teolemon** [etalab/data.gouv.fr#904]
## Description du bug

- [ ] Toutes les options de visualisation de GeoJSON ne fonctionnent pas
- De nombreuses communes n'ont plus d'eau, et je voulais voir si Data.gouv.fr avait des données concernant les réseaux d'eau (et leur éventuelle interconnexion)
- Je suis tombé sur ce dataset: https://www.data.gouv.fr/fr/datasets/eau-reseaux-eaux-usees-et-eaux-pluviales-grand-poitiers-donnees-metiers/
## Comment reproduire le bug
- J'ai tenté de le visualiser. 
- Le widget intégré montre une croix rouge
- Lien mort: https://transcode.geo.data.gouv.fr/services/5e2a1f56fa4268bc255d7e94/feature-types/Geoportail_WMS_Preview_2:Reseau_EU?format=GeoJSON&projection=WGS84

<img width="895" alt="image" src="https://user-images.githubusercontent.com/1689815/183256288-129565bb-5ccd-4929-9846-50c6f6330e39.png">

## Comportement attendu
- Soit une résolution du problème
- Soit un message indiquant que la visualisation est indisponible (la croix rouge suggère des données interdites)

**Comment by maudetes** [comment]
Merci pour la création cette issue !

La visualisation sur data.gouv.fr échoue car la ressource n'est plus disponible sur geo.data.gouv.fr (service plus maintenue).
Les producteurs sont incités à publier leurs données directement sur data.gouv.fr sans passer par geo.data.gouv.fr. Vous pourrez trouver de nouvelles données accessibles publiées par ce producteur, par exemple : https://www.data.gouv.fr/fr/datasets/eau-reseaux-eaux-usees-grand-poitiers-donnees-metiers/.
Je vous conseille de contacter directement le producteur des données (en bas de la page du jeux de données concerné) si vous ne trouvez pas les données équivalentes à celles qui sont inaccessibles.

N'hésitez pas à clore ce ticket s'il répond à votre question.
