### ISSUE TITLE
Revenir en arriere après une recherche

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#905]
Chaque caractère saisi dans la barre de recherche dans `/datasets`, change l'url de la page en ajoutant le caractère au paramètre `q`.
Par exemple : si je me trouve sur https://www.data.gouv.fr/fr/datasets/ et je veux chercher le mot « test », je vais saisir « test » dans le champ de recherche, et à chaque caractère saisi, l'url de la page change :
```
https://www.data.gouv.fr/fr/datasets/?q=t
https://www.data.gouv.fr/fr/datasets/?q=te
https://www.data.gouv.fr/fr/datasets/?q=tes
https://www.data.gouv.fr/fr/datasets/?q=test
```
**Si je veux revenir en arrière, je dois donc le faire autant de fois que de caractères dans la chaîne de recherche.**

https://user-images.githubusercontent.com/51122275/183906122-ab03928f-c93e-497a-9dcd-674dedc4de99.mov

**Comment by maudetes** [comment]
On pourrait ajouter un temps d'attente avant de déclencher la recherche (et mettre à jour l'url), qui réduirait le nombre de call et limiterait le problème du retour en arrière (sans le résoudre totalement, notamment si la frappe est lente).
Qu'est-ce que t'en penses @nicolaskempf57 ?

**Comment by nicolaskempf57** [comment]
Je vois 2 possibilités : 
- on peut mettre en place un `debounce` sur la saisie pour diminuer les requêtes successives
- on peut mettre à jour l'URL uniquement en cas de réponse, ce qui évitera d'ajouter les requêtes annulées à l'historique

**Comment by maudetes** [comment]
On pourrait même combiner les deux ? :wink:

**Comment by nicolaskempf57** [comment]
> On pourrait même combiner les deux ? 😉

Exact ! Ce serait encore mieux
