### ISSUE TITLE
Améliorer l'API et l'export catalogue pour les discussions

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#906]
L'API discussions https://doc.data.gouv.fr/api/reference/#/discussions et l'export des discussions du catalogue https://www.data.gouv.fr/fr/datasets/catalogue-des-donnees-de-data-gouv-fr/ ont plusieurs limites.

L'export catalogue présente uniquement les champs suivants :
`id | user | subject | title | size | messages | created | closed | closed_by`

L'API permet d'obtenir une discussion à partir de son ID et, il me semble, de l'ID du jeu de données (feature pas documentée cf. #218).

Ce serait très utile de pouvoir télécharger / obtenir via API une liste des discussions liées à une organisation. Par exemple en ajoutant une colonne `organisation` dans l'export csv, qui fait référence à l'organisation productrice du jeu de données sur lequel le commentaire a été posté. Pour aller plus loin, proposer un téléchargement déjà filtré aux admins/editors de l'orga serait une bonne idée, ou simplement un endpoint API pour pouvoir obtenir les discussions liées à une organisation.

Cf. #217, #173

**Comment by maudetes** [comment]
Merci pour ce ticket! Il y a en effet un besoin de nettoyer un peu la doc sur la gestion des discussions. Ce serait probablement à traiter au moment de l'EPIC autour des discussions, j'imagine.

En tout cas, pour la liste des discussions liées à une orga, il y a cette route api https://www.data.gouv.fr/api/1/organizations/etalab/discussions/ ou encore cet export csv: https://www.data.gouv.fr/fr/organizations/etalab/discussions.csv.
Si pertinent, on peut en effet rajouter un champ pour l'user ou l'orga productrice, à voir pour le wording que ça ne rende pas ça encore plus flou.
