### ISSUE TITLE
Impossible d’éditer un jeu de données dont le titre est accentué

### ISSUE THREAD

**Issue by bboulesteix** [etalab/data.gouv.fr#91]
_Bug signalé par e-mail sur `info@data.gouv.fr`. Test effectué sous Windows avec IE 7 et Firefox 62._

## Description du bug
Il semble impossible de gérer les accents lors d’une « réédition » d’un jeu de données existant. En clair, nous avons pu créer un titre avec un accent mais il nous a été impossible d’éditer, par la suite, ce jeu de données. Le titre est refusé lors du « réenregistrement » — message « titre requis » (voir capture).

![pb dg 1](https://user-images.githubusercontent.com/3286488/47074718-4639f500-d1fb-11e8-8240-e74cd417e3b2.JPG)

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Créer un titre avec un accent ;
2. Tenter de l’éditer par la suite ;
3. Le titre est refusé lors du de la sauvegarde.

## Comportement attendu
Il faudrait que le nouveau titre puisse être enregistré, même si sa version initiale contenait un accent.

**Comment by taniki** [comment]
Il y a un problème d'échappement des straight single quotes. Les apostrophes françaises passent toutes seules.

**Comment by taniki** [comment]
Je n'arrive pas à reproduire le bug sur next.

Exemple : https://next.data.gouv.fr/fr/admin/dataset/5bc6fbf5dc47092933685cf8 j'ai édité plusieurs fois le titre et la description

**Comment by taniki** [comment]
le problème semble avoir été réglé
