### ISSUE TITLE
Faire une passe de nettoyage sur la catalogue des utilisateurs

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#911]
De nombreux comptes utilisateurs sont créés sur data.gouv.fr quotidiennement, dont une partie qui semble être uniquement du spam.
Ces comptes ne sont pas trouvables depuis datagouv ni indexés sur google et les éventuels liens sont en `no-follow`, mais du contenu spam existe néanmoins dans le catalogue de data.gouv.fr.

On propose de faire un export des utilisateurs qui ont :
- une description avec au moins une url _ou_ le champ url rempli
- aucune activité (commentaire, publication, follow)
- une adresse qui n'est pas en gouv.fr
- (optionnel) aucune connexion depuis le jour de création

Sur l'export, on s'attend à pouvoir supprimer la majorité de ces comptes. A voir s'il est possible de faire une passe manuelle ou d'utiliser d'autres heuristiques.

**Comment by restuccia** [comment]
Si nous supprimons un compte par erreur, il peut être recréé avec la même adresse mail, on est d'accord ?

**Comment by maudetes** [comment]
> Yes, pas de soucis pour recréer un compte. Il faut s'assurer qu'on supprime que des comptes sans aucune activité, sinon ce serait perdu par contre.

**Comment by restuccia** [comment]
Du coup comme critère on peut se dire : pas de datasets, pas de reuses, pas de organisations, pas de gouv.fr. Followers et following c'est pas grave je dirais.

**Comment by maudetes** [comment]
Une liste basée sur les différentes heuristique ci-dessus a été créé et vérifiée à la main.

Cependant, la suppression d'un utilisateur lui envoie un mail. On préfère donc ne pas effectuer la suppression pour ne pas envoyer des mails non sollicités qui pourraient paraître arbitraires aux utilisateurs.
