### ISSUE TITLE
[Meta] Migrer toutes les api v1 vers l'API v2 sans flask-restplus

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#917]
Créer ci-dessous les sous-tickets en migrant namespace par namespace (ex: Orga, Discussions, etc.).
- [x] https://github.com/etalab/data.gouv.fr/issues/895
- [ ] #937

En profiter pour réfléchir à modifier l'API de certaines routes (type discussion, harvest) qui ne sont pas très lisibles aujourd'hui.

**Comment by quaxsze** [comment]
Dépriorisation de ce sujet, passage sur flask-rest-x
