### ISSUE TITLE
Pouvoir supprimer ou cacher les commentaires un par un

### ISSUE THREAD

**Issue by Jguilbaud** [etalab/data.gouv.fr#92]
Bonjour,

Il est fortement souhaitable de pouvoir supprimer un commentaire dans un jeu de donnée, ou a minima pouvoir le cacher aux utilisateurs (visiteurs).
J'ai en effet dans des fils de discussions, sur les jeux de données dont je suis en charge, du spam que je ne peux pas supprimer....
C'est dangereux pour les utilisateurs (s'ils cliquent sur le lien) et amène un potentiel risque sur l'image de la plateforme et du fournisseur du jeu de données.

merci par avance

**Comment by bboulesteix** [comment]
Merci d’avoir pris le temps de nous faire part de votre demande de nouvelle fonctionnalité, @Jguilbaud. C’est très gentil à vous. Vous avez raison, il ne serait pas inutile de pouvoir supprimer (ou cacher) les commentaires un par un, ne serait-ce que pour faciliter le travail des modérateurs.

**Comment by abulte** [comment]
La politique actuelle de la plateforme de data.gouv.fr est de ne pas permettre aux producteurs de supprimer les discussions. Vous pouvez nous contacter sur support@data.gouv.fr afin que nous fassions le ménage pour vous au cas par cas.
