### ISSUE TITLE
Il n'est pas possible d'obtenir une liste de jeux de données privés

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#920]
Les admins et éditeurs d'une organisation peuvent voir les jeux de données privés de leur organisation. Cependant, il n'y a aucune manière de consulter rapidement une liste de tous les jeux de données privés :
- L'export csv n'inclut pas les jdd privés (#166) ;
- La recherche `https://www.data.gouv.fr/fr/datasets/` ne permet pas de trier ni de filter par rapport au statut privé ;
- Dans l'admin `https://www.data.gouv.fr/fr/admin/organization/` la colonne "statut" ne propose pas de bouton de tri.

**Comment by maudetes** [comment]
En effet, il n'y a pas de vue ou d'export direct des jeux de données privés d'une organisation.
Il est cependant possible de récupérer par API (avec le token) la liste des jeux de données d'une orga, dont ceux privés. Ex: https://www.data.gouv.fr/api/1/organizations/etalab/datasets/?page_size=100
