### ISSUE TITLE
Mettre en prod l'explorateur beta

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#923]

**Comment by geoffreyaldebert** [comment]
- [ ] https://github.com/etalab/csvapi/pull/109
- [ ] https://github.com/etalab/csvapi/pull/110
- [ ] https://github.com/etalab/csvapi/pull/111
- [ ] https://github.com/etalab/csvapi/pull/112 => On ne le fait pas finalement
- [ ] montée de version csv-detective (donc modification requirements csvapi) en cours (semaine pro).
