### ISSUE TITLE
Ajouter le critère qualité dans l'export du catalogue et csv des orgas

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#927]
@agarrone, would the score do (between 0 and 1)?
dumping the dict would be ugly in a csv, and I don't think we need a column for each property (such as metrics).

You can see a catalog example in the linked PR: https://github.com/opendatateam/udata/pull/2785.

**Comment by agarrone** [comment]
A column for each property can be tricky indeed since the criterium might change. 
Between 0 and 1 seems good to me. (2 digits after 0 ?)
