### ISSUE TITLE
Rendre le menu du header plus lisible

### ISSUE THREAD

**Issue by taniki** [etalab/data.gouv.fr#93]
## problème

- l'élément « Découvrez l'open data » est le premier de toutes les pages et renvoie vers la documentation qui est un site différent
- ce n'est pas évident non plus de savoir qu'il s'agit d'une documentation d'aide

## proposition

- changer le lien vers la documentation en « Aide » et le mettre en 4ème position
- faire une vraie page « Découvrez l'open data »

**Comment by abulte** [comment]
s/problème/Problème/ s/proposition/Proposition/ :trollface:

**Comment by bboulesteix** [comment]
Merci pour cette issue @taniki. 

Je vais essayer de répondre précisément sur le sujet évoqué ici, car je sens que cette discussion pourrait vite dériver en débat sur la refonte de la page d’accueil _dans son ensemble_ — en la matière je trouve [celle de New York](https://opendata.cityofnewyork.us) très bien faite, mais j’ai dit que je ne parlerai pas de refonte, alors j’en reste là. 🙅‍♂️ 

## Réponses

Pour répondre aux propositions, disons que la documentation est :

* mal nommés quand elle est facile d’accès : cas du lien **Découvrez l’open data**, facilement accessible mais source potentielle d’équivoque — mieux vaudrait appeler ça **Aide**, je suis d’accord ;
* difficile d’accès quand elle est bien nommée : cas du lien **Documentation** en pied de page, qu’il faut un peu chercher pour trouver.

Donc :

> changer le lien vers la documentation en « Aide » et le mettre en 4ème position

Ça me va. 👍 

> faire une vraie page « Découvrez l'open data »

Ça me va, mais où faire cette page ? 🤔 J’aime bien cette idée, hein, mais je m’interroge : si nous créons une page statique de ce type, par quel outil serait-elle engendrée ? Ce qui pose la question suivante, plus large : souhaitons-nous faire de uData un générateur de pages statiques ? Pas sûr.

**Comment by taniki** [comment]
Pour info, il y a déjà des pages statiques sur le site qui sont gérées directement dans le thème et sans outil particulier.

Exemple : https://www.data.gouv.fr/fr/licences + ensemble des pages statiques https://github.com/etalab/udata-gouvfr/tree/master/udata_gouvfr/templates

**Comment by taniki** [comment]
https://github.com/etalab/udata-gouvfr/pull/388
