### ISSUE TITLE
Le texte de la description d'une orga est parfois coupé

### ISSUE THREAD

**Issue by restuccia** [etalab/data.gouv.fr#936]
En lien avec #601 #669 et https://github.com/etalab/udata-front/pull/65

J'arrive à reproduire le bug sur la page https://www.data.gouv.fr/fr/organizations/institut-de-radioprotection-et-de-surete-nucleaire-irsn/ 

<img width="832" alt="Capture d’écran 2022-09-21 à 16 02 49" src="https://user-images.githubusercontent.com/51122275/191526142-ea5dd3c4-9741-4171-98de-dace08c205fb.png">

**Comment by nicolaskempf57** [comment]
Merci du retour ! 

Quelle est ta version de Chrome ? 
Est-ce que tu as le problème dès que tu arrives sur la page ?

**Comment by maudetes** [comment]
Perso j'ai reproduit sur Firefox, uniquement en diminuant la taille de la fenêtre sur une page déjà chargée.

**Comment by nicolaskempf57** [comment]
On peut régler ce problème en ajoutant un eventListener sur l'événement "resize". Ce n'est pas le cas actuellement

**Comment by restuccia** [comment]
Merci ! Moi aussi sur Firefox en diminuant la taille de la fenêtre

**Comment by agarrone** [comment]
@maudetes je ne reproduit pas peut-on clore ?

**Comment by nicolaskempf57** [comment]
Le problème arrive parce que le composant `<read-more>` vérifie s'il a besoin de se lancer uniquement quand on arrive sur la page et non quand on la redimensionne. Mais si on réactualise la page avec la nouvelle dimension, le problème se résout de lui-même.

**Comment by maudetes** [comment]
Yes merci @nicolaskempf57 !
Je dirais bien de clore ce ticket si ce problème arrive uniquement lors d'un redimensionnement (tu confirmes @restuccia?).

**Comment by restuccia** [comment]
Good for me :)
