### ISSUE TITLE
impossible de créer un nouveau compte sur la demo

### ISSUE THREAD

**Issue by mkazmiers** [etalab/data.gouv.fr#94]
Bonjour, 

Il n'est plus possible de créer de compte sur demo.data.gouv.fr ?
en tout cas, j'ai une erreur
![image](https://user-images.githubusercontent.com/16324693/47156902-61cef980-d2e8-11e8-958d-ba886e560445.png)

Merci

**Comment by abulte** [comment]
Notre démo est dans un état très instable ces derniers temps, vous pouvez utiliser next.data.gouv.fr pour faire des tests.
