### ISSUE TITLE
Tester de passer apiv1 à flask-restx

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#940]
En parallèle de https://github.com/etalab/data.gouv.fr/issues/917, tester de migrer l'api v1 vers flask-restx, fork maintenu par la communauté.

L'intérêt serait d'enlever notre dépendance à flask-restplus qui est non maintenu, tout en aillant un coût de migration très faible.
On pourrait à côté migrer sur api v2 les endpoints qui méritent à être repensés en priorité (sur le framework compatible de notre choix).

Prendre en compte les discussions de maintenance sur flask-restx: https://github.com/python-restx/flask-restx/issues/462

**Comment by Smixi** [comment]
Hello @maudetes je tombe par hasard sur cette issues en checkant les tickets de flask-restx. Le projet flask-restx est très peu maintenu (voir le nombre de MR et issue en attente sur les derniers mois) et des problèmes de compatibilité avec les dernières versions  de werkzeug rendent les upgrades assez .. compliqués, et bloque pas mal de CI. Les projets flask-restQQC ont l'air de toujours se faire forker en permanence (on a aussi migré de restplus à restx). Je post juste pour suivre l'issue/voir commentles gens font la transition.

**Comment by maudetes** [comment]
Merci du commentaire @Smixi. On est bien sûr curieux de savoir quelle option vous privilégiez de votre côté, si vous décidez de migrer pour une solution sans flask_restQQC :)
