### ISSUE TITLE
Accès à la care des défibrillateurs erronées

### ISSUE THREAD

**Issue by randomstuff** [etalab/data.gouv.fr#952]
## Description du bug

Je tente de consulter la carte des défibrillateurs tirée de la base de données GeoDAE et j'obtiens le résultats ci-dessous.

![geodae1](https://user-images.githubusercontent.com/946727/196821354-490489e2-edbb-4e87-9dec-c9bcdef8b719.png)

![geodae2](https://user-images.githubusercontent.com/946727/196821366-053a4e29-932c-4340-a102-fc2ecdf00f9e.png)

Il y a visiblement un soucis : tous les défibrillateurs recensés sont localisés en Afrique (Somalie essentiellement) ou dans l'océan indien.

Par ailleurs, un accès plus direct et ergonomique à cette base de donnait serait très utile.

## Comment reproduire le bug

1. Aller à (https://geo.data.gouv.fr/fr/datasets/a701db3964e8fd81823c92afc029f138ffa207b3
2. Cliquer sur geodae_publique "Visualiser"

## Comportement attendu

Je m'attendrais à avoir un lien vers une carte qui :

* affiche des informations correctes ;
* permet la géolocalisation ;
* charge rapidement.

**Comment by maudetes** [comment]
Bonjour,

Merci pour ce ticket. En effet, la visualisation semble erronée, possiblement à cause d'une inversion des coordonnées de latitude et de longitude.

Le service geo.data.gouv.fr est en phase d'extinction et n'est plus maintenu. Je vous invite à consulter https://www.data.gouv.fr/fr/posts/extinction-de-geo-data-gouv-fr/.

Vous pourrez trouver des données brutes récentes sur data.gouv.fr directement https://www.data.gouv.fr/fr/datasets/geodae-base-nationale-des-defibrillateurs/.
