### ISSUE TITLE
Interactions API via Swagger cassée

### ISSUE THREAD

**Issue by Timost** [etalab/data.gouv.fr#954]
## Description du bug

Bonjour,
Tout d'abord, merci pour data.gouv 🙏

J'ai l'impression qu'on ne peut plus faire de requêtes authentifiées via le swagger de l'api (directement dans le navigateur).
J'utilise Firefox.

La page d'api actuellement mise en avant est bloquée par les CORS: https://api.gouv.fr/documentation/api_data_gouv

J'ai essayé d'utiliser le swagger (https://doc.data.gouv.fr/api/reference) directement, en rentrant ma clef d'api via le bouton "Authorize".
Malheureusement, le header d'authentification n'est pas ajouté à mes requêtes.

En rajoutant le header à la main dans l'inspecteur, les requêtes marchent.

## Comment reproduire le bug
Étapes à suivre pour faire apparaître le bug :
1. Allez sur https://doc.data.gouv.fr/api/reference
3. Cliquez sur "Authorize"
4. Entrez votre clef d'api
5. Essayer https://doc.data.gouv.fr/api/reference/#/me/get_me par exemple
6. Constater le bug

## Comportement attendu
- Prévenir les utilisateurs que https://api.gouv.fr/documentation/api_data_gouv ne marchera pas à cause des CORS (ou trouver une autre solution)
- Rediriger vers https://doc.data.gouv.fr/api/reference
- Corriger le bouton "Authorize"

**Comment by maudetes** [comment]
Bonjour,

Merci pour ce signalement. En effet il semble que l'authentification ne fonctionne pas sur le swagger aujourd'hui.
En allons enquêter sur ce problème. Sauriez-vous dire si ce problème est apparu récemment seulement ?

**Comment by Timost** [comment]
Bonjour malheureusement c'est une feature que j'utilise une fois tous les 6 mois (bien pratique par contre) donc je ne sais pas si c'est récent '^^

**Comment by agarrone** [comment]
Pas d'investissement sur ce swagger pour l'instant. 
Lien vers la doc de l'API https://guides.data.gouv.fr/publier-des-donnees/guide-data.gouv.fr/api
