### ISSUE TITLE
Rajouter un bandeau pour la mise en avant de l'explore sur data.gouv.fr

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#959]
Passer par les configs (BANNER_HTML_CONTENT_EN, ...).

@agarrone est-ce que tu peux nous mettre le wording français et anglais please ? 🙏 

- Découvrez notre nouvel outil d’exploration des données 

- Try out our new data exploration tool!

**Comment by maudetes** [comment]
@agarrone, pour validation, je mets le lien vers la home de explore. Ex:
* Découvrez notre [nouvel outil d’exploration des données](https://explore.data.gouv.fr/)

**Comment by agarrone** [comment]
Est-ce que l'on veut pas attendre la mise en prod de la preview du coup ? Et mettre un lien vers un nouvel article maybe ?

**Comment by maudetes** [comment]
On peut! Après s'il y a article + changement des ressources avec nouveau bouton explore -> ça suffit peut-être ?
