### ISSUE TITLE
Pouvoir marquer les notifications commes "lues"

### ISSUE THREAD

**Issue by bzg** [etalab/data.gouv.fr#96]
## La fonctionnalité que vous avez en tête

Sur mon profil, en cliquant sur les notifications, je vois toutes les notifications et je n'ai pas moyen de les marquer comme vues pour ne plus les voir.

Je voudrais pouvoir les marquer _toutes_ comme vues, voire individuellement.

## Les alternatives possibles

Soit les marquer toutes, soit individuellement, mais de préférence les deux.

![datagouvnotifications](https://user-images.githubusercontent.com/63500/47206393-d22d5780-d388-11e8-9ebd-929cf5b42206.png)

**Comment by bboulesteix** [comment]
Merci d’avoir pris le temps de créer une issue @bzg.

Pour te répondre, je suis d’accord avec toi : nous pourrions faire mieux sur les notifications. 🙂 

Je suis d’accord avec toi pour dire que :

1. Une page `/notification` ne ferait pas de mal car elle permettrait de lire les notifications plus confortablement, sans distractions (à la https://github.com/notifications) ;
2. Avoir la possibilité de marquer une notification particulière comme lue serait utile ;
3. Avoir la possibilité de marquer toutes les notifications comme lues serait également utile.

GitHub permet de faire ce que tu demandes et je pense que nous pourrions nous en inspirer.

<img width="1015" alt="capture d ecran 2018-10-22 12 34 53" src="https://user-images.githubusercontent.com/3286488/47288653-4ff69a80-d5f7-11e8-9aeb-7d06883bb49b.png">

**Comment by bzg** [comment]
Merci d'avoir mis ça dans la feuille de route !

**Comment by bzg** [comment]
Hello, les notifications sont toujours un aspect un peu pénible. Est-ce qu'une personne de l'équipe a du temps pour avancer sur ce sujet dans les trois mois ?

**Comment by abulte** [comment]
Si les fonctionnalités de notification sont clairement à réinventer / redessiner, ce point s'insère à mon avis dans un chantier plus global et plus conséquent de refonte de l'administration. Je ne suis pas pour, à ce stade, investir dans des améliorations conséquentes de l'admin.

**Comment by bzg** [comment]
Hello, pour info, je sors cette issue de mon radar :)

**Comment by bzg** [comment]
Je vois que l'issue est fermée - est-ce que ça veut dire que c'est implémenté? Ou bien que c'est "won't fix"?

**Comment by agarrone** [comment]
Hello Bastien, 
Je me suis permit de clore l'issue en faisant un ménage de printemps :
- cf commentaire d'Alexandre ci dessus la problématique des notifications (et plus largement des interactions entre les producteurs et leurs jdd) fera l'objet d'un chantier plus profond 
- Surtout il existe une autre issue sur le backlog qui nous permet de le garder en tête :)

**Comment by bzg** [comment]
Hello Antonin, merci pour ta réponse!

Si je peux me permettre: recevoir une notification disant qu'une issue est fermée sans avoir les moyens de comprendre pourquoi est un classique de la frustration qu'on a parfois dans les projets sur GitHub...  Mon conseil: toujours mettre une phrase pour dire pourquoi on ferme et si possible un lien vers l'endroit où est suivie l'issue, si elle est reportée ailleurs - du coup je veux bien le lien que tu mentionnes sur la nouvelle issue :)  Merci !

**Comment by agarrone** [comment]
Hello Bastien, c'est bien noté. 
Je suis passé sur plus de 200 issues donc j'ai été un peu rapide par endroit 😅. 
Il y a cette issue relative aux notifications https://github.com/etalab/data.gouv.fr/issues/167 qui n'est pas tout à fait la même mais comme je te le disais c'est tout le système de notifications (et l'admin) qui est à revoir.

**Comment by bzg** [comment]
OK, bravo pour le "grand ménage" et merci pour la réféfence !
