### ISSUE TITLE
Explore : problèmes d'alignement sur les filtres

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#961]
Il arrive que les valeurs les plus fréquentes ne soient pas juste en dessous de leur cadre. 
Exemple sur les IRVE : https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2F8d9398ae-3037-48b2-be19-412c24561fbb

https://user-images.githubusercontent.com/60264344/199016679-0280fe38-8419-4775-95fa-602638659b9c.mov

**Comment by nicolasboeuf** [comment]
Il semble que le soucis soit posé par la fonction moveTooltipIfRequired appelée par le watcher de activeFilterBox. La suppression de l'appel à la fonction dans $nextTick semble régler le soucis. Mais j'imagine que cette fonction est là pour une raison que je ne comprend pas. Tu peux m'aider @nicolaskempf57 ?

**Comment by nicolaskempf57** [comment]
L'objectif de `moveTooltipIfRequired` est de déplacer le tooltip pour la cellule la plus à droite de l'écran, pour ne pas que le tooltip dépasse de l'écran.

**Comment by nicolasboeuf** [comment]
Ha oui évidemment. J'ai fait une [PR](https://github.com/etalab/csvapi-front/pull/111) pour reset la position de la tooltip si l'utilisateur scroll jusqu'à la faire tenir dans l'écran et je t'ai mis en review @nicolaskempf57
