### ISSUE TITLE
Proposer "demande d'amélioration" en plus de "demande de fonctionnalité"

### ISSUE THREAD

**Issue by bzg** [etalab/data.gouv.fr#97]
## La fonctionnalité que vous avez en tête

Sur Github, on a le choix entre demander une fonctionnalité ou signaler un bug.

Il y a une autre catégorie, les demandes d'améliorations de fonctionnalités existantes.

Proposer cette troisième catégorie donnerait plus de choix au contributeur en facilitant aussi le triage des issues.

## Les alternatives possibles

Une alternative est de simplement indiquer "fonctionnalité ou amélioration" dans la demande de fonctionnalité, mais je pense que ce serait moins efficace, notamment pour le triage des issues.

**Comment by bboulesteix** [comment]
Merci pour cette idée @bzg. Je ne sais pas si la nuance entre la demande d’une _nouvelle_ fonctionnalité et la demande d’amélioration d’une fonctionnalité _existante_ est si évidente que ça. 🤔 

À mon avis, pour que la création de nouvelles _issues_ reste simple, les modèles de tickets proposés doivent être à la fois peu nombreux et faciles à différencier. J’ajoute qu’il est toujours possible de créer une _issue_ **libre**, pour toutes les demandes qui ne correspondent pas aux modèles proposés. 

Mais pour aller dans ton sens, je pense que nous pourrions renommer le modèle **Demande de fonctionnalité** en **Proposer une amélioration**, ce qui couvrirait à la fois les nouvelles fonctionnalités et les fonctionnalités existantes.

**Comment by bzg** [comment]
Merci d'avoir pris le temps de répondre !

> Mais pour aller dans ton sens, je pense que nous pourrions renommer le modèle Demande de fonctionnalité en Proposer une amélioration, ce qui couvrirait à la fois les nouvelles fonctionnalités et les fonctionnalités existantes. Qu’en dis-tu ?

Oui, **Proposer une amélioration** serait très bien.
