### ISSUE TITLE
Changer l'icone utilisée pour indiquer les réutilisations

### ISSUE THREAD

**Issue by bzg** [etalab/data.gouv.fr#98]
## La fonctionnalité que vous avez en tête

Demande d'amélioration: l'icone pour indiquer le nombre de réutilisations sur un jeu de données est celle habituellement utilisée pour "retweeter" ou "faire suivre". C'est un peu confusant.

Je propose à la place d'utiliser l'icone "redo" (dans le sens des aiguilles d'une montre), qu'on trouve par exemple dans le kit d'icones de _material design_ [ici](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F0B4tcF52UnWX4ZEZxVXRUNDFvVVE%2Fusability-bidirectionality-guidelines-when13.png).

## Les alternatives possibles

D'autres icones sont peut-être plus appropriées.

**Comment by taniki** [comment]
l'icône "redo" ça veut dire "rafraîchir" dans un sens comme dans l'autre voire littéralement "rotation".

Pour l'instant, on est surtout calé sur la bibliothèque.Font Awesome 4. Du coup, je propose : 
- https://fontawesome.com/v4.7.0/icon/recycle
- https://fontawesome.com/v4.7.0/icon/leaf

**Comment by taniki** [comment]
En fait c'est pas la même icone dans l'admin et dans le front :upside_down_face: 

![image](https://user-images.githubusercontent.com/27315/50225718-92431a80-03a1-11e9-9fb0-091221428f73.png)

![image](https://user-images.githubusercontent.com/27315/50225766-b141ac80-03a1-11e9-93ca-b6514ff31615.png)

**Comment by bzg** [comment]
Merci pour la réponse. Oui, ma première proposition n'est pas la meilleure.

Si déjà on a la même icone en front et en admin c'est top.

Mais je trouve que ni _recycle_ ni _leaf_ assez explicite, je propose l'icone qu'on trouve au milieu de cette image:

![share-reuse](https://user-images.githubusercontent.com/63500/50273838-09c58800-043c-11e9-8c4b-8c06864d714f.jpg)

WDYT?

**Comment by taniki** [comment]
L'icône qui s'en rapproche plus dans FA c'est `code-fork` : https://fontawesome.com/v4.7.0/icon/code-fork

ça me va malgré la potentielle confusion avec un vrai fork. Je pense qu'en dehors des techs, peu d'autres personnes vont faire l'association directement et le concept reste assez similaire.

**Comment by abulte** [comment]
Jusqu'au jour où on propose de _forker_ des JDD 🙃 Perso j'aime bien _recycle_, le message derrière est bien, ça ressemble à ce qu'on a aujourd'hui donc la transition est plus facile, pas de confusion avec le _fork_.

**Comment by bzg** [comment]
Je suis pour la solution proposée par @abulte - est-ce qu'on pourrait la mettre en place d'ici l'été ? Dans l'esprit "le bien est l'ennemi du mieux"... merci !

**Comment by abulte** [comment]
@bzg yes, je prends
