### ISSUE TITLE
Jeu de données : en favori, suivi, etc. : impossible de comprendre 

### ISSUE THREAD

**Issue by bzg** [etalab/data.gouv.fr#99]
## Description du bug

C'est plutôt une demande d'amélioration sur le _first time user experience_. Il y a plusieurs problèmes liés:

- sur la page affichant la liste des jeux de données, il ne se passe rien quand je clique sur l'icone "étoile" (mettre en favori) d'un jeu de données: je m'attends à ce que cela soit mis en favoris ;
- sur la page d'un jeu de données: je peux _suivre_ un jeu de donnée (sous le bouton "Contacter"), mais je ne sais pas quelle est la différence entre _suivre_ et _mettre en favori_ ; 
- sur la même page, je peux être _informé de l'activité associée à un jeu de données_ mais je ne sais pas quelle est la différence avec _suivre_ un jeu de données.

Le tout est confus.

## Comportement attendu

Je m'attends à un seul bouton "mettre en favori", fonctionnel depuis la page avec les jeux de données ou la page d'un seul jeu de données, et qui me permette en même temps de "suivre" le jeu de données et d'être informé de son activité.

**Comment by bboulesteix** [comment]
Merci pour ce ticket @bzg. 👍 Tes remarques et tes impressions vont beaucoup m’aider à rédiger [un article d’aide](https://github.com/etalab/doc.data.gouv.fr/issues/36) au sujet de la mise en favoris des jeux de données. 

Pour être honnête, ce sujet reste assez nébuleux pour moi aussi et je suis rassuré de voir qu’il amène d’autres personnes à s’interroger. J’y vois le signe que nous avons encore un peu de travail à faire sur ce point, pour que les choses soient claires. 😎 

Pour te répondre, dans l’ordre :

> Sur la page affichant la liste des jeux de données, il ne se passe rien quand je clique sur l'icone "étoile" (mettre en favori) d'un jeu de données: je m'attends à ce que cela soit mis en favoris.

![screenshot](https://user-images.githubusercontent.com/3286488/47414463-4f820f00-d771-11e8-8f70-8915774547e8.png)

Je suis d’accord avec toi pour dire qu’il _devrait_ se passer quelque chose quand on clique sur l’icône en question (soulignée en jaune sur l’image ci-dessus). Que devrait-il se passer ? Je ne sais pas, nous pourrions :
1. Ajouter le jeu de données en question aux favoris de l’utilisateur, comme tu le proposes. C’est ce qui se passe sur Twitter, par exemple, quand on clique sur l’icône ❤️ sous un tweet, depuis la _timeline_, le tweet est ajouté au favoris.
2. Afficher la liste des utilisateurs qui ont déjà mis le jeu de données en question dans leurs favoris. C’est ce qui se passe sur GitHub, par exemple, quand on clique sur l’icône ⭐️ sous le nom d’un _repo_, depuis une liste de _repo_, on accède à la vue des `Stargazers` — les gens qui ont mis le repo en favoris.

***

> Sur la page d'un jeu de données: je peux suivre un jeu de donnée (sous le bouton "Contacter"), mais je ne sais pas quelle est la différence entre suivre et mettre en favori.

Si tu cliques sur le bouton en question, ce n’est pas au jeu de données que tu t’abonnes, mais à l’organisation (ou à l’utilisateur) qui en est à l’origine. Il y a une nuance et je suis d’accord avec toi pour dire qu’elle n’est pas évidente. Ici, dans le cas que tu décris, le bouton **Suivre** fonctionne exactement comme le bouton du même nom sur Twitter. Et sur Twitter tu ne peux pas suivre un tweet _en particulier_, tu ne peux suivre que des compte _en général_. Là encore, nous pouvons expliquer tout ça plus clairement je pense. 🙂 

***

> Sur la même page, je peux être informé de l'activité associée à un jeu de données mais je ne sais pas quelle est la différence avec suivre un jeu de données.

Le bouton **Suivre** permet de suivre **toutes** les publications de l’organisation à l’origine du jeu de données auquel tu t’intéresses, alors que l’icône en forme d’œil (👁) permet de garder un œil sur le jeu de données en question _en particulier_, c’est-à-dire sans suivre tout ce que produit l’organisation par ailleurs. C’est selon moi l’équivalent du _Watch/Unwatch_ que propose GitHub au niveau de chaque _repo_, sauf que GitHub ne permet pas de suivre des organisations, juste des _repositories_, ce qui réduit les risques d’équivoque. Nous avons, de notre côté, une complexité supplémentaire à gérer, tu as raison.

En tout cas, encore merci pour cette issue qui me permet de savoir quoi couvrir dans mon futur article sur le sujet.

**Comment by bzg** [comment]
Merci pour ce retour complet et très détaillé. S'il y a du nouveau sur l'interface, à votre disposition pour tester. Si tu as besoin de relecture aussi sur l'article d'aide, avec plaisir. Bonne journée !

**Comment by bzg** [comment]
Hello, cette issue commence à sacrément vieillir et se sent seule dans son petit appartement. Une bonne âme pour lui apporter le thé et lui lire un peu de Charles Dickens ? :)

**Comment by abulte** [comment]
Yo, voilà ce que je propose en mode _lean and mean_ :

- sur la liste des jeux de données, supprimer les incitations au clic sur les éléments non clicables de la "carte" du jeu de données (couvertures, favoris...)
- sur la page du jeu de données, remplacer le bouton "oeil" par un bouton "étoile"
- éventuellement remplacer le bouton "Suivre" par un bouton "Suivre l'organisation" dans l'encart producteur — toutefois celui-ci me parait assez clair en l'état vu son positionnement (encart producteur) et l'infobulle associée ("je serai informé de l'activité de cette organisation")

Cette première passe n'empêche de continuer à réfléchir à cette histoire de favoris/suivre qui n'est pas suivi d'effet : suppression totale ou mise en place de mécanismes de notification — mais c'est une autre histoire pour un autre jour.

**Comment by noirbizarre** [comment]
Elle n'est pas complètement pas suivi d'effet: ça contribue au scoring de recherche.

**Comment by bzg** [comment]
Hello, les propositions de @abulte font sens : est-ce que ça vous paraît pouvoir être implémenté bientôt ?

**Comment by taniki** [comment]
@bzg c’est dans mon radar des prochains jours
