### ISSUE TITLE
Ajouter la possibilité de modifier son adresse mail

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#992]
Il s'agit d'un point frustrant pour les utilisateurs.
Cela crée aussi de nombreux tickets support réguliers.

Exemple d'implémentation duquel s'inspirer : https://gist.github.com/Jaza/86096b4b0e933644cdf3bcc6e798c431 ?

Voir aussi https://mattermost.incubateur.net/betagouv/pl/6cigtfr7mjn7uq6zku5i1b9z4h

- [ ] https://github.com/etalab/data.gouv.fr/issues/1011

**Comment by agarrone** [comment]
- [ ] Designer la fonctionnalité de possibilité de changer de mail

**Comment by AntoineAugusti** [comment]
Awesome! @quaxsze @maudetes ❤️
