### ISSUE TITLE
Mettre à jour page d'accès données transport

### ISSUE THREAD

**Issue by agarrone** [etalab/data.gouv.fr#994]
Voir https://mattermost.incubateur.net/betagouv/pl/4nrzubi6878buqi817beiikane

**Comment by abulte** [comment]
En fait c'est la page générique OAuth. A ajouter : partage de l'adresse email.

**Comment by nicolaskempf57** [comment]
Je vous propose de modifier la description de la partie "Access your profile" en "Read your profile, your email address, the organization you belong to, your publications", au lieu de "Read your profile, the organization you belong to, your publications". Sinon on peut rajouter un 3e point juste pour cette information

**Comment by nicolaskempf57** [comment]
![Image](https://user-images.githubusercontent.com/8336712/207276206-67e7879c-c182-47b6-ba4a-9ccc30a3b91b.png)
