### ISSUE TITLE
Exposition RDF/DCAT des jeux de données pour chaque organisme

### ISSUE THREAD

**Issue by spelhate** [etalab/data.gouv.fr#997]
Bonjour,

Nous souhaitons  mettre en place en Bretagne un **moissonnage** DCAT depuis **data.gouv.fr** vers un catalogue régional.
UDATA permet bien de moissonner des catalogues DCAT. Mais il s'avère que le catalogue régional en question est également un catalogue **UDATA.**

Cela vous semble t'il possible ? 

- Est-ce que UDATA sait moissonner un autre catalogue UDATA ?
- Est-ce que UDATA expose un ou plusieurs catalogues DCAT  ( global + par organisme ) ?

Merci pour vos retours

**Comment by maudetes** [comment]
Bonjour,

Oui, le moissonnage entre plateformes udata est possible avec un moissonnage DCAT.
En effet, les plateformes udata exposent des catalogues DCAT des organisations. Exemple: https://data.gouv.fr/api/1/organizations/etalab/catalog.xml pour le catalogue des données de [l'organisation Etalab](data.gouv.fr/fr/organizations/etalab/) sur data.gouv.fr.

Il existe aussi un catalogue DCAT global des plateformes udata : https://data.gouv.fr/api/1/site/catalog.xml

Pour le cas spécifique d'un moissonnage depuis data.gouv.fr vers un catalogue régional, il faudra veiller à ne pas créer de boucle de moissonnage. Par exemple, qu'un jeu de données sur data.gouv.fr soit moissonné sur la plateforme régionale, qui soit elle-même moissonnée sur data.gouv.fr.

**Comment by spelhate** [comment]
Merci beaucoup pour ces éléments de réponse. On va tester.
Bonne journée !
