### ISSUE TITLE
Moissonnage de catalogues DCAT

### ISSUE THREAD

**Issue by spelhate** [etalab/data.gouv.fr#998]
Bonjour,
Pouvez-vous me confirmer que le moissonnage d'un catalogue DCAT moissonne uniquement les métadonnées ?
Je souhaite m'assurer que le moissonnage effectué depuis UDATA ne duplique pas les données (csv, json, shp...)  référencées par les métadonnées.
Merci.

**Comment by maudetes** [comment]
Bonjour,
Le moissonnage DCAT crée des jeux de données et copie les métadonnées des fichiers (ou distributions/ressources selon le vocabulaire utilisé) qui le composent. Mais le contenu (les données à proprement parler) n'est pas dupliqué, uniquement référencé.
Par exemple, sur [ce jeu de données moissonné](https://www.data.gouv.fr/fr/datasets/fontaines-6/), 6 fichiers ont été créés, mais si vous regarder l'URL, il s'agit de fichiers distants hébergés sur la plateforme moissonnée. Ex: https://ville-d-evian-opendata-ville-evian.hub.arcgis.com/datasets/538910f633534111934b4d11161c92aa_19.geojson?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D

**Comment by spelhate** [comment]
Merci pour les explications. C'est très clair.
